import type { LocaleTable } from './keys';

/**
 * Arabic (Modern Standard) UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key.
 *
 * Plural groups carry the full set of CLDR categories Arabic distinguishes —
 * `_zero` (0), `_one` (1), `_two` (2), `_few` (3–10), `_many` (11–99),
 * `_other` (everything else). A noun takes a different form in each, so unlike
 * Persian the `_other`-only shortcut would read as broken Arabic on "2 books"
 * or "3 books": `_few` takes the plural (٣ كتب), `_many` the accusative
 * singular with tanwīn (١١ كتابًا), `_two` the dual (كتابان).
 *
 * Every variant keeps `{{count}}`, including `_zero`, `_one` and `_two` where
 * idiomatic Arabic would rather write the numeral as a word — the package
 * compares each variant's placeholders against English's and a form that drops
 * `{{count}}` would render a countless sentence.
 *
 * Digits are left as the Latin ones the interpolated `{{count}}` produces
 * rather than being rewritten as Arabic-Indic numerals, so a counted string
 * never mixes two numeral systems in one sentence — matching fa.ts.
 *
 * Terminology fixed once, here: a tag/compilation is a *مجموعة*, a note a
 * *ملاحظة*, a cross-reference an *إحالة مرجعية* (shortened to *إحالة* in the
 * nav tiles and the reader's action bar, where the full term does not fit),
 * a passage a *فقرة*, Discover is *استكشاف*, the reader itself *القارئ*.
 * Arabic punctuation throughout: «» for quotation, «،» for the comma, «؟» for
 * the question mark. An arrow that means "forward" points left, because in
 * this script forward *is* left.
 */
export const ar: LocaleTable = {
  'common.cancel': 'إلغاء',
  'common.remove': 'إزالة',
  'common.removing': 'جارٍ الإزالة…',
  'common.save': 'حفظ',
  'common.done': 'تم',
  'common.ok': 'حسنًا',
  'common.continue': 'متابعة',
  'common.tryAgain': 'يُرجى المحاولة مرة أخرى.',
  'common.delete': 'حذف',
  'common.clear': 'مسح',
  'common.signInCreate': 'تسجيل الدخول / إنشاء حساب',
  'common.book_zero': '{{count}} كتاب',
  'common.book_one': '{{count}} كتاب',
  'common.book_two': '{{count}} كتابان',
  'common.book_few': '{{count}} كتب',
  'common.book_many': '{{count}} كتابًا',
  'common.book_other': '{{count}} كتاب',
  'common.saving': 'جارٍ الحفظ…',
  'common.loading': 'جارٍ التحميل…',
  'common.copy': 'نسخ',
  'common.retry': 'حاول مرة أخرى',
  'common.back': 'رجوع',
  'common.next': 'التالي',
  'common.searching': 'جارٍ البحث…',
  'common.noResults': 'لا توجد نتائج.',
  'common.dismiss': 'إغلاق',
  'common.options': 'خيارات',
  'common.collapseLibrary': 'طيّ المكتبة',
  'common.expandLibrary': 'توسيع المكتبة',
  'common.minutesAgo': 'قبل {{count}} د',
  'common.hoursAgo': 'قبل {{count}} س',
  'common.daysAgo': 'قبل {{count}} ي',
  'common.highlight_zero': '{{count}} تظليل',
  'common.highlight_one': '{{count}} تظليل',
  'common.highlight_two': '{{count}} تظليلان',
  'common.highlight_few': '{{count}} تظليلات',
  'common.highlight_many': '{{count}} تظليلًا',
  'common.highlight_other': '{{count}} تظليل',
  'common.edit': 'تحرير',
  'common.justNow': 'الآن',
  'common.opening': 'جارٍ الفتح…',
  'common.or': 'أو',
  'common.pleaseWait': 'يُرجى الانتظار…',
  'common.somethingWrong': 'حدث خطأ ما.',
  'common.rename': 'إعادة تسمية',
  'common.dragToReorder': 'اسحب لإعادة الترتيب',
  'common.openInReader': 'فتح في القارئ',
  // Fallback tradition name for a book whose category can't be resolved.
  'common.otherTradition': 'أخرى',

  // Primary navigation. The web sidebar shows these as its nav items; on
  // mobile the same destinations are the drawer's screen titles.
  'nav.home': 'الرئيسية',
  'nav.library': 'المكتبة',
  'nav.tags': 'المجموعات',
  'nav.notes': 'الملاحظات',
  // 'nav.xrefs' / 'home.xrefs' — the full «الإحالات المرجعية» does not fit a
  // nav item or a Home tile on a small phone, so both use the short form.
  'nav.xrefs': 'الإحالات',
  'nav.discover': 'استكشاف',
  'nav.settings': 'الإعدادات',
  'nav.guest': 'ضيف',
  'nav.reader': 'القارئ',
  'nav.signOut': 'تسجيل الخروج',

  'library.title': 'المكتبة',
  'library.languageSheetTitle': 'لغة المكتبة',
  'library.availableToDownload': 'متاحة للتنزيل',
  'library.downloading': 'جارٍ التنزيل {{percent}}%',
  'library.verifying': 'جارٍ التحقق…',
  'library.importing': 'جارٍ الإضافة…',
  'library.cleaning': 'جارٍ الإنهاء…',
  'library.downloadFailed': 'فشل التنزيل',
  'library.updateAvailable': 'يتوفر تحديث',
  'library.updateLanguageA11y': 'تحديث {{language}}',
  'library.changeLanguageA11y': '{{title}}، {{language}}. تغيير لغة المكتبة',

  'library.myBooks': 'كتبي',
  'library.searchAll': 'ابحث في كل الكتب…',
  'library.searchSelected_zero': 'ابحث في {{count}} كتاب محدد…',
  'library.searchSelected_one': 'ابحث في {{count}} كتاب محدد…',
  'library.searchSelected_two': 'ابحث في {{count}} كتابين محددين…',
  'library.searchSelected_few': 'ابحث في {{count}} كتب محددة…',
  'library.searchSelected_many': 'ابحث في {{count}} كتابًا محددًا…',
  'library.searchSelected_other': 'ابحث في {{count}} كتاب محدد…',
  'library.noResultsFor': 'لا توجد نتائج للبحث عن «{{query}}».',
  'library.result_zero': '{{count}} نتيجة',
  'library.result_one': '{{count}} نتيجة',
  'library.result_two': '{{count}} نتيجتان',
  'library.result_few': '{{count}} نتائج',
  'library.result_many': '{{count}} نتيجةً',
  'library.result_other': '{{count}} نتيجة',
  'library.relatedPassages': 'فقرات ذات صلة',
  'library.relatedOn': 'في',
  'library.relatedPrefix': 'ذات صلة',
  'library.booksAndSections': 'الكتب والأقسام',
  'library.tapToOpenHint': 'اضغط للفتح',
  'library.importTitle': 'إضافة كتاب (TXT، EPUB، DOCX، RTF، PDF)',
  'library.importProFeature':
    'إضافة الكتب ميزة Pro. رقِّ حسابك من الإعدادات لإضافة كتبك الخاصة.',
  'library.importFailed': 'فشلت الإضافة.',
  'library.importSucceeded': 'تمت إضافة «{{title}}» بنجاح.',
  'library.noImportedBooks':
    'لا توجد كتب مُضافة بعد. استخدم الزر المجاور لشريط البحث لإضافة كتاب.',
  'library.deleteBookConfirm': 'حذف «{{title}}»؟',
  'library.tagAction': 'مجموعة',

  'settings.language': 'اللغة',
  'settings.appLanguage': 'لغة التطبيق',
  'settings.appLanguageHint': 'الأزرار والقوائم. منفصلة عن لغة المكتبة التي تقرأها.',
  // Shown only when the chosen language runs in the other direction. React
  // Native mirrors the layout at startup and cannot re-mirror a running app,
  // so without this the setting would look like it had half-applied.
  'settings.restartForDirection': 'أعد التشغيل لإكمال التبديل',
  'settings.restartForDirectionBody':
    '{{language}} تُكتب من اليمين إلى اليسار. أغلِق Immerse ثم أعد فتحه لقلب التخطيط.',
  'settings.restartForDirectionBodyLtr':
    'أغلِق Immerse ثم أعد فتحه لإعادة التخطيط إلى الاتجاه من اليسار إلى اليمين.',
  'settings.downloadedLibraries': 'المكتبات المُنزَّلة',
  'settings.downloadedLibrariesHint': 'يمكنك التبديل بينها من شاشة المكتبة.',
  'settings.includedWithApp': 'مضمَّنة مع التطبيق',
  'settings.removeLanguageTitle': 'إزالة {{language}}؟',
  'settings.removeLanguageBody':
    'ستُحذف هذه الكتب من هذا الجهاز. يمكنك تنزيلها مرة أخرى في أي وقت.',
  'settings.removeLanguageKeepsAnnotations':
    'ستبقى {{annotations}} الخاصة بك في هذه الكتب، وستظهر مجددًا إذا نزَّلت {{language}} مرة أخرى.',
  'settings.removeFailed': 'تعذَّرت الإزالة',
  'settings.account': 'الحساب',
  'settings.fullName': 'الاسم الكامل',
  'settings.edit': 'تحرير',
  'settings.username': 'اسم المستخدم',
  'settings.plan': 'الخطة',
  'settings.fontSize': 'حجم الخط',
  'settings.fontPreview': 'نص المعاينة بحجم {{size}}. تتزامن هذه الإعدادات عبر جميع أجهزتك.',
  'settings.dailyReadings': 'الإشعارات',
  'settings.randomVersesAndPlan': 'آيات عشوائية وخطة قراءة',
  'settings.readingMorningEvening': 'قراءة كل صباح ومساء',
  'settings.appearance': 'المظهر',
  'settings.appearanceLight': 'فاتح',
  'settings.appearanceDark': 'داكن',
  'settings.appearanceSystem': 'النظام',
  'settings.upgrade': 'ترقية',
  'settings.upgradeCta': 'الترقية إلى Pro — 0.99 دولار شهريًا',
  'settings.upgradeBlurb':
    'افتح ملخصات الذكاء الاصطناعي وأصوات الاستماع المتميزة وإضافة كتبك الخاصة. 0.99 دولار شهريًا.',
  'settings.purchases': 'المشتريات',
  'settings.restorePurchase': 'استعادة الشراء',
  'settings.restorePurchaseHint': 'يستعيد اشتراك Pro الذي دفعت ثمنه من قبل — على App Store أو Google Play أو الويب.',
  'settings.about': 'حول التطبيق',
  'settings.version': 'الإصدار',
  'settings.privacyPolicy': 'سياسة الخصوصية',
  'settings.viewExternal': 'عرض ↗',
  'settings.termsOfService': 'شروط الخدمة',
  'settings.introTour': 'الجولة التعريفية',
  'settings.fullFeatureVideo': 'الفيديو التعريفي الكامل',
  'settings.replayOnboarding': 'إعادة عرض لقطات التعريف',
  'settings.view': 'عرض',
  'settings.watchFeatureVideo': 'مشاهدة الفيديو التعريفي الكامل',
  'settings.accountActions': 'إجراءات الحساب',
  'settings.legal': 'الشؤون القانونية',
  'settings.contactSupport': 'التواصل مع الدعم',
  'settings.communityGuidelines': 'إرشادات المجتمع',
  'settings.signOut': 'تسجيل الخروج',
  'settings.deleteAccount': 'حذف الحساب',
  'settings.deleting': 'جارٍ الحذف…',
  'settings.error': 'خطأ',
  'settings.deleteAccountConfirm':
    'سيؤدي هذا إلى حذف حسابك نهائيًا مع جميع تعليقاتك التوضيحية ومجموعاتك وملاحظاتك وتقدُّم قراءتك. لا يمكن التراجع عن هذا الإجراء.',
  'settings.areYouSure': 'هل أنت متأكد؟',
  'settings.deleteAccountFinal':
    'سيُحذف حسابك وجميع بياناتك فورًا ولا يمكن استرجاعها.',
  'settings.deletePermanently': 'نعم، احذف نهائيًا',
  'settings.restoreFailed': 'فشلت الاستعادة',
  'settings.proRestored': 'تمت استعادة اشتراك Pro!',
  'settings.proRestoredBody': 'اشتراكك نشط الآن.',
  'settings.noSubscription': 'لم يُعثر على اشتراك',
  'settings.noSubscriptionBody':
    'لم نتمكن من العثور على اشتراك نشط مرتبط بهذا الحساب.',
  'settings.planGuest': 'ضيف',
  'settings.planStandard': 'عادي',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (تجريبي)',

  // Web-only: the subscription-management link and the post-checkout banner
  // are Stripe flows that exist only on web (mobile purchases go through
  // RevenueCat and the App Store).
  'settings.welcomeToPro': 'مرحبًا بك في Pro!',
  'settings.manage': 'إدارة',
  'settings.subscribeToPro': 'الترقية إلى Pro',

  // Update prompt
  'update.available': 'يتوفر تحديث جديد.',
  'update.update': 'تحديث',
  'update.ignore': 'تجاهل',

  'home.tags': 'المجموعات',
  'home.notes': 'الملاحظات',
  'home.xrefs': 'الإحالات',
  'home.readingPlan': 'خطة القراءة',
  'home.dailyVerses': 'آيات يومية',
  'home.dayStreak_zero': 'سلسلة {{count}} يوم',
  'home.dayStreak_one': 'سلسلة {{count}} يوم',
  'home.dayStreak_two': 'سلسلة {{count}} يومين',
  'home.dayStreak_few': 'سلسلة {{count}} أيام',
  'home.dayStreak_many': 'سلسلة {{count}} يومًا',
  'home.dayStreak_other': 'سلسلة {{count}} يوم',
  'home.dailyReading': 'القراءة اليومية',
  'home.dailyReadingsTitle': 'القراءات اليومية',
  'home.tapToSetUp': 'اضغط للإعداد',
  'home.tapToReadVerse': 'اضغط لقراءة آية',
  'home.tapToContinue': 'اضغط للمتابعة',
  'home.planFinished': 'انتهت — اختر كتابك التالي',
  'home.recentlyViewed': 'شوهدت مؤخرًا',
  'home.removeFromRecent': 'إزالة من «شوهدت مؤخرًا»',
  'home.removeFromRecentBody': 'إزالة «{{title}}» وإعادة تعيين تقدُّم القراءة إلى 0%؟',
  'home.signInCreate': 'تسجيل الدخول / إنشاء حساب',
  'home.startReadingHint': 'ابدأ القراءة لترى كتبك الأخيرة هنا.',
  'home.viewLibrary': 'عرض المكتبة',

  // Web-only: the sign-in card on the web Home has no mobile counterpart —
  // mobile shows home.signInCreate on its own instead.
  'home.signInBlurb': 'سجِّل الدخول لترى كتبك المطالَعة مؤخرًا وتعليقاتك التوضيحية والمزيد على جميع أجهزتك.',

  'auth.tagline': 'قارئ إلكتروني وبحث بين الأديان',
  'auth.usernamePlaceholder': 'معرِّف اسم المستخدم *',
  'auth.fullNamePlaceholder': 'الاسم الكامل',
  'auth.emailPlaceholder': 'عنوان البريد الإلكتروني *',
  'auth.passwordPlaceholder': 'كلمة المرور *',
  'auth.emailAddressPlaceholder': 'عنوان البريد الإلكتروني *',
  'auth.signIn': 'تسجيل الدخول',
  'auth.signUp': 'إنشاء حساب',
  'auth.createAccount': 'إنشاء حساب',
  'auth.forgotPassword': 'هل نسيت كلمة المرور؟',
  'auth.browseWithout': 'التصفح بدون حساب',
  'auth.guestSubtext': 'اقرأ الكتب وابحث فيها — لن يُحفظ التقدُّم ولا الملاحظات',
  'auth.guestAccess': 'الوصول كضيف',
  'auth.continueWithGoogle': 'المتابعة باستخدام Google',
  'auth.continueWithApple': 'المتابعة باستخدام Apple',
  'auth.orContinueWith': 'أو المتابعة باستخدام',
  'auth.chooseUsernameTitle': 'اختر اسم مستخدم',
  'auth.chooseUsernameBlurb': 'هكذا سيراك الآخرون في استكشاف.',
  'auth.alreadyHaveAccount': 'هل لديك حساب Immerse بالفعل؟',
  'auth.linkAccountBlurb': 'أدخِل البريد الإلكتروني لحسابك الحالي — سنرسل رمزًا لتأكيد ملكيتك له، ثم نربط عملية تسجيل الدخول هذه به.',
  'auth.resetPassword': 'إعادة تعيين كلمة المرور',
  'auth.sendResetLink': 'إرسال رابط إعادة التعيين',
  'auth.createPasswordPlaceholder': 'إنشاء كلمة مرور *',
  'auth.backToSignIn': 'العودة إلى تسجيل الدخول',
  'auth.forgotBlurb':
    'أدخِل عنوان بريدك الإلكتروني وسنرسل إليك رابطًا لإعادة تعيين كلمة المرور.',
  'auth.usernameAvailable': '✓ متاح',
  'auth.usernameTakenShort': '✗ مستخدَم',
  'auth.usernameHint': '3–20 حرفًا',
  'auth.usernameAlreadyTaken': 'اسم المستخدم مستخدَم بالفعل.',
  'auth.resetLinkSent': 'أرسلنا رابط إعادة تعيين كلمة المرور إلى {{email}}',
  'auth.error': 'خطأ',
  'auth.missingFields': 'حقول ناقصة',
  'auth.missingFieldsBody': 'يُرجى إدخال البريد الإلكتروني وكلمة المرور.',
  'auth.invalidUsername': 'اسم مستخدم غير صالح',
  'auth.invalidUsernameBody': 'يجب أن يتكوَّن اسم المستخدم من 3–20 حرفًا: أحرف وأرقام وشرطات سفلية فقط.',
  'auth.usernameTaken': 'اسم المستخدم مستخدَم',
  'auth.usernameTakenBody': 'يُرجى اختيار اسم مستخدم مختلف.',
  'auth.checkUsername': 'التحقق من اسم المستخدم',
  'auth.checkUsernameBody': 'يُرجى الانتظار حتى يكتمل التحقق من اسم المستخدم.',
  'auth.enterCode': 'أدخِل رمزك',
  'auth.enterCodeBody': 'أرسلنا رمزًا من 6 أرقام إلى {{email}}',
  'auth.codePlaceholder': 'رمز من 6 أرقام',
  'auth.verify': 'تحقُّق',
  'auth.verifying': 'جارٍ التحقق…',
  'auth.resendCode': 'إعادة إرسال الرمز',
  'auth.resendCodeIn': 'إعادة الإرسال خلال {{seconds}} ثانية',
  'auth.codeIncorrect': 'لم ينجح هذا الرمز — تحقَّق منه أو أعِد الإرسال.',
  'auth.codeResent': 'تم إرسال رمز جديد.',
  'auth.wrongEmailBack': 'بريد إلكتروني خاطئ؟ ارجع',
  'auth.tooManyAttempts': 'محاولات كثيرة جدًا. انتظر دقيقة ثم حاول مرة أخرى.',
  'auth.enterEmail': 'أدخِل البريد الإلكتروني',
  'auth.enterEmailBody': 'يُرجى إدخال عنوان بريدك الإلكتروني.',
  'auth.emailSent': 'تم إرسال البريد',
  'auth.emailSentBody': 'تحقَّق من بريدك الوارد بحثًا عن رابط إعادة تعيين كلمة المرور.',

  'auth.emailConfirmed': 'تم تأكيد البريد الإلكتروني',
  'auth.accountReadySignIn':
    'حسابك جاهز. سجِّل الدخول ببريدك الإلكتروني وكلمة المرور للبدء.',
  'auth.accountReadyOpenApp':
    'حسابك جاهز. افتح تطبيق Immerse على هاتفك لتسجيل الدخول، أو تابع على الويب أدناه.',
  'auth.openingApp': 'حسابك جاهز. جارٍ فتح تطبيق Immerse وتسجيل دخولك…',
  'auth.openImmerse': 'فتح Immerse',
  'auth.continueOnWeb': 'المتابعة على الويب بدلًا من ذلك',
  'auth.signInToImmerse': 'تسجيل الدخول إلى Immerse',
  'auth.continueToImmerse': 'المتابعة إلى Immerse',
  'auth.chooseNewPassword': 'اختر كلمة مرور جديدة لحسابك',
  'auth.newPasswordPlaceholder': 'كلمة المرور الجديدة',
  'auth.confirmNewPasswordPlaceholder': 'تأكيد كلمة المرور الجديدة',
  'auth.updatePassword': 'تحديث كلمة المرور',
  'auth.enterConfirmPassword': 'يُرجى إدخال كلمة المرور الجديدة وتأكيدها.',
  'auth.passwordTooShort': 'يجب ألا تقل كلمة المرور عن 8 أحرف.',
  'auth.passwordsDontMatch': 'كلمتا المرور غير متطابقتين.',
  'auth.passwordUpdated': 'تم تحديث كلمة المرور',
  'auth.passwordUpdatedBody': 'يمكنك الآن استخدام كلمة مرورك الجديدة.',
  'auth.resetFailed':
    'تعذَّر تحديث كلمة المرور. ربما انتهت صلاحية رابط إعادة التعيين — يُرجى طلب رابط جديد.',

  'reminders.headerTitle': 'القراءات اليومية',
  'reminders.enable': 'تفعيل القراءات اليومية',
  'reminders.openSettings': 'فتح الإعدادات',
  'reminders.source': 'المصدر',
  'reminders.randomVerses': 'آيات عشوائية',
  'reminders.readingPlan': 'خطة قراءة',
  'reminders.chooseBook': 'اختر كتابًا',
  'reminders.bookFinished': 'انتهى ✓ — اختر كتابك التالي',
  'reminders.sessionLength': 'مدة الجلسة',
  'reminders.sessionCaption': 'تنطبق على كل جلسة — {{dur}} في الصباح و{{dur}} في المساء.',
  'reminders.reminders': 'التذكيرات',
  'reminders.time': 'الوقت',
  'reminders.morning': 'الصباح',
  'reminders.evening': 'المساء',
  'reminders.yourStreak': 'سلسلتك',
  'reminders.today': 'اليوم',
  'reminders.currentStreak': 'السلسلة الحالية',
  'reminders.bestStreak': 'أفضل سلسلة',
  'reminders.completedBooks': 'الكتب المكتملة',
  'reminders.day_zero': '{{count}} يوم',
  'reminders.day_one': '{{count}} يوم',
  'reminders.day_two': '{{count}} يومان',
  'reminders.day_few': '{{count}} أيام',
  'reminders.day_many': '{{count}} يومًا',
  'reminders.day_other': '{{count}} يوم',
  'reminders.hour': 'ساعة واحدة',
  'reminders.minutes': '{{count}} دقيقة',
  'reminders.signInRequired': 'تسجيل الدخول مطلوب',
  'reminders.signInRequiredBody': 'أنشئ حسابًا لمتابعة خطة قراءة وتتبُّع تقدُّمك.',
  'reminders.notNow': 'ليس الآن',
  'reminders.enabledSub': 'يعرض قراءتك اليومية على الشاشة الرئيسية.',
  'reminders.disabledSub': 'مُعطَّل — قراءتك اليومية مخفية عن الشاشة الرئيسية.',
  'reminders.chooseNextToResume': 'اختر كتابك التالي أعلاه لاستئناف التذكيرات.',
  'reminders.chooseBookToEnable': 'اختر كتابًا أعلاه لتفعيل التذكيرات.',
  'reminders.selectSourceToEnable': 'اختر مصدرًا واحدًا على الأقل أعلاه لتفعيل التذكيرات.',
  // Today's progress, shown as "morning ✓ · evening pending" when the plan asks
  // for two sessions and as a single word when it asks for one.
  'reminders.todayComplete': 'مكتملة ✓',
  'reminders.todayPending': 'قيد الانتظار',
  'reminders.todayMorningDone': 'الصباح ✓',
  'reminders.todayMorningPending': 'الصباح قيد الانتظار',
  'reminders.todayEveningDone': 'المساء ✓',
  'reminders.todayEveningPending': 'المساء قيد الانتظار',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'اقرأ بعمق أكبر. واربط أكثر.',
  'paywall.featureAiLabel': 'ملخصات الفقرات بالذكاء الاصطناعي',
  'paywall.featureAiDesc': 'اطلب شروحًا وتعليقات على أي فقرة',
  'paywall.featureVoicesLabel': 'أصوات استماع متميزة',
  'paywall.featureVoicesDesc': 'سرد طبيعي ومعبِّر بالصوت الذي تختاره',
  'paywall.featureImportLabel': 'أضِف كتبك الخاصة',
  'paywall.featureImportDesc': 'أضِف ملفات EPUB وPDF وDOCX إلى مكتبتك',
  'paywall.subscribe': 'الترقية إلى Pro — {{price}}/شهريًا',
  'paywall.cancelNote': 'يمكن الإلغاء في أي وقت · فوترة شهرية',
  'paywall.restore': 'استعادة المشتريات',
  'paywall.terms': 'شروط الخدمة',
  'paywall.privacy': 'سياسة الخصوصية',
  'paywall.notAvailable': 'غير متاح',
  'paywall.notAvailableBody': 'لم تُهيَّأ عمليات الشراء داخل التطبيق في هذه النسخة بعد. تحقَّق مرة أخرى بعد الإصدار على App Store.',
  'paywall.welcome': 'مرحبًا بك في Pro!',
  'paywall.welcomeBody': 'اشتراكك نشط الآن.',
  'paywall.purchaseFailed': 'فشل الشراء',
  'paywall.restoreFailed': 'فشلت الاستعادة',

  'xrefs.title': 'الإحالات المرجعية',
  'xrefs.empty': 'لا توجد إحالات مرجعية بعد. ستظهر هنا الإحالات المرجعية التي تنشئها في القارئ.',
  'xrefs.signInTitle': 'سجِّل الدخول لعرض إحالاتك المرجعية',
  'xrefs.signInBody': 'اربط الفقرات ذات الصلة من المكتبة بأكملها.',
  'xrefs.searchSelected': 'ابحث في الإحالات المرجعية المحددة...',
  'xrefs.searchPlaceholder': 'ابحث في الفقرات أو العناوين...',
  'xrefs.noMatch': 'لا توجد إحالات مرجعية تطابق بحثك.',
  'xrefs.addLabel': 'أضِف عنوانًا…',
  'xrefs.deleteConfirm': 'حذف الإحالة المرجعية؟',
  'xrefs.deleteBody': 'سيُحتفظ بالتحديدين المظلَّلين.',

  'notes.title': 'الملاحظات',
  'notes.empty': 'لا توجد ملاحظات بعد. ستظهر هنا الملاحظات التي تنشئها في القارئ.',
  'notes.signInTitle': 'سجِّل الدخول لعرض ملاحظاتك',
  'notes.signInBody': 'أضِف تعليقات وتأملات على الفقرات أثناء القراءة.',
  'notes.searchPlaceholder': 'ابحث في الملاحظات...',
  'notes.searchSelected': 'ابحث في الملاحظات المحددة...',
  'notes.byBook': 'حسب الكتاب',
  'notes.byDate': 'حسب التاريخ',
  'notes.writeNote': 'اكتب ملاحظتك…',
  'notes.noMatch': 'لا توجد ملاحظات تطابق بحثك.',
  'notes.deleteConfirm': 'حذف الملاحظة؟',
  'notes.deleteBody': 'سيُحتفظ بالتحديد المظلَّل.',

  'tags.title': 'المجموعات',
  'tags.empty': 'لا توجد مجموعات بعد. ستظهر هنا المجموعات التي تنشئها في القارئ.',
  'tags.signInTitle': 'سجِّل الدخول لعرض مجموعاتك',
  'tags.signInBody': 'أنشئ مجموعات اقتباسات من المكتبة بأكملها ونظِّمها.',
  'tags.organize': 'تنظيم',
  'tags.searchPlaceholder': 'ابحث في المجموعات...',
  'tags.searchSelected': 'ابحث في المجموعات المحددة...',
  'tags.noMatch': 'لا توجد مجموعات تطابق بحثك.',
  'tags.deleteConfirm': 'حذف المجموعة؟',
  'tags.deleteBody': 'ستُزال «{{name}}» وجميع تحديداتها.',

  'tags.renameTitle': 'إعادة تسمية المجموعة',
  'tags.setPrivate': 'جعلها خاصة',
  'tags.setPublic': 'جعلها عامة',
  'tags.publicTag': 'مجموعة عامة',
  'tags.removePassage': 'إزالة من المجموعة',
  'tags.removePassageConfirm': 'إزالة هذه الفقرة من المجموعة؟',
  'tags.indent': 'زيادة المسافة البادئة',
  'tags.outdent': 'تقليل المسافة البادئة',
  'tags.organizeHint':
    'اسحب المقبض لإعادة الترتيب · ⇤ ⇥ لتغيير التداخل · انقر مجموعة لإعادة ترتيب اقتباساتها.',
  // Web-only: the web exports straight from a dropdown on the Tags header,
  // where mobile opens its ExportFormatPanel sheet.
  'tags.searchTagsPassages': 'ابحث في المجموعات والفقرات…',
  'tags.exportSelected': 'تصدير المجموعات المحددة',
  'xrefs.exportSelected': 'تصدير الإحالات المرجعية المحددة',
  'tags.export': 'تصدير',
  'tags.exporting': 'جارٍ التصدير…',
  'tags.exportInclude': 'تضمين',
  'tags.exportNothingToInclude': 'لا تحتوي أي من المجموعات المحددة على {{items}}',

  'panel.createAccount': 'إنشاء حساب',
  'panel.signInToSave': 'أنشئ حسابًا مجانيًا لحفظ المجموعات والملاحظات والإحالات المرجعية.',
  'panel.editSelection': 'تحرير تحديد النص',

  'reader.xrefMode': 'وضع الإحالة المرجعية — اضغط مطولًا لاختيار فقرة',
  'reader.error': 'خطأ في القارئ',
  'reader.opening': 'جارٍ فتح الكتاب…',
  'reader.loadingCount_zero': 'تم تحميل {{count}} فقرة حتى الآن…',
  'reader.loadingCount_one': 'تم تحميل {{count}} فقرة حتى الآن…',
  'reader.loadingCount_two': 'تم تحميل {{count}} فقرتان حتى الآن…',
  'reader.loadingCount_few': 'تم تحميل {{count}} فقرات حتى الآن…',
  'reader.loadingCount_many': 'تم تحميل {{count}} فقرةً حتى الآن…',
  'reader.loadingCount_other': 'تم تحميل {{count}} فقرة حتى الآن…',
  'reader.loadingMoreBanner': 'جارٍ تحميل بقية الكتاب…',
  'reader.footnote': 'حاشية',

  // Web-only: the web reader is a DOM view with its own chrome, where mobile
  // renders the book in a WebView and uses the OS selection menu.
  'reader.selectBook': 'اختر كتابًا لتبدأ القراءة',
  'reader.tableOfContents': 'جدول المحتويات',
  'reader.tocButtonHint': 'انتقل إلى قسم في هذا الكتاب',
  'reader.expandSection': 'توسيع القسم',
  'reader.collapseSection': 'طيّ القسم',
  'reader.expand': 'توسيع',
  'reader.collapse': 'طيّ',
  'reader.actionTag': 'مجموعة',
  'reader.actionNote': 'ملاحظة',
  'reader.actionXref': 'إحالة',
  'reader.actionAi': 'الذكاء الاصطناعي',
  'reader.actionCopy': 'نسخ',
  'reader.updateSelection': 'تحديث التحديد',
  'reader.updating': 'جارٍ التحديث…',
  'reader.pickAsXref': 'اختره كإحالة مرجعية',
  'reader.editSelectionHint':
    'ظلِّل النص الجديد لهذا التعليق التوضيحي، ثم اختر',
  'reader.savingXref': 'جارٍ حفظ الإحالة المرجعية…',
  'reader.pickTargetHint': 'حدِّد نصًا أو انقر فقرة لربطها',
  'reader.footnoteUnavailable': 'نص الحاشية غير متاح في نسخة الويب.',
  'reader.bookNotFound': 'لم يُعثر على الكتاب',
  'reader.viewTags': 'عرض المجموعات',
  'reader.viewNote': 'عرض الملاحظة',
  'reader.viewXrefs': 'عرض الإحالات المرجعية',
  'reader.noQuotesFiled': 'لا توجد اقتباسات محفوظة هنا.',
  // Shown in the reader when an imported book's file is missing on this device
  // (its annotations survived a sync but the content did not).
  'reader.importedStubBody':
    'هذا الكتاب غير موجود على هذا الجهاز. أعِد إضافة الملف لقراءته هنا — ملاحظاتك ومجموعاتك الخاصة به في أمان.',

  'ai.summary': 'ملخص الذكاء الاصطناعي',
  'ai.upgradeBlurb': 'رقِّ حسابك إلى Immerse Pro بـ 0.99 دولار فقط لاستخدام ملخصات الذكاء الاصطناعي وغيرها من ميزات Pro.',
  'ai.upgradeBtn': 'الترقية إلى Pro — 0.99 دولار شهريًا',
  'ai.thinking': 'جارٍ التفكير…',
  'ai.error': 'تعذَّر الحصول على ملخص الذكاء الاصطناعي. يُرجى التحقق من اتصالك والمحاولة مرة أخرى.',
  'ai.copied': '✓ تم النسخ',
  'ai.copyHint': 'اضغط مطولًا للنسخ',
  'ai.bahaiDisclaimer': 'من إنشاء الذكاء الاصطناعي — وليس تفسيرًا معتمدًا للآثار البهائية.',

  'note.title': 'ملاحظة',
  'note.addTitle': 'إضافة ملاحظة',
  'note.placeholder': 'اكتب ملاحظتك هنا…',
  'note.loading': 'جارٍ التحميل…',
  'note.emptyTitle': 'ملاحظة فارغة',
  'note.emptyBody': 'يُرجى كتابة شيء قبل الحفظ.',
  'note.saveFailed': 'تعذَّر حفظ الملاحظة',
  'note.deleteTitle': 'حذف الملاحظة؟',
  'note.deleteBody': 'سيؤدي هذا إلى إزالة الملاحظة. وإذا لم تكن هناك تعليقات توضيحية أخرى على هذه الفقرة، فسيُزال التحديد أيضًا.',
  'note.deleteFailed': 'تعذَّر حذف الملاحظة',
  'note.signInRequired': 'تسجيل الدخول مطلوب',
  'note.signInBody': 'تُحفظ الملاحظات في حسابك. يُرجى تسجيل الدخول أو إنشاء حساب.',

  'xref.title': 'إحالة مرجعية',
  'xref.yourSelection': 'تحديدك',
  'xref.pickSecond': 'اختر الفقرة الثانية  ←',
  'xref.noneFound': 'لم يُعثر على إحالات مرجعية.',

  // Web-only. The web builds a cross-reference through a two-step panel —
  // search for the target, then confirm the pair — where mobile has you pick
  // the second passage in the reader itself.
  'xref.findPassage': 'ابحث عن فقرة لربطها',
  'xref.searchPlaceholder': 'ابحث في أي فقرة…',
  'xref.save': 'حفظ الإحالة المرجعية',
  'xref.from': 'من',
  'xref.to': 'إلى',
  'xref.linksTo': 'يرتبط بـ',

  // "Suggest a match" flow in the cross-reference tool: the reader asks for
  // AI-suggested passages, then picks one (or falls back to picking manually).
  'xref.suggestMatch': 'اقترح تطابقًا',
  'xref.suggesting': 'جارٍ البحث عن فقرات ذات صلة…',
  'xref.suggestError': 'تعذَّر الحصول على اقتراحات الآن',
  'xref.noMatches': 'لم يُعثر على تطابقات. اختر واحدة بنفسك.',
  'xref.looseMatch': 'تطابق تقريبي',
  'xref.useThisPassage': 'استخدم هذه الفقرة',
  'xref.inCompilation': 'في مجموعتك «{{name}}»',
  'xref.youNotedThis': 'لقد دوَّنت ملاحظة على هذه الفقرة',

  // Web-only: the install banner shown on mobile browsers.
  'banner.googlePlay': 'احصل عليه من Google Play',
  'banner.appStore': 'نزِّله من App Store',
  'banner.install': 'تثبيت',
  'banner.get': 'احصل عليه',

  'tagPanel.new': 'مجموعة جديدة',
  'tagPanel.createWithin': 'أنشئ مجموعة داخل «{{parent}}»',
  'tagPanel.addTitle': 'إضافة إلى مجموعة',
  'tagPanel.viewTitle': 'المجموعات',
  'tagPanel.addSubTag': 'إضافة مجموعة فرعية',
  'tagPanel.emptyAdd': 'لا توجد مجموعات بعد — أنشئ واحدة أعلاه',
  'tagPanel.emptyView': 'لا توجد مجموعات على هذا التحديد',

  'voice.title': 'صوت القراءة',
  'voice.onyx': 'Onyx — عميق ودافئ',
  'voice.cedar': 'Cedar — طبيعي وثري',
  'voice.ash': 'Ash — واضح ومباشر',
  'voice.nova': 'Nova — مشرق',
  'voice.shimmer': 'Shimmer — ناعم',
  'voice.marin': 'Marin — طبيعي ولطيف',
  'voice.system': 'صوت النظام — متاح دون اتصال',
  'voice.previewHint': 'جرّب هذه الأصوات في الإعدادات',
  'voice.previewPlay': 'تشغيل المعاينة',
  'voice.previewPause': 'إيقاف المعاينة',

  'listen.connectionLostTitle': 'انقطع الاتصال',
  'listen.connectionLostBody': 'تعذّر الوصول إلى الصوت المميز. حاول مرة أخرى، أو انتقل إلى صوت النظام المتاح دون اتصال بالإنترنت.',
  'listen.useSystemVoice': 'استخدام صوت النظام',

  'reader.signInRequired': 'تسجيل الدخول مطلوب',
  'reader.signInBody': 'أنشئ حسابًا لحفظ المجموعات والملاحظات والإحالات المرجعية أثناء القراءة.',
  'reader.notNow': 'ليس الآن',
  'reader.signIn': 'تسجيل الدخول',
  'reader.pdfNotFound': 'تعذَّر تحديد موقع ملف PDF.',
  'reader.contentLoadFailed': 'تعذَّر تحميل المحتوى',
  'reader.noBook': 'لم يُحدَّد أي كتاب',
  'reader.storageError': 'خطأ في التخزين',

  'discover.recent': 'الأحدث',
  'discover.trending': 'الرائج',
  'discover.searchPlaceholder': 'ابحث في المجموعات والمستخدمين…',
  'discover.searchSelected': 'ابحث في المجموعات المحددة…',
  'discover.import': 'إضافة',
  'discover.imported': 'تمت الإضافة',
  'discover.import_zero': '{{count}} إضافة',
  'discover.import_one': '{{count}} إضافة',
  'discover.import_two': '{{count}} إضافتان',
  'discover.import_few': '{{count}} إضافات',
  'discover.import_many': '{{count}} إضافة',
  'discover.import_other': '{{count}} إضافة',
  'discover.noneYet': 'لا توجد مجموعات مشتركة بعد',
  'discover.noResults': 'لا نتائج',
  'discover.tryDifferent': 'جرِّب مصطلح بحث مختلفًا.',
  'discover.signInTitle': 'سجِّل الدخول للوصول إلى استكشاف',
  'discover.signInBody': 'اطَّلِع على ما يكتشفه القرّاء الآخرون عبر جميع التقاليد.',
  'discover.anonymous': 'مجهول',
  'discover.beFirst': 'كن أول من يشارك مجموعة.',
  'discover.ownTag': 'هذه مجموعتك أنت',
  'discover.alreadyImported': 'تمت إضافتها بالفعل',
  'discover.importFailed': 'فشلت الإضافة',
  'discover.exportFailed': 'فشل التصدير',
  'discover.unknownError': 'خطأ غير معروف',

  // ── Imported books: Discover / share links (Plan B) ───────────────────────
  // Imported books are private to the reader who added them, so their quotes
  // are dropped from anything public and kept read-only on a share link.
  'discover.importedDroppedTitle': 'تنبيه',
  'discover.importedDroppedNotice_zero':
    'تم استبعاد {{count}} اقتباس من الكتب المُضافة — الكتب المُضافة لا تُعرض علنًا.',
  'discover.importedDroppedNotice_one':
    'تم استبعاد {{count}} اقتباس من كتاب مُضاف — الكتب المُضافة لا تُعرض علنًا.',
  'discover.importedDroppedNotice_two':
    'تم استبعاد {{count}} اقتباسين من الكتب المُضافة — الكتب المُضافة لا تُعرض علنًا.',
  'discover.importedDroppedNotice_few':
    'تم استبعاد {{count}} اقتباسات من الكتب المُضافة — الكتب المُضافة لا تُعرض علنًا.',
  'discover.importedDroppedNotice_many':
    'تم استبعاد {{count}} اقتباسًا من الكتب المُضافة — الكتب المُضافة لا تُعرض علنًا.',
  'discover.importedDroppedNotice_other':
    'تم استبعاد {{count}} اقتباس من الكتب المُضافة — الكتب المُضافة لا تُعرض علنًا.',
  'discover.publishBlockedTitle': 'تعذَّر النشر',
  'discover.publishFailed': 'تعذَّر نشر هذه المجموعة.',
  'discover.importedOnlyError':
    'جميع اقتباسات هذه المجموعة من كتب مُضافة، ولا يمكن نشرها في استكشاف.',

  'usertags.autoImports': 'يضيف تلقائيًا المجموعات العامة لهذا المستخدم إلى تطبيقك',
  'usertags.noTags': 'لا توجد مجموعات عامة',
  'usertags.noTagsBody': 'لم يشارك هذا المستخدم أي مجموعات بعد.',
  'usertags.follow': 'متابعة',
  'usertags.unfollow': 'إلغاء المتابعة',
  'usertags.share': 'مشاركة',
  'usertags.error': 'خطأ',
  'usertags.somethingWrong': 'حدث خطأ ما',

  'onboarding.chooseLanguage': 'اختر لغتك',
  'onboarding.changeLaterSettings': 'يمكنك تغيير ذلك لاحقًا من الإعدادات.',
  'onboarding.libraryDownloadHint': 'لتنزيل المكتبة بلغة {{language}}، اضغط على ⌄ بجوار «المكتبة» في شاشة المكتبة.',
  'onboarding.continue': 'متابعة',
  'onboarding.chooseTextSize': 'اختر حجم النص',
  'onboarding.fontPreviewQuote':
    '«اطلبوا تجدوا، واقرعوا يُفتح لكم.»',
  'onboarding.getStarted': 'ابدأ الآن',

  // First-login Pro-trial intro — a full onboarding step (STEP_TRIAL) shown once
  // to a new signed-in user after the font step. Not shown to guests, or to an
  // account whose 30-day trial is already spent.
  'proTrialIntro.title': 'مرحبًا بك في Immerse!',
  'proTrialIntro.lede': 'تبدأ بحساب Pro — مجانًا لمدة 30 يومًا.',
  'proTrialIntro.body':
    'استمتع بجميع ميزات Pro دون أي تكلفة. وبعد انتهاء فترتك التجريبية البالغة 30 يومًا، يتحوَّل حسابك تلقائيًا إلى الحساب العادي المجاني. ولا توجد أي رسوم إلا إذا اخترت الترقية إلى Pro.',
  'proTrialIntro.priceLine': 'اشتراك Pro بـ 0.99 دولار شهريًا فقط إذا قررت الاحتفاظ بالميزات الإضافية:',
  'proTrialIntro.featureAiSummary': 'ملخص النصوص بالذكاء الاصطناعي',
  'proTrialIntro.featureImport': 'إضافة كتبك الخاصة إلى المكتبة',
  'proTrialIntro.featureVoices': 'أصوات متميزة طبيعية للقراءة بصوت مسموع',
  'proTrialIntro.cta': 'ابدأ الاستكشاف',

  // Web-only: the intro screenshot walkthrough replayed from Settings → About.
  'onboarding.closeIntro': 'إغلاق المقدمة',
  'onboarding.goToStep': 'الانتقال إلى الخطوة {{number}}',
  'onboarding.libraryTitle': 'المكتبة',
  'onboarding.libraryCaption': 'تصفَّح مكتبة منتقاة تضم تقاليد متعددة. اضغط على أي كتاب لتبدأ القراءة.',
  'onboarding.searchTitle': 'ابحث في كل شيء',
  'onboarding.searchCaption': 'ابحث في كل الكتب دفعة واحدة وانتقل مباشرة إلى الفقرة.',
  'onboarding.tagAsYouGoTitle': 'جمِّع أثناء القراءة',
  'onboarding.tagAsYouGoCaption': 'أضِف فقرة إلى مجموعة مباشرة من نتائج البحث.',
  'onboarding.buildTagsTitle': 'ابنِ مجموعاتك',
  'onboarding.buildTagsCaption': 'اجمع الفقرات ضمن مجموعاتك الخاصة لاسترجاعها بسهولة.',
  'onboarding.selectActTitle': 'حدِّد ونفِّذ',
  'onboarding.selectActCaption': 'حدِّد أي نص لتظليله أو إضافته إلى مجموعة أو كتابة ملاحظة عليه أو ربطه بإحالة مرجعية.',
  'onboarding.marginTitle': 'التعليقات الهامشية',
  'onboarding.marginCaption': 'مجموعاتك وملاحظاتك وإحالاتك المرجعية تعيش كلها في الهامش.',
  'onboarding.navigateTitle': 'تنقَّل بسرعة',
  'onboarding.navigateCaption': 'افتح جدول المحتويات للتنقل داخل الكتاب.',
  'onboarding.yourTagsTitle': 'مجموعاتك',
  'onboarding.yourTagsCaption': 'عُد إلى كل فقرة جمَّعتها، مرتَّبة حسب المجموعة.',
  'onboarding.xrefsTitle': 'الإحالات المرجعية',
  'onboarding.xrefsCaption': 'اربط الفقرات ذات الصلة عبر الكتب والتقاليد.',
  'onboarding.shareTitle': 'المشاركة والنشر',
  'onboarding.shareCaption': 'شارك اقتباسًا أو انشر مجموعة للمجتمع.',

  // ── Share links (Phase 5) ────────────────────────────────────────────────
  // A share link is a private web page for one compilation — link-only, never
  // listed in Discover. Publishing to Discover is the separate, public path.
  'share.createLink': 'إنشاء رابط مشاركة',
  'share.createLinkHint': 'صفحة ويب خاصة. لا تظهر في استكشاف.',
  'share.createLinkMultiHint': 'صفحة ويب خاصة تضم كل المجموعات المحددة. لا تظهر في استكشاف.',
  'share.bundleTitle': 'مجموعات مشتركة',
  'share.linkReady': 'الرابط جاهز',
  'share.linkCopied': 'تم نسخ الرابط',
  'share.copyLink': 'نسخ الرابط',
  'share.shareVia': 'مشاركة…',
  'share.revoke': 'إبطال',
  'share.revokeConfirm': 'إبطال هذا الرابط؟ سيفقد كل من يملكه إمكانية الوصول.',
  'share.discoverToggle': 'النشر في استكشاف',
  'share.discoverToggleHint': 'يمكن لأي شخص العثور على هذه المجموعة وحفظها.',
  'share.stopDiscover': 'إزالة من استكشاف',
  'share.publishedNote': 'منشورة في استكشاف — أوقف المفتاح لإيقاف المشاركة.',
  'share.selectOne': 'اختر مجموعة واحدة لإنشاء رابط.',
  'sharePage.eyebrow': 'مجموعة مشتركة',
  'sharePage.openInReader': 'فتح في القارئ',
  'sharePage.save': 'حفظ في مجموعاتي',
  'sharePage.saving': 'جارٍ الحفظ…',
  'sharePage.saved': 'تم الحفظ في مجموعاتك',
  'sharePage.saveHint': 'يفتح تطبيق Immerse، أو سجِّل الدخول للحفظ على الويب.',
  'sharePage.signInToSave': 'سجِّل الدخول لحفظ هذه المجموعة في مجموعاتك.',
  'sharePage.footer': 'اقرأ المزيد في Immerse',
  'sharePage.needLanguagePack':
    'هذا الاقتباس من مكتبة {{language}}. نزِّلها من قائمة اللغات في المكتبة لقراءته هنا.',
  // Shown when the shared compilation contains only imported-book quotes, so
  // it cannot be copied — the reader can look but not save.
  'sharePage.viewOnly': 'هذه المجموعة المشتركة للعرض فقط.',
  'sharePage.fromPrivateImport': 'من إضافة خاصة',

  // ── Share links: cross-references (Phase 8) ───────────────────────────────
  'share.createLinkXrefHint': 'صفحة ويب خاصة تعرض هذه الإحالات المرجعية. لا تظهر في استكشاف.',
  'sharePage.xrefEyebrow': 'إحالات مرجعية مشتركة',
  'sharePage.saveXrefs': 'حفظ في إحالاتي المرجعية',
  'sharePage.savedXrefs': 'تم الحفظ في إحالاتك المرجعية',
  'sharePage.savedXrefsPartial': 'تم حفظ {{saved}} من {{total}} — {{skipped}} تحتاج إلى محتوى لا تملكه',
  'sharePage.xrefsGone': 'لم تعد هذه الإحالات المرجعية متاحة',

  // ── Export sheet ──────────────────────────────────────────────────────────
  'export.shareTags_zero': 'مشاركة {{count}} مجموعة',
  'export.shareTags_one': 'مشاركة {{count}} مجموعة',
  'export.shareTags_two': 'مشاركة {{count}} مجموعتين',
  'export.shareTags_few': 'مشاركة {{count}} مجموعات',
  'export.shareTags_many': 'مشاركة {{count}} مجموعة',
  'export.shareTags_other': 'مشاركة {{count}} مجموعة',
  'export.shareTagsGeneric': 'مشاركة المجموعات',
  'export.shareXrefs_zero': 'مشاركة {{count}} إحالة مرجعية',
  'export.shareXrefs_one': 'مشاركة {{count}} إحالة مرجعية',
  'export.shareXrefs_two': 'مشاركة {{count}} إحالتين مرجعيتين',
  'export.shareXrefs_few': 'مشاركة {{count}} إحالات مرجعية',
  'export.shareXrefs_many': 'مشاركة {{count}} إحالة مرجعية',
  'export.shareXrefs_other': 'مشاركة {{count}} إحالة مرجعية',
  'export.preparing': 'جارٍ التحضير…',
  'export.notesOn': 'ملاحظاتك المكتوبة على كل فقرة',
  'export.notesNone': 'لا توجد ملاحظات على هذه الفقرات',
  'export.xrefsOn': 'الفقرات المرتبطة أسفل كل اقتباس',
  'export.xrefsNone': 'لا توجد إحالات مرجعية على هذه الفقرات',
  'export.docxTitle': 'مستند Word (.docx)',
  // The web's export menu uses a shorter label than mobile's format sheet.
  'export.docxShort': 'Word (.docx)',
  'export.docxDesc': 'عناوين المجموعات مع الفقرات المقتبسة. يُفتح في Word أو Pages أو Google Docs.',
  'export.pdfTitle': 'مستند PDF',
  'export.pdfDesc': 'مستند منسَّق للطباعة أو المشاركة.',
  'export.csvTitle': 'جدول بيانات (.csv)',
  'export.csvDesc': 'صف واحد لكل فقرة. يُفتح في Excel أو Numbers أو Google Sheets.',
  'export.mdTitle': 'Markdown (.md)',
  'export.mdDesc': 'لـ Obsidian أو Notion أو أي أداة نص عادي.',
  // Inside the exported document itself, which is written in the reader's
  // language like everything else.
  'export.noPassagesTagged': '(لا توجد فقرات في هذه المجموعة)',
  'export.seeAlso': 'انظر أيضًا:',

  // ── Reading plan ──────────────────────────────────────────────────────────
  'plan.chooseBook': 'اختر كتابًا',
  'plan.searchBooks': 'ابحث في الكتب…',
  'plan.noBooksMatch': 'لا توجد كتب تطابق «{{query}}».',
  'plan.readingComplete': 'اكتملت القراءة',
  'plan.morningSession': 'جلسة الصباح',
  'plan.eveningSession': 'جلسة المساء',
  'plan.minutes': '{{count}} دقيقة',
  'plan.streakDay': 'يوم السلسلة {{count}} ✓',
  'plan.sessionsToday': '{{done}} من {{required}} جلسات اليوم',
  'plan.youFinished': 'لقد أنهيت {{title}}',
  'plan.readOverDays_zero': 'اقرأه على مدى {{count}} يوم',
  'plan.readOverDays_one': 'اقرأه على مدى {{count}} يوم',
  'plan.readOverDays_two': 'اقرأه على مدى {{count}} يومين',
  'plan.readOverDays_few': 'اقرأه على مدى {{count}} أيام',
  'plan.readOverDays_many': 'اقرأه على مدى {{count}} يومًا',
  'plan.readOverDays_other': 'اقرأه على مدى {{count}} يوم',
  'plan.remindersPaused': 'التذكيرات متوقفة مؤقتًا',
  'plan.chooseNextBook': 'اختر كتابك التالي',
  'completed.title': 'الكتب المكتملة',
  'completed.empty': 'ستظهر هنا الكتب التي تنهيها في خطة قراءتك.',
  'completed.finishedOn': 'انتهت في {{date}}',
  'completed.day_zero': '{{count}} يوم',
  'completed.day_one': '{{count}} يوم',
  'completed.day_two': '{{count}} يومان',
  'completed.day_few': '{{count}} أيام',
  'completed.day_many': '{{count}} يومًا',
  'completed.day_other': '{{count}} يوم',

  // ── Library leftovers ─────────────────────────────────────────────────────
  'library.selectPassageForXref': 'حدِّد فقرة للإحالة المرجعية',
  'library.findingRelated': 'جارٍ البحث عن فقرات ذات صلة…',
  'library.aiSearchOffline': 'يلزم اتصال بالإنترنت للبحث بطرح سؤال',
  'library.importFailedTitle': 'فشلت الإضافة',
  'library.couldNotImport': 'تعذَّرت إضافة الملف.',
  'library.bookAdded': 'تمت إضافة الكتاب',
  'library.bookAddedBody': '«{{title}}» أصبح الآن في «كتبي».',
  'library.importErrorTitle': 'خطأ في الإضافة',
  'library.unexpectedError': 'حدث خطأ غير متوقع.',
  'nav.browsingAsGuest': 'التصفح كضيف',
  'reader.selectBookToBegin': 'اختر كتابًا لتبدأ القراءة',
  'tags.exportFailed': 'فشل التصدير',
  'tags.couldNotExport': 'تعذَّر تصدير المجموعات.',
  'tags.couldNotRemoveSelection': 'تعذَّرت إزالة التحديد',
  'tags.reorderHint': 'اسحب المقبض لإعادة الترتيب · ⇤ ⇥ لتغيير التداخل · اضغط مجموعة لإعادة ترتيب اقتباساتها.',
  'tags.swipeHint': 'اسحب المجموعة إلى اليمين لجعلها عامة أو خاصة.',
  'discover.publishHint': 'اسحب مجموعة إلى اليمين في شاشة المجموعات لنشرها هنا.',
  'reminders.notificationsOff':
    'الإشعارات مُعطَّلة لتطبيق Immerse، لذا لا يمكن تسليم التذكيرات. '
    + 'فعِّلها من إعدادات جهازك.',
  // Body of the scheduled reading reminder. User-visible on the lock screen,
  // so it belongs here even though no screen renders it.
  'plan.continueJourney': 'واصل رحلتك في القراءة',
  'plan.yourBook': 'كتابك',
  'reader.notesInParagraph_zero': '{{count}} ملاحظة في هذه الفقرة',
  'reader.notesInParagraph_one': '{{count}} ملاحظة في هذه الفقرة',
  'reader.notesInParagraph_two': '{{count}} ملاحظتان في هذه الفقرة',
  'reader.notesInParagraph_few': '{{count}} ملاحظات في هذه الفقرة',
  'reader.notesInParagraph_many': '{{count}} ملاحظةً في هذه الفقرة',
  'reader.notesInParagraph_other': '{{count}} ملاحظة في هذه الفقرة',
  'plan.awaitsMorning': '{{book}} في انتظارك — قراءة الصباح',
  'plan.awaitsEvening': '{{book}} في انتظارك — قراءة المساء',
  'reminders.dailyReadingFrom': 'القراءة اليومية · {{source}}',
  'library.tapToExpandHint': 'اضغط للتوسيع · اضغط مطولًا للفتح في القارئ',
  'library.deleteBookImportedBody': 'سيُزال هذا الكتاب وجميع تعليقاته التوضيحية نهائيًا.',
  'library.deleteBookBundledBody':
    'سيُزال هذا الكتاب وجميع تعليقاته التوضيحية. وسيعود عند تحديث المكتبة في المرة القادمة.',
  'library.deleteCategoryConfirm': 'حذف «{{name}}»؟',
  'library.deleteCategoryBody_zero': 'سيؤدي هذا أيضًا إلى إزالة {{count}} كتاب وجميع تعليقاته التوضيحية.',
  'library.deleteCategoryBody_one': 'سيؤدي هذا أيضًا إلى إزالة {{count}} كتاب وجميع تعليقاته التوضيحية.',
  'library.deleteCategoryBody_two': 'سيؤدي هذا أيضًا إلى إزالة {{count}} كتابين وجميع تعليقاتهما التوضيحية.',
  'library.deleteCategoryBody_few': 'سيؤدي هذا أيضًا إلى إزالة {{count}} كتب وجميع تعليقاتها التوضيحية.',
  'library.deleteCategoryBody_many': 'سيؤدي هذا أيضًا إلى إزالة {{count}} كتابًا وجميع تعليقاتها التوضيحية.',
  'library.deleteCategoryBody_other': 'سيؤدي هذا أيضًا إلى إزالة {{count}} كتاب وجميع تعليقاتها التوضيحية.',
  'library.deleteCategoryEmptyBody': 'ستُزال هذه الفئة نهائيًا.',

  // ── Imported books: re-import & multi-import (Plan B) ─────────────────────
  'library.reimportToRead': 'أعِد الإضافة للقراءة هنا',
  'library.importFinishedTitle': 'اكتملت الإضافة',
  'library.multiImportSummary_zero': 'تمت إضافة {{count}} كتاب.',
  'library.multiImportSummary_one': 'تمت إضافة {{count}} كتاب.',
  'library.multiImportSummary_two': 'تمت إضافة {{count}} كتابين.',
  'library.multiImportSummary_few': 'تمت إضافة {{count}} كتب.',
  'library.multiImportSummary_many': 'تمت إضافة {{count}} كتابًا.',
  'library.multiImportSummary_other': 'تمت إضافة {{count}} كتاب.',
  'library.multiImportFailed_zero': 'تعذَّرت قراءة {{count}} ملف: {{names}}.',
  'library.multiImportFailed_one': 'تعذَّرت قراءة {{count}} ملف: {{names}}.',
  'library.multiImportFailed_two': 'تعذَّرت قراءة {{count}} ملفين: {{names}}.',
  'library.multiImportFailed_few': 'تعذَّرت قراءة {{count}} ملفات: {{names}}.',
  'library.multiImportFailed_many': 'تعذَّرت قراءة {{count}} ملفًا: {{names}}.',
  'library.multiImportFailed_other': 'تعذَّرت قراءة {{count}} ملف: {{names}}.',
  'library.stubNotFound': 'لم يعد هذا الكتاب في مكتبتك.',
  'library.stubNotImported': 'هذا ليس كتابًا مُضافًا.',
  'library.stubAlreadyHasContent': 'هذا الكتاب يحتوي بالفعل على محتوى على هذا الجهاز.',

  // Onboarding's sign-up form omits the asterisk the standalone auth screens
  // use to mark a required field.
  'auth.passwordTooShortTitle': 'كلمة المرور قصيرة جدًا',
  'auth.passwordsMustMatch': 'يُرجى التأكد من تطابق كلمتي المرور.',
  'auth.usernamePlain': 'معرِّف اسم المستخدم',
  'auth.fullNameOptional': 'الاسم الكامل (اختياري)',
  'auth.emailPlain': 'البريد الإلكتروني',
  'auth.passwordPlain': 'كلمة المرور',
  'auth.emailAddressPlain': 'عنوان البريد الإلكتروني',

  // ── Onboarding tour (mobile) ──────────────────────────────────────────────
  // Sixteen slides, distinct from the web's nine: these describe touch gestures
  // that have no desktop equivalent, so the `onboarding.*Caption` keys above
  // cannot be reused. Each slide's `.label` is a fallback for a missing image.
  'onboarding.skip': 'تخطٍّ',
  'onboarding.tour.libraryMain.label': 'شاشة المكتبة',
  'onboarding.tour.libraryMain.caption':
    'تضم المكتبة أكثر من 400 نص مقدس من جميع التقاليد الكبرى. اضغط على أي تقليد لاستكشاف كتبه.',
  'onboarding.tour.libraryExpanded.label': 'المكتبة موسَّعة',
  'onboarding.tour.libraryExpanded.caption':
    'يتوسَّع كل تقليد ليُظهر المؤلفين والمجموعات. اضغط على أي عنوان لفتحه في القارئ.',
  'onboarding.tour.librarySearch.label': 'بحث المكتبة',
  'onboarding.tour.librarySearch.caption':
    'ابحث في أكثر من 400 نص دفعة واحدة. اضغط على نتيجة لتوسيعها — واضغط مطولًا لفتحها مباشرة في القارئ.',
  'onboarding.tour.searchQuickTag.label': 'مجموعة سريعة من نتائج البحث',
  'onboarding.tour.searchQuickTag.caption':
    'حدِّد نتيجة بحث واحدة أو عدة نتائج وأسندها إلى مجموعة بضغطة واحدة. طريقة سريعة لبناء مجموعة موضوعية من المكتبة بأكملها.',
  'onboarding.tour.home.label': 'الشاشة الرئيسية',
  'onboarding.tour.home.caption':
    'تعرض شاشتك الرئيسية عدد المجموعات والملاحظات والإحالات المرجعية التي أنشأتها، إضافة إلى كتبك المقروءة مؤخرًا. اضغط على أي عنوان لمتابعة القراءة.',
  'onboarding.tour.homePlan.label': 'خطة القراءة في الشاشة الرئيسية',
  'onboarding.tour.homePlan.caption':
    'كوِّن عادة قراءة يومية: اتبع خطة قراءة في أي كتاب تختاره وبالمدة التي تختارها، أو استقبل آيات عشوائية من التقاليد التي تحددها — مع تذكيرات يومية وسلسلة تنمو كل يوم تقرأ فيه.',
  'onboarding.tour.settingsDaily.label': 'إعدادات القراءات اليومية',
  'onboarding.tour.settingsDaily.caption':
    'في الإعدادات، هيِّئ الآيات العشوائية باختيار التقاليد التي تُستقى منها وأوقات اليوم التي تودّ أن يصلك فيها تذكير لطيف — أو انتقل إلى خطة قراءة لتقرأ كتابًا واحدًا يوميًا.',
  'onboarding.tour.readerSelect.label': 'تحديد النص في القارئ',
  'onboarding.tour.readerSelect.caption':
    'اضغط مطولًا على أي فقرة لتحديدها. استخدم الأيقونات في أسفل الشاشة لإضافتها إلى مجموعة أو كتابة ملاحظة أو إنشاء إحالة مرجعية أو الحصول على ملخص بالذكاء الاصطناعي.',
  'onboarding.tour.readerNote.label': 'عرض ملاحظة في القارئ',
  'onboarding.tour.readerNote.caption':
    'ترتبط الملاحظات بالنص الذي حددته بالضبط. وتتيح لك العلامة الذهبية في الهامش العثور عليها وإعادة فتحها في أي وقت.',
  'onboarding.tour.readerXref.label': 'عرض إحالة مرجعية في القارئ',
  'onboarding.tour.readerXref.caption':
    'تربط الإحالات المرجعية بين الفقرات عبر كتب وتقاليد مختلفة. اضغط مطولًا على أي اقتباس مرتبط للانتقال إليه في القارئ.',
  'onboarding.tour.readerAi.label': 'ملخص الذكاء الاصطناعي في القارئ',
  'onboarding.tour.readerAi.caption':
    'بعد تحديد فقرة، اضغط على أيقونة البريق للحصول على ملخص فوري بالذكاء الاصطناعي — وهو مفيد بوجه خاص للنصوص الكثيفة أو غير المألوفة.',
  'onboarding.tour.readerListen.label': 'وضع الاستماع في القارئ',
  'onboarding.tour.readerListen.caption':
    'اضغط على زر السماعات ليُقرأ أي كتاب بصوت مسموع — ويظلِّل القارئ كل فقرة أثناء تشغيلها. اضغط مطولًا على زر السماعات لاختيار صوت من مجموعة أصوات طبيعية.',
  'onboarding.tour.tags.label': 'شاشة المجموعات',
  'onboarding.tour.tags.caption':
    'تجمع شاشة المجموعات فقراتك المجمَّعة حسب الموضوع. اضغط على اسم مجموعة لعرض فقراتها المقتبسة مع الاستشهادات الكاملة.',
  'onboarding.tour.xrefs.label': 'شاشة الإحالات المرجعية',
  'onboarding.tour.xrefs.caption':
    'تعرض شاشة الإحالات المرجعية جميع فقراتك المرتبطة جنبًا إلى جنب. اضغط مطولًا على أي من الجانبين للانتقال إلى تلك الفقرة في القارئ.',
  'onboarding.tour.discover.label': 'شاشة استكشاف',
  'onboarding.tour.discover.caption':
    'في شاشة استكشاف، اعثر على مجموعات شاركها قرّاء آخرون. اضغط على مجموعة لمعاينة فقراتها، ثم أضِفها إلى مكتبتك.',
  'onboarding.tour.tagShare.label': 'لوحة مشاركة المجموعة',
  'onboarding.tour.tagShare.caption':
    'صدِّر أي مجموعة كمستند Word أو PDF أو جدول بيانات أو Markdown وغيرها — مع ملاحظاتك وإحالاتك المرجعية.',

  // ── Appearance (reader typography) ───────────────────────────────────────
  'appearance.title': 'المظهر',
  'appearance.navHint': 'الخط والتباعد ولون الصفحة',
  'appearance.reading': 'القراءة',
  'appearance.preview': 'معاينة',
  'appearance.previewText': 'القراءة حوار هادئ يمتد عبر القرون.',
  'appearance.previewHeading': 'الفصل الأول',
  'appearance.typeface': 'الخط',
  'appearance.typefaceSystem': 'النظام',
  'appearance.typefaceLiterataBlurb': 'صُمِّم للقراءة الطويلة. ويتكيَّف مع الحجم.',
  'appearance.typefaceCharisBlurb': 'سليل خط Charter. متين في الأحجام الصغيرة.',
  'appearance.typefaceGaramondBlurb': 'كلاسيكي بالطراز القديم. أخفّ على الصفحة.',
  'appearance.typefaceSystemBlurb': 'أيًّا كان ما يوفره هذا الجهاز.',
  'appearance.faceAmiriBlurb': 'خط نسخ كتابي مُحيًّا. دافئ ومتساوٍ.',
  'appearance.faceScheherazadeBlurb': 'نسخ تقليدي. أكبر قليلًا في السطر.',
  'appearance.faceIranNastaliqBlurb': 'خط النستعليق الفارسي التقليدي. مائل ومتدفق.',
  'appearance.faceLxgwBlurb': 'خط صيني منتظم مرسوم بالفرشاة. لمسات لطيفة.',
  'appearance.faceNotoSerifScBlurb': 'خط صيني مطبعي منتظم. محايد وواضح.',
  'appearance.textSize': 'حجم النص',
  // Size-step labels for the text-size picker, keyed by the internal size name.
  // The picker shifts the scale down a notch — the smallest step reads "XS",
  // not "S" — so these do not match the key names. Written out in Arabic
  // rather than kept as Latin garment codes, the way zh spells them out.
  'appearance.textSizeSmall': 'صغير جدًا',
  'appearance.textSizeMedium': 'صغير',
  'appearance.textSizeLarge': 'متوسط',
  'appearance.textSizeXL': 'كبير',
  'appearance.textSizeXXL': 'أكبر',
  'appearance.textSizeXXXL': 'كبير جدًا',
  'appearance.lineSpacing': 'تباعد الأسطر',
  'appearance.lineSpacingTight': 'ضيق',
  'appearance.lineSpacingNormal': 'عادي',
  'appearance.lineSpacingRelaxed': 'مريح',
  'appearance.lineSpacingLoose': 'واسع',
  'appearance.margins': 'الهوامش',
  'appearance.marginsNarrow': 'ضيقة',
  'appearance.marginsNormal': 'عادية',
  'appearance.marginsWide': 'واسعة',
  'appearance.justify': 'ضبط النص',
  'appearance.justifyHint': 'يحاذي كلتا الحافتين، مع تقسيم الكلمات.',
  'appearance.paragraphStyle': 'الفقرات',
  'appearance.paragraphSpaced': 'متباعدة',
  'appearance.paragraphIndented': 'بمسافة بادئة',
  'appearance.paragraphHint': 'المسافة البادئة هي التنسيق التقليدي للكتب.',
  'appearance.theme': 'لون الصفحة',
  'appearance.themeLight': 'فاتح',
  'appearance.themeSepia': 'سيبيا',
  'appearance.themeQuiet': 'هادئ',
  'appearance.themeDark': 'داكن',
  'appearance.themeNight': 'ليلي',
  'appearance.themeSystem': 'مطابقة التطبيق',
  'appearance.fineTuning': 'ضبط دقيق',
  'appearance.characterSpacing': 'تباعد الأحرف',
  'appearance.wordSpacing': 'تباعد الكلمات',
  'appearance.textWeight': 'سماكة النص',
  'appearance.paragraphNumbers': 'أرقام الفقرات',
  'appearance.paragraphNumbersHint': 'إظهار الأرقام المرجعية في الهامش.',
  'appearance.appTheme': 'سمة التطبيق',
  'appearance.appThemeHint': 'تنطبق خارج القارئ.',
  'appearance.reset': 'إعادة التعيين إلى الإعدادات الافتراضية',

  // ── Citation collection labels ────────────────────────────────────────────
  // The short name a scripture is cited under, rendered inside the passage's
  // own language.
  'citation.bible': 'الكتاب المقدس',
  'citation.tanakh': 'التناخ',
  'citation.quran': 'القرآن الكريم',
  'citation.guruGranthSahib': 'غورو غرانث صاحب',
};
