import type { LocaleTable } from './keys';

/**
 * German UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key.
 *
 * Register: the formal *Sie* throughout, matching the French locale's *vous*
 * and the contemplative tone of an interfaith reader. Imperatives are the
 * Sie-form ("Melden Sie sich an", "Wählen Sie ein Buch").
 *
 * Terminology fixed once, here:
 *  - a tag/compilation is a *Zusammenstellung* — the same word the German
 *    content library already uses for the Bahá'í compilations shelf, so the
 *    feature and the shelf read alike.
 *  - a cross-reference is a *Querverweis* (plural *Querverweise*); the nav chip
 *    abbreviates to *Querverw.* to fit.
 *  - a passage is a *Textstelle*, a note a *Notiz*, the Discover screen
 *    *Entdecken*, the reader *Leseansicht*.
 *  - "Pro" (the subscription tier) stays "Pro".
 *
 * German plurals are English-shaped (one/other), so every group carries both
 * variants; a count of 0 resolves through `_other`, as in English.
 *
 * German quotation marks are „…“ — opening „ (U+201E), closing “ (U+201C).
 */
export const de: LocaleTable = {
  'common.cancel': 'Abbrechen',
  'common.remove': 'Entfernen',
  'common.removing': 'Wird entfernt…',
  'common.save': 'Speichern',
  'common.done': 'Fertig',
  'common.ok': 'OK',
  'common.continue': 'Weiter',
  'common.tryAgain': 'Bitte versuchen Sie es erneut.',
  'common.delete': 'Löschen',
  'common.clear': 'Leeren',
  'common.signInCreate': 'Anmelden / Registrieren',
  'common.book_one': '{{count}} Buch',
  'common.book_other': '{{count}} Bücher',
  'common.saving': 'Wird gespeichert…',
  'common.loading': 'Wird geladen…',
  'common.copy': 'Kopieren',
  'common.retry': 'Erneut versuchen',
  'common.back': 'Zurück',
  'common.next': 'Weiter',
  'common.searching': 'Wird gesucht…',
  'common.noResults': 'Keine Ergebnisse gefunden.',
  'common.dismiss': 'Schließen',
  'common.options': 'Optionen',
  'common.collapseLibrary': 'Bibliothek einklappen',
  'common.expandLibrary': 'Bibliothek ausklappen',
  'common.minutesAgo': 'vor {{count}} Min.',
  'common.hoursAgo': 'vor {{count}} Std.',
  'common.daysAgo': 'vor {{count}} T.',
  'common.highlight_one': '{{count}} Markierung',
  'common.highlight_other': '{{count}} Markierungen',
  'common.edit': 'Bearbeiten',
  'common.justNow': 'gerade eben',
  'common.opening': 'Wird geöffnet…',
  'common.or': 'oder',
  'common.pleaseWait': 'Bitte warten…',
  'common.somethingWrong': 'Etwas ist schiefgelaufen.',
  'common.rename': 'Umbenennen',
  'common.dragToReorder': 'Zum Umsortieren ziehen',
  'common.openInReader': 'In der Leseansicht öffnen',
  'common.otherTradition': 'Weitere',

  'nav.home': 'Start',
  'nav.library': 'Bibliothek',
  'nav.tags': 'Zusammenstellungen',
  'nav.notes': 'Notizen',
  'nav.xrefs': 'Querverw.',
  'nav.discover': 'Entdecken',
  'nav.settings': 'Einstellungen',
  'nav.guest': 'Gast',
  'nav.reader': 'Leseansicht',
  'nav.signOut': 'Abmelden',

  'library.title': 'Bibliothek',
  'library.languageSheetTitle': 'Sprache der Bibliothek',
  'library.availableToDownload': 'Zum Herunterladen verfügbar',
  'library.downloading': 'Wird heruntergeladen {{percent}} %',
  'library.verifying': 'Wird geprüft…',
  'library.importing': 'Wird importiert…',
  'library.cleaning': 'Wird abgeschlossen…',
  'library.downloadFailed': 'Download fehlgeschlagen',
  'library.updateAvailable': 'Update verfügbar',
  'library.updateLanguageA11y': '{{language}} aktualisieren',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Sprache der Bibliothek ändern',

  'library.myBooks': 'Meine Bücher',
  'library.searchAll': 'Alle Bücher durchsuchen…',
  'library.searchSelected_one': '{{count}} ausgewähltes Buch durchsuchen…',
  'library.searchSelected_other': '{{count}} ausgewählte Bücher durchsuchen…',
  'library.noResultsFor': 'Keine Ergebnisse für „{{query}}“.',
  'library.result_one': '{{count}} Ergebnis',
  'library.result_other': '{{count}} Ergebnisse',
  'library.relatedPassages': 'Verwandte Textstellen',
  'library.relatedOn': 'zu',
  'library.relatedPrefix': 'VERWANDT',
  'library.booksAndSections': 'Bücher & Abschnitte',
  'library.tapToOpenHint': 'Zum Öffnen tippen',
  'library.importTitle': 'Buch importieren (TXT, EPUB, DOCX, RTF, PDF)',
  'library.importProFeature':
    'Der Buchimport ist eine Pro-Funktion. Führen Sie in den Einstellungen ein Upgrade durch, um eigene Bücher zu importieren.',
  'library.importFailed': 'Import fehlgeschlagen.',
  'library.importSucceeded': '„{{title}}“ wurde erfolgreich importiert.',
  'library.noImportedBooks':
    'Noch keine importierten Bücher. Nutzen Sie die Schaltfläche neben der Suchleiste, um ein Buch zu importieren.',
  'library.deleteBookConfirm': '„{{title}}“ löschen?',
  'library.tagAction': 'Zusammenstellung',

  'settings.language': 'Sprache',
  'settings.appLanguage': 'App-Sprache',
  'settings.appLanguageHint': 'Schaltflächen und Menüs. Unabhängig davon, welche Bibliothek Sie lesen.',
  'settings.restartForDirection': 'Zum Abschließen des Wechsels neu starten',
  'settings.restartForDirectionBody':
    '{{language}} wird von rechts nach links geschrieben. Schließen Sie Immerse und öffnen Sie es erneut, um das Layout umzustellen.',
  'settings.restartForDirectionBodyLtr':
    'Schließen Sie Immerse und öffnen Sie es erneut, um das Layout wieder auf links-nach-rechts umzustellen.',
  'settings.downloadedLibraries': 'Heruntergeladene Bibliotheken',
  'settings.downloadedLibrariesHint': 'Wechseln Sie zwischen ihnen über den Bibliotheksbildschirm.',
  'settings.includedWithApp': 'in der App enthalten',
  'settings.removeLanguageTitle': '{{language}} entfernen?',
  'settings.removeLanguageBody':
    'Diese Bücher werden von diesem Gerät gelöscht. Sie können sie jederzeit erneut herunterladen.',
  'settings.removeLanguageKeepsAnnotations':
    'Ihre {{annotations}} in diesen Büchern bleiben erhalten und erscheinen wieder, wenn Sie {{language}} erneut herunterladen.',
  'settings.removeFailed': 'Konnte nicht entfernt werden',
  'settings.account': 'Konto',
  'settings.fullName': 'Vollständiger Name',
  'settings.edit': 'Bearbeiten',
  'settings.username': 'Benutzername',
  'settings.plan': 'Tarif',
  'settings.fontSize': 'Schriftgröße',
  'settings.fontPreview': 'Vorschautext in Größe {{size}}. Diese Einstellung wird auf allen Ihren Geräten synchronisiert.',
  'settings.dailyReadings': 'Benachrichtigungen',
  'settings.randomVersesAndPlan': 'Zufällige Verse und Leseplan',
  'settings.readingMorningEvening': 'Eine Lesung morgens und abends',
  'settings.appearance': 'Darstellung',
  'settings.appearanceLight': 'Hell',
  'settings.appearanceDark': 'Dunkel',
  'settings.appearanceSystem': 'System',
  'settings.upgrade': 'Upgrade',
  'settings.upgradeCta': 'UPGRADE AUF PRO – 0,99 $/MONAT',
  'settings.upgradeBlurb':
    'Schalten Sie KI-Zusammenfassungen, hochwertige Vorlesestimmen und den Import eigener Bücher frei. 0,99 $/Monat.',
  'settings.purchases': 'Käufe',
  'settings.restorePurchase': 'Kauf wiederherstellen',
  'settings.restorePurchaseHint': 'Stellt bereits bezahlten Pro-Zugang wieder her – im App Store, bei Google Play oder im Web.',
  'settings.about': 'Über',
  'settings.version': 'Version',
  'settings.privacyPolicy': 'Datenschutzerklärung',
  'settings.viewExternal': 'Ansehen ↗',
  'settings.termsOfService': 'Nutzungsbedingungen',
  'settings.introTour': 'Einführungstour',
  'settings.fullFeatureVideo': 'Vollständiges Funktionsvideo',
  'settings.replayOnboarding': 'Einführungs-Screenshots erneut ansehen',
  'settings.view': 'Ansehen',
  'settings.watchFeatureVideo': 'Vollständiges Funktionsvideo ansehen',
  'settings.accountActions': 'Kontoaktionen',
  'settings.legal': 'Rechtliches',
  'settings.contactSupport': 'Support kontaktieren',
  'settings.communityGuidelines': 'Community-Richtlinien',
  'settings.signOut': 'Abmelden',
  'settings.deleteAccount': 'Konto löschen',
  'settings.deleting': 'Wird gelöscht…',
  'settings.error': 'Fehler',
  'settings.deleteAccountConfirm':
    'Dadurch werden Ihr Konto und alle Ihre Anmerkungen, Zusammenstellungen, Notizen und Ihr Lesefortschritt dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden.',
  'settings.areYouSure': 'Sind Sie sicher?',
  'settings.deleteAccountFinal':
    'Ihr Konto und alle Daten werden sofort gelöscht und können nicht wiederhergestellt werden.',
  'settings.deletePermanently': 'Ja, dauerhaft löschen',
  'settings.restoreFailed': 'Wiederherstellung fehlgeschlagen',
  'settings.proRestored': 'Pro wiederhergestellt!',
  'settings.proRestoredBody': 'Ihr Abonnement ist jetzt aktiv.',
  'settings.noSubscription': 'Kein Abonnement gefunden',
  'settings.noSubscriptionBody':
    'Wir konnten kein aktives Abonnement finden, das mit diesem Konto verknüpft ist.',
  'settings.planGuest': 'Gast',
  'settings.planStandard': 'Standard',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (Testphase)',

  'settings.welcomeToPro': 'Willkommen bei Pro!',
  'settings.manage': 'Verwalten',
  'settings.subscribeToPro': 'Pro abonnieren',

  // Home stat-tile label only (not the shelf name / nav). Truncated like
  // 'home.xrefs' — "Zusammenstellungen" is too long for the tile on small phones.
  'home.tags': 'Zusammenst.',
  'home.notes': 'Notizen',
  'home.xrefs': 'Querverw.',
  'home.readingPlan': 'LESEPLAN',
  'home.dailyVerses': 'TÄGLICHE VERSE',
  'home.dayStreak_one': 'Serie: {{count}} Tag',
  'home.dayStreak_other': 'Serie: {{count}} Tage',
  'home.dailyReading': 'Tägliche Lesung',
  'home.dailyReadingsTitle': 'Tägliche Lesungen',
  'home.tapToSetUp': 'Zum Einrichten tippen',
  'home.tapToReadVerse': 'Tippen, um einen Vers zu lesen',
  'home.tapToContinue': 'Zum Fortfahren tippen',
  'home.planFinished': 'Abgeschlossen – wählen Sie Ihr nächstes Buch',
  'home.recentlyViewed': 'Zuletzt angesehen',
  'home.removeFromRecent': 'Aus „Zuletzt angesehen“ entfernen',
  'home.removeFromRecentBody': '„{{title}}“ entfernen und den Lesefortschritt auf 0 % zurücksetzen?',
  'home.signInCreate': 'Anmelden / Registrieren',
  'home.startReadingHint': 'Beginnen Sie zu lesen, um Ihre zuletzt gelesenen Bücher hier zu sehen.',
  'home.viewLibrary': 'BIBLIOTHEK ANSEHEN',

  'home.signInBlurb': 'Melden Sie sich an, um Ihre zuletzt angesehenen Bücher, Anmerkungen und mehr auf all Ihren Geräten zu sehen.',

  'auth.tagline': 'Interreligiöser E-Reader & Recherche',
  'auth.usernamePlaceholder': 'Benutzername-ID *',
  'auth.fullNamePlaceholder': 'Vollständiger Name',
  'auth.emailPlaceholder': 'E-Mail-Adresse *',
  'auth.passwordPlaceholder': 'Passwort *',
  'auth.emailAddressPlaceholder': 'E-Mail-Adresse *',
  'auth.signIn': 'Anmelden',
  'auth.signUp': 'Registrieren',
  'auth.createAccount': 'Konto erstellen',
  'auth.forgotPassword': 'Passwort vergessen?',
  'auth.browseWithout': 'Ohne Konto durchsuchen',
  'auth.guestSubtext': 'Bücher lesen und durchsuchen – Fortschritt und Notizen werden nicht gespeichert',
  'auth.resetPassword': 'Passwort zurücksetzen',
  'auth.sendResetLink': 'Link zum Zurücksetzen senden',
  'auth.createPasswordPlaceholder': 'Passwort erstellen *',
  'auth.backToSignIn': 'Zurück zur Anmeldung',
  'auth.forgotBlurb':
    'Geben Sie Ihre E-Mail-Adresse ein, und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.',
  'auth.usernameAvailable': '✓ Verfügbar',
  'auth.usernameTakenShort': '✗ Vergeben',
  'auth.usernameHint': '3–20 Zeichen',
  'auth.usernameAlreadyTaken': 'Der Benutzername ist bereits vergeben.',
  'auth.resetLinkSent': 'Wir haben einen Link zum Zurücksetzen des Passworts an {{email}} gesendet',
  'auth.error': 'Fehler',
  'auth.missingFields': 'Fehlende Angaben',
  'auth.missingFieldsBody': 'Bitte geben Sie E-Mail und Passwort ein.',
  'auth.invalidUsername': 'Ungültiger Benutzername',
  'auth.invalidUsernameBody': 'Der Benutzername muss 3–20 Zeichen lang sein: nur Buchstaben, Zahlen und Unterstriche.',
  'auth.usernameTaken': 'Benutzername vergeben',
  'auth.usernameTakenBody': 'Bitte wählen Sie einen anderen Benutzernamen.',
  'auth.checkUsername': 'Benutzername prüfen',
  'auth.checkUsernameBody': 'Bitte warten Sie, bis die Benutzernamenprüfung abgeschlossen ist.',
  'auth.checkEmail': 'Prüfen Sie Ihre E-Mails',
  'auth.checkEmailBody': 'Wir haben einen Bestätigungslink an {{email}} gesendet',
  'auth.checkEmailSignInBody':
    'Wir haben einen Bestätigungslink an {{email}} gesendet. Melden Sie sich nach der Bestätigung an, um auf Ihr Konto zuzugreifen.',
  'auth.enterEmail': 'E-Mail eingeben',
  'auth.enterEmailBody': 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
  'auth.emailSent': 'E-Mail gesendet',
  'auth.emailSentBody': 'Prüfen Sie Ihren Posteingang auf einen Link zum Zurücksetzen des Passworts.',

  'auth.emailConfirmed': 'E-Mail bestätigt',
  'auth.accountReadySignIn':
    'Ihr Konto ist bereit. Melden Sie sich mit Ihrer E-Mail und Ihrem Passwort an, um loszulegen.',
  'auth.accountReadyOpenApp':
    'Ihr Konto ist bereit. Öffnen Sie die Immerse-App auf Ihrem Telefon, um sich anzumelden, oder fahren Sie unten im Web fort.',
  'auth.openingApp': 'Ihr Konto ist bereit. Die Immerse-App wird geöffnet und Sie werden angemeldet…',
  'auth.openImmerse': 'Immerse öffnen',
  'auth.continueOnWeb': 'Stattdessen im Web fortfahren',
  'auth.signInToImmerse': 'Bei Immerse anmelden',
  'auth.continueToImmerse': 'Weiter zu Immerse',
  'auth.chooseNewPassword': 'Wählen Sie ein neues Passwort für Ihr Konto',
  'auth.newPasswordPlaceholder': 'Neues Passwort',
  'auth.confirmNewPasswordPlaceholder': 'Neues Passwort bestätigen',
  'auth.updatePassword': 'Passwort aktualisieren',
  'auth.enterConfirmPassword': 'Bitte geben Sie Ihr neues Passwort ein und bestätigen Sie es.',
  'auth.passwordTooShort': 'Das Passwort muss mindestens 8 Zeichen lang sein.',
  'auth.passwordsDontMatch': 'Die Passwörter stimmen nicht überein.',
  'auth.passwordUpdated': 'Passwort aktualisiert',
  'auth.passwordUpdatedBody': 'Sie können jetzt Ihr neues Passwort verwenden.',
  'auth.resetFailed':
    'Ihr Passwort konnte nicht aktualisiert werden. Der Link zum Zurücksetzen ist möglicherweise abgelaufen – bitte fordern Sie einen neuen an.',

  'reminders.headerTitle': 'Tägliche Lesungen',
  'reminders.enable': 'Tägliche Lesungen aktivieren',
  'reminders.openSettings': 'Einstellungen öffnen',
  'reminders.source': 'Quelle',
  'reminders.randomVerses': 'Zufällige Verse',
  'reminders.readingPlan': 'Leseplan',
  'reminders.chooseBook': 'Ein Buch wählen',
  'reminders.bookFinished': 'Abgeschlossen ✓ – wählen Sie Ihr nächstes Buch',
  'reminders.sessionLength': 'Länge der Sitzung',
  'reminders.sessionCaption': 'Gilt für jede Sitzung – {{dur}} morgens und {{dur}} abends.',
  'reminders.reminders': 'Erinnerungen',
  'reminders.time': 'Uhrzeit',
  'reminders.morning': 'Morgens',
  'reminders.evening': 'Abends',
  'reminders.yourStreak': 'Ihre Serie',
  'reminders.today': 'Heute',
  'reminders.currentStreak': 'Aktuelle Serie',
  'reminders.bestStreak': 'Beste Serie',
  'reminders.completedBooks': 'Abgeschlossene Bücher',
  'reminders.day_one': '{{count}} Tag',
  'reminders.day_other': '{{count}} Tage',
  'reminders.hour': '1 Std.',
  'reminders.minutes': '{{count}} Min.',
  'reminders.signInRequired': 'Anmeldung erforderlich',
  'reminders.signInRequiredBody': 'Erstellen Sie ein Konto, um einem Leseplan zu folgen und Ihren Fortschritt zu verfolgen.',
  'reminders.notNow': 'Jetzt nicht',
  'reminders.enabledSub': 'Zeigt Ihre tägliche Lesung auf dem Startbildschirm an.',
  'reminders.disabledSub': 'Aus – Ihre tägliche Lesung wird auf dem Startbildschirm ausgeblendet.',
  'reminders.chooseNextToResume': 'Wählen Sie oben Ihr nächstes Buch, um die Erinnerungen fortzusetzen.',
  'reminders.chooseBookToEnable': 'Wählen Sie oben ein Buch, um Erinnerungen zu aktivieren.',
  'reminders.selectSourceToEnable': 'Wählen Sie oben mindestens eine Quelle, um Erinnerungen zu aktivieren.',
  'reminders.todayComplete': 'abgeschlossen ✓',
  'reminders.todayPending': 'ausstehend',
  'reminders.todayMorningDone': 'morgens ✓',
  'reminders.todayMorningPending': 'morgens ausstehend',
  'reminders.todayEveningDone': 'abends ✓',
  'reminders.todayEveningPending': 'abends ausstehend',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Tiefer lesen. Mehr verbinden.',
  'paywall.featureAiLabel': 'KI-Zusammenfassungen von Textstellen',
  'paywall.featureAiDesc': 'Bitten Sie um Erläuterungen und Kommentare zu jeder Textstelle',
  'paywall.featureVoicesLabel': 'Hochwertige Vorlesestimmen',
  'paywall.featureVoicesDesc': 'Natürliche, ausdrucksstarke Erzählung in der Stimme Ihrer Wahl',
  'paywall.featureImportLabel': 'Eigene Bücher importieren',
  'paywall.featureImportDesc': 'Fügen Sie EPUB-, PDF- und DOCX-Dateien zu Ihrer Bibliothek hinzu',
  'paywall.subscribe': 'Abonnieren – {{price}}/Monat',
  'paywall.cancelNote': 'Jederzeit kündbar · Monatliche Abrechnung',
  'paywall.restore': 'Käufe wiederherstellen',
  'paywall.terms': 'Nutzungsbedingungen',
  'paywall.privacy': 'Datenschutzerklärung',
  'paywall.notAvailable': 'Nicht verfügbar',
  'paywall.notAvailableBody': 'In-App-Käufe sind in dieser Version noch nicht eingerichtet. Schauen Sie nach dem App-Store-Release wieder vorbei.',
  'paywall.welcome': 'Willkommen bei Pro!',
  'paywall.welcomeBody': 'Ihr Abonnement ist jetzt aktiv.',
  'paywall.purchaseFailed': 'Kauf fehlgeschlagen',
  'paywall.restoreFailed': 'Wiederherstellung fehlgeschlagen',

  'xrefs.title': 'Querverweise',
  'xrefs.empty': 'Noch keine Querverweise. Querverweise, die Sie in der Leseansicht erstellen, erscheinen hier.',
  'xrefs.signInTitle': 'Anmelden, um Ihre Querverweise zu sehen',
  'xrefs.signInBody': 'Verbinden Sie verwandte Textstellen aus der gesamten Bibliothek.',
  'xrefs.searchSelected': 'Ausgewählte Querverweise durchsuchen…',
  'xrefs.searchPlaceholder': 'Textstellen oder Bezeichnungen durchsuchen…',
  'xrefs.noMatch': 'Keine Querverweise entsprechen Ihrer Suche.',
  'xrefs.addLabel': 'Bezeichnung hinzufügen…',
  'xrefs.deleteConfirm': 'Querverweis löschen?',
  'xrefs.deleteBody': 'Die beiden markierten Auswahlen bleiben erhalten.',

  'notes.title': 'Notizen',
  'notes.empty': 'Noch keine Notizen. Notizen, die Sie in der Leseansicht erstellen, erscheinen hier.',
  'notes.signInTitle': 'Anmelden, um Ihre Notizen zu sehen',
  'notes.signInBody': 'Fügen Sie Textstellen beim Lesen Kommentare und Gedanken hinzu.',
  'notes.searchPlaceholder': 'Notizen durchsuchen…',
  'notes.searchSelected': 'Ausgewählte Notizen durchsuchen…',
  'notes.byBook': 'Nach Buch',
  'notes.byDate': 'Nach Datum',
  'notes.writeNote': 'Schreiben Sie Ihre Notiz…',
  'notes.noMatch': 'Keine Notizen entsprechen Ihrer Suche.',
  'notes.deleteConfirm': 'Notiz löschen?',
  'notes.deleteBody': 'Die markierte Auswahl bleibt erhalten.',

  'tags.title': 'Zusammenstellungen',
  'tags.empty': 'Noch keine Zusammenstellungen. Zusammenstellungen, die Sie in der Leseansicht erstellen, erscheinen hier.',
  'tags.signInTitle': 'Anmelden, um Ihre Zusammenstellungen zu sehen',
  'tags.signInBody': 'Erstellen und ordnen Sie Zitat-Zusammenstellungen aus der gesamten Bibliothek.',
  'tags.organize': 'Ordnen',
  'tags.searchPlaceholder': 'Zusammenstellungen durchsuchen…',
  'tags.searchSelected': 'Ausgewählte Zusammenstellungen durchsuchen…',
  'tags.noMatch': 'Keine Zusammenstellungen entsprechen Ihrer Suche.',
  'tags.deleteConfirm': 'Zusammenstellung löschen?',
  'tags.deleteBody': '„{{name}}“ und alle darin enthaltenen Auswahlen werden entfernt.',

  'tags.renameTitle': 'Zusammenstellung umbenennen',
  'tags.setPrivate': 'Auf privat setzen',
  'tags.setPublic': 'Auf öffentlich setzen',
  'tags.publicTag': 'Öffentliche Zusammenstellung',
  'tags.removePassage': 'Aus Zusammenstellung entfernen',
  'tags.removePassageConfirm': 'Diese Textstelle aus der Zusammenstellung entfernen?',
  'tags.indent': 'Einrücken',
  'tags.outdent': 'Ausrücken',
  'tags.organizeHint':
    'Ziehen Sie am Griff zum Umsortieren · ⇤ ⇥ zum Ändern der Verschachtelung · tippen Sie auf eine Zusammenstellung, um ihre Zitate umzusortieren.',
  'tags.searchTagsPassages': 'Zusammenstellungen und Textstellen durchsuchen…',
  'tags.exportSelected': 'Ausgewählte Zusammenstellungen exportieren',
  'xrefs.exportSelected': 'Ausgewählte Querverweise exportieren',
  'tags.export': 'Exportieren',
  'tags.exporting': 'Wird exportiert…',
  'tags.exportInclude': 'Einschließen',
  'tags.exportNothingToInclude': 'Keine der ausgewählten Zusammenstellungen hat {{items}}',

  'panel.createAccount': 'Konto erstellen',
  'panel.signInToSave': 'Erstellen Sie ein kostenloses Konto, um Zusammenstellungen, Notizen und Querverweise zu speichern.',
  'panel.editSelection': 'Textauswahl bearbeiten',

  'reader.xrefMode': 'Querverweis-Modus – lange drücken, um eine Textstelle zu wählen',
  'reader.error': 'Fehler in der Leseansicht',
  'reader.opening': 'Buch wird geöffnet…',
  'reader.footnote': 'Fußnote',

  'reader.selectBook': 'Wählen Sie ein Buch, um mit dem Lesen zu beginnen',
  'reader.tableOfContents': 'Inhaltsverzeichnis',
  'reader.tocButtonHint': 'Zu einem Abschnitt in diesem Buch springen',
  'reader.expandSection': 'Abschnitt ausklappen',
  'reader.collapseSection': 'Abschnitt einklappen',
  'reader.expand': 'Ausklappen',
  'reader.collapse': 'Einklappen',
  'reader.actionTag': 'Zusammenstellung',
  'reader.actionNote': 'Notiz',
  'reader.actionXref': 'Querverw.',
  'reader.actionAi': 'KI',
  'reader.actionCopy': 'Kopieren',
  'reader.updateSelection': 'Auswahl aktualisieren',
  'reader.updating': 'Wird aktualisiert…',
  'reader.pickAsXref': 'Als Querverweis wählen',
  'reader.editSelectionHint':
    'Markieren Sie den neuen Text für diese Anmerkung und wählen Sie dann',
  'reader.savingXref': 'Querverweis wird gespeichert…',
  'reader.pickTargetHint': 'Text auswählen oder auf eine Textstelle klicken, um zu verknüpfen',
  'reader.footnoteUnavailable': 'Fußnotentext ist in der Web-Version nicht verfügbar.',
  'reader.bookNotFound': 'Buch nicht gefunden',
  'reader.viewTags': 'Zusammenstellungen ansehen',
  'reader.viewNote': 'Notiz ansehen',
  'reader.viewXrefs': 'Querverweise ansehen',
  'reader.noQuotesFiled': 'Hier sind keine Zitate abgelegt.',
  'reader.importedStubBody':
    'Dieses Buch ist nicht auf diesem Gerät. Importieren Sie die Datei erneut, um es hier zu lesen — Ihre Notizen und Zusammenstellungen dazu bleiben erhalten.',

  'ai.summary': 'KI-Zusammenfassung',
  'ai.upgradeBlurb': 'Führen Sie für nur 0,99 $ ein Upgrade auf Immerse Pro durch, um KI-Zusammenfassungen und weitere Pro-Funktionen zu nutzen.',
  'ai.upgradeBtn': 'Upgrade auf Pro – 0,99 $/Monat',
  'ai.thinking': 'Denkt nach…',
  'ai.error': 'KI-Zusammenfassung konnte nicht abgerufen werden. Bitte prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
  'ai.copied': '✓ Kopiert',
  'ai.copyHint': 'Zum Kopieren lange drücken',

  'note.title': 'Notiz',
  'note.addTitle': 'Notiz hinzufügen',
  'note.placeholder': 'Schreiben Sie hier Ihre Notiz…',
  'note.loading': 'Wird geladen…',
  'note.emptyTitle': 'Leere Notiz',
  'note.emptyBody': 'Bitte schreiben Sie etwas, bevor Sie speichern.',
  'note.saveFailed': 'Notiz konnte nicht gespeichert werden',
  'note.deleteTitle': 'Notiz löschen?',
  'note.deleteBody': 'Dadurch wird die Notiz entfernt. Wenn diese Textstelle keine weiteren Anmerkungen hat, wird auch die Auswahl entfernt.',
  'note.deleteFailed': 'Notiz konnte nicht gelöscht werden',
  'note.signInRequired': 'Anmeldung erforderlich',
  'note.signInBody': 'Notizen werden in Ihrem Konto gespeichert. Bitte melden Sie sich an oder erstellen Sie ein Konto.',

  'xref.title': 'Querverweis',
  'xref.yourSelection': 'IHRE AUSWAHL',
  'xref.pickSecond': 'Zweite Textstelle wählen  →',
  'xref.noneFound': 'Keine Querverweise gefunden.',

  'xref.findPassage': 'Eine Textstelle zum Verknüpfen finden',
  'xref.searchPlaceholder': 'Beliebige Textstelle durchsuchen…',
  'xref.save': 'Querverweis speichern',
  'xref.from': 'Von',
  'xref.to': 'Zu',
  'xref.linksTo': 'verweist auf',

  'xref.suggestMatch': 'Eine Entsprechung vorschlagen',
  'xref.suggesting': 'Verwandte Textstellen werden gesucht…',
  'xref.suggestError': 'Vorschläge konnten gerade nicht abgerufen werden',
  'xref.noMatches': 'Keine Entsprechungen gefunden. Wählen Sie selbst eine aus.',
  'xref.looseMatch': 'lose Entsprechung',
  'xref.useThisPassage': 'Diese Textstelle verwenden',
  'xref.inCompilation': 'In Ihrer Zusammenstellung „{{name}}“',
  'xref.youNotedThis': 'Sie haben diese Textstelle mit einer Notiz versehen',

  'banner.googlePlay': 'Bei Google Play herunterladen',
  'banner.appStore': 'Im App Store laden',
  'banner.install': 'Installieren',
  'banner.get': 'Holen',

  'tagPanel.new': 'Neue Zusammenstellung',
  'tagPanel.createWithin': 'Eine Zusammenstellung innerhalb von „{{parent}}“ erstellen',
  'tagPanel.addTitle': 'Zu Zusammenstellung hinzufügen',
  'tagPanel.viewTitle': 'Zusammenstellungen',
  'tagPanel.addSubTag': 'Unter-Zusammenstellung hinzufügen',
  'tagPanel.emptyAdd': 'Noch keine Zusammenstellungen – erstellen Sie oben eine',
  'tagPanel.emptyView': 'Keine Zusammenstellungen für diese Auswahl',

  'voice.title': 'Vorlesestimme',
  'voice.onyx': 'Onyx – tief & warm',
  'voice.cedar': 'Cedar – natürlich & voll',
  'voice.ash': 'Ash – klar & direkt',
  'voice.nova': 'Nova – hell',
  'voice.shimmer': 'Shimmer – weich',
  'voice.marin': 'Marin – natürlich & sanft',

  'reader.signInRequired': 'Anmeldung erforderlich',
  'reader.signInBody': 'Erstellen Sie ein Konto, um Zusammenstellungen, Notizen und Querverweise beim Lesen zu speichern.',
  'reader.notNow': 'Jetzt nicht',
  'reader.signIn': 'Anmelden',
  'reader.pdfNotFound': 'Die PDF-Datei konnte nicht gefunden werden.',
  'reader.contentLoadFailed': 'Inhalt konnte nicht geladen werden',
  'reader.noBook': 'Kein Buch angegeben',
  'reader.storageError': 'Speicherfehler',

  'discover.recent': 'NEU',
  'discover.trending': 'BELIEBT',
  'discover.searchPlaceholder': 'Zusammenstellungen und Nutzer durchsuchen…',
  'discover.searchSelected': 'Ausgewählte Zusammenstellungen durchsuchen…',
  'discover.import': 'Importieren',
  'discover.imported': 'Importiert',
  'discover.import_one': '{{count}} Import',
  'discover.import_other': '{{count}} Importe',
  'discover.noneYet': 'Noch keine geteilten Zusammenstellungen',
  'discover.noResults': 'Keine Ergebnisse',
  'discover.tryDifferent': 'Versuchen Sie einen anderen Suchbegriff.',
  'discover.signInTitle': 'Anmelden, um auf Entdecken zuzugreifen',
  'discover.signInBody': 'Sehen Sie, was andere Leser über alle Traditionen hinweg entdecken.',
  'discover.anonymous': 'Anonym',
  'discover.beFirst': 'Teilen Sie als Erste oder Erster eine Zusammenstellung.',
  'discover.ownTag': 'Dies ist Ihre eigene Zusammenstellung',
  'discover.alreadyImported': 'Bereits importiert',
  'discover.importFailed': 'Import fehlgeschlagen',
  'discover.exportFailed': 'Export fehlgeschlagen',
  'discover.unknownError': 'Unbekannter Fehler',

  // ── Importierte Bücher: Entdecken / Freigabelinks (Plan B) ────────────────
  'discover.importedDroppedTitle': 'Hinweis',
  'discover.importedDroppedNotice_one':
    '{{count}} Zitat aus einem importierten Buch wurde ausgelassen — importierte Bücher werden nicht öffentlich angezeigt.',
  'discover.importedDroppedNotice_other':
    '{{count}} Zitate aus importierten Büchern wurden ausgelassen — importierte Bücher werden nicht öffentlich angezeigt.',
  'discover.publishBlockedTitle': 'Veröffentlichen nicht möglich',
  'discover.publishFailed': 'Diese Zusammenstellung konnte nicht veröffentlicht werden.',
  'discover.importedOnlyError':
    'Die Zitate dieser Zusammenstellung stammen alle aus importierten Büchern, die nicht in Entdecken veröffentlicht werden können.',

  'usertags.autoImports': 'Importiert automatisch die öffentlichen Zusammenstellungen der Nutzerin oder des Nutzers in Ihre App',
  'usertags.noTags': 'Keine öffentlichen Zusammenstellungen',
  'usertags.noTagsBody': 'Diese Person hat noch keine Zusammenstellungen geteilt.',
  'usertags.follow': 'Folgen',
  'usertags.unfollow': 'Nicht mehr folgen',
  'usertags.share': 'Teilen',
  'usertags.error': 'Fehler',
  'usertags.somethingWrong': 'Etwas ist schiefgelaufen',

  'onboarding.chooseLanguage': 'Wählen Sie Ihre Sprache',
  'onboarding.changeLaterSettings': 'Sie können dies später in den Einstellungen ändern.',
  'onboarding.libraryDownloadHint': 'Um die Bibliothek in {{language}} herunterzuladen, tippen Sie auf das ⌄ neben „Bibliothek“ im Bibliotheksbildschirm.',
  'onboarding.continue': 'Weiter',
  'onboarding.chooseTextSize': 'Wählen Sie die Textgröße',
  'onboarding.fontPreviewQuote':
    '„Suchet, so werdet ihr finden; klopfet an, so wird euch aufgetan.“',
  'onboarding.getStarted': 'Loslegen',

  'onboarding.closeIntro': 'Einführung schließen',
  'onboarding.goToStep': 'Zu Schritt {{number}} gehen',
  'onboarding.libraryTitle': 'Die Bibliothek',
  'onboarding.libraryCaption': 'Durchstöbern Sie eine kuratierte Bibliothek mehrerer Traditionen. Tippen Sie auf ein Buch, um mit dem Lesen zu beginnen.',
  'onboarding.searchTitle': 'Alles durchsuchen',
  'onboarding.searchCaption': 'Durchsuchen Sie alle Bücher gleichzeitig und springen Sie direkt zur Textstelle.',
  'onboarding.tagAsYouGoTitle': 'Beim Lesen zusammenstellen',
  'onboarding.tagAsYouGoCaption': 'Fügen Sie eine Textstelle direkt aus den Suchergebnissen zu einer Zusammenstellung hinzu.',
  'onboarding.buildTagsTitle': 'Bauen Sie Ihre Zusammenstellungen auf',
  'onboarding.buildTagsCaption': 'Gruppieren Sie Textstellen unter Ihren eigenen Zusammenstellungen, um sie leicht wiederzufinden.',
  'onboarding.selectActTitle': 'Auswählen & handeln',
  'onboarding.selectActCaption': 'Wählen Sie beliebigen Text aus, um ihn zu markieren, zusammenzustellen, zu notieren oder als Querverweis zu verknüpfen.',
  'onboarding.marginTitle': 'Anmerkungen am Rand',
  'onboarding.marginCaption': 'Ihre Zusammenstellungen, Notizen und Querverweise befinden sich am Rand.',
  'onboarding.navigateTitle': 'Schnell navigieren',
  'onboarding.navigateCaption': 'Öffnen Sie das Inhaltsverzeichnis, um sich in einem Buch zu bewegen.',
  'onboarding.yourTagsTitle': 'Ihre Zusammenstellungen',
  'onboarding.yourTagsCaption': 'Kehren Sie zu jeder zusammengestellten Textstelle zurück, geordnet nach Zusammenstellung.',
  'onboarding.xrefsTitle': 'Querverweise',
  'onboarding.xrefsCaption': 'Verknüpfen Sie verwandte Textstellen über Bücher und Traditionen hinweg.',
  'onboarding.shareTitle': 'Teilen & veröffentlichen',
  'onboarding.shareCaption': 'Teilen Sie ein Zitat oder veröffentlichen Sie eine Zusammenstellung für die Community.',

  'share.createLink': 'Freigabelink erstellen',
  'share.createLinkHint': 'Eine private Webseite. Wird nicht in Entdecken angezeigt.',
  'share.createLinkMultiHint': 'Eine private Webseite mit allen ausgewählten Zusammenstellungen. Wird nicht in Entdecken angezeigt.',
  'share.bundleTitle': 'Geteilte Zusammenstellungen',
  'share.linkReady': 'Link bereit',
  'share.linkCopied': 'Link kopiert',
  'share.copyLink': 'Link kopieren',
  'share.shareVia': 'Teilen…',
  'share.revoke': 'Widerrufen',
  'share.revokeConfirm': 'Diesen Link widerrufen? Wer ihn hat, verliert den Zugriff.',
  'share.discoverToggle': 'In Entdecken veröffentlichen',
  'share.discoverToggleHint': 'Jeder kann diese Zusammenstellung finden und speichern.',
  'share.stopDiscover': 'Aus Entdecken entfernen',
  'share.publishedNote': 'In Entdecken veröffentlicht – schalten Sie den Schalter aus, um das Teilen zu beenden.',
  'share.selectOne': 'Wählen Sie eine Zusammenstellung, um einen Link zu erstellen.',
  'sharePage.eyebrow': 'Geteilte Zusammenstellung',
  'sharePage.openInReader': 'In der Leseansicht öffnen',
  'sharePage.save': 'In meinen Zusammenstellungen speichern',
  'sharePage.saving': 'Wird gespeichert…',
  'sharePage.saved': 'In Ihren Zusammenstellungen gespeichert',
  'sharePage.saveHint': 'Öffnet die Immerse-App, oder melden Sie sich an, um im Web zu speichern.',
  'sharePage.signInToSave': 'Melden Sie sich an, um dies in Ihren Zusammenstellungen zu speichern.',
  'sharePage.footer': 'Mehr lesen in Immerse',
  'sharePage.needLanguagePack':
    'Dieses Zitat stammt aus der Bibliothek {{language}}. Laden Sie sie über das Sprachmenü in „Bibliothek“ herunter, um es hier zu lesen.',
  'sharePage.viewOnly': 'Diese geteilte Zusammenstellung kann nur angesehen werden.',
  'sharePage.fromPrivateImport': 'aus einem privaten Import',

  'share.createLinkXrefHint': 'Eine private Webseite, die diese Querverweise zeigt. Wird nicht in Entdecken angezeigt.',
  'sharePage.xrefEyebrow': 'Geteilte Querverweise',
  'sharePage.saveXrefs': 'In meinen Querverweisen speichern',
  'sharePage.savedXrefs': 'In Ihren Querverweisen gespeichert',
  'sharePage.savedXrefsPartial': '{{saved}} von {{total}} gespeichert – {{skipped}} benötigen Inhalte, die Sie nicht haben',
  'sharePage.xrefsGone': 'Diese Querverweise sind nicht mehr verfügbar',

  'export.shareTags_one': '{{count}} Zusammenstellung teilen',
  'export.shareTags_other': '{{count}} Zusammenstellungen teilen',
  'export.shareTagsGeneric': 'Zusammenstellungen teilen',
  'export.shareXrefs_one': '{{count}} Querverweis teilen',
  'export.shareXrefs_other': '{{count}} Querverweise teilen',
  'export.preparing': 'Wird vorbereitet…',
  'export.notesOn': 'Ihre schriftlichen Notizen zu jeder Textstelle',
  'export.notesNone': 'Keine Notizen zu diesen Textstellen',
  'export.xrefsOn': 'Verknüpfte Textstellen unter jedem Zitat',
  'export.xrefsNone': 'Keine Querverweise zu diesen Textstellen',
  'export.docxTitle': 'Word-Dokument (.docx)',
  'export.docxShort': 'Word (.docx)',
  'export.docxDesc': 'Zusammenstellungs-Überschriften mit zitierten Textstellen. Öffnet sich in Word, Pages oder Google Docs.',
  'export.pdfTitle': 'PDF-Dokument',
  'export.pdfDesc': 'Formatiertes Dokument zum Drucken oder Teilen.',
  'export.csvTitle': 'Tabelle (.csv)',
  'export.csvDesc': 'Eine Zeile pro Textstelle. Öffnet sich in Excel, Numbers oder Google Sheets.',
  'export.mdTitle': 'Markdown (.md)',
  'export.mdDesc': 'Für Obsidian, Notion oder jedes Klartext-Werkzeug.',
  'export.noPassagesTagged': '(keine Textstellen in dieser Zusammenstellung)',
  'export.seeAlso': 'Siehe auch:',

  'plan.chooseBook': 'Ein Buch wählen',
  'plan.searchBooks': 'Bücher durchsuchen…',
  'plan.noBooksMatch': 'Keine Bücher entsprechen „{{query}}“.',
  'plan.readingComplete': 'Lesung abgeschlossen',
  'plan.morningSession': 'Morgensitzung',
  'plan.eveningSession': 'Abendsitzung',
  'plan.minutes': '{{count}} Min.',
  'plan.streakDay': 'Serientag {{count}} ✓',
  'plan.sessionsToday': '{{done}} von {{required}} Sitzungen heute',
  'plan.youFinished': 'Sie haben {{title}} abgeschlossen',
  'plan.readOverDays_one': 'Über {{count}} Tag gelesen',
  'plan.readOverDays_other': 'Über {{count}} Tage gelesen',
  'plan.remindersPaused': 'Erinnerungen sind pausiert',
  'plan.chooseNextBook': 'Wählen Sie Ihr nächstes Buch',
  'completed.title': 'Abgeschlossene Bücher',
  'completed.empty': 'Bücher, die Sie in Ihrem Leseplan abschließen, erscheinen hier.',
  'completed.finishedOn': 'Abgeschlossen am {{date}}',
  'completed.day_one': '{{count}} Tag',
  'completed.day_other': '{{count}} Tage',

  'library.selectPassageForXref': 'Textstelle für Querverweis auswählen',
  'library.findingRelated': 'Verwandte Textstellen werden gesucht…',
  'library.aiSearchOffline': 'Für die Suche per Frage ist eine Internetverbindung erforderlich',
  'library.importFailedTitle': 'Import fehlgeschlagen',
  'library.couldNotImport': 'Die Datei konnte nicht importiert werden.',
  'library.bookAdded': 'Buch hinzugefügt',
  'library.bookAddedBody': '„{{title}}“ ist jetzt in „Meine Bücher“.',
  'library.importErrorTitle': 'Importfehler',
  'library.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten.',
  'nav.browsingAsGuest': 'Als Gast unterwegs',
  'reader.selectBookToBegin': 'Wählen Sie ein Buch, um mit dem Lesen zu beginnen',
  'tags.exportFailed': 'Export fehlgeschlagen',
  'tags.couldNotExport': 'Zusammenstellungen konnten nicht exportiert werden.',
  'tags.couldNotRemoveSelection': 'Auswahl konnte nicht entfernt werden',
  'tags.reorderHint': 'Ziehen Sie am Griff zum Umsortieren · ⇤ ⇥ zum Ändern der Verschachtelung · tippen Sie auf eine Zusammenstellung, um ihre Zitate umzusortieren.',
  'tags.swipeHint': 'Wischen Sie auf einer Zusammenstellung nach rechts, um sie öffentlich oder privat zu machen.',
  'discover.publishHint': 'Wischen Sie im Bildschirm „Zusammenstellungen“ auf einer Zusammenstellung nach rechts, um sie hier zu veröffentlichen.',
  'reminders.notificationsOff':
    'Benachrichtigungen für Immerse sind ausgeschaltet, daher können keine Erinnerungen zugestellt werden. '
    + 'Aktivieren Sie sie in Ihren Geräteeinstellungen.',
  'plan.continueJourney': 'Setzen Sie Ihre Lesereise fort',
  'plan.yourBook': 'Ihr Buch',
  'reader.notesInParagraph_one': '{{count}} Notiz in diesem Absatz',
  'reader.notesInParagraph_other': '{{count}} Notizen in diesem Absatz',
  'plan.awaitsMorning': '{{book}} wartet – Morgenlesung',
  'plan.awaitsEvening': '{{book}} wartet – Abendlesung',
  'reminders.dailyReadingFrom': 'Tägliche Lesung · {{source}}',
  'library.tapToExpandHint': 'Tippen zum Ausklappen · Halten zum Öffnen in der Leseansicht',
  'library.deleteBookImportedBody': 'Dieses Buch und alle seine Anmerkungen werden dauerhaft entfernt.',
  'library.deleteBookBundledBody':
    'Dieses Buch und alle seine Anmerkungen werden entfernt. Es kehrt zurück, wenn die Bibliothek das nächste Mal aktualisiert wird.',
  'library.deleteCategoryConfirm': '„{{name}}“ löschen?',
  'library.deleteCategoryBody_one': 'Dadurch werden auch {{count}} Buch und alle seine Anmerkungen entfernt.',
  'library.deleteCategoryBody_other': 'Dadurch werden auch {{count}} Bücher und alle ihre Anmerkungen entfernt.',
  'library.deleteCategoryEmptyBody': 'Diese Kategorie wird dauerhaft entfernt.',

  // ── Importierte Bücher: erneuter Import & Mehrfachimport (Plan B) ─────────
  'library.reimportToRead': 'Zum Lesen erneut importieren',
  'library.importFinishedTitle': 'Import abgeschlossen',
  'library.multiImportSummary_one': '{{count}} Buch importiert.',
  'library.multiImportSummary_other': '{{count}} Bücher importiert.',
  'library.multiImportFailed_one': '{{count}} Datei konnte nicht gelesen werden: {{names}}.',
  'library.multiImportFailed_other': '{{count}} Dateien konnten nicht gelesen werden: {{names}}.',
  'library.stubNotFound': 'Dieses Buch ist nicht mehr in Ihrer Bibliothek.',
  'library.stubNotImported': 'Das ist kein importiertes Buch.',
  'library.stubAlreadyHasContent': 'Dieses Buch hat auf diesem Gerät bereits Inhalte.',

  'auth.passwordTooShortTitle': 'Passwort zu kurz',
  'auth.passwordsMustMatch': 'Bitte stellen Sie sicher, dass beide Passwörter gleich sind.',
  'auth.usernamePlain': 'Benutzername-ID',
  'auth.fullNameOptional': 'Vollständiger Name (optional)',
  'auth.emailPlain': 'E-Mail',
  'auth.passwordPlain': 'Passwort',
  'auth.emailAddressPlain': 'E-Mail-Adresse',

  'onboarding.skip': 'Überspringen',
  'onboarding.tour.libraryMain.label': 'Bibliotheksbildschirm',
  'onboarding.tour.libraryMain.caption':
    'Die Bibliothek umfasst über 400 heilige Texte aus allen großen Traditionen. Tippen Sie auf eine Tradition, um ihre Bücher zu erkunden.',
  'onboarding.tour.libraryExpanded.label': 'Bibliothek ausgeklappt',
  'onboarding.tour.libraryExpanded.caption':
    'Jede Tradition klappt auf und zeigt Autoren und Sammlungen. Tippen Sie auf einen Titel, um ihn in der Leseansicht zu öffnen.',
  'onboarding.tour.librarySearch.label': 'Bibliothekssuche',
  'onboarding.tour.librarySearch.caption':
    'Durchsuchen Sie alle über 400 Texte gleichzeitig. Tippen Sie auf ein Ergebnis, um es auszuklappen – lange drücken, um es direkt in der Leseansicht zu öffnen.',
  'onboarding.tour.searchQuickTag.label': 'Schnelle Zusammenstellung aus Suchergebnissen',
  'onboarding.tour.searchQuickTag.caption':
    'Wählen Sie eines oder viele Suchergebnisse aus und ordnen Sie sie mit einem Tipp einer Zusammenstellung zu. Ein schneller Weg, eine thematische Sammlung aus der gesamten Bibliothek aufzubauen.',
  'onboarding.tour.home.label': 'Startbildschirm',
  'onboarding.tour.home.caption':
    'Ihr Startbildschirm zeigt, wie viele Zusammenstellungen, Notizen und Querverweise Sie erstellt haben, sowie Ihre zuletzt gelesenen Bücher. Tippen Sie auf einen Titel, um weiterzulesen.',
  'onboarding.tour.homePlan.label': 'Leseplan auf dem Startbildschirm',
  'onboarding.tour.homePlan.caption':
    'Bauen Sie eine tägliche Lesegewohnheit auf: Folgen Sie einem Leseplan durch ein Buch Ihrer Wahl und in der Dauer Ihrer Wahl, oder erhalten Sie zufällige Verse aus den von Ihnen gewählten Traditionen – mit täglichen Erinnerungen und einer Serie, die mit jedem Lesetag wächst.',
  'onboarding.tour.settingsDaily.label': 'Einstellungen für tägliche Lesungen',
  'onboarding.tour.settingsDaily.caption':
    'Richten Sie in den Einstellungen zufällige Verse ein, indem Sie die Traditionen und die Tageszeiten wählen, zu denen Sie eine sanfte Erinnerung möchten – oder wechseln Sie zu einem Leseplan, um täglich ein Buch durchzuarbeiten.',
  'onboarding.tour.readerSelect.label': 'Leseansicht mit Textauswahl',
  'onboarding.tour.readerSelect.caption':
    'Drücken Sie lange auf eine Textstelle, um sie auszuwählen. Nutzen Sie die Symbole am unteren Bildschirmrand, um sie einer Zusammenstellung hinzuzufügen, eine Notiz zu ergänzen, einen Querverweis zu erstellen oder eine KI-Zusammenfassung zu erhalten.',
  'onboarding.tour.readerNote.label': 'Leseansicht mit Notiz',
  'onboarding.tour.readerNote.caption':
    'Notizen hängen an genau dem Text, den Sie ausgewählt haben. Über die goldene Markierung am Rand finden und öffnen Sie sie jederzeit wieder.',
  'onboarding.tour.readerXref.label': 'Leseansicht mit Querverweis',
  'onboarding.tour.readerXref.caption':
    'Querverweise verknüpfen Textstellen über verschiedene Bücher und Traditionen hinweg. Drücken Sie lange auf ein verknüpftes Zitat, um in der Leseansicht dorthin zu springen.',
  'onboarding.tour.readerAi.label': 'KI-Zusammenfassung in der Leseansicht',
  'onboarding.tour.readerAi.caption':
    'Nachdem Sie eine Textstelle ausgewählt haben, tippen Sie auf das Funkel-Symbol für eine sofortige KI-Zusammenfassung – besonders hilfreich bei dichten oder unbekannten Texten.',
  'onboarding.tour.readerListen.label': 'Vorlesemodus der Leseansicht',
  'onboarding.tour.readerListen.caption':
    'Tippen Sie auf die Kopfhörer-Schaltfläche, um sich jedes Buch vorlesen zu lassen – die Leseansicht hebt jede Textstelle beim Abspielen hervor. Halten Sie die Kopfhörer-Schaltfläche gedrückt, um aus einer Auswahl natürlicher Stimmen zu wählen.',
  'onboarding.tour.tags.label': 'Zusammenstellungsbildschirm',
  'onboarding.tour.tags.caption':
    'Der Zusammenstellungsbildschirm gruppiert Ihre zusammengestellten Textstellen nach Thema. Tippen Sie auf den Namen einer Zusammenstellung, um ihre zitierten Textstellen mit vollständigen Quellenangaben zu sehen.',
  'onboarding.tour.xrefs.label': 'Querverweisbildschirm',
  'onboarding.tour.xrefs.caption':
    'Der Querverweisbildschirm zeigt alle Ihre verknüpften Textstellen nebeneinander. Drücken Sie lange auf eine der beiden Seiten, um in der Leseansicht zu dieser Textstelle zu springen.',
  'onboarding.tour.discover.label': 'Entdecken-Bildschirm',
  'onboarding.tour.discover.caption':
    'Im Entdecken-Bildschirm finden Sie Zusammenstellungen, die andere Leser geteilt haben. Tippen Sie auf eine Zusammenstellung, um ihre Textstellen anzusehen, und importieren Sie sie dann in Ihre eigene Bibliothek.',
  'onboarding.tour.tagShare.label': 'Freigabefeld für Zusammenstellungen',
  'onboarding.tour.tagShare.caption':
    'Exportieren Sie jede Zusammenstellung als Word-Dokument, PDF, Tabelle, Markdown und mehr – samt Ihren Notizen und Querverweisen.',

  'appearance.title': 'Darstellung',
  'appearance.navHint': 'Schriftart, Abstände, Seitenfarbe',
  'appearance.reading': 'Lesen',
  'appearance.preview': 'Vorschau',
  'appearance.previewText': 'Lesen ist ein stilles Gespräch, das über Jahrhunderte hinweg reicht.',
  'appearance.previewHeading': 'Erstes Kapitel',
  'appearance.typeface': 'Schriftart',
  'appearance.typefaceSystem': 'System',
  'appearance.typefaceLiterataBlurb': 'Für langes Lesen gemacht. Passt sich der Größe an.',
  'appearance.typefaceCharisBlurb': 'Ein Charter-Nachfahre. Robust in kleiner Größe.',
  'appearance.typefaceGaramondBlurb': 'Klassische Renaissance-Antiqua. Leichter auf der Seite.',
  'appearance.typefaceSystemBlurb': 'Was auch immer dieses Gerät bereitstellt.',
  'appearance.textSize': 'Textgröße',
  'appearance.lineSpacing': 'Zeilenabstand',
  'appearance.lineSpacingTight': 'Eng',
  'appearance.lineSpacingNormal': 'Normal',
  'appearance.lineSpacingRelaxed': 'Locker',
  'appearance.lineSpacingLoose': 'Weit',
  'appearance.margins': 'Ränder',
  'appearance.marginsNarrow': 'Schmal',
  'appearance.marginsNormal': 'Normal',
  'appearance.marginsWide': 'Breit',
  'appearance.justify': 'Blocksatz',
  'appearance.justifyHint': 'Richtet beide Ränder aus, mit Silbentrennung.',
  'appearance.paragraphStyle': 'Absätze',
  'appearance.paragraphSpaced': 'Mit Abstand',
  'appearance.paragraphIndented': 'Eingerückt',
  'appearance.paragraphHint': 'Eingerückt ist die traditionelle Buchgestaltung.',
  'appearance.theme': 'Seitenfarbe',
  'appearance.themeLight': 'Hell',
  'appearance.themeSepia': 'Sepia',
  'appearance.themeQuiet': 'Gedämpft',
  'appearance.themeDark': 'Dunkel',
  'appearance.themeNight': 'Nacht',
  'appearance.themeSystem': 'An App anpassen',
  'appearance.fineTuning': 'Feinabstimmung',
  'appearance.characterSpacing': 'Zeichenabstand',
  'appearance.wordSpacing': 'Wortabstand',
  'appearance.textWeight': 'Schriftstärke',
  'appearance.paragraphNumbers': 'Absatznummern',
  'appearance.paragraphNumbersHint': 'Referenznummern am Rand anzeigen.',
  'appearance.appTheme': 'App-Design',
  'appearance.appThemeHint': 'Gilt außerhalb der Leseansicht.',
  'appearance.reset': 'Auf Standard zurücksetzen',

  'citation.bible': 'Die Bibel',
  'citation.tanakh': 'Tanach',
  'citation.quran': 'Der Koran',
  'citation.guruGranthSahib': 'Guru Granth Sahib',
};
