/**
 * English UI strings — the reference locale.
 *
 * Keys are `screen.element`, or `common.*` for anything genuinely shared. Add a
 * key here first: en is the fallback for every other locale, so a string absent
 * here has nothing to fall back to.
 *
 * Plurals use `_one` / `_other` suffixes, selected by the `count` variable.
 * Interpolation is `{{name}}`.
 *
 * These are interface strings only. Scripture is content and lives in the
 * corpus, never here.
 */
export const en = {
  'common.cancel': 'Cancel',
  'common.remove': 'Remove',
  'common.removing': 'Removing…',
  'common.save': 'Save',
  'common.done': 'Done',
  'common.tryAgain': 'Please try again.',
  'common.delete': 'Delete',
  'common.clear': 'Clear',
  'common.signInCreate': 'Sign In or Create Account',
  'common.book_one': '{{count}} book',
  'common.book_other': '{{count}} books',
  'common.saving': 'Saving…',
  'common.loading': 'Loading…',
  'common.copy': 'Copy',
  'common.retry': 'Try again',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.searching': 'Searching…',
  'common.noResults': 'No results found.',
  'common.dismiss': 'Dismiss',
  'common.options': 'Options',
  'common.collapseLibrary': 'Collapse Library',
  'common.expandLibrary': 'Expand Library',
  'common.minutesAgo': '{{count}}m ago',
  'common.hoursAgo': '{{count}}h ago',
  'common.daysAgo': '{{count}}d ago',
  'common.highlight_one': '{{count}} highlight',
  'common.highlight_other': '{{count}} highlights',
  'common.edit': 'Edit',
  'common.justNow': 'just now',
  'common.opening': 'Opening\u2026',
  'common.or': 'or',
  'common.pleaseWait': 'Please wait\u2026',
  'common.somethingWrong': 'Something went wrong.',
  'common.rename': 'Rename',
  'common.dragToReorder': 'Drag to reorder',
  'common.openInReader': 'Open in reader',
  // Fallback tradition name for a book whose category can't be resolved.
  'common.otherTradition': 'Other',

  // Primary navigation. The web sidebar shows these as its nav items; on
  // mobile the same destinations are the drawer's screen titles.
  'nav.home': 'Home',
  'nav.library': 'Library',
  'nav.tags': 'Tags',
  'nav.notes': 'Notes',
  'nav.xrefs': 'X-Refs',
  'nav.discover': 'Discover',
  'nav.settings': 'Settings',
  'nav.guest': 'Guest',
  'nav.reader': 'Reader',
  'nav.signOut': 'Sign Out',

  'library.title': 'Library',
  'library.languageSheetTitle': 'Library language',
  'library.availableToDownload': 'Available to download',
  'library.downloading': 'Downloading {{percent}}%',
  'library.verifying': 'Verifying…',
  'library.importing': 'Importing…',
  'library.cleaning': 'Finishing…',
  'library.downloadFailed': 'Download failed',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Change library language',

  'library.myBooks': 'My Books',
  'library.searchAll': 'Search all books\u2026',
  'library.searchSelected_one': 'Search {{count}} selected book\u2026',
  'library.searchSelected_other': 'Search {{count}} selected books\u2026',
  'library.noResultsFor': 'No results found for \u201c{{query}}\u201d.',
  'library.result_one': '{{count}} result',
  'library.result_other': '{{count}} results',
  'library.relatedPassages': 'Related passages',
  'library.relatedOn': 'on',
  'library.relatedPrefix': 'RELATED',
  'library.importTitle': 'Import a book (TXT, EPUB, DOCX, RTF, PDF)',
  'library.importProFeature':
    'Book import is a Pro feature. Upgrade in Settings to import your own books.',
  'library.importFailed': 'Import failed.',
  'library.importSucceeded': '\u201c{{title}}\u201d imported successfully.',
  'library.noImportedBooks':
    'No imported books yet. Use the button near the search bar to import a book.',
  'library.deleteBookConfirm': 'Delete \u201c{{title}}\u201d?',
  'library.tagAction': 'Tag',

  'settings.language': 'Language',
  'settings.appLanguage': 'App language',
  'settings.appLanguageHint': 'Buttons and menus. Separate from which library you read.',
  'settings.downloadedLibraries': 'Downloaded libraries',
  'settings.downloadedLibrariesHint': 'Switch between them from the Library screen.',
  'settings.includedWithApp': 'included with the app',
  'settings.removeLanguageTitle': 'Remove {{language}}?',
  'settings.removeLanguageBody':
    'These books will be deleted from this device. You can download them again at any time.',
  'settings.removeLanguageKeepsAnnotations':
    'Your {{annotations}} in these books will be kept, and will reappear if you download {{language}} again.',
  'settings.removeFailed': 'Could not remove',
  'settings.account': 'Account',
  'settings.fullName': 'Full Name',
  'settings.edit': 'Edit',
  'settings.username': 'Username',
  'settings.plan': 'Plan',
  'settings.fontSize': 'Font Size',
  'settings.fontPreview': 'Preview text at {{size}} size. This setting syncs across all your devices.',
  'settings.dailyReadings': 'Daily Readings',
  'settings.randomVersesAndPlan': 'Random Verses and Reading Plan',
  'settings.readingMorningEvening': 'A reading each morning and evening',
  'settings.appearance': 'Appearance',
  'settings.appearanceLight': 'Light',
  'settings.appearanceDark': 'Dark',
  'settings.appearanceSystem': 'System',
  'settings.upgrade': 'Upgrade',
  'settings.upgradeCta': 'UPGRADE TO PRO — $0.99/MO',
  'settings.upgradeBlurb':
    'Unlock AI summaries, premium listening voices, and importing your own books. $0.99/month.',
  'settings.purchases': 'Purchases',
  'settings.restorePurchase': 'Restore Purchase',
  'settings.about': 'About',
  'settings.version': 'Version',
  'settings.privacyPolicy': 'Privacy Policy',
  'settings.viewExternal': 'View ↗',
  'settings.termsOfService': 'Terms of Service',
  'settings.introTour': 'Intro Tour',
  'settings.fullFeatureVideo': 'Full Feature Video',
  'settings.replayOnboarding': 'Replay on-boarding screenshots',
  'settings.view': 'View',
  'settings.watchFeatureVideo': 'Watch Full Feature Video',
  'settings.accountActions': 'Account Actions',
  'settings.legal': 'Legal',
  'settings.communityGuidelines': 'Community Guidelines',
  'settings.signOut': 'Sign Out',
  'settings.deleteAccount': 'Delete Account',
  'settings.deleting': 'Deleting…',
  'settings.error': 'Error',
  'settings.deleteAccountConfirm':
    'This will permanently delete your account and all your annotations, tags, notes, and reading progress. This cannot be undone.',
  'settings.areYouSure': 'Are you sure?',
  'settings.deleteAccountFinal':
    'Your account and all data will be deleted immediately and cannot be recovered.',
  'settings.deletePermanently': 'Yes, Delete Permanently',
  'settings.restoreFailed': 'Restore failed',
  'settings.proRestored': 'Pro restored!',
  'settings.proRestoredBody': 'Your subscription is now active.',
  'settings.noSubscription': 'No subscription found',
  'settings.noSubscriptionBody':
    "We couldn't find an active subscription linked to this account.",
  'settings.planGuest': 'Guest',
  'settings.planStandard': 'Standard',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (trial)',

  // Web-only: the subscription-management link and the post-checkout banner
  // are Stripe flows that exist only on web (mobile purchases go through
  // RevenueCat and the App Store).
  'settings.welcomeToPro': 'Welcome to Pro!',
  'settings.manage': 'Manage',

  'home.tags': 'Tags',
  'home.notes': 'Notes',
  'home.xrefs': 'X-Refs',
  'home.readingPlan': 'READING PLAN',
  'home.dailyVerses': 'DAILY VERSES',
  'home.dailyReadingsTitle': 'Daily Readings',
  'home.tapToSetUp': 'Tap to set up',
  'home.tapToReadVerse': 'Tap to read a verse',
  'home.tapToContinue': 'Tap to continue',
  'home.planFinished': 'Finished — choose your next book',
  'home.recentlyViewed': 'Recently Viewed',
  'home.removeFromRecent': 'Remove from Recently Viewed',
  'home.signInCreate': 'Sign In / Create Account',
  'home.startReadingHint': 'Start reading to see your recent books here.',
  'home.viewLibrary': 'VIEW LIBRARY',

  // Web-only: the sign-in card on the web Home has no mobile counterpart —
  // mobile shows home.signInCreate on its own instead.
  'home.signInBlurb': 'Sign in to see your recently viewed books, annotations, and more across all your devices.',

  'auth.tagline': 'Interfaith E-Reader & Research',
  'auth.usernamePlaceholder': 'Username *',
  'auth.fullNamePlaceholder': 'Full Name',
  'auth.emailPlaceholder': 'Email *',
  'auth.passwordPlaceholder': 'Password *',
  'auth.emailAddressPlaceholder': 'Email address *',
  'auth.signIn': 'Sign In',
  'auth.signUp': 'Sign Up',
  'auth.createAccount': 'Create Account',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.browseWithout': 'Browse without an account',
  'auth.guestSubtext': "Read and search books — progress and notes won't be saved",
  'auth.resetPassword': 'Reset Password',
  'auth.sendResetLink': 'Send Reset Link',
  'auth.createPasswordPlaceholder': 'Create Password *',
  'auth.backToSignIn': 'Back to Sign In',
  'auth.forgotBlurb':
    "Enter your email address and we'll send you a link to reset your password.",
  'auth.usernameAvailable': '\u2713 Available',
  'auth.usernameTakenShort': '\u2717 Taken',
  'auth.usernameHint': '3\u201320 chars',
  'auth.usernameAlreadyTaken': 'Username is already taken.',
  'auth.resetLinkSent': 'We sent a password reset link to {{email}}',
  'auth.error': 'Error',
  'auth.missingFields': 'Missing fields',
  'auth.missingFieldsBody': 'Please enter email and password.',
  'auth.invalidUsername': 'Invalid username',
  'auth.invalidUsernameBody': 'Username must be 3–20 characters: letters, numbers, underscores only.',
  'auth.usernameTaken': 'Username taken',
  'auth.usernameTakenBody': 'Please choose a different username.',
  'auth.checkUsername': 'Check username',
  'auth.checkUsernameBody': 'Please wait for username validation to complete.',
  'auth.checkEmail': 'Check your email',
  'auth.checkEmailBody': 'We sent a confirmation link to {{email}}',
  'auth.enterEmail': 'Enter email',
  'auth.enterEmailBody': 'Please enter your email address.',
  'auth.emailSent': 'Email sent',
  'auth.emailSentBody': 'Check your inbox for a password reset link.',

  'auth.emailConfirmed': 'Email Confirmed',
  'auth.accountReadySignIn':
    'Your account is ready. Sign in with your email and password to get started.',
  'auth.accountReadyOpenApp':
    'Your account is ready. Open the Immerse app on your phone to sign in, or continue on the web below.',
  'auth.openingApp': 'Your account is ready. Opening the Immerse app and signing you in\u2026',
  'auth.openImmerse': 'Open Immerse',
  'auth.continueOnWeb': 'Continue on the web instead',
  'auth.signInToImmerse': 'Sign In to Immerse',
  'auth.continueToImmerse': 'Continue to Immerse',
  'auth.chooseNewPassword': 'Choose a new password for your account',
  'auth.newPasswordPlaceholder': 'New password',
  'auth.confirmNewPasswordPlaceholder': 'Confirm new password',
  'auth.updatePassword': 'Update Password',
  'auth.enterConfirmPassword': 'Please enter and confirm your new password.',
  'auth.passwordTooShort': 'Password must be at least 8 characters.',
  'auth.passwordsDontMatch': 'Passwords don\u2019t match.',
  'auth.passwordUpdated': 'Password updated',
  'auth.passwordUpdatedBody': 'You can now use your new password.',
  'auth.resetFailed':
    'Could not update your password. The reset link may have expired \u2014 please request a new one.',

  'reminders.headerTitle': 'Daily Readings',
  'reminders.enable': 'Enable Daily Readings',
  'reminders.openSettings': 'Open Settings',
  'reminders.source': 'Source',
  'reminders.randomVerses': 'Random verses',
  'reminders.readingPlan': 'Reading plan',
  'reminders.chooseBook': 'Choose a book',
  'reminders.bookFinished': 'Finished ✓ — choose your next book',
  'reminders.sessionLength': 'Session length',
  'reminders.sessionCaption': 'Applies to each session — {{dur}} in the morning and {{dur}} in the evening.',
  'reminders.reminders': 'Reminders',
  'reminders.time': 'Time',
  'reminders.morning': 'Morning',
  'reminders.evening': 'Evening',
  'reminders.yourStreak': 'Your streak',
  'reminders.today': 'Today',
  'reminders.currentStreak': 'Current streak',
  'reminders.bestStreak': 'Best streak',
  'reminders.completedBooks': 'Completed books',
  'reminders.day_one': '{{count}} day',
  'reminders.day_other': '{{count}} days',
  'reminders.hour': '1 hr',
  'reminders.minutes': '{{count}} min',
  'reminders.signInRequired': 'Sign in required',
  'reminders.signInRequiredBody': 'Create an account to follow a reading plan and track your progress.',
  'reminders.notNow': 'Not Now',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Read deeper. Connect more.',
  'paywall.featureAiLabel': 'AI passage summaries',
  'paywall.featureAiDesc': 'Ask for explanations and commentary on any passage',
  'paywall.featureVoicesLabel': 'Premium listening voices',
  'paywall.featureVoicesDesc': 'Natural, expressive narration in the voice of your choice',
  'paywall.featureImportLabel': 'Import your own books',
  'paywall.featureImportDesc': 'Add EPUB, PDF, and DOCX files to your library',
  'paywall.subscribe': 'Subscribe — {{price}}/month',
  'paywall.cancelNote': 'Cancel anytime · Billed monthly',
  'paywall.restore': 'Restore Purchases',
  'paywall.terms': 'Terms of Service',
  'paywall.privacy': 'Privacy Policy',
  'paywall.notAvailable': 'Not available',
  'paywall.notAvailableBody': 'In-app purchases are not configured in this build yet. Check back after the App Store release.',
  'paywall.welcome': 'Welcome to Pro!',
  'paywall.welcomeBody': 'Your subscription is now active.',
  'paywall.purchaseFailed': 'Purchase failed',
  'paywall.restoreFailed': 'Restore failed',

  'xrefs.title': 'Cross-References',
  'xrefs.empty': 'No cross-references yet. Cross-references you create in the reader will appear here.',
  'xrefs.signInTitle': 'Sign In to See Your X-Refs',
  'xrefs.signInBody': 'Connect related passages from across the entire library.',
  'xrefs.searchSelected': 'Search selected cross-references...',
  'xrefs.searchPlaceholder': 'Search passages or labels...',
  'xrefs.noMatch': 'No cross-references match your search.',
  'xrefs.addLabel': 'Add label…',
  'xrefs.deleteConfirm': 'Delete cross-reference?',

  'notes.title': 'Notes',
  'notes.empty': 'No notes yet. Notes you create in the reader will appear here.',
  'notes.signInTitle': 'Sign In to See Your Notes',
  'notes.signInBody': 'Add comments and reflections to passages as you read.',
  'notes.searchPlaceholder': 'Search notes...',
  'notes.searchSelected': 'Search selected notes...',
  'notes.byBook': 'By Book',
  'notes.byDate': 'By Date',
  'notes.writeNote': 'Write your note…',
  'notes.noMatch': 'No notes match your search.',
  'notes.deleteConfirm': 'Delete note?',
  'notes.deleteBody': 'The highlighted selection will be kept.',

  'tags.title': 'Tags',
  'tags.empty': 'No tags yet. Tags you create in the reader will appear here.',
  'tags.signInTitle': 'Sign In to See Your Tags',
  'tags.signInBody': 'Create and organize quote compilations from across the library.',
  'tags.organize': 'Organize',
  'tags.searchPlaceholder': 'Search tags...',
  'tags.searchSelected': 'Search selected tags...',
  'tags.noMatch': 'No tags match your search.',
  'tags.deleteConfirm': 'Delete tag?',

  'tags.renameTitle': 'Rename Tag',
  'tags.setPrivate': 'Set Private',
  'tags.setPublic': 'Set Public',
  'tags.publicTag': 'Public tag',
  'tags.removePassage': 'Remove from tag',
  'tags.removePassageConfirm': 'Remove this passage from the tag?',
  'tags.indent': 'Indent',
  'tags.outdent': 'Outdent',
  'tags.organizeHint':
    'Drag the grip to reorder \u00b7 \u21e4 \u21e5 to change nesting \u00b7 click a tag to reorder its quotes.',
  // Web-only: the web exports straight from a dropdown on the Tags header,
  // where mobile opens its ExportFormatPanel sheet.
  'tags.searchTagsPassages': 'Search tags and passages\u2026',
  'tags.exportSelected': 'Export selected tags',
  'tags.export': 'Export',
  'tags.exporting': 'Exporting\u2026',
  'tags.exportInclude': 'Include',
  'tags.exportNothingToInclude': 'None of the selected tags have {{items}}',

  'panel.createAccount': 'Create Account',
  'panel.signInToSave': 'Create a free account to save tags, notes, and cross-references.',
  'panel.editSelection': 'Edit text selection',

  'reader.xrefMode': 'X-ref mode — long-press to pick a passage',
  'reader.error': 'Reader Error',
  'reader.opening': 'Opening book…',
  'reader.footnote': 'Footnote',

  // Web-only: the web reader is a DOM view with its own chrome, where mobile
  // renders the book in a WebView and uses the OS selection menu.
  'reader.selectBook': 'Select a book to begin reading',
  'reader.tableOfContents': 'Table of Contents',
  'reader.expandSection': 'Expand section',
  'reader.collapseSection': 'Collapse section',
  'reader.expand': 'Expand',
  'reader.collapse': 'Collapse',
  'reader.actionTag': 'Tag',
  'reader.actionNote': 'Note',
  'reader.actionXref': 'Xref',
  'reader.actionAi': 'AI',
  'reader.actionCopy': 'Copy',
  'reader.updateSelection': 'Update selection',
  'reader.updating': 'Updating\u2026',
  'reader.pickAsXref': 'Pick as X-Ref',
  'reader.editSelectionHint':
    'Highlight the new text for this annotation, then choose',
  'reader.savingXref': 'Saving cross-reference\u2026',
  'reader.pickTargetHint': 'Select text or click a passage to link',
  'reader.footnoteUnavailable': 'Footnote text not available in the web version.',
  'reader.bookNotFound': 'Book not found',
  'reader.viewTags': 'View tags',
  'reader.viewNote': 'View note',
  'reader.viewXrefs': 'View cross-references',
  'reader.noQuotesFiled': 'No quotes filed here.',

  'ai.summary': 'AI Summary',
  'ai.upgradeBlurb': 'Upgrade to Immerse Pro for only $0.99 to use AI summaries, and other Pro features.',
  'ai.upgradeBtn': 'Upgrade to Pro — $0.99/mo',
  'ai.thinking': 'Thinking…',
  'ai.error': 'Could not get AI summary. Please check your connection and try again.',
  'ai.copied': '✓ Copied',
  'ai.copyHint': 'Long press to copy',

  'note.title': 'Note',
  'note.addTitle': 'Add Note',
  'note.placeholder': 'Write your note here…',
  'note.loading': 'Loading…',
  'note.emptyTitle': 'Empty note',
  'note.emptyBody': 'Please write something before saving.',
  'note.saveFailed': 'Could not save note',
  'note.deleteTitle': 'Delete note?',
  'note.deleteBody': 'This will remove the note. If no other annotations are on this passage, the selection will also be removed.',
  'note.deleteFailed': 'Could not delete note',
  'note.signInRequired': 'Sign in required',
  'note.signInBody': 'Notes are saved to your account. Please sign in or create an account.',

  'xref.title': 'Cross-Reference',
  'xref.yourSelection': 'YOUR SELECTION',
  'xref.pickSecond': 'Pick second passage  →',
  'xref.noneFound': 'No cross-references found.',

  // Web-only. The web builds a cross-reference through a two-step panel —
  // search for the target, then confirm the pair — where mobile has you pick
  // the second passage in the reader itself.
  'xref.findPassage': 'Find a passage to link',
  'xref.searchPlaceholder': 'Search any passage…',
  'xref.save': 'Save Cross-Reference',
  'xref.from': 'From',
  'xref.to': 'To',
  'xref.linksTo': 'links to',

  // Web-only: the install banner shown on mobile browsers.
  'banner.googlePlay': 'Get it on Google Play',
  'banner.appStore': 'Download on the App Store',
  'banner.install': 'Install',
  'banner.get': 'Get',

  'tagPanel.new': 'New Tag',
  'tagPanel.create': 'Create',
  'tagPanel.addTitle': 'Add Tags',
  'tagPanel.viewTitle': 'Tags',
  'tagPanel.under': 'under',
  'tagPanel.addSubTag': 'Add sub-tag',
  'tagPanel.emptyAdd': 'No tags yet — create one above',
  'tagPanel.emptyView': 'No tags on this selection',

  'voice.title': 'Reading voice',
  'voice.onyx': 'Onyx — deep & warm',
  'voice.cedar': 'Cedar — natural & rich',
  'voice.ash': 'Ash — clear & direct',
  'voice.nova': 'Nova — bright',
  'voice.shimmer': 'Shimmer — soft',
  'voice.marin': 'Marin — natural & gentle',

  'reader.signInRequired': 'Sign in required',
  'reader.signInBody': 'Create an account to tag, annotate, and save your reading.',
  'reader.notNow': 'Not Now',
  'reader.signIn': 'Sign In',
  'reader.pdfNotFound': 'Could not locate the PDF file.',
  'reader.contentLoadFailed': 'Content could not load',
  'reader.noBook': 'No book specified',
  'reader.storageError': 'Storage error',

  'discover.recent': 'RECENT',
  'discover.trending': 'TRENDING',
  'discover.searchPlaceholder': 'Search tags and users…',
  'discover.searchSelected': 'Search selected tags…',
  'discover.import': 'Import',
  'discover.imported': 'Imported',
  'discover.import_one': '{{count}} import',
  'discover.import_other': '{{count}} imports',
  'discover.noneYet': 'No shared tags yet',
  'discover.noResults': 'No results',
  'discover.tryDifferent': 'Try a different search term.',
  'discover.signInTitle': 'Sign In to Access Discover',
  'discover.signInBody': 'See what other readers are discovering across all traditions.',
  'discover.anonymous': 'Anonymous',
  'discover.beFirst': 'Be the first to share a tag.',
  'discover.ownTag': 'This is your own tag',
  'discover.alreadyImported': 'Already imported',
  'discover.importFailed': 'Import failed',
  'discover.exportFailed': 'Export failed',
  'discover.unknownError': 'Unknown error',

  'usertags.autoImports': "Auto-imports user's public tags to your app",
  'usertags.noTags': 'No public tags',
  'usertags.noTagsBody': "This user hasn't shared any tags yet.",
  'usertags.follow': 'Follow',
  'usertags.unfollow': 'Unfollow',
  'usertags.share': 'Share',
  'usertags.error': 'Error',
  'usertags.somethingWrong': 'Something went wrong',

  'onboarding.chooseLanguage': 'Choose Your Language',
  'onboarding.changeLaterSettings': 'You can change this later in Settings.',
  'onboarding.libraryDownloadHint': 'To download the library in {{language}}, tap the ⌄ next to “Library” on the Library screen.',
  'onboarding.continue': 'Continue',
  'onboarding.chooseTextSize': 'Choose Text Size',
  'onboarding.getStarted': 'Get Started',

  // Web-only: the intro screenshot walkthrough replayed from Settings → About.
  // NOTE the screenshots themselves are English captures, so a Spanish caption
  // sits under an English image until localised screenshots exist.
  'onboarding.closeIntro': 'Close intro',
  'onboarding.goToStep': 'Go to step {{number}}',
  'onboarding.libraryTitle': 'The Library',
  'onboarding.libraryCaption': 'Browse a curated, multi-tradition library. Tap any book to start reading.',
  'onboarding.searchTitle': 'Search everything',
  'onboarding.searchCaption': 'Search across every book at once and jump straight to the passage.',
  'onboarding.tagAsYouGoTitle': 'Tag as you go',
  'onboarding.tagAsYouGoCaption': 'Add a tag to a passage right from the search results.',
  'onboarding.buildTagsTitle': 'Build your tags',
  'onboarding.buildTagsCaption': 'Group passages under your own tags for easy recall.',
  'onboarding.selectActTitle': 'Select & act',
  'onboarding.selectActCaption': 'Select any text to highlight, tag, note, or cross-reference it.',
  'onboarding.marginTitle': 'Margin annotations',
  'onboarding.marginCaption': 'Your tags, notes, and cross-references live in the margin.',
  'onboarding.navigateTitle': 'Navigate quickly',
  'onboarding.navigateCaption': 'Open the table of contents to move around a book.',
  'onboarding.yourTagsTitle': 'Your tags',
  'onboarding.yourTagsCaption': 'Revisit every tagged passage, organized by tag.',
  'onboarding.xrefsTitle': 'Cross-references',
  'onboarding.xrefsCaption': 'Link related passages across books and traditions.',
  'onboarding.shareTitle': 'Share & publish',
  'onboarding.shareCaption': 'Share a quote or publish a tag for the community.',
} as const;

/** Keys exactly as written above, including the `_one` / `_other` variants. */
export type RawTranslationKey = keyof typeof en;
