/**
 * English UI strings — the reference locale.
 *
 * Keys are `screen.element`, or `common.*` for anything genuinely shared. Add a
 * key here first: en is the fallback for every other locale, so a string absent
 * here has nothing to fall back to.
 *
 * Plurals use `_one` / `_other` suffixes, selected by the `count` variable.
 * Interpolation is `{{name}}`.
 *
 * These are interface strings only. Scripture is content and lives in the
 * corpus, never here.
 */
export const en = {
  'common.cancel': 'Cancel',
  'common.remove': 'Remove',
  'common.removing': 'Removing…',
  'common.save': 'Save',
  'common.done': 'Done',
  'common.tryAgain': 'Please try again.',
  'common.delete': 'Delete',
  'common.clear': 'Clear',
  'common.signInCreate': 'Sign In or Create Account',
  'common.book_one': '{{count}} book',
  'common.book_other': '{{count}} books',
  'common.highlight_one': '{{count}} highlight',
  'common.highlight_other': '{{count}} highlights',

  'library.title': 'Library',
  'library.languageSheetTitle': 'Library language',
  'library.availableToDownload': 'Available to download',
  'library.downloading': 'Downloading {{percent}}%',
  'library.verifying': 'Verifying…',
  'library.importing': 'Importing…',
  'library.cleaning': 'Finishing…',
  'library.downloadFailed': 'Download failed',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Change library language',

  'settings.language': 'Language',
  'settings.appLanguage': 'App language',
  'settings.appLanguageHint': 'Buttons and menus. Separate from which library you read.',
  'settings.downloadedLibraries': 'Downloaded libraries',
  'settings.downloadedLibrariesHint': 'Switch between them from the Library screen.',
  'settings.includedWithApp': 'included with the app',
  'settings.removeLanguageTitle': 'Remove {{language}}?',
  'settings.removeLanguageBody':
    'These books will be deleted from this device. You can download them again at any time.',
  'settings.removeLanguageKeepsAnnotations':
    'Your {{annotations}} in these books will be kept, and will reappear if you download {{language}} again.',
  'settings.removeFailed': 'Could not remove',
  'settings.account': 'Account',
  'settings.fullName': 'Full Name',
  'settings.edit': 'Edit',
  'settings.username': 'Username',
  'settings.plan': 'Plan',
  'settings.fontSize': 'Font Size',
  'settings.fontPreview': 'Preview text at {{size}} size. This setting syncs across all your devices.',
  'settings.dailyReadings': 'Daily Readings',
  'settings.randomVersesAndPlan': 'Random Verses and Reading Plan',
  'settings.readingMorningEvening': 'A reading each morning and evening',
  'settings.appearance': 'Appearance',
  'settings.appearanceLight': 'Light',
  'settings.appearanceDark': 'Dark',
  'settings.appearanceSystem': 'System',
  'settings.upgrade': 'Upgrade',
  'settings.upgradeCta': 'UPGRADE TO PRO — $0.99/MO',
  'settings.upgradeBlurb':
    'Unlock AI summaries, premium listening voices, and importing your own books. $0.99/month.',
  'settings.purchases': 'Purchases',
  'settings.restorePurchase': 'Restore Purchase',
  'settings.about': 'About',
  'settings.version': 'Version',
  'settings.privacyPolicy': 'Privacy Policy',
  'settings.viewExternal': 'View ↗',
  'settings.termsOfService': 'Terms of Service',
  'settings.replayOnboarding': 'Replay on-boarding screenshots',
  'settings.view': 'View',
  'settings.watchFeatureVideo': 'Watch Full Feature Video',
  'settings.accountActions': 'Account Actions',
  'settings.legal': 'Legal',
  'settings.communityGuidelines': 'Community Guidelines',
  'settings.signOut': 'Sign Out',
  'settings.deleteAccount': 'Delete Account',
  'settings.deleting': 'Deleting…',
  'settings.error': 'Error',
  'settings.deleteAccountConfirm':
    'This will permanently delete your account and all your annotations, tags, notes, and reading progress. This cannot be undone.',
  'settings.areYouSure': 'Are you sure?',
  'settings.deleteAccountFinal':
    'Your account and all data will be deleted immediately and cannot be recovered.',
  'settings.deletePermanently': 'Yes, Delete Permanently',
  'settings.restoreFailed': 'Restore failed',
  'settings.proRestored': 'Pro restored!',
  'settings.proRestoredBody': 'Your subscription is now active.',
  'settings.noSubscription': 'No subscription found',
  'settings.noSubscriptionBody':
    "We couldn't find an active subscription linked to this account.",
  'settings.planGuest': 'Guest',
  'settings.planStandard': 'Standard',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (trial)',

  'home.tags': 'Tags',
  'home.notes': 'Notes',
  'home.xrefs': 'X-Refs',
  'home.readingPlan': 'READING PLAN',
  'home.dailyVerses': 'DAILY VERSES',
  'home.dailyReadingsTitle': 'Daily Readings',
  'home.tapToSetUp': 'Tap to set up',
  'home.tapToReadVerse': 'Tap to read a verse',
  'home.tapToContinue': 'Tap to continue',
  'home.planFinished': 'Finished — choose your next book',
  'home.recentlyViewed': 'Recently Viewed',
  'home.removeFromRecent': 'Remove from Recently Viewed',
  'home.signInCreate': 'Sign In / Create Account',
  'home.startReadingHint': 'Start reading to see your recent books here.',
  'home.viewLibrary': 'VIEW LIBRARY',

  'auth.tagline': 'Interfaith E-Reader & Research',
  'auth.usernamePlaceholder': 'Username *',
  'auth.fullNamePlaceholder': 'Full Name',
  'auth.emailPlaceholder': 'Email *',
  'auth.passwordPlaceholder': 'Password *',
  'auth.emailAddressPlaceholder': 'Email address *',
  'auth.signIn': 'Sign In',
  'auth.signUp': 'Sign Up',
  'auth.createAccount': 'Create Account',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.browseWithout': 'Browse without an account',
  'auth.guestSubtext': "Read and search books — progress and notes won't be saved",
  'auth.resetPassword': 'Reset Password',
  'auth.sendResetLink': 'Send Reset Link',
  'auth.error': 'Error',
  'auth.missingFields': 'Missing fields',
  'auth.missingFieldsBody': 'Please enter email and password.',
  'auth.invalidUsername': 'Invalid username',
  'auth.invalidUsernameBody': 'Username must be 3–20 characters: letters, numbers, underscores only.',
  'auth.usernameTaken': 'Username taken',
  'auth.usernameTakenBody': 'Please choose a different username.',
  'auth.checkUsername': 'Check username',
  'auth.checkUsernameBody': 'Please wait for username validation to complete.',
  'auth.checkEmail': 'Check your email',
  'auth.checkEmailBody': 'We sent a confirmation link to {{email}}',
  'auth.enterEmail': 'Enter email',
  'auth.enterEmailBody': 'Please enter your email address.',
  'auth.emailSent': 'Email sent',
  'auth.emailSentBody': 'Check your inbox for a password reset link.',

  'reminders.headerTitle': 'Daily Readings',
  'reminders.enable': 'Enable Daily Readings',
  'reminders.openSettings': 'Open Settings',
  'reminders.source': 'Source',
  'reminders.randomVerses': 'Random verses',
  'reminders.readingPlan': 'Reading plan',
  'reminders.chooseBook': 'Choose a book',
  'reminders.bookFinished': 'Finished ✓ — choose your next book',
  'reminders.sessionLength': 'Session length',
  'reminders.sessionCaption': 'Applies to each session — {{dur}} in the morning and {{dur}} in the evening.',
  'reminders.reminders': 'Reminders',
  'reminders.time': 'Time',
  'reminders.morning': 'Morning',
  'reminders.evening': 'Evening',
  'reminders.yourStreak': 'Your streak',
  'reminders.today': 'Today',
  'reminders.currentStreak': 'Current streak',
  'reminders.bestStreak': 'Best streak',
  'reminders.completedBooks': 'Completed books',
  'reminders.day_one': '{{count}} day',
  'reminders.day_other': '{{count}} days',
  'reminders.hour': '1 hr',
  'reminders.minutes': '{{count}} min',
  'reminders.signInRequired': 'Sign in required',
  'reminders.signInRequiredBody': 'Create an account to follow a reading plan and track your progress.',
  'reminders.notNow': 'Not Now',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Read deeper. Connect more.',
  'paywall.featureAiLabel': 'AI passage summaries',
  'paywall.featureAiDesc': 'Ask for explanations and commentary on any passage',
  'paywall.featureVoicesLabel': 'Premium listening voices',
  'paywall.featureVoicesDesc': 'Natural, expressive narration in the voice of your choice',
  'paywall.featureImportLabel': 'Import your own books',
  'paywall.featureImportDesc': 'Add EPUB, PDF, and DOCX files to your library',
  'paywall.subscribe': 'Subscribe — {{price}}/month',
  'paywall.cancelNote': 'Cancel anytime · Billed monthly',
  'paywall.restore': 'Restore Purchases',
  'paywall.terms': 'Terms of Service',
  'paywall.privacy': 'Privacy Policy',
  'paywall.notAvailable': 'Not available',
  'paywall.notAvailableBody': 'In-app purchases are not configured in this build yet. Check back after the App Store release.',
  'paywall.welcome': 'Welcome to Pro!',
  'paywall.welcomeBody': 'Your subscription is now active.',
  'paywall.purchaseFailed': 'Purchase failed',
  'paywall.restoreFailed': 'Restore failed',

  'xrefs.signInTitle': 'Sign In to See Your X-Refs',
  'xrefs.signInBody': 'Connect related passages from across the entire library.',
  'xrefs.searchSelected': 'Search selected cross-references...',
  'xrefs.searchPlaceholder': 'Search passages or labels...',
  'xrefs.noMatch': 'No cross-references match your search.',
  'xrefs.addLabel': 'Add label…',
  'xrefs.deleteConfirm': 'Delete cross-reference?',

  'notes.signInTitle': 'Sign In to See Your Notes',
  'notes.signInBody': 'Add comments and reflections to passages as you read.',
  'notes.searchPlaceholder': 'Search notes...',
  'notes.searchSelected': 'Search selected notes...',
  'notes.byBook': 'By Book',
  'notes.byDate': 'By Date',
  'notes.writeNote': 'Write your note…',
  'notes.noMatch': 'No notes match your search.',
  'notes.deleteConfirm': 'Delete note?',
  'notes.deleteBody': 'The highlighted selection will be kept.',

  'tags.signInTitle': 'Sign In to See Your Tags',
  'tags.signInBody': 'Create and organize quote compilations from across the library.',
  'tags.organize': 'Organize',
  'tags.searchPlaceholder': 'Search tags...',
  'tags.searchSelected': 'Search selected tags...',
  'tags.noMatch': 'No tags match your search.',
  'tags.deleteConfirm': 'Delete tag?',

  'panel.createAccount': 'Create Account',
  'panel.signInToSave': 'Create a free account to save tags, notes, and cross-references.',
  'panel.editSelection': 'Edit text selection',

  'reader.xrefMode': 'X-ref mode — long-press to pick a passage',
  'reader.error': 'Reader Error',
  'reader.opening': 'Opening book…',
  'reader.footnote': 'Footnote',

  'ai.summary': 'AI Summary',
  'ai.upgradeBlurb': 'Upgrade to Immerse Pro for only $0.99 to use AI summaries, and other Pro features.',
  'ai.upgradeBtn': 'Upgrade to Pro — $0.99/mo',
  'ai.thinking': 'Thinking…',
  'ai.error': 'Could not get AI summary. Please check your connection and try again.',
  'ai.copied': '✓ Copied',
  'ai.copyHint': 'Long press to copy',

  'note.placeholder': 'Write your note here…',
  'note.loading': 'Loading…',
  'note.emptyTitle': 'Empty note',
  'note.emptyBody': 'Please write something before saving.',
  'note.saveFailed': 'Could not save note',
  'note.deleteTitle': 'Delete note?',
  'note.deleteBody': 'This will remove the note. If no other annotations are on this passage, the selection will also be removed.',
  'note.deleteFailed': 'Could not delete note',
  'note.signInRequired': 'Sign in required',
  'note.signInBody': 'Notes are saved to your account. Please sign in or create an account.',

  'xref.title': 'Cross-Reference',
  'xref.yourSelection': 'YOUR SELECTION',
  'xref.pickSecond': 'Pick second passage  →',
  'xref.noneFound': 'No cross-references found.',

  'tagPanel.new': 'New Tag',
  'tagPanel.create': 'Create',

  'voice.title': 'Reading voice',
  'voice.onyx': 'Onyx — deep & warm',
  'voice.cedar': 'Cedar — natural & rich',
  'voice.ash': 'Ash — clear & direct',
  'voice.nova': 'Nova — bright',
  'voice.shimmer': 'Shimmer — soft',
  'voice.marin': 'Marin — natural & gentle',

  'reader.signInRequired': 'Sign in required',
  'reader.signInBody': 'Create an account to tag, annotate, and save your reading.',
  'reader.notNow': 'Not Now',
  'reader.signIn': 'Sign In',
  'reader.pdfNotFound': 'Could not locate the PDF file.',
  'reader.contentLoadFailed': 'Content could not load',
  'reader.noBook': 'No book specified',
  'reader.storageError': 'Storage error',

  'discover.recent': 'RECENT',
  'discover.trending': 'TRENDING',
  'discover.searchPlaceholder': 'Search tags and users…',
  'discover.searchSelected': 'Search selected tags…',
  'discover.import': 'Import',
  'discover.imported': 'Imported',
  'discover.import_one': '{{count}} import',
  'discover.import_other': '{{count}} imports',
  'discover.noneYet': 'No shared tags yet',
  'discover.noResults': 'No results',
  'discover.tryDifferent': 'Try a different search term.',
  'discover.signInTitle': 'Sign In to Access Discover',
  'discover.signInBody': 'See what other readers are discovering across all traditions.',
  'discover.importFailed': 'Import failed',
  'discover.exportFailed': 'Export failed',
  'discover.unknownError': 'Unknown error',

  'usertags.autoImports': "Auto-imports user's public tags to your app",
  'usertags.noTags': 'No public tags',
  'usertags.noTagsBody': "This user hasn't shared any tags yet.",
  'usertags.follow': 'Follow',
  'usertags.unfollow': 'Unfollow',
  'usertags.share': 'Share',
  'usertags.error': 'Error',
  'usertags.somethingWrong': 'Something went wrong',

  'onboarding.chooseLanguage': 'Choose Your Language',
  'onboarding.changeLaterSettings': 'You can change this later in Settings.',
  'onboarding.libraryDownloadHint': 'To download the library in {{language}}, tap the ⌄ next to “Library” on the Library screen.',
  'onboarding.continue': 'Continue',
  'onboarding.chooseTextSize': 'Choose Text Size',
  'onboarding.getStarted': 'Get Started',
} as const;

/** Keys exactly as written above, including the `_one` / `_other` variants. */
export type RawTranslationKey = keyof typeof en;
