import type { en } from './en';

/**
 * Spanish UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key, so this file can be filled in gradually without the app
 * ever showing `settings.appLanguage` to a user.
 */
export const es: Partial<Record<keyof typeof en, string>> = {
  'common.cancel': 'Cancelar',
  'common.remove': 'Eliminar',
  'common.removing': 'Eliminando…',
  'common.save': 'Guardar',
  'common.done': 'Listo',
  'common.ok': 'Aceptar',
  'common.continue': 'Continuar',
  'common.tryAgain': 'Inténtalo de nuevo.',
  'common.delete': 'Eliminar',
  'common.clear': 'Borrar',
  'common.signInCreate': 'Iniciar sesión o crear cuenta',
  'common.book_one': '{{count}} libro',
  'common.book_other': '{{count}} libros',
  'common.saving': 'Guardando…',
  'common.loading': 'Cargando…',
  'common.copy': 'Copiar',
  'common.retry': 'Inténtalo de nuevo',
  'common.back': 'Atrás',
  'common.next': 'Siguiente',
  'common.searching': 'Buscando…',
  'common.noResults': 'No se encontraron resultados.',
  'common.dismiss': 'Descartar',
  'common.options': 'Opciones',
  'common.collapseLibrary': 'Contraer biblioteca',
  'common.expandLibrary': 'Expandir biblioteca',
  'common.minutesAgo': 'hace {{count}} min',
  'common.hoursAgo': 'hace {{count}} h',
  'common.daysAgo': 'hace {{count}} d',
  'common.highlight_one': '{{count}} subrayado',
  'common.highlight_other': '{{count}} subrayados',
  'common.edit': 'Editar',
  'common.justNow': 'ahora mismo',
  'common.opening': 'Abriendo\u2026',
  'common.or': 'o',
  'common.pleaseWait': 'Espera\u2026',
  'common.somethingWrong': 'Algo sali\u00f3 mal.',
  'common.rename': 'Cambiar el nombre',
  'common.dragToReorder': 'Arrastra para reordenar',
  'common.openInReader': 'Abrir en el lector',
  'common.otherTradition': 'Otros',

  'nav.home': 'Inicio',
  'nav.library': 'Biblioteca',
  'nav.tags': 'Etiquetas',
  'nav.notes': 'Notas',
  'nav.xrefs': 'Remisiones',
  'nav.discover': 'Descubrir',
  'nav.settings': 'Ajustes',
  'nav.guest': 'Invitado',
  'nav.reader': 'Lector',
  'nav.signOut': 'Cerrar sesión',

  'library.title': 'Biblioteca',
  'library.languageSheetTitle': 'Idioma de la biblioteca',
  'library.availableToDownload': 'Disponible para descargar',
  'library.downloading': 'Descargando {{percent}} %',
  'library.verifying': 'Verificando…',
  'library.importing': 'Importando…',
  'library.cleaning': 'Finalizando…',
  'library.downloadFailed': 'Error en la descarga',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Cambiar el idioma de la biblioteca',

  'library.myBooks': 'Mis libros',
  'library.searchAll': 'Buscar en todos los libros\u2026',
  'library.searchSelected_one': 'Buscar en {{count}} libro seleccionado\u2026',
  'library.searchSelected_other': 'Buscar en {{count}} libros seleccionados\u2026',
  'library.noResultsFor': 'No se encontraron resultados para \u201c{{query}}\u201d.',
  'library.result_one': '{{count}} resultado',
  'library.result_other': '{{count}} resultados',
  'library.relatedPassages': 'Pasajes relacionados',
  'library.relatedOn': 'activado',
  'library.relatedPrefix': 'RELACIONADO',
  'library.importTitle': 'Importar un libro (TXT, EPUB, DOCX, RTF, PDF)',
  'library.importProFeature':
    'La importaci\u00f3n de libros es una funci\u00f3n Pro. Hazte Pro en Ajustes para importar tus propios libros.',
  'library.importFailed': 'Error al importar.',
  'library.importSucceeded': '\u201c{{title}}\u201d se import\u00f3 correctamente.',
  'library.noImportedBooks':
    'A\u00fan no hay libros importados. Usa el bot\u00f3n junto a la barra de b\u00fasqueda para importar uno.',
  'library.deleteBookConfirm': '\u00bfEliminar \u201c{{title}}\u201d?',
  'library.tagAction': 'Etiquetar',

  'settings.language': 'Idioma',
  'settings.appLanguage': 'Idioma de la aplicación',
  'settings.appLanguageHint':
    'Botones y menús. Independiente de la biblioteca que lees.',
  'settings.restartForDirection': 'Reinicia para completar el cambio',
  'settings.restartForDirectionBody':
    '{{language}} se escribe de derecha a izquierda. Cierra y vuelve a abrir Immerse para voltear el diseño.',
  'settings.restartForDirectionBodyLtr':
    'Cierra y vuelve a abrir Immerse para que el diseño vuelva a ser de izquierda a derecha.',
  'settings.downloadedLibraries': 'Bibliotecas descargadas',
  'settings.downloadedLibrariesHint':
    'Cambia entre ellas desde la pantalla Biblioteca.',
  'settings.includedWithApp': 'incluida con la aplicación',
  'settings.removeLanguageTitle': '¿Eliminar {{language}}?',
  'settings.removeLanguageBody':
    'Estos libros se eliminarán de este dispositivo. Puedes descargarlos de nuevo cuando quieras.',
  'settings.removeLanguageKeepsAnnotations':
    'Tus {{annotations}} en estos libros se conservarán y reaparecerán si vuelves a descargar {{language}}.',
  'settings.removeFailed': 'No se pudo eliminar',
  'settings.account': 'Cuenta',
  'settings.fullName': 'Nombre completo',
  'settings.edit': 'Editar',
  'settings.username': 'Nombre de usuario',
  'settings.plan': 'Plan',
  'settings.fontSize': 'Tamaño de letra',
  'settings.fontPreview': 'Texto de muestra en tamaño {{size}}. Este ajuste se sincroniza en todos tus dispositivos.',
  'settings.dailyReadings': 'Lecturas diarias',
  'settings.randomVersesAndPlan': 'Versículos aleatorios y plan de lectura',
  'settings.readingMorningEvening': 'Una lectura por la mañana y por la noche',
  'settings.appearance': 'Apariencia',
  'settings.appearanceLight': 'Claro',
  'settings.appearanceDark': 'Oscuro',
  'settings.appearanceSystem': 'Sistema',
  'settings.upgrade': 'Mejorar',
  'settings.upgradeCta': 'HAZTE PRO — 0,99 USD/MES',
  'settings.upgradeBlurb':
    'Desbloquea resúmenes con IA, voces premium de lectura e importación de tus propios libros. 0,99 USD al mes.',
  'settings.purchases': 'Compras',
  'settings.restorePurchase': 'Restaurar compra',
  'settings.about': 'Acerca de',
  'settings.version': 'Versión',
  'settings.privacyPolicy': 'Política de privacidad',
  'settings.viewExternal': 'Ver ↗',
  'settings.termsOfService': 'Términos del servicio',
  'settings.introTour': 'Introducci\u00f3n',
  'settings.fullFeatureVideo': 'V\u00eddeo completo de funciones',
  'settings.replayOnboarding': 'Volver a ver la introducción',
  'settings.view': 'Ver',
  'settings.watchFeatureVideo': 'Ver el vídeo completo de funciones',
  'settings.accountActions': 'Acciones de la cuenta',
  'settings.legal': 'Legal',
  'settings.communityGuidelines': 'Normas de la comunidad',
  'settings.signOut': 'Cerrar sesión',
  'settings.deleteAccount': 'Eliminar cuenta',
  'settings.deleting': 'Eliminando…',
  'settings.error': 'Error',
  'settings.deleteAccountConfirm':
    'Esto eliminará de forma permanente tu cuenta y todos tus subrayados, etiquetas, notas y progreso de lectura. No se puede deshacer.',
  'settings.areYouSure': '¿Estás seguro?',
  'settings.deleteAccountFinal':
    'Tu cuenta y todos tus datos se eliminarán de inmediato y no se podrán recuperar.',
  'settings.deletePermanently': 'Sí, eliminar permanentemente',
  'settings.restoreFailed': 'Error al restaurar',
  'settings.proRestored': '¡Pro restaurado!',
  'settings.proRestoredBody': 'Tu suscripción ya está activa.',
  'settings.noSubscription': 'No se encontró ninguna suscripción',
  'settings.noSubscriptionBody':
    'No encontramos una suscripción activa vinculada a esta cuenta.',
  'settings.planGuest': 'Invitado',
  'settings.planStandard': 'Estándar',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (prueba)',
  'settings.welcomeToPro': '¡Bienvenido a Pro!',
  'settings.manage': 'Gestionar',

  'home.tags': 'Etiquetas',
  'home.notes': 'Notas',
  'home.xrefs': 'Remisiones',
  'home.readingPlan': 'PLAN DE LECTURA',
  'home.dailyVerses': 'VERSÍCULOS DIARIOS',
  'home.dailyReadingsTitle': 'Lecturas diarias',
  'home.tapToSetUp': 'Toca para configurar',
  'home.tapToReadVerse': 'Toca para leer un versículo',
  'home.tapToContinue': 'Toca para continuar',
  'home.planFinished': 'Terminado: elige tu próximo libro',
  'home.recentlyViewed': 'Visto recientemente',
  'home.removeFromRecent': 'Quitar de Visto recientemente',
  'home.removeFromRecentBody': '¿Quitar «{{title}}» y restablecer el progreso de lectura a 0 %?',
  'home.signInCreate': 'Iniciar sesión / Crear cuenta',
  'home.startReadingHint': 'Empieza a leer para ver aquí tus libros recientes.',
  'home.viewLibrary': 'VER BIBLIOTECA',
  'home.signInBlurb': 'Inicia sesión para ver tus libros vistos recientemente, tus anotaciones y más en todos tus dispositivos.',

  'auth.tagline': 'Lectura e investigación interreligiosa',
  'auth.usernamePlaceholder': 'Nombre de usuario *',
  'auth.fullNamePlaceholder': 'Nombre completo',
  'auth.emailPlaceholder': 'Correo electrónico *',
  'auth.passwordPlaceholder': 'Contraseña *',
  'auth.emailAddressPlaceholder': 'Dirección de correo *',
  'auth.signIn': 'Iniciar sesión',
  'auth.signUp': 'Registrarse',
  'auth.createAccount': 'Crear cuenta',
  'auth.forgotPassword': '¿Olvidaste tu contraseña?',
  'auth.browseWithout': 'Explorar sin una cuenta',
  'auth.guestSubtext': 'Lee y busca en los libros; el progreso y las notas no se guardarán',
  'auth.resetPassword': 'Restablecer contraseña',
  'auth.sendResetLink': 'Enviar enlace de restablecimiento',
  'auth.createPasswordPlaceholder': 'Crear contrase\u00f1a *',
  'auth.backToSignIn': 'Volver a iniciar sesi\u00f3n',
  'auth.forgotBlurb':
    'Introduce tu correo electr\u00f3nico y te enviaremos un enlace para restablecer la contrase\u00f1a.',
  'auth.usernameAvailable': '\u2713 Disponible',
  'auth.usernameTakenShort': '\u2717 En uso',
  'auth.usernameHint': '3\u201320 caracteres',
  'auth.usernameAlreadyTaken': 'El nombre de usuario ya est\u00e1 en uso.',
  'auth.resetLinkSent': 'Te enviamos un enlace para restablecer la contrase\u00f1a a {{email}}',
  'auth.error': 'Error',
  'auth.missingFields': 'Faltan campos',
  'auth.missingFieldsBody': 'Introduce el correo y la contraseña.',
  'auth.invalidUsername': 'Nombre de usuario no válido',
  'auth.invalidUsernameBody': 'El nombre de usuario debe tener de 3 a 20 caracteres: solo letras, números y guiones bajos.',
  'auth.usernameTaken': 'Nombre de usuario en uso',
  'auth.usernameTakenBody': 'Elige un nombre de usuario diferente.',
  'auth.checkUsername': 'Verifica el nombre de usuario',
  'auth.checkUsernameBody': 'Espera a que termine la validación del nombre de usuario.',
  'auth.checkEmail': 'Revisa tu correo',
  'auth.checkEmailBody': 'Enviamos un enlace de confirmación a {{email}}',
  'auth.checkEmailSignInBody':
    'Enviamos un enlace de confirmación a {{email}}. Después de confirmarlo, inicia sesión para acceder a tu cuenta.',
  'auth.enterEmail': 'Introduce el correo',
  'auth.enterEmailBody': 'Introduce tu dirección de correo electrónico.',
  'auth.emailSent': 'Correo enviado',
  'auth.emailSentBody': 'Revisa tu bandeja de entrada para ver el enlace de restablecimiento.',

  'auth.emailConfirmed': 'Correo confirmado',
  'auth.accountReadySignIn':
    'Tu cuenta est\u00e1 lista. Inicia sesi\u00f3n con tu correo y contrase\u00f1a para empezar.',
  'auth.accountReadyOpenApp':
    'Tu cuenta est\u00e1 lista. Abre la aplicaci\u00f3n Immerse en tu tel\u00e9fono para iniciar sesi\u00f3n, o contin\u00faa en la web m\u00e1s abajo.',
  'auth.openingApp': 'Tu cuenta est\u00e1 lista. Abriendo Immerse e iniciando tu sesi\u00f3n\u2026',
  'auth.openImmerse': 'Abrir Immerse',
  'auth.continueOnWeb': 'Continuar en la web',
  'auth.signInToImmerse': 'Iniciar sesi\u00f3n en Immerse',
  'auth.continueToImmerse': 'Continuar a Immerse',
  'auth.chooseNewPassword': 'Elige una contrase\u00f1a nueva para tu cuenta',
  'auth.newPasswordPlaceholder': 'Contrase\u00f1a nueva',
  'auth.confirmNewPasswordPlaceholder': 'Confirma la contrase\u00f1a nueva',
  'auth.updatePassword': 'Actualizar la contrase\u00f1a',
  'auth.enterConfirmPassword': 'Introduce y confirma tu contrase\u00f1a nueva.',
  'auth.passwordTooShort': 'La contrase\u00f1a debe tener al menos 8 caracteres.',
  'auth.passwordsDontMatch': 'Las contrase\u00f1as no coinciden.',
  'auth.passwordUpdated': 'Contrase\u00f1a actualizada',
  'auth.passwordUpdatedBody': 'Ya puedes usar tu contrase\u00f1a nueva.',
  'auth.resetFailed':
    'No se pudo actualizar la contrase\u00f1a. Es posible que el enlace haya caducado; solicita uno nuevo.',

  'reminders.headerTitle': 'Lecturas diarias',
  'reminders.enable': 'Activar lecturas diarias',
  'reminders.openSettings': 'Abrir Ajustes',
  'reminders.source': 'Fuente',
  'reminders.randomVerses': 'Versículos aleatorios',
  'reminders.readingPlan': 'Plan de lectura',
  'reminders.chooseBook': 'Elegir un libro',
  'reminders.bookFinished': 'Terminado ✓ — elige tu próximo libro',
  'reminders.sessionLength': 'Duración de la sesión',
  'reminders.sessionCaption': 'Se aplica a cada sesión: {{dur}} por la mañana y {{dur}} por la noche.',
  'reminders.reminders': 'Recordatorios',
  'reminders.time': 'Hora',
  'reminders.morning': 'Mañana',
  'reminders.evening': 'Noche',
  'reminders.yourStreak': 'Tu racha',
  'reminders.today': 'Hoy',
  'reminders.currentStreak': 'Racha actual',
  'reminders.bestStreak': 'Mejor racha',
  'reminders.completedBooks': 'Libros completados',
  'reminders.day_one': '{{count}} día',
  'reminders.day_other': '{{count}} días',
  'reminders.hour': '1 h',
  'reminders.minutes': '{{count}} min',
  'reminders.signInRequired': 'Se requiere iniciar sesión',
  'reminders.signInRequiredBody': 'Crea una cuenta para seguir un plan de lectura y llevar tu progreso.',
  'reminders.notNow': 'Ahora no',
  'reminders.enabledSub': 'Muestra tu lectura diaria en la pantalla de inicio.',
  'reminders.disabledSub': 'Desactivado: tu lectura diaria está oculta en la pantalla de inicio.',
  'reminders.chooseNextToResume': 'Elige arriba tu próximo libro para reanudar los recordatorios.',
  'reminders.chooseBookToEnable': 'Elige un libro arriba para activar los recordatorios.',
  'reminders.selectSourceToEnable': 'Selecciona al menos una fuente arriba para activar los recordatorios.',
  'reminders.todayComplete': 'completado ✓',
  'reminders.todayPending': 'pendiente',
  'reminders.todayMorningDone': 'mañana ✓',
  'reminders.todayMorningPending': 'mañana pendiente',
  'reminders.todayEveningDone': 'noche ✓',
  'reminders.todayEveningPending': 'noche pendiente',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Lee con más profundidad. Conecta más.',
  'paywall.featureAiLabel': 'Resúmenes de pasajes con IA',
  'paywall.featureAiDesc': 'Pide explicaciones y comentarios sobre cualquier pasaje',
  'paywall.featureVoicesLabel': 'Voces de lectura premium',
  'paywall.featureVoicesDesc': 'Narración natural y expresiva con la voz que elijas',
  'paywall.featureImportLabel': 'Importa tus propios libros',
  'paywall.featureImportDesc': 'Añade archivos EPUB, PDF y DOCX a tu biblioteca',
  'paywall.subscribe': 'Suscribirse — {{price}}/mes',
  'paywall.cancelNote': 'Cancela cuando quieras · Facturación mensual',
  'paywall.restore': 'Restaurar compras',
  'paywall.terms': 'Términos del servicio',
  'paywall.privacy': 'Política de privacidad',
  'paywall.notAvailable': 'No disponible',
  'paywall.notAvailableBody': 'Las compras dentro de la app aún no están configuradas en esta versión. Vuelve después del lanzamiento en la App Store.',
  'paywall.welcome': '¡Te damos la bienvenida a Pro!',
  'paywall.welcomeBody': 'Tu suscripción ya está activa.',
  'paywall.purchaseFailed': 'Error en la compra',
  'paywall.restoreFailed': 'Error al restaurar',

  'xrefs.title': 'Remisiones',
  'xrefs.empty': 'Aún no hay remisiones. Las remisiones que crees en el lector aparecerán aquí.',
  'xrefs.signInTitle': 'Inicia sesión para ver tus remisiones',
  'xrefs.signInBody': 'Conecta pasajes relacionados de toda la biblioteca.',
  'xrefs.searchSelected': 'Buscar en las remisiones seleccionadas...',
  'xrefs.searchPlaceholder': 'Buscar pasajes o etiquetas...',
  'xrefs.noMatch': 'Ninguna remisión coincide con tu búsqueda.',
  'xrefs.addLabel': 'Añadir etiqueta…',
  'xrefs.deleteConfirm': '¿Eliminar la remisión?',
  'xrefs.deleteBody': 'Las dos selecciones resaltadas se conservarán.',

  'notes.title': 'Notas',
  'notes.empty': 'Aún no hay notas. Las notas que crees en el lector aparecerán aquí.',
  'notes.signInTitle': 'Inicia sesión para ver tus notas',
  'notes.signInBody': 'Añade comentarios y reflexiones a los pasajes mientras lees.',
  'notes.searchPlaceholder': 'Buscar notas...',
  'notes.searchSelected': 'Buscar en las notas seleccionadas...',
  'notes.byBook': 'Por libro',
  'notes.byDate': 'Por fecha',
  'notes.writeNote': 'Escribe tu nota…',
  'notes.noMatch': 'Ninguna nota coincide con tu búsqueda.',
  'notes.deleteConfirm': '¿Eliminar la nota?',
  'notes.deleteBody': 'El subrayado se conservará.',

  'tags.title': 'Etiquetas',
  'tags.empty': 'Aún no hay etiquetas. Las etiquetas que crees en el lector aparecerán aquí.',
  'tags.signInTitle': 'Inicia sesión para ver tus etiquetas',
  'tags.signInBody': 'Crea y organiza recopilaciones de citas de toda la biblioteca.',
  'tags.organize': 'Organizar',
  'tags.searchPlaceholder': 'Buscar etiquetas...',
  'tags.searchSelected': 'Buscar en las etiquetas seleccionadas...',
  'tags.noMatch': 'Ninguna etiqueta coincide con tu búsqueda.',
  'tags.deleteConfirm': '¿Eliminar la etiqueta?',
  'tags.deleteBody': 'Se eliminarán «{{name}}» y todas sus selecciones.',

  'tags.renameTitle': 'Cambiar el nombre de la etiqueta',
  'tags.setPrivate': 'Hacer privada',
  'tags.setPublic': 'Hacer p\u00fablica',
  'tags.publicTag': 'Etiqueta p\u00fablica',
  'tags.removePassage': 'Quitar de la etiqueta',
  'tags.removePassageConfirm': '\u00bfQuitar este pasaje de la etiqueta?',
  'tags.indent': 'Aumentar sangr\u00eda',
  'tags.outdent': 'Reducir sangr\u00eda',
  'tags.organizeHint':
    'Arrastra el asa para reordenar \u00b7 \u21e4 \u21e5 para cambiar el nivel \u00b7 toca una etiqueta para reordenar sus citas.',
  'tags.searchTagsPassages': 'Buscar etiquetas y pasajes\u2026',
  'tags.exportSelected': 'Exportar las etiquetas seleccionadas',
  'tags.export': 'Exportar',
  'tags.exporting': 'Exportando\u2026',
  'tags.exportInclude': 'Incluir',
  'tags.exportNothingToInclude': 'Ninguna de las etiquetas seleccionadas tiene {{items}}',

  'panel.createAccount': 'Crear cuenta',
  'panel.signInToSave': 'Crea una cuenta gratuita para guardar etiquetas, notas y remisiones.',
  'panel.editSelection': 'Editar la selección de texto',

  'reader.xrefMode': 'Modo remisión: mantén pulsado para elegir un pasaje',
  'reader.error': 'Error del lector',
  'reader.opening': 'Abriendo el libro…',
  'reader.footnote': 'Nota al pie',

  'reader.selectBook': 'Elige un libro para empezar a leer',
  'reader.tableOfContents': '\u00cdndice',
  'reader.expandSection': 'Desplegar la secci\u00f3n',
  'reader.collapseSection': 'Contraer la secci\u00f3n',
  'reader.expand': 'Desplegar',
  'reader.collapse': 'Contraer',
  'reader.actionTag': 'Etiquetar',
  'reader.actionNote': 'Nota',
  'reader.actionXref': 'Remisi\u00f3n',
  'reader.actionAi': 'IA',
  'reader.actionCopy': 'Copiar',
  'reader.updateSelection': 'Actualizar la selecci\u00f3n',
  'reader.updating': 'Actualizando\u2026',
  'reader.pickAsXref': 'Elegir como remisi\u00f3n',
  'reader.editSelectionHint':
    'Resalta el nuevo texto de esta anotaci\u00f3n y luego elige',
  'reader.savingXref': 'Guardando la remisi\u00f3n\u2026',
  'reader.pickTargetHint': 'Selecciona texto o toca un pasaje para enlazarlo',
  'reader.footnoteUnavailable': 'El texto de la nota al pie no est\u00e1 disponible en la versi\u00f3n web.',
  'reader.bookNotFound': 'Libro no encontrado',
  'reader.viewTags': 'Ver las etiquetas',
  'reader.viewNote': 'Ver la nota',
  'reader.viewXrefs': 'Ver las remisiones',
  'reader.noQuotesFiled': 'Aqu\u00ed no hay citas archivadas.',

  'ai.summary': 'Resumen con IA',
  'ai.upgradeBlurb': 'Hazte Immerse Pro por solo 0,99 USD para usar los resúmenes con IA y otras funciones Pro.',
  'ai.upgradeBtn': 'Hazte Pro — 0,99 USD/mes',
  'ai.thinking': 'Pensando…',
  'ai.error': 'No se pudo obtener el resumen con IA. Comprueba tu conexión e inténtalo de nuevo.',
  'ai.copied': '✓ Copiado',
  'ai.copyHint': 'Mantén pulsado para copiar',

  'note.title': 'Nota',
  'note.addTitle': 'Añadir nota',
  'note.placeholder': 'Escribe tu nota aquí…',
  'note.loading': 'Cargando…',
  'note.emptyTitle': 'Nota vacía',
  'note.emptyBody': 'Escribe algo antes de guardar.',
  'note.saveFailed': 'No se pudo guardar la nota',
  'note.deleteTitle': '¿Eliminar la nota?',
  'note.deleteBody': 'Esto eliminará la nota. Si no hay otras anotaciones en este pasaje, también se eliminará la selección.',
  'note.deleteFailed': 'No se pudo eliminar la nota',
  'note.signInRequired': 'Se requiere iniciar sesión',
  'note.signInBody': 'Las notas se guardan en tu cuenta. Inicia sesión o crea una cuenta.',

  'xref.title': 'Remisión',
  'xref.yourSelection': 'TU SELECCIÓN',
  'xref.pickSecond': 'Elegir el segundo pasaje  →',
  'xref.noneFound': 'No se encontraron remisiones.',
  'xref.findPassage': 'Busca un pasaje para enlazar',
  'xref.searchPlaceholder': 'Buscar cualquier pasaje…',
  'xref.save': 'Guardar remisión',
  'xref.from': 'Desde',
  'xref.to': 'Hasta',
  'xref.linksTo': 'enlaza con',

  'banner.googlePlay': 'Disponible en Google Play',
  'banner.appStore': 'Descárgala en el App Store',
  'banner.install': 'Instalar',
  'banner.get': 'Obtener',

  'tagPanel.new': 'Nueva etiqueta',
  'tagPanel.create': 'Crear',
  'tagPanel.addTitle': 'Añadir etiquetas',
  'tagPanel.viewTitle': 'Etiquetas',
  'tagPanel.under': 'dentro de',
  'tagPanel.addSubTag': 'Añadir subetiqueta',
  'tagPanel.emptyAdd': 'Aún no hay etiquetas: crea una arriba',
  'tagPanel.emptyView': 'Esta selección no tiene etiquetas',

  'voice.title': 'Voz de lectura',
  'voice.onyx': 'Onyx — profunda y cálida',
  'voice.cedar': 'Cedar — natural y rica',
  'voice.ash': 'Ash — clara y directa',
  'voice.nova': 'Nova — brillante',
  'voice.shimmer': 'Shimmer — suave',
  'voice.marin': 'Marin — natural y suave',

  'reader.signInRequired': 'Se requiere iniciar sesión',
  'reader.signInBody': 'Crea una cuenta para etiquetar, anotar y guardar tu lectura.',
  'reader.notNow': 'Ahora no',
  'reader.signIn': 'Iniciar sesión',
  'reader.pdfNotFound': 'No se pudo encontrar el archivo PDF.',
  'reader.contentLoadFailed': 'No se pudo cargar el contenido',
  'reader.noBook': 'No se especificó ningún libro',
  'reader.storageError': 'Error de almacenamiento',

  'discover.recent': 'RECIENTES',
  'discover.trending': 'TENDENCIAS',
  'discover.searchPlaceholder': 'Buscar etiquetas y usuarios…',
  'discover.searchSelected': 'Buscar en las etiquetas seleccionadas…',
  'discover.import': 'Importar',
  'discover.imported': 'Importada',
  'discover.import_one': '{{count}} importación',
  'discover.import_other': '{{count}} importaciones',
  'discover.noneYet': 'Aún no hay etiquetas compartidas',
  'discover.noResults': 'Sin resultados',
  'discover.tryDifferent': 'Prueba con otro término de búsqueda.',
  'discover.signInTitle': 'Inicia sesión para acceder a Discover',
  'discover.signInBody': 'Descubre lo que otros lectores están explorando en todas las tradiciones.',
  'discover.anonymous': 'An\u00f3nimo',
  'discover.beFirst': 'S\u00e9 el primero en compartir una etiqueta.',
  'discover.ownTag': 'Esta etiqueta es tuya',
  'discover.alreadyImported': 'Ya importada',
  'discover.importFailed': 'Error al importar',
  'discover.exportFailed': 'Error al exportar',
  'discover.unknownError': 'Error desconocido',

  'usertags.autoImports': 'Importa automáticamente las etiquetas públicas del usuario a tu app',
  'usertags.noTags': 'Sin etiquetas públicas',
  'usertags.noTagsBody': 'Este usuario aún no ha compartido ninguna etiqueta.',
  'usertags.follow': 'Seguir',
  'usertags.unfollow': 'Dejar de seguir',
  'usertags.share': 'Compartir',
  'usertags.error': 'Error',
  'usertags.somethingWrong': 'Algo salió mal',

  'onboarding.chooseLanguage': 'Elige tu idioma',
  'onboarding.changeLaterSettings': 'Puedes cambiarlo más tarde en Ajustes.',
  'onboarding.libraryDownloadHint': 'Para descargar la biblioteca en {{language}}, toca el ⌄ junto a «Biblioteca» en la pantalla Biblioteca.',
  'onboarding.continue': 'Continuar',
  'onboarding.chooseTextSize': 'Elige el tamaño del texto',
  'onboarding.fontPreviewQuote':
    '«Buscad y hallaréis; llamad y se os abrirá.»',
  'onboarding.getStarted': 'Comenzar',
  'onboarding.closeIntro': 'Cerrar introducción',
  'onboarding.goToStep': 'Ir al paso {{number}}',
  'onboarding.libraryTitle': 'La Biblioteca',
  'onboarding.libraryCaption': 'Explora una biblioteca curada de múltiples tradiciones. Toca cualquier libro para empezar a leer.',
  'onboarding.searchTitle': 'Busca en todo',
  'onboarding.searchCaption': 'Busca en todos los libros a la vez y salta directamente al pasaje.',
  'onboarding.tagAsYouGoTitle': 'Etiqueta sobre la marcha',
  'onboarding.tagAsYouGoCaption': 'Añade una etiqueta a un pasaje desde los resultados de búsqueda.',
  'onboarding.buildTagsTitle': 'Crea tus etiquetas',
  'onboarding.buildTagsCaption': 'Agrupa pasajes bajo tus propias etiquetas para recordarlos fácilmente.',
  'onboarding.selectActTitle': 'Selecciona y actúa',
  'onboarding.selectActCaption': 'Selecciona cualquier texto para resaltarlo, etiquetarlo, anotarlo o crear una remisión.',
  'onboarding.marginTitle': 'Anotaciones al margen',
  'onboarding.marginCaption': 'Tus etiquetas, notas y remisiones viven en el margen.',
  'onboarding.navigateTitle': 'Navega rápidamente',
  'onboarding.navigateCaption': 'Abre el índice para moverte por un libro.',
  'onboarding.yourTagsTitle': 'Tus etiquetas',
  'onboarding.yourTagsCaption': 'Vuelve a cada pasaje etiquetado, organizado por etiqueta.',
  'onboarding.xrefsTitle': 'Remisiones',
  'onboarding.xrefsCaption': 'Enlaza pasajes relacionados entre libros y tradiciones.',
  'onboarding.shareTitle': 'Comparte y publica',
  'onboarding.shareCaption': 'Comparte una cita o publica una etiqueta para la comunidad.',

  // ── Hoja de exportación ───────────────────────────────────────────────────
  'export.shareTags_one': 'Compartir {{count}} etiqueta',
  'export.shareTags_other': 'Compartir {{count}} etiquetas',
  'export.shareTagsGeneric': 'Compartir etiquetas',
  'export.preparing': 'Preparando…',
  'export.notesOn': 'Tus notas escritas en cada pasaje',
  'export.notesNone': 'No hay notas en estos pasajes',
  'export.xrefsOn': 'Pasajes enlazados bajo cada cita',
  'export.xrefsNone': 'No hay remisiones en estos pasajes',
  'export.docxTitle': 'Documento de Word (.docx)',
  'export.docxShort': 'Word (.docx)',
  'export.docxDesc': 'Encabezados de etiqueta con los pasajes citados. Se abre en Word, Pages o Google Docs.',
  'export.pdfTitle': 'Documento PDF',
  'export.pdfDesc': 'Documento con formato para imprimir o compartir.',
  'export.csvTitle': 'Hoja de cálculo (.csv)',
  'export.csvDesc': 'Una fila por pasaje. Se abre en Excel, Numbers o Google Sheets.',
  'export.mdTitle': 'Markdown (.md)',
  'export.mdDesc': 'Para Obsidian, Notion o cualquier herramienta de texto plano.',
  'export.noPassagesTagged': '(ningún pasaje etiquetado)',
  'export.seeAlso': 'Véase también:',

  // ── Plan de lectura ───────────────────────────────────────────────────────
  'plan.chooseBook': 'Elige un libro',
  'plan.searchBooks': 'Buscar libros…',
  'plan.noBooksMatch': 'Ningún libro coincide con «{{query}}».',
  'plan.readingComplete': 'Lectura completada',
  'plan.morningSession': 'Sesión de la mañana',
  'plan.eveningSession': 'Sesión de la tarde',
  'plan.minutes': '{{count}} min',
  'plan.streakDay': 'Día {{count}} de racha ✓',
  'plan.sessionsToday': '{{done}} de {{required}} sesiones hoy',
  'plan.youFinished': 'Has terminado {{title}}',
  'plan.readOverDays_one': 'Leído en {{count}} día',
  'plan.readOverDays_other': 'Leído en {{count}} días',
  'plan.remindersPaused': 'los recordatorios están en pausa',
  'plan.chooseNextBook': 'Elige tu próximo libro',
  'completed.title': 'Libros completados',
  'completed.empty': 'Los libros que termines en tu plan de lectura aparecerán aquí.',
  'completed.finishedOn': 'Terminado el {{date}}',
  'completed.day_one': '{{count}} día',
  'completed.day_other': '{{count}} días',

  // ── Biblioteca ────────────────────────────────────────────────────────────
  'library.selectPassageForXref': 'Selecciona el pasaje para la remisión',
  'library.findingRelated': 'Buscando pasajes relacionados…',
  'library.importFailedTitle': 'Error al importar',
  'library.couldNotImport': 'No se pudo importar el archivo.',
  'library.bookAdded': 'Libro añadido',
  'library.bookAddedBody': '«{{title}}» ya está en Mis libros.',
  'library.importErrorTitle': 'Error de importación',
  'library.unexpectedError': 'Se ha producido un error inesperado.',
  'nav.browsingAsGuest': 'Navegando como invitado',
  'reader.selectBookToBegin': 'Selecciona un libro para empezar a leer',
  'tags.exportFailed': 'Error al exportar',
  'tags.couldNotExport': 'No se pudieron exportar las etiquetas.',
  'tags.couldNotRemoveSelection': 'No se pudo quitar la selección',
  'tags.reorderHint': 'Arrastra el asa para reordenar · ⇤ ⇥ para cambiar el nivel · toca una etiqueta para reordenar sus citas.',
  'tags.swipeHint': 'Desliza una etiqueta a la derecha para hacerla pública o privada.',
  'discover.publishHint':
    'Desliza a la derecha sobre una etiqueta en tu pantalla de Etiquetas para publicarla aquí.',
  'reminders.notificationsOff':
    'Las notificaciones están desactivadas para Immerse, así que no se pueden enviar '
    + 'recordatorios. Actívalas en los ajustes de tu dispositivo.',
  'plan.continueJourney': 'Continúa tu camino de lectura',
  'plan.yourBook': 'Tu libro',
  'reader.notesInParagraph_one': '{{count}} nota en este párrafo',
  'reader.notesInParagraph_other': '{{count}} notas en este párrafo',
  'plan.awaitsMorning': '{{book}} te espera — lectura de la mañana',
  'plan.awaitsEvening': '{{book}} te espera — lectura de la tarde',
  'reminders.dailyReadingFrom': 'Lectura diaria · {{source}}',
  'library.tapToExpandHint': 'Toca para desplegar · Mantén pulsado para abrir en el lector',
  'library.deleteBookImportedBody': 'Este libro y todas sus anotaciones se eliminarán permanentemente.',
  'library.deleteBookBundledBody':
    'Este libro y todas sus anotaciones se eliminarán. Volverá a aparecer la próxima vez que se actualice la biblioteca.',
  'library.deleteCategoryConfirm': '¿Eliminar «{{name}}»?',
  'library.deleteCategoryBody_one': 'Esto también eliminará {{count}} libro y todas sus anotaciones.',
  'library.deleteCategoryBody_other': 'Esto también eliminará {{count}} libros y todas sus anotaciones.',
  'library.deleteCategoryEmptyBody': 'Esta categoría se eliminará permanentemente.',

  'auth.passwordTooShortTitle': 'Contraseña demasiado corta',
  'auth.passwordsMustMatch': 'Asegúrate de que ambas contraseñas sean iguales.',
  'auth.usernamePlain': 'Nombre de usuario',
  'auth.fullNameOptional': 'Nombre completo (opcional)',
  'auth.emailPlain': 'Correo electrónico',
  'auth.passwordPlain': 'Contraseña',
  'auth.emailAddressPlain': 'Dirección de correo electrónico',

  // ── Tour de bienvenida (móvil) ────────────────────────────────────────────
  'onboarding.skip': 'Saltar',
  'onboarding.tour.libraryMain.label': 'Pantalla de la biblioteca',
  'onboarding.tour.libraryMain.caption':
    'La Biblioteca contiene más de 400 textos sagrados de todas las grandes tradiciones. Toca una tradición para explorar sus libros.',
  'onboarding.tour.libraryExpanded.label': 'Biblioteca desplegada',
  'onboarding.tour.libraryExpanded.caption':
    'Cada tradición se despliega para mostrar autores y colecciones. Toca cualquier título para abrirlo en el lector.',
  'onboarding.tour.librarySearch.label': 'Búsqueda en la biblioteca',
  'onboarding.tour.librarySearch.caption':
    'Busca en los más de 400 textos a la vez. Toca un resultado para desplegarlo o mantenlo pulsado para abrirlo directamente en el lector.',
  'onboarding.tour.searchQuickTag.label': 'Etiquetado rápido de resultados',
  'onboarding.tour.searchQuickTag.caption':
    'Selecciona uno o varios resultados de búsqueda y asígnalos a una etiqueta con un solo toque. Una forma rápida de crear una colección temática a partir de toda la biblioteca.',
  'onboarding.tour.home.label': 'Pantalla de inicio',
  'onboarding.tour.home.caption':
    'Tu pantalla de inicio muestra cuántas etiquetas, notas y remisiones has creado, además de tus libros leídos recientemente. Toca cualquier título para seguir leyendo.',
  'onboarding.tour.homePlan.label': 'Plan de lectura en el inicio',
  'onboarding.tour.homePlan.caption':
    'Crea el hábito de leer a diario: sigue un plan de lectura por el libro que elijas y durante el tiempo que quieras, o recibe versículos aleatorios de las tradiciones que selecciones, con recordatorios diarios y una racha que crece cada día que lees.',
  'onboarding.tour.settingsDaily.label': 'Ajustes de lecturas diarias',
  'onboarding.tour.settingsDaily.caption':
    'En Ajustes, configura los versículos aleatorios eligiendo las tradiciones de las que se extraen y las horas del día en las que quieres un recordatorio suave, o cambia a un plan de lectura para avanzar por un libro cada día.',
  'onboarding.tour.readerSelect.label': 'Selección de texto en el lector',
  'onboarding.tour.readerSelect.caption':
    'Mantén pulsado cualquier pasaje para seleccionarlo. Usa los iconos de la parte inferior de la pantalla para añadir una etiqueta, una nota o una remisión, u obtener un resumen con IA.',
  'onboarding.tour.readerNote.label': 'Nota en el lector',
  'onboarding.tour.readerNote.caption':
    'Las notas se adjuntan al texto exacto que seleccionaste. El marcador dorado del margen te permite encontrarlas y volver a abrirlas cuando quieras.',
  'onboarding.tour.readerXref.label': 'Remisión en el lector',
  'onboarding.tour.readerXref.caption':
    'Las remisiones enlazan pasajes de distintos libros y tradiciones. Mantén pulsada cualquier cita enlazada para saltar a ella en el lector.',
  'onboarding.tour.readerAi.label': 'Resumen con IA en el lector',
  'onboarding.tour.readerAi.caption':
    'Después de seleccionar un pasaje, toca el icono de destellos para obtener un resumen instantáneo con IA, especialmente útil en textos densos o poco conocidos.',
  'onboarding.tour.readerListen.label': 'Modo escucha en el lector',
  'onboarding.tour.readerListen.caption':
    'Toca el botón de auriculares para escuchar cualquier libro en voz alta: el lector resalta cada pasaje a medida que suena. Mantén pulsado el botón de auriculares para elegir entre una selección de voces naturales.',
  'onboarding.tour.tags.label': 'Pantalla de etiquetas',
  'onboarding.tour.tags.caption':
    'La pantalla de Etiquetas agrupa por tema los pasajes que has etiquetado. Toca el nombre de una etiqueta para ver sus pasajes citados con las referencias completas.',
  'onboarding.tour.xrefs.label': 'Pantalla de remisiones',
  'onboarding.tour.xrefs.caption':
    'La pantalla de Remisiones muestra todos tus pasajes enlazados uno junto a otro. Mantén pulsado cualquiera de los dos lados para saltar a ese pasaje en el lector.',
  'onboarding.tour.discover.label': 'Pantalla Descubrir',
  'onboarding.tour.discover.caption':
    'En la pantalla Descubrir encontrarás colecciones de etiquetas compartidas por otros lectores. Toca una etiqueta para ver sus pasajes y luego impórtala a tu propia biblioteca.',
  'onboarding.tour.tagShare.label': 'Panel para compartir etiquetas',
  'onboarding.tour.tagShare.caption':
    'Exporta cualquier colección de etiquetas como documento de Word, PDF, hoja de cálculo, Markdown y más, incluyendo tus notas y remisiones.',
};
