import type { en } from './en';

/**
 * Spanish UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key, so this file can be filled in gradually without the app
 * ever showing `settings.appLanguage` to a user.
 */
export const es: Partial<Record<keyof typeof en, string>> = {
  'common.cancel': 'Cancelar',
  'common.remove': 'Eliminar',
  'common.removing': 'Eliminando…',
  'common.save': 'Guardar',
  'common.done': 'Listo',
  'common.tryAgain': 'Inténtalo de nuevo.',
  'common.delete': 'Eliminar',
  'common.clear': 'Borrar',
  'common.signInCreate': 'Iniciar sesión o crear cuenta',
  'common.book_one': '{{count}} libro',
  'common.book_other': '{{count}} libros',
  'common.highlight_one': '{{count}} subrayado',
  'common.highlight_other': '{{count}} subrayados',

  'library.title': 'Biblioteca',
  'library.languageSheetTitle': 'Idioma de la biblioteca',
  'library.availableToDownload': 'Disponible para descargar',
  'library.downloading': 'Descargando {{percent}} %',
  'library.verifying': 'Verificando…',
  'library.importing': 'Importando…',
  'library.cleaning': 'Finalizando…',
  'library.downloadFailed': 'Error en la descarga',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Cambiar el idioma de la biblioteca',

  'settings.language': 'Idioma',
  'settings.appLanguage': 'Idioma de la aplicación',
  'settings.appLanguageHint':
    'Botones y menús. Independiente de la biblioteca que lees.',
  'settings.downloadedLibraries': 'Bibliotecas descargadas',
  'settings.downloadedLibrariesHint':
    'Cambia entre ellas desde la pantalla Biblioteca.',
  'settings.includedWithApp': 'incluida con la aplicación',
  'settings.removeLanguageTitle': '¿Eliminar {{language}}?',
  'settings.removeLanguageBody':
    'Estos libros se eliminarán de este dispositivo. Puedes descargarlos de nuevo cuando quieras.',
  'settings.removeLanguageKeepsAnnotations':
    'Tus {{annotations}} en estos libros se conservarán y reaparecerán si vuelves a descargar {{language}}.',
  'settings.removeFailed': 'No se pudo eliminar',
  'settings.account': 'Cuenta',
  'settings.fullName': 'Nombre completo',
  'settings.edit': 'Editar',
  'settings.username': 'Nombre de usuario',
  'settings.plan': 'Plan',
  'settings.fontSize': 'Tamaño de letra',
  'settings.fontPreview': 'Texto de muestra en tamaño {{size}}. Este ajuste se sincroniza en todos tus dispositivos.',
  'settings.dailyReadings': 'Lecturas diarias',
  'settings.randomVersesAndPlan': 'Versículos aleatorios y plan de lectura',
  'settings.readingMorningEvening': 'Una lectura por la mañana y por la noche',
  'settings.appearance': 'Apariencia',
  'settings.appearanceLight': 'Claro',
  'settings.appearanceDark': 'Oscuro',
  'settings.appearanceSystem': 'Sistema',
  'settings.upgrade': 'Mejorar',
  'settings.upgradeCta': 'HAZTE PRO — 0,99 USD/MES',
  'settings.upgradeBlurb':
    'Desbloquea resúmenes con IA, voces premium de lectura e importación de tus propios libros. 0,99 USD al mes.',
  'settings.purchases': 'Compras',
  'settings.restorePurchase': 'Restaurar compra',
  'settings.about': 'Acerca de',
  'settings.version': 'Versión',
  'settings.privacyPolicy': 'Política de privacidad',
  'settings.viewExternal': 'Ver ↗',
  'settings.termsOfService': 'Términos del servicio',
  'settings.replayOnboarding': 'Volver a ver la introducción',
  'settings.view': 'Ver',
  'settings.watchFeatureVideo': 'Ver el vídeo completo de funciones',
  'settings.accountActions': 'Acciones de la cuenta',
  'settings.legal': 'Legal',
  'settings.communityGuidelines': 'Normas de la comunidad',
  'settings.signOut': 'Cerrar sesión',
  'settings.deleteAccount': 'Eliminar cuenta',
  'settings.deleting': 'Eliminando…',
  'settings.error': 'Error',
  'settings.deleteAccountConfirm':
    'Esto eliminará de forma permanente tu cuenta y todos tus subrayados, etiquetas, notas y progreso de lectura. No se puede deshacer.',
  'settings.areYouSure': '¿Estás seguro?',
  'settings.deleteAccountFinal':
    'Tu cuenta y todos tus datos se eliminarán de inmediato y no se podrán recuperar.',
  'settings.deletePermanently': 'Sí, eliminar permanentemente',
  'settings.restoreFailed': 'Error al restaurar',
  'settings.proRestored': '¡Pro restaurado!',
  'settings.proRestoredBody': 'Tu suscripción ya está activa.',
  'settings.noSubscription': 'No se encontró ninguna suscripción',
  'settings.noSubscriptionBody':
    'No encontramos una suscripción activa vinculada a esta cuenta.',
  'settings.planGuest': 'Invitado',
  'settings.planStandard': 'Estándar',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (prueba)',

  'home.tags': 'Etiquetas',
  'home.notes': 'Notas',
  'home.xrefs': 'Remisiones',
  'home.readingPlan': 'PLAN DE LECTURA',
  'home.dailyVerses': 'VERSÍCULOS DIARIOS',
  'home.dailyReadingsTitle': 'Lecturas diarias',
  'home.tapToSetUp': 'Toca para configurar',
  'home.tapToReadVerse': 'Toca para leer un versículo',
  'home.tapToContinue': 'Toca para continuar',
  'home.planFinished': 'Terminado: elige tu próximo libro',
  'home.recentlyViewed': 'Visto recientemente',
  'home.removeFromRecent': 'Quitar de Visto recientemente',
  'home.signInCreate': 'Iniciar sesión / Crear cuenta',
  'home.startReadingHint': 'Empieza a leer para ver aquí tus libros recientes.',
  'home.viewLibrary': 'VER BIBLIOTECA',

  'auth.tagline': 'Lectura e investigación interreligiosa',
  'auth.usernamePlaceholder': 'Nombre de usuario *',
  'auth.fullNamePlaceholder': 'Nombre completo',
  'auth.emailPlaceholder': 'Correo electrónico *',
  'auth.passwordPlaceholder': 'Contraseña *',
  'auth.emailAddressPlaceholder': 'Dirección de correo *',
  'auth.signIn': 'Iniciar sesión',
  'auth.signUp': 'Registrarse',
  'auth.createAccount': 'Crear cuenta',
  'auth.forgotPassword': '¿Olvidaste tu contraseña?',
  'auth.browseWithout': 'Explorar sin una cuenta',
  'auth.guestSubtext': 'Lee y busca en los libros; el progreso y las notas no se guardarán',
  'auth.resetPassword': 'Restablecer contraseña',
  'auth.sendResetLink': 'Enviar enlace de restablecimiento',
  'auth.error': 'Error',
  'auth.missingFields': 'Faltan campos',
  'auth.missingFieldsBody': 'Introduce el correo y la contraseña.',
  'auth.invalidUsername': 'Nombre de usuario no válido',
  'auth.invalidUsernameBody': 'El nombre de usuario debe tener de 3 a 20 caracteres: solo letras, números y guiones bajos.',
  'auth.usernameTaken': 'Nombre de usuario en uso',
  'auth.usernameTakenBody': 'Elige un nombre de usuario diferente.',
  'auth.checkUsername': 'Verifica el nombre de usuario',
  'auth.checkUsernameBody': 'Espera a que termine la validación del nombre de usuario.',
  'auth.checkEmail': 'Revisa tu correo',
  'auth.checkEmailBody': 'Enviamos un enlace de confirmación a {{email}}',
  'auth.enterEmail': 'Introduce el correo',
  'auth.enterEmailBody': 'Introduce tu dirección de correo electrónico.',
  'auth.emailSent': 'Correo enviado',
  'auth.emailSentBody': 'Revisa tu bandeja de entrada para ver el enlace de restablecimiento.',

  'reminders.headerTitle': 'Lecturas diarias',
  'reminders.enable': 'Activar lecturas diarias',
  'reminders.openSettings': 'Abrir Ajustes',
  'reminders.source': 'Fuente',
  'reminders.randomVerses': 'Versículos aleatorios',
  'reminders.readingPlan': 'Plan de lectura',
  'reminders.chooseBook': 'Elegir un libro',
  'reminders.bookFinished': 'Terminado ✓ — elige tu próximo libro',
  'reminders.sessionLength': 'Duración de la sesión',
  'reminders.sessionCaption': 'Se aplica a cada sesión: {{dur}} por la mañana y {{dur}} por la noche.',
  'reminders.reminders': 'Recordatorios',
  'reminders.time': 'Hora',
  'reminders.morning': 'Mañana',
  'reminders.evening': 'Noche',
  'reminders.yourStreak': 'Tu racha',
  'reminders.today': 'Hoy',
  'reminders.currentStreak': 'Racha actual',
  'reminders.bestStreak': 'Mejor racha',
  'reminders.completedBooks': 'Libros completados',
  'reminders.day_one': '{{count}} día',
  'reminders.day_other': '{{count}} días',
  'reminders.hour': '1 h',
  'reminders.minutes': '{{count}} min',
  'reminders.signInRequired': 'Se requiere iniciar sesión',
  'reminders.signInRequiredBody': 'Crea una cuenta para seguir un plan de lectura y llevar tu progreso.',
  'reminders.notNow': 'Ahora no',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Lee con más profundidad. Conecta más.',
  'paywall.featureAiLabel': 'Resúmenes de pasajes con IA',
  'paywall.featureAiDesc': 'Pide explicaciones y comentarios sobre cualquier pasaje',
  'paywall.featureVoicesLabel': 'Voces de lectura premium',
  'paywall.featureVoicesDesc': 'Narración natural y expresiva con la voz que elijas',
  'paywall.featureImportLabel': 'Importa tus propios libros',
  'paywall.featureImportDesc': 'Añade archivos EPUB, PDF y DOCX a tu biblioteca',
  'paywall.subscribe': 'Suscribirse — {{price}}/mes',
  'paywall.cancelNote': 'Cancela cuando quieras · Facturación mensual',
  'paywall.restore': 'Restaurar compras',
  'paywall.terms': 'Términos del servicio',
  'paywall.privacy': 'Política de privacidad',
  'paywall.notAvailable': 'No disponible',
  'paywall.notAvailableBody': 'Las compras dentro de la app aún no están configuradas en esta versión. Vuelve después del lanzamiento en la App Store.',
  'paywall.welcome': '¡Te damos la bienvenida a Pro!',
  'paywall.welcomeBody': 'Tu suscripción ya está activa.',
  'paywall.purchaseFailed': 'Error en la compra',
  'paywall.restoreFailed': 'Error al restaurar',

  'xrefs.signInTitle': 'Inicia sesión para ver tus remisiones',
  'xrefs.signInBody': 'Conecta pasajes relacionados de toda la biblioteca.',
  'xrefs.searchSelected': 'Buscar en las remisiones seleccionadas...',
  'xrefs.searchPlaceholder': 'Buscar pasajes o etiquetas...',
  'xrefs.noMatch': 'Ninguna remisión coincide con tu búsqueda.',
  'xrefs.addLabel': 'Añadir etiqueta…',
  'xrefs.deleteConfirm': '¿Eliminar la remisión?',

  'notes.signInTitle': 'Inicia sesión para ver tus notas',
  'notes.signInBody': 'Añade comentarios y reflexiones a los pasajes mientras lees.',
  'notes.searchPlaceholder': 'Buscar notas...',
  'notes.searchSelected': 'Buscar en las notas seleccionadas...',
  'notes.byBook': 'Por libro',
  'notes.byDate': 'Por fecha',
  'notes.writeNote': 'Escribe tu nota…',
  'notes.noMatch': 'Ninguna nota coincide con tu búsqueda.',
  'notes.deleteConfirm': '¿Eliminar la nota?',
  'notes.deleteBody': 'El subrayado se conservará.',

  'tags.signInTitle': 'Inicia sesión para ver tus etiquetas',
  'tags.signInBody': 'Crea y organiza recopilaciones de citas de toda la biblioteca.',
  'tags.organize': 'Organizar',
  'tags.searchPlaceholder': 'Buscar etiquetas...',
  'tags.searchSelected': 'Buscar en las etiquetas seleccionadas...',
  'tags.noMatch': 'Ninguna etiqueta coincide con tu búsqueda.',
  'tags.deleteConfirm': '¿Eliminar la etiqueta?',

  'panel.createAccount': 'Crear cuenta',
  'panel.signInToSave': 'Crea una cuenta gratuita para guardar etiquetas, notas y remisiones.',
  'panel.editSelection': 'Editar la selección de texto',

  'reader.xrefMode': 'Modo remisión: mantén pulsado para elegir un pasaje',
  'reader.error': 'Error del lector',
  'reader.opening': 'Abriendo el libro…',
  'reader.footnote': 'Nota al pie',

  'ai.summary': 'Resumen con IA',
  'ai.upgradeBlurb': 'Hazte Immerse Pro por solo 0,99 USD para usar los resúmenes con IA y otras funciones Pro.',
  'ai.upgradeBtn': 'Hazte Pro — 0,99 USD/mes',
  'ai.thinking': 'Pensando…',
  'ai.error': 'No se pudo obtener el resumen con IA. Comprueba tu conexión e inténtalo de nuevo.',
  'ai.copied': '✓ Copiado',
  'ai.copyHint': 'Mantén pulsado para copiar',

  'note.placeholder': 'Escribe tu nota aquí…',
  'note.loading': 'Cargando…',
  'note.emptyTitle': 'Nota vacía',
  'note.emptyBody': 'Escribe algo antes de guardar.',
  'note.saveFailed': 'No se pudo guardar la nota',
  'note.deleteTitle': '¿Eliminar la nota?',
  'note.deleteBody': 'Esto eliminará la nota. Si no hay otras anotaciones en este pasaje, también se eliminará la selección.',
  'note.deleteFailed': 'No se pudo eliminar la nota',
  'note.signInRequired': 'Se requiere iniciar sesión',
  'note.signInBody': 'Las notas se guardan en tu cuenta. Inicia sesión o crea una cuenta.',

  'xref.title': 'Remisión',
  'xref.yourSelection': 'TU SELECCIÓN',
  'xref.pickSecond': 'Elegir el segundo pasaje  →',
  'xref.noneFound': 'No se encontraron remisiones.',

  'tagPanel.new': 'Nueva etiqueta',
  'tagPanel.create': 'Crear',

  'voice.title': 'Voz de lectura',
  'voice.onyx': 'Onyx — profunda y cálida',
  'voice.cedar': 'Cedar — natural y rica',
  'voice.ash': 'Ash — clara y directa',
  'voice.nova': 'Nova — brillante',
  'voice.shimmer': 'Shimmer — suave',
  'voice.marin': 'Marin — natural y suave',

  'reader.signInRequired': 'Se requiere iniciar sesión',
  'reader.signInBody': 'Crea una cuenta para etiquetar, anotar y guardar tu lectura.',
  'reader.notNow': 'Ahora no',
  'reader.signIn': 'Iniciar sesión',
  'reader.pdfNotFound': 'No se pudo encontrar el archivo PDF.',
  'reader.contentLoadFailed': 'No se pudo cargar el contenido',
  'reader.noBook': 'No se especificó ningún libro',
  'reader.storageError': 'Error de almacenamiento',

  'discover.recent': 'RECIENTES',
  'discover.trending': 'TENDENCIAS',
  'discover.searchPlaceholder': 'Buscar etiquetas y usuarios…',
  'discover.searchSelected': 'Buscar en las etiquetas seleccionadas…',
  'discover.import': 'Importar',
  'discover.imported': 'Importada',
  'discover.import_one': '{{count}} importación',
  'discover.import_other': '{{count}} importaciones',
  'discover.noneYet': 'Aún no hay etiquetas compartidas',
  'discover.noResults': 'Sin resultados',
  'discover.tryDifferent': 'Prueba con otro término de búsqueda.',
  'discover.signInTitle': 'Inicia sesión para acceder a Discover',
  'discover.signInBody': 'Descubre lo que otros lectores están explorando en todas las tradiciones.',
  'discover.importFailed': 'Error al importar',
  'discover.exportFailed': 'Error al exportar',
  'discover.unknownError': 'Error desconocido',

  'usertags.autoImports': 'Importa automáticamente las etiquetas públicas del usuario a tu app',
  'usertags.noTags': 'Sin etiquetas públicas',
  'usertags.noTagsBody': 'Este usuario aún no ha compartido ninguna etiqueta.',
  'usertags.follow': 'Seguir',
  'usertags.unfollow': 'Dejar de seguir',
  'usertags.share': 'Compartir',
  'usertags.error': 'Error',
  'usertags.somethingWrong': 'Algo salió mal',

  'onboarding.chooseLanguage': 'Elige tu idioma',
  'onboarding.changeLaterSettings': 'Puedes cambiarlo más tarde en Ajustes.',
  'onboarding.libraryDownloadHint': 'Para descargar la biblioteca en {{language}}, toca el ⌄ junto a «Biblioteca» en la pantalla Biblioteca.',
  'onboarding.continue': 'Continuar',
  'onboarding.chooseTextSize': 'Elige el tamaño del texto',
  'onboarding.getStarted': 'Comenzar',
};
