import type { LocaleTable } from './keys';

/**
 * Persian UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key.
 *
 * Every plural group carries only `_other`. A Persian noun stays singular after
 * a numeral — «۱ کتاب», «۵ کتاب» — so a separate `_one` would repeat the same
 * sentence word for word; the CLDR `one` category resolves to `_other`.
 *
 * Digits are left as the Latin ones the interpolated `{{count}}` produces
 * rather than being written as Persian numerals in the surrounding text, so a
 * counted string never mixes two numeral systems in one sentence.
 *
 * Persian punctuation throughout: «» for quotation, ‏«،» for the comma, «؟» for
 * the question mark. Arrows that mean "forward" point left, because in this
 * script forward *is* left — the one place an English arrow cannot be copied.
 *
 * Terminology fixed once, here: a tag/compilation is a *گزیده* (renamed
 * 2026-08-17 from *برچسب*), a note a *یادداشت*, a cross-reference an *ارجاع
 * متقابل*, a passage a *بند*, the reader itself the *کتاب‌خوان*. An x-ref's
 * own label is an *عنوان*, never a *گزیده*, so the two annotation kinds stay
 * tellable apart.
 */
export const fa: LocaleTable = {
  'common.cancel': 'لغو',
  'common.remove': 'برداشتن',
  'common.removing': 'در حال برداشتن…',
  'common.save': 'ذخیره',
  'common.done': 'تمام',
  'common.ok': 'تأیید',
  'common.continue': 'ادامه',
  'common.tryAgain': 'لطفاً دوباره تلاش کنید.',
  'common.delete': 'حذف',
  'common.clear': 'پاک کردن',
  'common.signInCreate': 'ورود / ثبت‌نام',
  'common.book_other': '{{count}} کتاب',
  'common.saving': 'در حال ذخیره…',
  'common.loading': 'در حال بارگذاری…',
  'common.copy': 'کپی',
  'common.retry': 'تلاش دوباره',
  'common.back': 'بازگشت',
  'common.next': 'بعدی',
  'common.searching': 'در حال جستجو…',
  'common.noResults': 'نتیجه‌ای یافت نشد.',
  'common.dismiss': 'بستن',
  'common.options': 'گزینه‌ها',
  'common.collapseLibrary': 'جمع کردن کتابخانه',
  'common.expandLibrary': 'باز کردن کتابخانه',
  'common.minutesAgo': '{{count}} دقیقه پیش',
  'common.hoursAgo': '{{count}} ساعت پیش',
  'common.daysAgo': '{{count}} روز پیش',
  'common.highlight_other': '{{count}} برجسته‌سازی',
  'common.edit': 'ویرایش',
  'common.justNow': 'هم‌اکنون',
  'common.opening': 'در حال باز کردن…',
  'common.or': 'یا',
  'common.pleaseWait': 'لطفاً صبر کنید…',
  'common.somethingWrong': 'مشکلی پیش آمد.',
  'common.rename': 'تغییر نام',
  'common.dragToReorder': 'برای تغییر ترتیب بکشید',
  'common.openInReader': 'باز کردن در کتاب‌خوان',
  'common.otherTradition': 'سایر',

  'nav.home': 'خانه',
  'nav.library': 'کتابخانه',
  'nav.tags': 'گزیده‌ها',
  'nav.notes': 'یادداشت‌ها',
  'nav.xrefs': 'ارجاعات',
  'nav.discover': 'کشف',
  'nav.settings': 'تنظیمات',
  'nav.guest': 'مهمان',
  'nav.reader': 'کتاب‌خوان',
  'nav.signOut': 'خروج',

  'library.title': 'کتابخانه',
  'library.languageSheetTitle': 'زبان کتابخانه',
  'library.availableToDownload': 'قابل دانلود',
  'library.downloading': 'در حال دانلود {{percent}}٪',
  'library.verifying': 'در حال بررسی…',
  'library.importing': 'در حال وارد کردن…',
  'library.cleaning': 'در حال اتمام…',
  'library.downloadFailed': 'دانلود ناموفق بود',
  'library.updateAvailable': 'به‌روزرسانی موجود است',
  'library.updateLanguageA11y': 'به‌روزرسانی {{language}}',
  'library.changeLanguageA11y': '{{title}}، {{language}}. تغییر زبان کتابخانه',

  'library.myBooks': 'کتاب‌های من',
  'library.searchAll': 'جستجو در همهٔ کتاب‌ها…',
  'library.searchSelected_other': 'جستجو در {{count}} کتاب انتخاب‌شده…',
  'library.noResultsFor': 'نتیجه‌ای برای «{{query}}» یافت نشد.',
  'library.result_other': '{{count}} نتیجه',
  'library.relatedPassages': 'بندهای مرتبط',
  'library.relatedOn': 'در',
  'library.relatedPrefix': 'مرتبط',
  'library.booksAndSections': 'کتاب‌ها و بخش‌ها',
  'library.tapToOpenHint': 'برای باز کردن ضربه بزنید',
  'library.importTitle': 'وارد کردن کتاب (TXT، EPUB، DOCX، RTF، PDF)',
  'library.importProFeature':
    'وارد کردن کتاب یک قابلیت پرو است. برای وارد کردن کتاب‌های خودتان، در تنظیمات ارتقا دهید.',
  'library.importFailed': 'وارد کردن ناموفق بود.',
  'library.importSucceeded': '«{{title}}» با موفقیت وارد شد.',
  'library.noImportedBooks':
    'هنوز کتابی وارد نشده است. برای وارد کردن کتاب از دکمهٔ کنار نوار جستجو استفاده کنید.',
  'library.deleteBookConfirm': '«{{title}}» حذف شود؟',
  'library.tagAction': 'گزیده',

  'settings.language': 'زبان',
  'settings.appLanguage': 'زبان برنامه',
  'settings.appLanguageHint': 'دکمه‌ها و منوها. جدا از کتابخانه‌ای که می‌خوانید.',
  'settings.restartForDirection': 'برای تکمیل تغییر، برنامه را دوباره باز کنید',
  'settings.restartForDirectionBody':
    '{{language}} از راست به چپ نوشته می‌شود. برای برگرداندن چیدمان، Immerse را ببندید و دوباره باز کنید.',
  'settings.restartForDirectionBodyLtr':
    'برای بازگرداندن چیدمان به چپ‌به‌راست، Immerse را ببندید و دوباره باز کنید.',
  'settings.downloadedLibraries': 'کتابخانه‌های دانلودشده',
  'settings.downloadedLibrariesHint': 'از صفحهٔ کتابخانه میان آن‌ها جابه‌جا شوید.',
  'settings.includedWithApp': 'همراه برنامه',
  'settings.removeLanguageTitle': '{{language}} برداشته شود؟',
  'settings.removeLanguageBody':
    'این کتاب‌ها از این دستگاه حذف می‌شوند. هر زمان بخواهید می‌توانید دوباره آن‌ها را دانلود کنید.',
  'settings.removeLanguageKeepsAnnotations':
    '{{annotations}} شما در این کتاب‌ها نگه داشته می‌شود و اگر دوباره {{language}} را دانلود کنید، بازمی‌گردد.',
  'settings.removeFailed': 'برداشتن ممکن نشد',
  'settings.account': 'حساب کاربری',
  'settings.fullName': 'نام کامل',
  'settings.edit': 'ویرایش',
  'settings.username': 'نام کاربری',
  'settings.plan': 'اشتراک',
  'settings.fontSize': 'اندازهٔ متن',
  'settings.fontPreview': 'پیش‌نمایش متن در اندازهٔ {{size}}. این تنظیم در همهٔ دستگاه‌های شما هماهنگ می‌شود.',
  'settings.dailyReadings': 'اعلان‌ها',
  'settings.randomVersesAndPlan': 'آیات تصادفی و برنامهٔ مطالعه',
  'settings.readingMorningEvening': 'یک مطالعه هر صبح و هر شب',
  'settings.appearance': 'ظاهر',
  'settings.appearanceLight': 'روشن',
  'settings.appearanceDark': 'تیره',
  'settings.appearanceSystem': 'سیستم',
  'settings.upgrade': 'ارتقا',
  'settings.upgradeCta': 'ارتقا به پرو — ماهانه $0.99',
  'settings.upgradeBlurb':
    'خلاصه‌های هوش مصنوعی، صداهای ویژهٔ گوینده و وارد کردن کتاب‌های خودتان را باز کنید. ماهانه $0.99.',
  'settings.purchases': 'خریدها',
  'settings.restorePurchase': 'بازیابی خرید',
  'settings.restorePurchaseHint': 'دسترسی Pro که پیش‌تر خریداری کرده‌اید را بازمی‌گرداند — از App Store، Google Play یا وب‌سایت.',
  'settings.about': 'درباره',
  'settings.version': 'نسخه',
  'settings.privacyPolicy': 'سیاست حریم خصوصی',
  'settings.viewExternal': 'مشاهده ↗',
  'settings.termsOfService': 'شرایط استفاده',
  'settings.introTour': 'تور معرفی',
  'settings.fullFeatureVideo': 'ویدیوی کامل قابلیت‌ها',
  'settings.replayOnboarding': 'پخش دوبارهٔ تصاویر معرفی',
  'settings.view': 'مشاهده',
  'settings.watchFeatureVideo': 'تماشای ویدیوی کامل قابلیت‌ها',
  'settings.accountActions': 'اقدامات حساب',
  'settings.legal': 'حقوقی',
  'settings.contactSupport': 'تماس با پشتیبانی',
  'settings.communityGuidelines': 'قواعد انجمن',
  'settings.signOut': 'خروج',
  'settings.deleteAccount': 'حذف حساب',
  'settings.deleting': 'در حال حذف…',
  'settings.error': 'خطا',
  'settings.deleteAccountConfirm':
    'این کار حساب شما و همهٔ حاشیه‌نویسی‌ها، گزیده‌ها، یادداشت‌ها و پیشرفت مطالعه‌تان را برای همیشه حذف می‌کند. این کار برگشت‌پذیر نیست.',
  'settings.areYouSure': 'مطمئن هستید؟',
  'settings.deleteAccountFinal':
    'حساب و همهٔ داده‌های شما بی‌درنگ حذف می‌شود و قابل بازیابی نخواهد بود.',
  'settings.deletePermanently': 'بله، برای همیشه حذف کن',
  'settings.restoreFailed': 'بازیابی ناموفق بود',
  'settings.proRestored': 'پرو بازیابی شد!',
  'settings.proRestoredBody': 'اشتراک شما اکنون فعال است.',
  'settings.noSubscription': 'اشتراکی یافت نشد',
  'settings.noSubscriptionBody':
    'اشتراک فعالی مرتبط با این حساب پیدا نکردیم.',
  'settings.planGuest': 'مهمان',
  'settings.planStandard': 'استاندارد',
  'settings.planPro': 'پرو',
  'settings.planTrial': 'پرو (آزمایشی)',

  'settings.welcomeToPro': 'به پرو خوش آمدید!',
  'settings.manage': 'مدیریت',
  'settings.subscribeToPro': 'اشتراک پرو',

  'home.tags': 'گزیده‌ها',
  'home.notes': 'یادداشت‌ها',
  'home.xrefs': 'ارجاعات',
  'home.readingPlan': 'برنامهٔ مطالعه',
  'home.dailyVerses': 'آیات روزانه',
  'home.dayStreak_other': '{{count}} روز پیاپی',
  'home.dailyReading': 'مطالعهٔ روزانه',
  'home.dailyReadingsTitle': 'مطالعهٔ روزانه',
  'home.tapToSetUp': 'برای تنظیم ضربه بزنید',
  'home.tapToReadVerse': 'برای خواندن یک آیه ضربه بزنید',
  'home.tapToContinue': 'برای ادامه ضربه بزنید',
  'home.planFinished': 'به پایان رسید — کتاب بعدی خود را انتخاب کنید',
  'home.recentlyViewed': 'اخیراً مشاهده‌شده',
  'home.removeFromRecent': 'برداشتن از موارد اخیر',
  'home.removeFromRecentBody': '«{{title}}» برداشته و پیشرفت مطالعه به ۰٪ بازنشانی شود؟',
  'home.signInCreate': 'ورود / ثبت‌نام',
  'home.startReadingHint': 'برای دیدن کتاب‌های اخیرتان در اینجا، مطالعه را آغاز کنید.',
  'home.viewLibrary': 'مشاهدهٔ کتابخانه',

  'home.signInBlurb': 'وارد شوید تا کتاب‌های اخیر، حاشیه‌نویسی‌ها و بیشتر را روی همهٔ دستگاه‌هایتان ببینید.',

  'auth.tagline': 'کتاب‌خوان و پژوهش بین‌ادیانی',
  'auth.usernamePlaceholder': 'نام کاربری ID *',
  'auth.fullNamePlaceholder': 'نام کامل',
  'auth.emailPlaceholder': 'ایمیل *',
  'auth.passwordPlaceholder': 'گذرواژه *',
  'auth.emailAddressPlaceholder': 'نشانی ایمیل *',
  'auth.signIn': 'ورود',
  'auth.signUp': 'ثبت‌نام',
  'auth.createAccount': 'ایجاد حساب',
  'auth.forgotPassword': 'گذرواژه را فراموش کرده‌اید؟',
  'auth.browseWithout': 'مرور بدون حساب کاربری',
  'auth.guestSubtext': 'کتاب‌ها را بخوانید و جستجو کنید — پیشرفت و یادداشت‌ها ذخیره نمی‌شود',
  'auth.resetPassword': 'بازنشانی گذرواژه',
  'auth.sendResetLink': 'ارسال پیوند بازنشانی',
  'auth.createPasswordPlaceholder': 'ساخت گذرواژه *',
  'auth.backToSignIn': 'بازگشت به ورود',
  'auth.forgotBlurb':
    'نشانی ایمیل خود را وارد کنید تا پیوندی برای بازنشانی گذرواژه برایتان بفرستیم.',
  'auth.usernameAvailable': '✓ در دسترس',
  'auth.usernameTakenShort': '✗ گرفته‌شده',
  'auth.usernameHint': '۳ تا ۲۰ نویسه',
  'auth.usernameAlreadyTaken': 'این نام کاربری قبلاً گرفته شده است.',
  'auth.resetLinkSent': 'پیوند بازنشانی گذرواژه را به {{email}} فرستادیم',
  'auth.error': 'خطا',
  'auth.missingFields': 'فیلدهای ناقص',
  'auth.missingFieldsBody': 'لطفاً ایمیل و گذرواژه را وارد کنید.',
  'auth.invalidUsername': 'نام کاربری نامعتبر',
  'auth.invalidUsernameBody': 'نام کاربری باید ۳ تا ۲۰ نویسه باشد: فقط حروف، ارقام و زیرخط.',
  'auth.usernameTaken': 'نام کاربری گرفته‌شده',
  'auth.usernameTakenBody': 'لطفاً نام کاربری دیگری انتخاب کنید.',
  'auth.checkUsername': 'بررسی نام کاربری',
  'auth.checkUsernameBody': 'لطفاً تا پایان بررسی نام کاربری صبر کنید.',
  'auth.checkEmail': 'ایمیل خود را بررسی کنید',
  'auth.checkEmailBody': 'پیوند تأیید را به {{email}} فرستادیم',
  'auth.checkEmailSignInBody':
    'پیوند تأیید را به {{email}} فرستادیم. پس از تأیید، برای دسترسی به حسابتان وارد شوید.',
  'auth.enterEmail': 'ایمیل را وارد کنید',
  'auth.enterEmailBody': 'لطفاً نشانی ایمیل خود را وارد کنید.',
  'auth.emailSent': 'ایمیل ارسال شد',
  'auth.emailSentBody': 'صندوق ورودی خود را برای پیوند بازنشانی گذرواژه بررسی کنید.',

  'auth.emailConfirmed': 'ایمیل تأیید شد',
  'auth.accountReadySignIn':
    'حساب شما آماده است. برای شروع، با ایمیل و گذرواژهٔ خود وارد شوید.',
  'auth.accountReadyOpenApp':
    'حساب شما آماده است. برای ورود، برنامهٔ Immerse را روی گوشی خود باز کنید، یا در ادامه از وب استفاده کنید.',
  'auth.openingApp': 'حساب شما آماده است. در حال باز کردن برنامهٔ Immerse و ورود شما…',
  'auth.openImmerse': 'باز کردن Immerse',
  'auth.continueOnWeb': 'در عوض، ادامه در وب',
  'auth.signInToImmerse': 'ورود به Immerse',
  'auth.continueToImmerse': 'ادامه به Immerse',
  'auth.chooseNewPassword': 'گذرواژهٔ تازه‌ای برای حساب خود انتخاب کنید',
  'auth.newPasswordPlaceholder': 'گذرواژهٔ جدید',
  'auth.confirmNewPasswordPlaceholder': 'تأیید گذرواژهٔ جدید',
  'auth.updatePassword': 'به‌روزرسانی گذرواژه',
  'auth.enterConfirmPassword': 'لطفاً گذرواژهٔ جدید خود را وارد و تأیید کنید.',
  'auth.passwordTooShort': 'گذرواژه باید دست‌کم ۸ نویسه باشد.',
  'auth.passwordsDontMatch': 'گذرواژه‌ها یکسان نیستند.',
  'auth.passwordUpdated': 'گذرواژه به‌روزرسانی شد',
  'auth.passwordUpdatedBody': 'اکنون می‌توانید از گذرواژهٔ جدید خود استفاده کنید.',
  'auth.resetFailed':
    'به‌روزرسانی گذرواژه ممکن نشد. ممکن است پیوند بازنشانی منقضی شده باشد — لطفاً پیوند تازه‌ای درخواست کنید.',

  'reminders.headerTitle': 'مطالعهٔ روزانه',
  'reminders.enable': 'فعال کردن مطالعهٔ روزانه',
  'reminders.openSettings': 'باز کردن تنظیمات',
  'reminders.source': 'منبع',
  'reminders.randomVerses': 'آیات تصادفی',
  'reminders.readingPlan': 'برنامهٔ مطالعه',
  'reminders.chooseBook': 'یک کتاب انتخاب کنید',
  'reminders.bookFinished': 'به پایان رسید ✓ — کتاب بعدی خود را انتخاب کنید',
  'reminders.sessionLength': 'مدت هر نشست',
  'reminders.sessionCaption': 'برای هر نشست اعمال می‌شود — {{dur}} صبح و {{dur}} شب.',
  'reminders.reminders': 'یادآورها',
  'reminders.time': 'زمان',
  'reminders.morning': 'صبح',
  'reminders.evening': 'شب',
  'reminders.yourStreak': 'روزهای پیاپی شما',
  'reminders.today': 'امروز',
  'reminders.currentStreak': 'روزهای پیاپی کنونی',
  'reminders.bestStreak': 'بهترین رکورد',
  'reminders.completedBooks': 'کتاب‌های تمام‌شده',
  'reminders.day_other': '{{count}} روز',
  'reminders.hour': '۱ ساعت',
  'reminders.minutes': '{{count}} دقیقه',
  'reminders.signInRequired': 'ورود لازم است',
  'reminders.signInRequiredBody': 'برای دنبال کردن برنامهٔ مطالعه و پیگیری پیشرفت خود، حساب بسازید.',
  'reminders.notNow': 'الان نه',
  'reminders.enabledSub': 'مطالعهٔ روزانهٔ شما را در صفحهٔ خانه نشان می‌دهد.',
  'reminders.disabledSub': 'خاموش — مطالعهٔ روزانهٔ شما از صفحهٔ خانه پنهان است.',
  'reminders.chooseNextToResume': 'برای از سرگیری یادآورها، کتاب بعدی خود را در بالا انتخاب کنید.',
  'reminders.chooseBookToEnable': 'برای روشن کردن یادآورها، کتابی را در بالا انتخاب کنید.',
  'reminders.selectSourceToEnable': 'برای روشن کردن یادآورها، دست‌کم یک منبع را در بالا انتخاب کنید.',
  'reminders.todayComplete': 'انجام شد ✓',
  'reminders.todayPending': 'در انتظار',
  'reminders.todayMorningDone': 'صبح ✓',
  'reminders.todayMorningPending': 'صبح در انتظار',
  'reminders.todayEveningDone': 'شب ✓',
  'reminders.todayEveningPending': 'شب در انتظار',

  'paywall.heading': 'Immerse پرو',
  'paywall.subheading': 'ژرف‌تر بخوانید. بیشتر پیوند بزنید.',
  'paywall.featureAiLabel': 'خلاصه‌های هوش مصنوعی برای بندها',
  'paywall.featureAiDesc': 'برای هر بند توضیح و شرح بخواهید',
  'paywall.featureVoicesLabel': 'صداهای ویژهٔ گوینده',
  'paywall.featureVoicesDesc': 'روایت طبیعی و گویا با صدای دلخواه شما',
  'paywall.featureImportLabel': 'وارد کردن کتاب‌های خودتان',
  'paywall.featureImportDesc': 'فایل‌های EPUB، PDF و DOCX را به کتابخانهٔ خود بیفزایید',
  'paywall.subscribe': 'اشتراک — {{price}} در ماه',
  'paywall.cancelNote': 'لغو در هر زمان · صورت‌حساب ماهانه',
  'paywall.restore': 'بازیابی خریدها',
  'paywall.terms': 'شرایط استفاده',
  'paywall.privacy': 'سیاست حریم خصوصی',
  'paywall.notAvailable': 'در دسترس نیست',
  'paywall.notAvailableBody': 'خرید درون‌برنامه‌ای هنوز در این نسخه پیکربندی نشده است. پس از انتشار در App Store دوباره سر بزنید.',
  'paywall.welcome': 'به پرو خوش آمدید!',
  'paywall.welcomeBody': 'اشتراک شما اکنون فعال است.',
  'paywall.purchaseFailed': 'خرید ناموفق بود',
  'paywall.restoreFailed': 'بازیابی ناموفق بود',

  'xrefs.title': 'ارجاعات متقابل',
  'xrefs.empty': 'هنوز ارجاع متقابلی نیست. ارجاعاتی که در کتاب‌خوان می‌سازید اینجا نمایان می‌شوند.',
  'xrefs.signInTitle': 'برای دیدن ارجاعات خود وارد شوید',
  'xrefs.signInBody': 'بندهای مرتبط را از سراسر کتابخانه به هم پیوند دهید.',
  'xrefs.searchSelected': 'جستجو در ارجاعات انتخاب‌شده...',
  'xrefs.searchPlaceholder': 'جستجوی بندها یا عنوان‌ها...',
  'xrefs.noMatch': 'هیچ ارجاعی با جستجوی شما مطابقت ندارد.',
  'xrefs.addLabel': 'افزودن عنوان…',
  'xrefs.deleteConfirm': 'ارجاع متقابل حذف شود؟',
  'xrefs.deleteBody': 'دو بند برجسته‌شده نگه داشته می‌شوند.',

  'notes.title': 'یادداشت‌ها',
  'notes.empty': 'هنوز یادداشتی نیست. یادداشت‌هایی که در کتاب‌خوان می‌سازید اینجا نمایان می‌شوند.',
  'notes.signInTitle': 'برای دیدن یادداشت‌های خود وارد شوید',
  'notes.signInBody': 'هنگام مطالعه، نظرها و تأملات خود را به بندها بیفزایید.',
  'notes.searchPlaceholder': 'جستجوی یادداشت‌ها...',
  'notes.searchSelected': 'جستجو در یادداشت‌های انتخاب‌شده...',
  'notes.byBook': 'بر پایهٔ کتاب',
  'notes.byDate': 'بر پایهٔ تاریخ',
  'notes.writeNote': 'یادداشت خود را بنویسید…',
  'notes.noMatch': 'هیچ یادداشتی با جستجوی شما مطابقت ندارد.',
  'notes.deleteConfirm': 'یادداشت حذف شود؟',
  'notes.deleteBody': 'بند برجسته‌شده نگه داشته می‌شود.',

  'tags.title': 'گزیده‌ها',
  'tags.empty': 'هنوز گزیده‌ای نیست. گزیده‌هایی که در کتاب‌خوان می‌سازید اینجا نمایان می‌شوند.',
  'tags.signInTitle': 'برای دیدن گزیده‌های خود وارد شوید',
  'tags.signInBody': 'مجموعه‌های نقل‌قول را از سراسر کتابخانه بسازید و سامان دهید.',
  'tags.organize': 'سامان‌دهی',
  'tags.searchPlaceholder': 'جستجوی گزیده‌ها...',
  'tags.searchSelected': 'جستجو در گزیده‌های انتخاب‌شده...',
  'tags.noMatch': 'هیچ گزیده‌ای با جستجوی شما مطابقت ندارد.',
  'tags.deleteConfirm': 'گزیده حذف شود؟',
  'tags.deleteBody': '«{{name}}» و همهٔ انتخاب‌هایش برداشته می‌شوند.',

  'tags.renameTitle': 'تغییر نام گزیده',
  'tags.setPrivate': 'خصوصی کردن',
  'tags.setPublic': 'عمومی کردن',
  'tags.publicTag': 'گزیدهٔ عمومی',
  'tags.removePassage': 'برداشتن از گزیده',
  'tags.removePassageConfirm': 'این بند از گزیده برداشته شود؟',
  'tags.indent': 'تورفتگی',
  'tags.outdent': 'بیرون‌بردگی',
  'tags.organizeHint':
    'برای تغییر ترتیب، دستگیره را بکشید \u00b7 \u21e4 \u21e5 برای تغییر سطح \u00b7 برای تغییر ترتیب نقل‌قول‌ها روی گزیده کلیک کنید.',
  'tags.searchTagsPassages': 'جستجوی گزیده‌ها و بندها…',
  'tags.exportSelected': 'برون‌بری گزیده‌های انتخاب‌شده',
  'xrefs.exportSelected': 'برون‌بری ارجاعات متقابل انتخاب‌شده',
  'tags.export': 'برون‌بری',
  'tags.exporting': 'در حال برون‌بری…',
  'tags.exportInclude': 'شامل',
  'tags.exportNothingToInclude': 'هیچ‌یک از گزیده‌های انتخاب‌شده {{items}} ندارند',

  'panel.createAccount': 'ایجاد حساب',
  'panel.signInToSave': 'برای ذخیرهٔ گزیده‌ها، یادداشت‌ها و ارجاعات، حساب رایگان بسازید.',
  'panel.editSelection': 'ویرایش متن انتخاب‌شده',

  'reader.xrefMode': 'حالت ارجاع — برای انتخاب بند، لمس طولانی کنید',
  'reader.error': 'خطای کتاب‌خوان',
  'reader.opening': 'در حال باز کردن کتاب…',
  'reader.footnote': 'پانویس',

  'reader.selectBook': 'برای شروع مطالعه، کتابی را انتخاب کنید',
  'reader.tableOfContents': 'فهرست مطالب',
  'reader.tocButtonHint': 'رفتن به بخشی از این کتاب',
  'reader.expandSection': 'باز کردن بخش',
  'reader.collapseSection': 'جمع کردن بخش',
  'reader.expand': 'باز کردن',
  'reader.collapse': 'جمع کردن',
  'reader.actionTag': 'گزیده',
  'reader.actionNote': 'یادداشت',
  'reader.actionXref': 'ارجاع',
  'reader.actionAi': 'هوش مصنوعی',
  'reader.actionCopy': 'کپی',
  'reader.updateSelection': 'به‌روزرسانی انتخاب',
  'reader.updating': 'در حال به‌روزرسانی…',
  'reader.pickAsXref': 'انتخاب به‌عنوان ارجاع',
  'reader.editSelectionHint':
    'متن تازه را برای این حاشیه‌نویسی برجسته کنید، سپس انتخاب کنید',
  'reader.savingXref': 'در حال ذخیرهٔ ارجاع متقابل…',
  'reader.pickTargetHint': 'متنی را انتخاب کنید یا برای پیوند روی بندی کلیک کنید',
  'reader.footnoteUnavailable': 'متن پانویس در نسخهٔ وب در دسترس نیست.',
  'reader.bookNotFound': 'کتاب پیدا نشد',
  'reader.viewTags': 'مشاهدهٔ گزیده‌ها',
  'reader.viewNote': 'مشاهدهٔ یادداشت',
  'reader.viewXrefs': 'مشاهدهٔ ارجاعات متقابل',
  'reader.noQuotesFiled': 'هیچ نقل‌قولی اینجا ثبت نشده است.',

  'ai.summary': 'خلاصهٔ هوش مصنوعی',
  'ai.upgradeBlurb': 'برای استفاده از خلاصه‌های هوش مصنوعی و دیگر قابلیت‌های پرو، تنها با $0.99 به Immerse پرو ارتقا دهید.',
  'ai.upgradeBtn': 'ارتقا به پرو — ماهانه $0.99',
  'ai.thinking': 'در حال اندیشیدن…',
  'ai.error': 'دریافت خلاصهٔ هوش مصنوعی ممکن نشد. لطفاً اتصال خود را بررسی کنید و دوباره تلاش کنید.',
  'ai.copied': '✓ کپی شد',
  'ai.copyHint': 'برای کپی، لمس طولانی کنید',

  'note.title': 'یادداشت',
  'note.addTitle': 'افزودن یادداشت',
  'note.placeholder': 'یادداشت خود را اینجا بنویسید…',
  'note.loading': 'در حال بارگذاری…',
  'note.emptyTitle': 'یادداشت خالی',
  'note.emptyBody': 'لطفاً پیش از ذخیره چیزی بنویسید.',
  'note.saveFailed': 'ذخیرهٔ یادداشت ممکن نشد',
  'note.deleteTitle': 'یادداشت حذف شود؟',
  'note.deleteBody': 'این کار یادداشت را برمی‌دارد. اگر حاشیه‌نویسی دیگری روی این بند نباشد، انتخاب هم برداشته می‌شود.',
  'note.deleteFailed': 'حذف یادداشت ممکن نشد',
  'note.signInRequired': 'ورود لازم است',
  'note.signInBody': 'یادداشت‌ها در حساب شما ذخیره می‌شوند. لطفاً وارد شوید یا حساب بسازید.',

  'xref.title': 'ارجاع متقابل',
  'xref.yourSelection': 'انتخاب شما',
  'xref.pickSecond': 'انتخاب بند دوم  ←',
  'xref.noneFound': 'ارجاع متقابلی یافت نشد.',

  'xref.findPassage': 'بندی برای پیوند بیابید',
  'xref.searchPlaceholder': 'جستجوی هر بند…',
  'xref.save': 'ذخیرهٔ ارجاع متقابل',
  'xref.from': 'از',
  'xref.to': 'به',
  'xref.linksTo': 'پیوند دارد به',

  'xref.suggestMatch': 'پیشنهاد یک مورد مرتبط',
  'xref.suggesting': 'در حال یافتن بندهای مرتبط…',
  'xref.suggestError': 'در حال حاضر دریافت پیشنهاد ممکن نشد',
  'xref.noMatches': 'موردی یافت نشد. خودتان یکی را انتخاب کنید.',
  'xref.looseMatch': 'تطابق تقریبی',
  'xref.useThisPassage': 'استفاده از این بند',
  'xref.inCompilation': 'در گزیدهٔ «{{name}}» شما',
  'xref.youNotedThis': 'برای این بند یادداشت دارید',

  'banner.googlePlay': 'دریافت از Google Play',
  'banner.appStore': 'دانلود از App Store',
  'banner.install': 'نصب',
  'banner.get': 'دریافت',

  'tagPanel.new': 'گزیدهٔ جدید',
  'tagPanel.createWithin': 'ایجاد گزیده‌ای در «{{parent}}»',
  'tagPanel.addTitle': 'افزودن به گزیده',
  'tagPanel.viewTitle': 'گزیده‌ها',
  'tagPanel.addSubTag': 'افزودن زیرگزیده',
  'tagPanel.emptyAdd': 'هنوز گزیده‌ای نیست — در بالا یکی بسازید',
  'tagPanel.emptyView': 'گزیده‌ای روی این انتخاب نیست',

  'voice.title': 'صدای خواندن',
  'voice.onyx': 'اونیکس — ژرف و گرم',
  'voice.cedar': 'سیدار — طبیعی و پرمایه',
  'voice.ash': 'اَش — شفاف و مستقیم',
  'voice.nova': 'نوا — روشن',
  'voice.shimmer': 'شیمر — نرم',
  'voice.marin': 'مارین — طبیعی و ملایم',

  'reader.signInRequired': 'ورود لازم است',
  'reader.signInBody': 'برای ذخیرهٔ گزیده‌ها، یادداشت‌ها و ارجاعات هنگام مطالعه، حساب بسازید.',
  'reader.notNow': 'الان نه',
  'reader.signIn': 'ورود',
  'reader.pdfNotFound': 'فایل PDF پیدا نشد.',
  'reader.contentLoadFailed': 'محتوا بارگذاری نشد',
  'reader.noBook': 'کتابی مشخص نشده است',
  'reader.storageError': 'خطای ذخیره‌سازی',

  'discover.recent': 'اخیر',
  'discover.trending': 'پرطرفدار',
  'discover.searchPlaceholder': 'جستجوی گزیده‌ها و کاربران…',
  'discover.searchSelected': 'جستجو در گزیده‌های انتخاب‌شده…',
  'discover.import': 'وارد کردن',
  'discover.imported': 'وارد شد',
  'discover.import_other': '{{count}} بار وارد شده',
  'discover.noneYet': 'هنوز گزیدهٔ هم‌رسانی‌شده‌ای نیست',
  'discover.noResults': 'نتیجه‌ای نیست',
  'discover.tryDifferent': 'عبارت جستجوی دیگری را امتحان کنید.',
  'discover.signInTitle': 'برای دسترسی به کشف وارد شوید',
  'discover.signInBody': 'ببینید دیگر خوانندگان در همهٔ سنت‌ها چه کشف می‌کنند.',
  'discover.anonymous': 'ناشناس',
  'discover.beFirst': 'نخستین کسی باشید که گزیده‌ای هم‌رسانی می‌کند.',
  'discover.ownTag': 'این گزیده خودتان است',
  'discover.alreadyImported': 'قبلاً وارد شده',
  'discover.importFailed': 'وارد کردن ناموفق بود',
  'discover.exportFailed': 'برون‌بری ناموفق بود',
  'discover.unknownError': 'خطای ناشناخته',

  'usertags.autoImports': 'گزیده‌های عمومی کاربر را به‌طور خودکار به برنامهٔ شما وارد می‌کند',
  'usertags.noTags': 'گزیدهٔ عمومی نیست',
  'usertags.noTagsBody': 'این کاربر هنوز گزیده‌ای هم‌رسانی نکرده است.',
  'usertags.follow': 'دنبال کردن',
  'usertags.unfollow': 'لغو دنبال کردن',
  'usertags.share': 'هم‌رسانی',
  'usertags.error': 'خطا',
  'usertags.somethingWrong': 'مشکلی پیش آمد',

  'onboarding.chooseLanguage': 'زبان خود را انتخاب کنید',
  'onboarding.changeLaterSettings': 'می‌توانید این را بعداً در تنظیمات تغییر دهید.',
  'onboarding.libraryDownloadHint': 'برای دانلود کتابخانه به {{language}}، در صفحهٔ کتابخانه روی ⌄ کنار «کتابخانه» ضربه بزنید.',
  'onboarding.continue': 'ادامه',
  'onboarding.chooseTextSize': 'اندازهٔ متن را انتخاب کنید',
  'onboarding.fontPreviewQuote':
    '«بجویید تا بیابید؛ بکوبید تا در به رویتان گشوده شود.»',
  'onboarding.getStarted': 'شروع کنیم',

  'onboarding.closeIntro': 'بستن معرفی',
  'onboarding.goToStep': 'رفتن به گام {{number}}',
  'onboarding.libraryTitle': 'کتابخانه',
  'onboarding.libraryCaption': 'کتابخانه‌ای گزیده از سنت‌های گوناگون را مرور کنید. برای شروع مطالعه روی هر کتابی ضربه بزنید.',
  'onboarding.searchTitle': 'جستجو در همه چیز',
  'onboarding.searchCaption': 'در همهٔ کتاب‌ها یکجا جستجو کنید و مستقیم به بند مورد نظر بروید.',
  'onboarding.tagAsYouGoTitle': 'همان‌جا گزیده بسازید',
  'onboarding.tagAsYouGoCaption': 'از همان نتایج جستجو، یک بند را به گزیده‌ای بیفزایید.',
  'onboarding.buildTagsTitle': 'گزیده‌های خود را بسازید',
  'onboarding.buildTagsCaption': 'بندها را زیر گزیده‌های خودتان گرد آورید تا آسان بازیابید.',
  'onboarding.selectActTitle': 'انتخاب و اقدام',
  'onboarding.selectActCaption': 'هر متنی را انتخاب کنید تا آن را برجسته کنید، به گزیده‌ای بیفزایید، یادداشت یا ارجاع دهید.',
  'onboarding.marginTitle': 'حاشیه‌نویسی‌های کناری',
  'onboarding.marginCaption': 'گزیده‌ها، یادداشت‌ها و ارجاعات شما در حاشیه جای دارند.',
  'onboarding.navigateTitle': 'جابه‌جایی سریع',
  'onboarding.navigateCaption': 'برای گشتن در کتاب، فهرست مطالب را باز کنید.',
  'onboarding.yourTagsTitle': 'گزیده‌های شما',
  'onboarding.yourTagsCaption': 'هر بندِ افزوده‌شده به گزیده را، مرتب‌شده بر پایهٔ گزیده، دوباره ببینید.',
  'onboarding.xrefsTitle': 'ارجاعات متقابل',
  'onboarding.xrefsCaption': 'بندهای مرتبط را در میان کتاب‌ها و سنت‌ها به هم پیوند دهید.',
  'onboarding.shareTitle': 'هم‌رسانی و انتشار',
  'onboarding.shareCaption': 'نقل‌قولی را هم‌رسانی کنید یا گزیده‌ای را برای انجمن منتشر کنید.',

  // ── پیوندهای هم‌رسانی (فاز ۵) ────────────────────────────────────────────
  'share.createLink': 'ساختن پیوند هم‌رسانی',
  'share.createLinkHint': 'یک صفحهٔ وب خصوصی. در کشف نمایش داده نمی‌شود.',
  'share.createLinkMultiHint': 'یک صفحهٔ وب خصوصی شامل همهٔ گردآوری‌های انتخاب‌شده. در کشف نمایش داده نمی‌شود.',
  'share.bundleTitle': 'گردآوری‌های به‌اشتراک‌گذاشته‌شده',
  'share.linkReady': 'پیوند آماده است',
  'share.linkCopied': 'پیوند رونوشت شد',
  'share.copyLink': 'رونوشت پیوند',
  'share.shareVia': 'هم‌رسانی…',
  'share.revoke': 'لغو',
  'share.revokeConfirm': 'این پیوند لغو شود؟ هر کسی که آن را دارد دسترسی‌اش را از دست می‌دهد.',
  'share.discoverToggle': 'انتشار در کشف',
  'share.discoverToggleHint': 'هر کسی می‌تواند این گزیده را بیابد و ذخیره کند.',
  'share.stopDiscover': 'حذف از کشف',
  'share.publishedNote': 'در کشف منتشر شد — برای توقف هم‌رسانی، کلید را خاموش کنید.',
  'share.selectOne': 'برای ساختن پیوند، یک گزیده انتخاب کنید.',
  'sharePage.eyebrow': 'گزیدهٔ هم‌رسانی‌شده',
  'sharePage.openInReader': 'باز کردن در کتاب‌خوان',
  'sharePage.save': 'ذخیره در گزیده‌های من',
  'sharePage.saving': 'در حال ذخیره…',
  'sharePage.saved': 'در گزیده‌های شما ذخیره شد',
  'sharePage.saveHint': 'برنامهٔ Immerse را باز می‌کند، یا برای ذخیره در وب وارد شوید.',
  'sharePage.signInToSave': 'برای ذخیرهٔ این در گزیده‌هایتان وارد شوید.',
  'sharePage.footer': 'در Immerse بیشتر بخوانید',

  // ── Share links: cross-references (Phase 8) ───────────────────────────────
  'share.createLinkXrefHint': 'یک صفحهٔ وب خصوصی که این ارجاعات متقابل را نشان می‌دهد. در کشف نمایش داده نمی‌شود.',
  'sharePage.xrefEyebrow': 'ارجاعات متقابل هم‌رسانی‌شده',
  'sharePage.saveXrefs': 'ذخیره در ارجاعات متقابل من',
  'sharePage.savedXrefs': 'در ارجاعات متقابل شما ذخیره شد',
  'sharePage.savedXrefsPartial': '{{saved}} از {{total}} ذخیره شد — {{skipped}} مورد به محتوایی نیاز دارد که ندارید',
  'sharePage.xrefsGone': 'این ارجاعات متقابل دیگر در دسترس نیستند',

  'export.shareTags_other': 'هم‌رسانی {{count}} گزیده',
  'export.shareTagsGeneric': 'هم‌رسانی گزیده‌ها',
  'export.shareXrefs_other': 'هم‌رسانی {{count}} ارجاع متقابل',
  'export.preparing': 'در حال آماده‌سازی…',
  'export.notesOn': 'یادداشت‌های نوشتهٔ شما روی هر بند',
  'export.notesNone': 'یادداشتی روی این بندها نیست',
  'export.xrefsOn': 'بندهای پیونددادهٔ زیر هر نقل‌قول',
  'export.xrefsNone': 'ارجاع متقابلی روی این بندها نیست',
  'export.docxTitle': 'سند Word (.docx)',
  'export.docxShort': 'ورد (.docx)',
  'export.docxDesc': 'سرعنوان گزیده‌ها همراه با بندهای نقل‌شده. در Word، Pages یا Google Docs باز می‌شود.',
  'export.pdfTitle': 'سند PDF',
  'export.pdfDesc': 'سندی قالب‌بندی‌شده برای چاپ یا هم‌رسانی.',
  'export.csvTitle': 'صفحه‌گسترده (.csv)',
  'export.csvDesc': 'هر بند در یک سطر. در Excel، Numbers یا Google Sheets باز می‌شود.',
  'export.mdTitle': 'مارک‌داون (.md)',
  'export.mdDesc': 'برای Obsidian، Notion یا هر ابزار متن ساده.',
  'export.noPassagesTagged': '(بندی در این گزیده نیست)',
  'export.seeAlso': 'همچنین ببینید:',

  'plan.chooseBook': 'یک کتاب انتخاب کنید',
  'plan.searchBooks': 'جستجوی کتاب‌ها…',
  'plan.noBooksMatch': 'هیچ کتابی با «{{query}}» مطابقت ندارد.',
  'plan.readingComplete': 'مطالعه کامل شد',
  'plan.morningSession': 'نشست صبح',
  'plan.eveningSession': 'نشست شب',
  'plan.minutes': '{{count}} دقیقه',
  'plan.streakDay': 'روز پیاپی {{count}} ✓',
  'plan.sessionsToday': '{{done}} از {{required}} نشست امروز',
  'plan.youFinished': '{{title}} را به پایان رساندید',
  'plan.readOverDays_other': 'خواندن در {{count}} روز',
  'plan.remindersPaused': 'یادآورها متوقف شده‌اند',
  'plan.chooseNextBook': 'کتاب بعدی خود را انتخاب کنید',
  'completed.title': 'کتاب‌های تمام‌شده',
  'completed.empty': 'کتاب‌هایی که در برنامهٔ مطالعه به پایان می‌رسانید اینجا نمایان می‌شوند.',
  'completed.finishedOn': 'پایان‌یافته در {{date}}',
  'completed.day_other': '{{count}} روز',

  'library.selectPassageForXref': 'بند را برای ارجاع متقابل انتخاب کنید',
  'library.findingRelated': 'در حال یافتن بندهای مرتبط…',
  'library.aiSearchOffline': 'برای جست‌وجو با پرسش به اتصال اینترنت نیاز است',
  'library.importFailedTitle': 'وارد کردن ناموفق بود',
  'library.couldNotImport': 'وارد کردن فایل ممکن نشد.',
  'library.bookAdded': 'کتاب افزوده شد',
  'library.bookAddedBody': '«{{title}}» اکنون در کتاب‌های من است.',
  'library.importErrorTitle': 'خطای وارد کردن',
  'library.unexpectedError': 'خطای غیرمنتظره‌ای رخ داد.',
  'nav.browsingAsGuest': 'مرور به‌عنوان مهمان',
  'reader.selectBookToBegin': 'برای شروع مطالعه، کتابی را انتخاب کنید',
  'tags.exportFailed': 'برون‌بری ناموفق بود',
  'tags.couldNotExport': 'برون‌بری گزیده‌ها ممکن نشد.',
  'tags.couldNotRemoveSelection': 'برداشتن انتخاب ممکن نشد',
  'tags.reorderHint': 'برای تغییر ترتیب، دستگیره را بکشید · ⇤ ⇥ برای تغییر سطح · برای تغییر ترتیب نقل‌قول‌ها روی گزیده ضربه بزنید.',
  'tags.swipeHint': 'برای عمومی یا خصوصی کردن گزیده، آن را به راست بکشید.',
  'discover.publishHint': 'برای انتشار گزیده در اینجا، در صفحهٔ گزیده‌ها آن را به راست بکشید.',
  'reminders.notificationsOff':
    'اعلان‌ها برای Immerse خاموش است، بنابراین یادآورها نمی‌توانند فرستاده شوند. '
    + 'آن‌ها را در تنظیمات دستگاه خود فعال کنید.',
  'plan.continueJourney': 'سفر مطالعهٔ خود را ادامه دهید',
  'plan.yourBook': 'کتاب شما',
  'reader.notesInParagraph_other': '{{count}} یادداشت در این بند',
  'plan.awaitsMorning': '{{book}} در انتظار است — مطالعهٔ صبح',
  'plan.awaitsEvening': '{{book}} در انتظار است — مطالعهٔ شب',
  'reminders.dailyReadingFrom': 'مطالعهٔ روزانه · {{source}}',
  'library.tapToExpandHint': 'برای باز شدن ضربه بزنید · برای باز کردن در کتاب‌خوان نگه دارید',
  'library.deleteBookImportedBody': 'این کتاب و همهٔ حاشیه‌نویسی‌هایش برای همیشه برداشته می‌شوند.',
  'library.deleteBookBundledBody':
    'این کتاب و همهٔ حاشیه‌نویسی‌هایش برداشته می‌شوند. در به‌روزرسانی بعدی کتابخانه بازمی‌گردد.',
  'library.deleteCategoryConfirm': '«{{name}}» حذف شود؟',
  'library.deleteCategoryBody_other': 'این کار {{count}} کتاب و همهٔ حاشیه‌نویسی‌هایشان را نیز برمی‌دارد.',
  'library.deleteCategoryEmptyBody': 'این دسته برای همیشه برداشته می‌شود.',

  'auth.passwordTooShortTitle': 'گذرواژه بسیار کوتاه است',
  'auth.passwordsMustMatch': 'لطفاً مطمئن شوید هر دو گذرواژه یکسان‌اند.',
  'auth.usernamePlain': 'نام کاربری ID',
  'auth.fullNameOptional': 'نام کامل (اختیاری)',
  'auth.emailPlain': 'ایمیل',
  'auth.passwordPlain': 'گذرواژه',
  'auth.emailAddressPlain': 'نشانی ایمیل',

  'onboarding.skip': 'رد کردن',
  'onboarding.tour.libraryMain.label': 'صفحهٔ کتابخانه',
  'onboarding.tour.libraryMain.caption':
    'کتابخانه بیش از ۴۰۰ متن مقدس از همهٔ سنت‌های بزرگ را در بر دارد. برای کاوش کتاب‌های هر سنت، روی آن ضربه بزنید.',
  'onboarding.tour.libraryExpanded.label': 'کتابخانهٔ بازشده',
  'onboarding.tour.libraryExpanded.caption':
    'هر سنت باز می‌شود و نویسندگان و مجموعه‌ها را نشان می‌دهد. برای باز کردن هر عنوان در کتاب‌خوان، روی آن ضربه بزنید.',
  'onboarding.tour.librarySearch.label': 'جستجوی کتابخانه',
  'onboarding.tour.librarySearch.caption':
    'در بیش از ۴۰۰ متن یکجا جستجو کنید. برای باز شدن نتیجه روی آن ضربه بزنید — برای باز کردن مستقیم در کتاب‌خوان لمس طولانی کنید.',
  'onboarding.tour.searchQuickTag.label': 'گزیدهٔ سریع نتیجهٔ جستجو',
  'onboarding.tour.searchQuickTag.caption':
    'یک یا چند نتیجهٔ جستجو را انتخاب کنید و با یک ضربه به گزیده‌ای بیفزایید. راهی سریع برای ساختن مجموعه‌ای موضوعی از سراسر کتابخانه.',
  'onboarding.tour.home.label': 'صفحهٔ خانه',
  'onboarding.tour.home.caption':
    'صفحهٔ خانهٔ شما نشان می‌دهد چند گزیده، یادداشت و ارجاع ساخته‌اید، به‌همراه کتاب‌هایی که اخیراً خوانده‌اید. برای ادامهٔ مطالعه روی هر عنوان ضربه بزنید.',
  'onboarding.tour.homePlan.label': 'برنامهٔ مطالعه در صفحهٔ خانه',
  'onboarding.tour.homePlan.caption':
    'عادت مطالعهٔ روزانه بسازید: برنامهٔ مطالعه‌ای را در کتاب دلخواه و به مدت دلخواه دنبال کنید، یا آیات تصادفی از سنت‌های برگزیدهٔ خود دریافت کنید — با یادآورهای روزانه و شمار روزهای پیاپی که با هر روز مطالعه بیشتر می‌شود.',
  'onboarding.tour.settingsDaily.label': 'تنظیمات مطالعهٔ روزانه',
  'onboarding.tour.settingsDaily.caption':
    'در تنظیمات، آیات تصادفی را با برگزیدن سنت‌های منبع و ساعت‌هایی که دوست دارید یادآوری ملایمی دریافت کنید تنظیم کنید — یا به برنامهٔ مطالعه بروید تا هر روز یک کتاب را پیش ببرید.',
  'onboarding.tour.readerSelect.label': 'انتخاب متن در کتاب‌خوان',
  'onboarding.tour.readerSelect.caption':
    'برای انتخاب هر بند، لمس طولانی کنید. از نمادهای پایین صفحه برای افزودن به گزیده، یادداشت، ارجاع متقابل یا گرفتن خلاصهٔ هوش مصنوعی استفاده کنید.',
  'onboarding.tour.readerNote.label': 'مشاهدهٔ یادداشت در کتاب‌خوان',
  'onboarding.tour.readerNote.caption':
    'یادداشت‌ها به همان متنی که انتخاب کرده‌اید می‌چسبند. نشانگر طلایی در حاشیه به شما امکان می‌دهد هر زمان آن‌ها را بیابید و دوباره باز کنید.',
  'onboarding.tour.readerXref.label': 'مشاهدهٔ ارجاع متقابل در کتاب‌خوان',
  'onboarding.tour.readerXref.caption':
    'ارجاعات متقابل، بندها را در کتاب‌ها و سنت‌های گوناگون به هم پیوند می‌دهند. برای رفتن به هر نقل‌قول پیونددار در کتاب‌خوان، روی آن لمس طولانی کنید.',
  'onboarding.tour.readerAi.label': 'خلاصهٔ هوش مصنوعی در کتاب‌خوان',
  'onboarding.tour.readerAi.caption':
    'پس از انتخاب یک بند، روی نماد درخشش ضربه بزنید تا بی‌درنگ خلاصه‌ای هوشمند بگیرید — به‌ویژه برای متن‌های دشوار یا ناآشنا سودمند است.',
  'onboarding.tour.readerListen.label': 'حالت شنیدن در کتاب‌خوان',
  'onboarding.tour.readerListen.caption':
    'برای شنیدن هر کتاب، روی دکمهٔ هدفون ضربه بزنید — کتاب‌خوان هر بند را هنگام پخش برجسته می‌کند. برای برگزیدن از میان صداهای طبیعی، دکمهٔ هدفون را لمس کنید و نگه دارید.',
  'onboarding.tour.tags.label': 'صفحهٔ گزیده‌ها',
  'onboarding.tour.tags.caption':
    'صفحهٔ گزیده‌ها بندهای افزوده‌شده به گزیده‌های شما را بر پایهٔ موضوع گرد می‌آورد. برای دیدن بندهای نقل‌شده با ارجاع کامل، روی نام گزیده ضربه بزنید.',
  'onboarding.tour.xrefs.label': 'صفحهٔ ارجاعات متقابل',
  'onboarding.tour.xrefs.caption':
    'صفحهٔ ارجاعات متقابل همهٔ بندهای پیونددادهٔ شما را کنار هم نشان می‌دهد. برای رفتن به هر بند در کتاب‌خوان، روی هر سو لمس طولانی کنید.',
  'onboarding.tour.discover.label': 'صفحهٔ کشف',
  'onboarding.tour.discover.caption':
    'در صفحهٔ کشف، گزیده‌هایی را بیابید که دیگر خوانندگان هم‌رسانی کرده‌اند. برای پیش‌نمایش بندهای یک گزیده روی آن ضربه بزنید، سپس آن را به کتابخانهٔ خود وارد کنید.',
  'onboarding.tour.tagShare.label': 'پنل هم‌رسانی گزیده',
  'onboarding.tour.tagShare.caption':
    'هر گزیده‌ای را به‌صورت سند Word، PDF، صفحه‌گسترده، مارک‌داون و بیشتر برون‌بری کنید — همراه با یادداشت‌ها و ارجاعات شما.',

  // ── Appearance (reader typography) ───────────────────────────────────────
  'appearance.title': 'ظاهر',
  'appearance.navHint': 'قلم، فاصله، رنگ صفحه',
  'appearance.reading': 'خواندن',
  'appearance.preview': 'پیش‌نمایش',
  'appearance.previewText': 'خواندن گفت‌وگویی آرام است که از میان قرن‌ها می‌گذرد.',
  'appearance.previewHeading': 'فصل اول',
  'appearance.typeface': 'قلم',
  'appearance.typefaceSystem': 'پیش‌فرض دستگاه',
  'appearance.typefaceLiterataBlurb': 'ساخته‌شده برای خواندن طولانی. با اندازه سازگار می‌شود.',
  'appearance.typefaceCharisBlurb': 'برگرفته از Charter. در اندازهٔ کوچک خوانا.',
  'appearance.typefaceGaramondBlurb': 'کلاسیک و قدیمی. سبک‌تر بر صفحه.',
  'appearance.typefaceSystemBlurb': 'هر قلمی که این دستگاه دارد.',
  'appearance.textSize': 'اندازهٔ متن',
  'appearance.lineSpacing': 'فاصلهٔ خطوط',
  'appearance.lineSpacingTight': 'فشرده',
  'appearance.lineSpacingNormal': 'معمولی',
  'appearance.lineSpacingRelaxed': 'راحت',
  'appearance.lineSpacingLoose': 'بسیار باز',
  'appearance.margins': 'حاشیه‌ها',
  'appearance.marginsNarrow': 'باریک',
  'appearance.marginsNormal': 'معمولی',
  'appearance.marginsWide': 'پهن',
  'appearance.justify': 'تراز دوطرفه',
  'appearance.justifyHint': 'هر دو لبه را تراز می‌کند، همراه با شکستن کلمات.',
  'appearance.paragraphStyle': 'بندها',
  'appearance.paragraphSpaced': 'با فاصله',
  'appearance.paragraphIndented': 'با تورفتگی',
  'appearance.paragraphHint': 'تورفتگی، شیوهٔ سنتی صفحه‌آرایی کتاب است.',
  'appearance.theme': 'رنگ صفحه',
  'appearance.themeLight': 'روشن',
  'appearance.themeSepia': 'سپیا',
  'appearance.themeQuiet': 'ملایم',
  'appearance.themeDark': 'تیره',
  'appearance.themeNight': 'شب',
  'appearance.themeSystem': 'مانند برنامه',
  'appearance.fineTuning': 'تنظیم دقیق',
  'appearance.characterSpacing': 'فاصلهٔ حروف',
  'appearance.wordSpacing': 'فاصلهٔ کلمات',
  'appearance.textWeight': 'ضخامت متن',
  'appearance.paragraphNumbers': 'شمارهٔ بندها',
  'appearance.paragraphNumbersHint': 'شماره‌های ارجاع را در حاشیه نشان می‌دهد.',
  'appearance.appTheme': 'پوستهٔ برنامه',
  'appearance.appThemeHint': 'بیرون از صفحهٔ خواندن اعمال می‌شود.',
  'appearance.reset': 'بازنشانی به پیش‌فرض',

  // ── برچسب‌های مجموعه برای ارجاع ───────────────────────────────────────────
  'citation.bible': 'کتاب مقدس',
  'citation.tanakh': 'تنخ',
  'citation.quran': 'قرآن',
  'citation.guruGranthSahib': 'گورو گرانت صاحب',
};
