import type { LocaleTable } from './keys';

/**
 * French UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key, so this file can be filled in gradually without the app
 * ever showing `settings.appLanguage` to a user.
 *
 * Terminology fixed once, here: a cross-reference is a *renvoi* (the word the
 * French scriptural apparatus already uses), a tag/compilation is a
 * *compilation* (renamed 2026-08-17 from *étiquette*, kept as the internal
 * key names' English gloss only). Both recur across a dozen screens, so they
 * are worth settling before translating.
 */
export const fr: LocaleTable = {
  'common.cancel': 'Annuler',
  'common.remove': 'Retirer',
  'common.removing': 'Retrait…',
  'common.save': 'Enregistrer',
  'common.done': 'Terminé',
  'common.ok': 'OK',
  'common.continue': 'Continuer',
  'common.tryAgain': 'Veuillez réessayer.',
  'common.delete': 'Supprimer',
  'common.clear': 'Effacer',
  'common.signInCreate': 'Se connecter / S’inscrire',
  'common.book_one': '{{count}} livre',
  'common.book_other': '{{count}} livres',
  'common.saving': 'Enregistrement…',
  'common.loading': 'Chargement…',
  'common.copy': 'Copier',
  'common.retry': 'Réessayer',
  'common.back': 'Retour',
  'common.next': 'Suivant',
  'common.searching': 'Recherche…',
  'common.noResults': 'Aucun résultat.',
  'common.dismiss': 'Ignorer',
  'common.options': 'Options',
  'common.collapseLibrary': 'Réduire la bibliothèque',
  'common.expandLibrary': 'Développer la bibliothèque',
  'common.minutesAgo': 'il y a {{count}} min',
  'common.hoursAgo': 'il y a {{count}} h',
  'common.daysAgo': 'il y a {{count}} j',
  'common.highlight_one': '{{count}} surlignage',
  'common.highlight_other': '{{count}} surlignages',
  'common.edit': 'Modifier',
  'common.justNow': 'à l’instant',
  'common.opening': 'Ouverture…',
  'common.or': 'ou',
  'common.pleaseWait': 'Veuillez patienter…',
  'common.somethingWrong': 'Une erreur s’est produite.',
  'common.rename': 'Renommer',
  'common.dragToReorder': 'Faites glisser pour réorganiser',
  'common.openInReader': 'Ouvrir dans le lecteur',
  'common.otherTradition': 'Autres',

  'nav.home': 'Accueil',
  'nav.library': 'Bibliothèque',
  'nav.tags': 'Compilations',
  'nav.notes': 'Notes',
  'nav.xrefs': 'Renvois',
  'nav.discover': 'Découvrir',
  'nav.settings': 'Réglages',
  'nav.guest': 'Invité',
  'nav.reader': 'Lecteur',
  'nav.signOut': 'Se déconnecter',

  'library.title': 'Bibliothèque',
  'library.languageSheetTitle': 'Langue de la bibliothèque',
  'library.availableToDownload': 'Disponible au téléchargement',
  'library.downloading': 'Téléchargement {{percent}} %',
  'library.verifying': 'Vérification…',
  'library.importing': 'Importation…',
  'library.cleaning': 'Finalisation…',
  'library.downloadFailed': 'Échec du téléchargement',
  'library.updateAvailable': 'Mise à jour disponible',
  'library.updateLanguageA11y': 'Mettre à jour {{language}}',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Changer la langue de la bibliothèque',

  'library.myBooks': 'Mes livres',
  'library.searchAll': 'Rechercher dans tous les livres…',
  'library.searchSelected_one': 'Rechercher dans {{count}} livre sélectionné…',
  'library.searchSelected_other': 'Rechercher dans {{count}} livres sélectionnés…',
  'library.noResultsFor': 'Aucun résultat pour « {{query}} ».',
  'library.result_one': '{{count}} résultat',
  'library.result_other': '{{count}} résultats',
  'library.relatedPassages': 'Passages liés',
  'library.relatedOn': 'dans',
  'library.relatedPrefix': 'EN LIEN',
  'library.booksAndSections': 'Livres et sections',
  'library.tapToOpenHint': 'Touchez pour ouvrir',
  'library.importTitle': 'Importer un livre (TXT, EPUB, DOCX, RTF, PDF)',
  'library.importProFeature':
    'L’import de livres est une fonction Pro. Passez à Pro dans les Réglages pour importer vos propres livres.',
  'library.importFailed': 'Échec de l’importation.',
  'library.importSucceeded': '« {{title}} » a été importé.',
  'library.noImportedBooks':
    'Aucun livre importé pour l’instant. Utilisez le bouton près de la barre de recherche pour en importer un.',
  'library.deleteBookConfirm': 'Supprimer « {{title}} » ?',
  'library.tagAction': 'Compilation',

  'settings.language': 'Langue',
  'settings.appLanguage': 'Langue de l’application',
  'settings.appLanguageHint': 'Boutons et menus. Indépendant de la bibliothèque que vous lisez.',
  'settings.restartForDirection': 'Redémarrez pour terminer le changement',
  'settings.restartForDirectionBody':
    '{{language}} s’écrit de droite à gauche. Fermez puis rouvrez Immerse pour inverser la mise en page.',
  'settings.restartForDirectionBodyLtr':
    'Fermez puis rouvrez Immerse pour revenir à une mise en page de gauche à droite.',
  'settings.downloadedLibraries': 'Bibliothèques téléchargées',
  'settings.downloadedLibrariesHint': 'Passez de l’une à l’autre depuis l’écran Bibliothèque.',
  'settings.includedWithApp': 'incluse dans l’application',
  'settings.removeLanguageTitle': 'Retirer {{language}} ?',
  'settings.removeLanguageBody':
    'Ces livres seront supprimés de cet appareil. Vous pourrez les télécharger de nouveau à tout moment.',
  'settings.removeLanguageKeepsAnnotations':
    'Vos {{annotations}} dans ces livres seront conservées et réapparaîtront si vous téléchargez de nouveau {{language}}.',
  'settings.removeFailed': 'Retrait impossible',
  'settings.account': 'Compte',
  'settings.fullName': 'Nom complet',
  'settings.edit': 'Modifier',
  'settings.username': 'Nom d’utilisateur',
  'settings.plan': 'Formule',
  'settings.fontSize': 'Taille du texte',
  'settings.fontPreview': 'Aperçu du texte en taille {{size}}. Ce réglage est synchronisé sur tous vos appareils.',
  'settings.dailyReadings': 'Notifications',
  'settings.randomVersesAndPlan': 'Versets aléatoires et plan de lecture',
  'settings.readingMorningEvening': 'Une lecture chaque matin et chaque soir',
  'settings.appearance': 'Apparence',
  'settings.appearanceLight': 'Clair',
  'settings.appearanceDark': 'Sombre',
  'settings.appearanceSystem': 'Système',
  'settings.upgrade': 'Passer à Pro',
  'settings.upgradeCta': 'PASSER À PRO — 0,99 $/MOIS',
  'settings.upgradeBlurb':
    'Débloquez les résumés IA, les voix de lecture premium et l’import de vos propres livres. 0,99 $/mois.',
  'settings.purchases': 'Achats',
  'settings.restorePurchase': 'Restaurer l’achat',
  'settings.restorePurchaseHint': 'Récupère l’accès Pro déjà payé — sur l’App Store, Google Play ou le web.',
  'settings.about': 'À propos',
  'settings.version': 'Version',
  'settings.privacyPolicy': 'Politique de confidentialité',
  'settings.viewExternal': 'Voir ↗',
  'settings.termsOfService': 'Conditions d’utilisation',
  'settings.introTour': 'Visite guidée',
  'settings.fullFeatureVideo': 'Vidéo de présentation complète',
  'settings.replayOnboarding': 'Revoir les captures de bienvenue',
  'settings.view': 'Voir',
  'settings.watchFeatureVideo': 'Regarder la vidéo de présentation',
  'settings.accountActions': 'Actions sur le compte',
  'settings.legal': 'Mentions légales',
  'settings.contactSupport': 'Contacter le support',
  'settings.communityGuidelines': 'Règles de la communauté',
  'settings.signOut': 'Se déconnecter',
  'settings.deleteAccount': 'Supprimer le compte',
  'settings.deleting': 'Suppression…',
  'settings.error': 'Erreur',
  'settings.deleteAccountConfirm':
    'Cela supprimera définitivement votre compte ainsi que toutes vos annotations, compilations, notes et votre progression de lecture. Cette action est irréversible.',
  'settings.areYouSure': 'Êtes-vous sûr ?',
  'settings.deleteAccountFinal':
    'Votre compte et toutes vos données seront supprimés immédiatement et ne pourront pas être récupérés.',
  'settings.deletePermanently': 'Oui, supprimer définitivement',
  'settings.restoreFailed': 'Échec de la restauration',
  'settings.proRestored': 'Pro restauré !',
  'settings.proRestoredBody': 'Votre abonnement est désormais actif.',
  'settings.noSubscription': 'Aucun abonnement trouvé',
  'settings.noSubscriptionBody':
    'Nous n’avons trouvé aucun abonnement actif lié à ce compte.',
  'settings.planGuest': 'Invité',
  'settings.planStandard': 'Standard',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (essai)',

  'settings.welcomeToPro': 'Bienvenue dans Pro !',
  'settings.manage': 'Gérer',
  'settings.subscribeToPro': 'S’abonner à Pro',

  'home.tags': 'Compilations',
  'home.notes': 'Notes',
  'home.xrefs': 'Renvois',
  'home.readingPlan': 'PLAN DE LECTURE',
  'home.dailyVerses': 'VERSETS DU JOUR',
  'home.dayStreak_one': 'série de {{count}} jour',
  'home.dayStreak_other': 'série de {{count}} jours',
  'home.dailyReading': 'Lecture du jour',
  'home.dailyReadingsTitle': 'Lectures quotidiennes',
  'home.tapToSetUp': 'Touchez pour configurer',
  'home.tapToReadVerse': 'Touchez pour lire un verset',
  'home.tapToContinue': 'Touchez pour continuer',
  'home.planFinished': 'Terminé — choisissez votre prochain livre',
  'home.recentlyViewed': 'Consultés récemment',
  'home.removeFromRecent': 'Retirer des consultés récemment',
  'home.removeFromRecentBody': 'Retirer « {{title}} » et remettre la progression à 0 % ?',
  'home.signInCreate': 'Se connecter / S’inscrire',
  'home.startReadingHint': 'Commencez à lire pour retrouver vos livres récents ici.',
  'home.viewLibrary': 'VOIR LA BIBLIOTHÈQUE',

  'home.signInBlurb': 'Connectez-vous pour retrouver vos livres consultés récemment, vos annotations et bien plus, sur tous vos appareils.',

  'auth.tagline': 'Liseuse et recherche interreligieuses',
  'auth.usernamePlaceholder': 'Nom d’utilisateur ID *',
  'auth.fullNamePlaceholder': 'Nom complet',
  'auth.emailPlaceholder': 'E-mail *',
  'auth.passwordPlaceholder': 'Mot de passe *',
  'auth.emailAddressPlaceholder': 'Adresse e-mail *',
  'auth.signIn': 'Se connecter',
  'auth.signUp': 'S’inscrire',
  'auth.createAccount': 'Créer un compte',
  'auth.forgotPassword': 'Mot de passe oublié ?',
  'auth.browseWithout': 'Parcourir sans compte',
  'auth.guestSubtext': 'Lisez et cherchez dans les livres — la progression et les notes ne seront pas enregistrées',
  'auth.resetPassword': 'Réinitialiser le mot de passe',
  'auth.sendResetLink': 'Envoyer le lien',
  'auth.createPasswordPlaceholder': 'Créer un mot de passe *',
  'auth.backToSignIn': 'Retour à la connexion',
  'auth.forgotBlurb':
    'Saisissez votre adresse e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
  'auth.usernameAvailable': '✓ Disponible',
  'auth.usernameTakenShort': '✗ Pris',
  'auth.usernameHint': '3 à 20 caractères',
  'auth.usernameAlreadyTaken': 'Ce nom d’utilisateur est déjà pris.',
  'auth.resetLinkSent': 'Nous avons envoyé un lien de réinitialisation à {{email}}',
  'auth.error': 'Erreur',
  'auth.missingFields': 'Champs manquants',
  'auth.missingFieldsBody': 'Veuillez saisir votre e-mail et votre mot de passe.',
  'auth.invalidUsername': 'Nom d’utilisateur invalide',
  'auth.invalidUsernameBody': 'Le nom d’utilisateur doit comporter 3 à 20 caractères : lettres, chiffres et tirets bas uniquement.',
  'auth.usernameTaken': 'Nom d’utilisateur pris',
  'auth.usernameTakenBody': 'Veuillez en choisir un autre.',
  'auth.checkUsername': 'Vérification en cours',
  'auth.checkUsernameBody': 'Veuillez attendre la fin de la vérification du nom d’utilisateur.',
  'auth.checkEmail': 'Consultez votre boîte mail',
  'auth.checkEmailBody': 'Nous avons envoyé un lien de confirmation à {{email}}',
  'auth.checkEmailSignInBody':
    'Nous avons envoyé un lien de confirmation à {{email}}. Une fois confirmé, connectez-vous pour accéder à votre compte.',
  'auth.enterEmail': 'Saisissez votre e-mail',
  'auth.enterEmailBody': 'Veuillez saisir votre adresse e-mail.',
  'auth.emailSent': 'E-mail envoyé',
  'auth.emailSentBody': 'Consultez votre boîte de réception pour le lien de réinitialisation.',

  'auth.emailConfirmed': 'E-mail confirmé',
  'auth.accountReadySignIn':
    'Votre compte est prêt. Connectez-vous avec votre e-mail et votre mot de passe pour commencer.',
  'auth.accountReadyOpenApp':
    'Votre compte est prêt. Ouvrez l’application Immerse sur votre téléphone pour vous connecter, ou continuez sur le web ci-dessous.',
  'auth.openingApp': 'Votre compte est prêt. Ouverture d’Immerse et connexion en cours…',
  'auth.openImmerse': 'Ouvrir Immerse',
  'auth.continueOnWeb': 'Continuer sur le web',
  'auth.signInToImmerse': 'Se connecter à Immerse',
  'auth.continueToImmerse': 'Continuer vers Immerse',
  'auth.chooseNewPassword': 'Choisissez un nouveau mot de passe pour votre compte',
  'auth.newPasswordPlaceholder': 'Nouveau mot de passe',
  'auth.confirmNewPasswordPlaceholder': 'Confirmer le nouveau mot de passe',
  'auth.updatePassword': 'Mettre à jour le mot de passe',
  'auth.enterConfirmPassword': 'Veuillez saisir et confirmer votre nouveau mot de passe.',
  'auth.passwordTooShort': 'Le mot de passe doit comporter au moins 8 caractères.',
  'auth.passwordsDontMatch': 'Les mots de passe ne correspondent pas.',
  'auth.passwordUpdated': 'Mot de passe mis à jour',
  'auth.passwordUpdatedBody': 'Vous pouvez désormais utiliser votre nouveau mot de passe.',
  'auth.resetFailed':
    'Impossible de mettre à jour votre mot de passe. Le lien de réinitialisation a peut-être expiré — veuillez en demander un nouveau.',

  'reminders.headerTitle': 'Lectures quotidiennes',
  'reminders.enable': 'Activer les lectures quotidiennes',
  'reminders.openSettings': 'Ouvrir les réglages',
  'reminders.source': 'Source',
  'reminders.randomVerses': 'Versets aléatoires',
  'reminders.readingPlan': 'Plan de lecture',
  'reminders.chooseBook': 'Choisir un livre',
  'reminders.bookFinished': 'Terminé ✓ — choisissez votre prochain livre',
  'reminders.sessionLength': 'Durée de la session',
  'reminders.sessionCaption': 'S’applique à chaque session — {{dur}} le matin et {{dur}} le soir.',
  'reminders.reminders': 'Rappels',
  'reminders.time': 'Heure',
  'reminders.morning': 'Matin',
  'reminders.evening': 'Soir',
  'reminders.yourStreak': 'Votre série',
  'reminders.today': 'Aujourd’hui',
  'reminders.currentStreak': 'Série en cours',
  'reminders.bestStreak': 'Meilleure série',
  'reminders.completedBooks': 'Livres terminés',
  'reminders.day_one': '{{count}} jour',
  'reminders.day_other': '{{count}} jours',
  'reminders.hour': '1 h',
  'reminders.minutes': '{{count}} min',
  'reminders.signInRequired': 'Connexion requise',
  'reminders.signInRequiredBody': 'Créez un compte pour suivre un plan de lecture et votre progression.',
  'reminders.notNow': 'Plus tard',
  'reminders.enabledSub': 'Affiche votre lecture du jour sur l’écran d’accueil.',
  'reminders.disabledSub': 'Désactivé — votre lecture du jour est masquée sur l’écran d’accueil.',
  'reminders.chooseNextToResume': 'Choisissez votre prochain livre ci-dessus pour reprendre les rappels.',
  'reminders.chooseBookToEnable': 'Choisissez un livre ci-dessus pour activer les rappels.',
  'reminders.selectSourceToEnable': 'Sélectionnez au moins une source ci-dessus pour activer les rappels.',
  'reminders.todayComplete': 'terminé ✓',
  'reminders.todayPending': 'en attente',
  'reminders.todayMorningDone': 'matin ✓',
  'reminders.todayMorningPending': 'matin en attente',
  'reminders.todayEveningDone': 'soir ✓',
  'reminders.todayEveningPending': 'soir en attente',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Lisez plus en profondeur. Reliez davantage.',
  'paywall.featureAiLabel': 'Résumés IA des passages',
  'paywall.featureAiDesc': 'Demandez des explications et des commentaires sur n’importe quel passage',
  'paywall.featureVoicesLabel': 'Voix de lecture premium',
  'paywall.featureVoicesDesc': 'Une narration naturelle et expressive, dans la voix de votre choix',
  'paywall.featureImportLabel': 'Importez vos propres livres',
  'paywall.featureImportDesc': 'Ajoutez des fichiers EPUB, PDF et DOCX à votre bibliothèque',
  'paywall.subscribe': 'S’abonner — {{price}}/mois',
  'paywall.cancelNote': 'Annulable à tout moment · Facturation mensuelle',
  'paywall.restore': 'Restaurer les achats',
  'paywall.terms': 'Conditions d’utilisation',
  'paywall.privacy': 'Politique de confidentialité',
  'paywall.notAvailable': 'Indisponible',
  'paywall.notAvailableBody': 'Les achats intégrés ne sont pas encore configurés dans cette version. Revenez après la publication sur l’App Store.',
  'paywall.welcome': 'Bienvenue dans Pro !',
  'paywall.welcomeBody': 'Votre abonnement est désormais actif.',
  'paywall.purchaseFailed': 'Échec de l’achat',
  'paywall.restoreFailed': 'Échec de la restauration',

  'xrefs.title': 'Renvois',
  'xrefs.empty': 'Aucun renvoi pour l’instant. Les renvois que vous créez dans le lecteur apparaîtront ici.',
  'xrefs.signInTitle': 'Connectez-vous pour voir vos renvois',
  'xrefs.signInBody': 'Reliez des passages venus de toute la bibliothèque.',
  'xrefs.searchSelected': 'Rechercher dans les renvois sélectionnés...',
  'xrefs.searchPlaceholder': 'Rechercher des passages ou des libellés...',
  'xrefs.noMatch': 'Aucun renvoi ne correspond à votre recherche.',
  'xrefs.addLabel': 'Ajouter un libellé…',
  'xrefs.deleteConfirm': 'Supprimer le renvoi ?',
  'xrefs.deleteBody': 'Les deux sélections surlignées seront conservées.',

  'notes.title': 'Notes',
  'notes.empty': 'Aucune note pour l’instant. Les notes que vous créez dans le lecteur apparaîtront ici.',
  'notes.signInTitle': 'Connectez-vous pour voir vos notes',
  'notes.signInBody': 'Ajoutez commentaires et réflexions aux passages au fil de votre lecture.',
  'notes.searchPlaceholder': 'Rechercher dans les notes...',
  'notes.searchSelected': 'Rechercher dans les notes sélectionnées...',
  'notes.byBook': 'Par livre',
  'notes.byDate': 'Par date',
  'notes.writeNote': 'Écrivez votre note…',
  'notes.noMatch': 'Aucune note ne correspond à votre recherche.',
  'notes.deleteConfirm': 'Supprimer la note ?',
  'notes.deleteBody': 'La sélection surlignée sera conservée.',

  'tags.title': 'Compilations',
  'tags.empty': 'Aucune compilation pour l’instant. Les compilations que vous créez dans le lecteur apparaîtront ici.',
  'tags.signInTitle': 'Connectez-vous pour voir vos compilations',
  'tags.signInBody': 'Créez et organisez des recueils de citations puisés dans toute la bibliothèque.',
  'tags.organize': 'Organiser',
  'tags.searchPlaceholder': 'Rechercher des compilations...',
  'tags.searchSelected': 'Rechercher dans les compilations sélectionnées...',
  'tags.noMatch': 'Aucune compilation ne correspond à votre recherche.',
  'tags.deleteConfirm': 'Supprimer la compilation ?',
  'tags.deleteBody': '« {{name}} » et toutes ses sélections seront supprimées.',

  'tags.renameTitle': 'Renommer la compilation',
  'tags.setPrivate': 'Rendre privée',
  'tags.setPublic': 'Rendre publique',
  'tags.publicTag': 'Compilation publique',
  'tags.removePassage': 'Retirer de la compilation',
  'tags.removePassageConfirm': 'Retirer ce passage de la compilation ?',
  'tags.indent': 'Indenter',
  'tags.outdent': 'Désindenter',
  'tags.organizeHint':
    'Faites glisser la poignée pour réorganiser \u00b7 \u21e4 \u21e5 pour changer le niveau \u00b7 cliquez sur une compilation pour réordonner ses citations.',
  'tags.searchTagsPassages': 'Rechercher compilations et passages…',
  'tags.exportSelected': 'Exporter les compilations sélectionnées',
  'xrefs.exportSelected': 'Exporter les renvois sélectionnés',
  'tags.export': 'Exporter',
  'tags.exporting': 'Exportation…',
  'tags.exportInclude': 'Inclure',
  'tags.exportNothingToInclude': 'Aucune des compilations sélectionnées n’a de {{items}}',

  'panel.createAccount': 'Créer un compte',
  'panel.signInToSave': 'Créez un compte gratuit pour enregistrer compilations, notes et renvois.',
  'panel.editSelection': 'Modifier la sélection de texte',

  'reader.xrefMode': 'Mode renvoi — appui long pour choisir un passage',
  'reader.error': 'Erreur du lecteur',
  'reader.opening': 'Ouverture du livre…',
  'reader.footnote': 'Note de bas de page',

  'reader.selectBook': 'Sélectionnez un livre pour commencer à lire',
  'reader.tableOfContents': 'Table des matières',
  'reader.tocButtonHint': 'Aller à une section de ce livre',
  'reader.expandSection': 'Développer la section',
  'reader.collapseSection': 'Réduire la section',
  'reader.expand': 'Développer',
  'reader.collapse': 'Réduire',
  'reader.actionTag': 'Compilation',
  'reader.actionNote': 'Note',
  'reader.actionXref': 'Renvoi',
  'reader.actionAi': 'IA',
  'reader.actionCopy': 'Copier',
  'reader.updateSelection': 'Mettre à jour la sélection',
  'reader.updating': 'Mise à jour…',
  'reader.pickAsXref': 'Choisir comme renvoi',
  'reader.editSelectionHint':
    'Surlignez le nouveau texte de cette annotation, puis choisissez',
  'reader.savingXref': 'Enregistrement du renvoi…',
  'reader.pickTargetHint': 'Sélectionnez du texte ou cliquez sur un passage à relier',
  'reader.footnoteUnavailable': 'Le texte de la note n’est pas disponible dans la version web.',
  'reader.bookNotFound': 'Livre introuvable',
  'reader.viewTags': 'Voir les compilations',
  'reader.viewNote': 'Voir la note',
  'reader.viewXrefs': 'Voir les renvois',
  'reader.noQuotesFiled': 'Aucune citation classée ici.',

  'ai.summary': 'Résumé IA',
  'ai.upgradeBlurb': 'Passez à Immerse Pro pour seulement 0,99 $ afin d’utiliser les résumés IA et les autres fonctions Pro.',
  'ai.upgradeBtn': 'Passer à Pro — 0,99 $/mois',
  'ai.thinking': 'Réflexion…',
  'ai.error': 'Impossible d’obtenir le résumé IA. Vérifiez votre connexion et réessayez.',
  'ai.copied': '✓ Copié',
  'ai.copyHint': 'Appui long pour copier',

  'note.title': 'Note',
  'note.addTitle': 'Ajouter une note',
  'note.placeholder': 'Écrivez votre note ici…',
  'note.loading': 'Chargement…',
  'note.emptyTitle': 'Note vide',
  'note.emptyBody': 'Veuillez écrire quelque chose avant d’enregistrer.',
  'note.saveFailed': 'Impossible d’enregistrer la note',
  'note.deleteTitle': 'Supprimer la note ?',
  'note.deleteBody': 'La note sera supprimée. Si aucune autre annotation ne porte sur ce passage, la sélection sera également retirée.',
  'note.deleteFailed': 'Impossible de supprimer la note',
  'note.signInRequired': 'Connexion requise',
  'note.signInBody': 'Les notes sont enregistrées dans votre compte. Connectez-vous ou créez un compte.',

  'xref.title': 'Renvoi',
  'xref.yourSelection': 'VOTRE SÉLECTION',
  'xref.pickSecond': 'Choisir le second passage  →',
  'xref.noneFound': 'Aucun renvoi trouvé.',

  'xref.findPassage': 'Trouver un passage à relier',
  'xref.searchPlaceholder': 'Rechercher un passage…',
  'xref.save': 'Enregistrer le renvoi',
  'xref.from': 'De',
  'xref.to': 'À',
  'xref.linksTo': 'renvoie à',

  'xref.suggestMatch': 'Suggérer une correspondance',
  'xref.suggesting': 'Recherche de passages liés…',
  'xref.suggestError': 'Impossible d’obtenir des suggestions pour le moment',
  'xref.noMatches': 'Aucune correspondance trouvée. Choisissez-en un vous-même.',
  'xref.looseMatch': 'correspondance approximative',
  'xref.useThisPassage': 'Utiliser ce passage',
  'xref.inCompilation': 'Dans votre compilation « {{name}} »',
  'xref.youNotedThis': 'Vous avez annoté ce passage',

  'banner.googlePlay': 'Disponible sur Google Play',
  'banner.appStore': 'Télécharger dans l’App Store',
  'banner.install': 'Installer',
  'banner.get': 'Obtenir',

  'tagPanel.new': 'Nouvelle compilation',
  'tagPanel.createWithin': 'Créer une compilation dans « {{parent}} »',
  'tagPanel.addTitle': 'Ajouter à une compilation',
  'tagPanel.viewTitle': 'Compilations',
  'tagPanel.addSubTag': 'Ajouter une sous-compilation',
  'tagPanel.emptyAdd': 'Aucune compilation — créez-en une ci-dessus',
  'tagPanel.emptyView': 'Aucune compilation sur cette sélection',

  'voice.title': 'Voix de lecture',
  'voice.onyx': 'Onyx — grave et chaleureuse',
  'voice.cedar': 'Cedar — naturelle et riche',
  'voice.ash': 'Ash — claire et directe',
  'voice.nova': 'Nova — lumineuse',
  'voice.shimmer': 'Shimmer — douce',
  'voice.marin': 'Marin — naturelle et posée',

  'reader.signInRequired': 'Connexion requise',
  'reader.signInBody': 'Créez un compte pour enregistrer compilations, notes et renvois au fil de votre lecture.',
  'reader.notNow': 'Plus tard',
  'reader.signIn': 'Se connecter',
  'reader.pdfNotFound': 'Impossible de localiser le fichier PDF.',
  'reader.contentLoadFailed': 'Le contenu n’a pas pu être chargé',
  'reader.noBook': 'Aucun livre indiqué',
  'reader.storageError': 'Erreur de stockage',

  'discover.recent': 'RÉCENTS',
  'discover.trending': 'TENDANCES',
  'discover.searchPlaceholder': 'Rechercher compilations et utilisateurs…',
  'discover.searchSelected': 'Rechercher dans les compilations sélectionnées…',
  'discover.import': 'Importer',
  'discover.imported': 'Importée',
  'discover.import_one': '{{count}} import',
  'discover.import_other': '{{count}} imports',
  'discover.noneYet': 'Aucune compilation partagée pour l’instant',
  'discover.noResults': 'Aucun résultat',
  'discover.tryDifferent': 'Essayez un autre terme de recherche.',
  'discover.signInTitle': 'Connectez-vous pour accéder à Découvrir',
  'discover.signInBody': 'Voyez ce que d’autres lecteurs découvrent dans toutes les traditions.',
  'discover.anonymous': 'Anonyme',
  'discover.beFirst': 'Soyez le premier à partager une compilation.',
  'discover.ownTag': 'C’est votre propre compilation',
  'discover.alreadyImported': 'Déjà importée',
  'discover.importFailed': 'Échec de l’importation',
  'discover.exportFailed': 'Échec de l’exportation',
  'discover.unknownError': 'Erreur inconnue',

  'usertags.autoImports': 'Importe automatiquement les compilations publiques de cet utilisateur dans votre app',
  'usertags.noTags': 'Aucune compilation publique',
  'usertags.noTagsBody': 'Cet utilisateur n’a encore partagé aucune compilation.',
  'usertags.follow': 'Suivre',
  'usertags.unfollow': 'Ne plus suivre',
  'usertags.share': 'Partager',
  'usertags.error': 'Erreur',
  'usertags.somethingWrong': 'Une erreur s’est produite',

  'onboarding.chooseLanguage': 'Choisissez votre langue',
  'onboarding.changeLaterSettings': 'Vous pourrez changer cela plus tard dans les Réglages.',
  'onboarding.libraryDownloadHint': 'Pour télécharger la bibliothèque en {{language}}, touchez le ⌄ à côté de « Bibliothèque » sur l’écran Bibliothèque.',
  'onboarding.continue': 'Continuer',
  'onboarding.chooseTextSize': 'Choisissez la taille du texte',
  'onboarding.fontPreviewQuote':
    '« Cherchez et vous trouverez ; frappez et l’on vous ouvrira. »',
  'onboarding.getStarted': 'Commencer',

  'onboarding.closeIntro': 'Fermer l’introduction',
  'onboarding.goToStep': 'Aller à l’étape {{number}}',
  'onboarding.libraryTitle': 'La bibliothèque',
  'onboarding.libraryCaption': 'Parcourez une bibliothèque multi-traditions soigneusement composée. Touchez un livre pour commencer à lire.',
  'onboarding.searchTitle': 'Cherchez partout',
  'onboarding.searchCaption': 'Cherchez dans tous les livres à la fois et allez droit au passage.',
  'onboarding.tagAsYouGoTitle': 'Compilez au fil de la lecture',
  'onboarding.tagAsYouGoCaption': 'Ajoutez un passage à une compilation directement depuis les résultats de recherche.',
  'onboarding.buildTagsTitle': 'Construisez vos compilations',
  'onboarding.buildTagsCaption': 'Regroupez des passages sous vos propres compilations pour les retrouver facilement.',
  'onboarding.selectActTitle': 'Sélectionnez et agissez',
  'onboarding.selectActCaption': 'Sélectionnez n’importe quel texte pour le surligner, le compiler, l’annoter ou le relier.',
  'onboarding.marginTitle': 'Annotations en marge',
  'onboarding.marginCaption': 'Vos compilations, notes et renvois vivent dans la marge.',
  'onboarding.navigateTitle': 'Naviguez rapidement',
  'onboarding.navigateCaption': 'Ouvrez la table des matières pour vous déplacer dans un livre.',
  'onboarding.yourTagsTitle': 'Vos compilations',
  'onboarding.yourTagsCaption': 'Retrouvez chaque passage compilé, classé par compilation.',
  'onboarding.xrefsTitle': 'Renvois',
  'onboarding.xrefsCaption': 'Reliez des passages entre livres et traditions.',
  'onboarding.shareTitle': 'Partagez et publiez',
  'onboarding.shareCaption': 'Partagez une citation ou publiez une compilation pour la communauté.',

  // ── Liens de partage (Phase 5) ───────────────────────────────────────────
  'share.createLink': 'Créer un lien de partage',
  'share.createLinkHint': 'Une page web privée. Non affichée dans Découvrir.',
  'share.linkReady': 'Lien prêt',
  'share.linkCopied': 'Lien copié',
  'share.copyLink': 'Copier le lien',
  'share.shareVia': 'Partager…',
  'share.revoke': 'Révoquer',
  'share.revokeConfirm': 'Révoquer ce lien ? Toute personne qui le possède perdra l’accès.',
  'share.discoverToggle': 'Publier dans Découvrir',
  'share.discoverToggleHint': 'N’importe qui peut trouver et enregistrer cette compilation.',
  'share.stopDiscover': 'Retirer de Découvrir',
  'share.publishedNote': 'Publiée dans Découvrir — désactivez l’option pour arrêter le partage.',
  'share.selectOne': 'Sélectionnez une compilation pour créer un lien.',
  'sharePage.eyebrow': 'Compilation partagée',
  'sharePage.openInReader': 'Ouvrir dans le lecteur',
  'sharePage.save': 'Enregistrer dans mes compilations',
  'sharePage.saving': 'Enregistrement…',
  'sharePage.saved': 'Enregistrée dans vos compilations',
  'sharePage.saveHint': 'Ouvre l’application Immerse, ou connectez-vous pour enregistrer sur le web.',
  'sharePage.signInToSave': 'Connectez-vous pour l’enregistrer dans vos compilations.',
  'sharePage.footer': 'Lire plus dans Immerse',

  // ── Feuille d’export ──────────────────────────────────────────────────────
  'export.shareTags_one': 'Partager {{count}} compilation',
  'export.shareTags_other': 'Partager {{count}} compilations',
  'export.shareTagsGeneric': 'Partager les compilations',
  'export.shareXrefs_one': 'Partager {{count}} renvoi',
  'export.shareXrefs_other': 'Partager {{count}} renvois',
  'export.preparing': 'Préparation…',
  'export.notesOn': 'Vos notes écrites sur chaque passage',
  'export.notesNone': 'Aucune note sur ces passages',
  'export.xrefsOn': 'Passages reliés sous chaque citation',
  'export.xrefsNone': 'Aucun renvoi sur ces passages',
  'export.docxTitle': 'Document Word (.docx)',
  'export.docxShort': 'Word (.docx)',
  'export.docxDesc': 'Titres de compilation avec les passages cités. S’ouvre dans Word, Pages ou Google Docs.',
  'export.pdfTitle': 'Document PDF',
  'export.pdfDesc': 'Document mis en forme pour l’impression ou le partage.',
  'export.csvTitle': 'Tableur (.csv)',
  'export.csvDesc': 'Une ligne par passage. S’ouvre dans Excel, Numbers ou Google Sheets.',
  'export.mdTitle': 'Markdown (.md)',
  'export.mdDesc': 'Pour Obsidian, Notion ou tout outil en texte brut.',
  'export.noPassagesTagged': '(aucun passage dans cette compilation)',
  'export.seeAlso': 'Voir aussi :',

  // ── Plan de lecture ───────────────────────────────────────────────────────
  'plan.chooseBook': 'Choisir un livre',
  'plan.searchBooks': 'Rechercher des livres…',
  'plan.noBooksMatch': 'Aucun livre ne correspond à « {{query}} ».',
  'plan.readingComplete': 'Lecture terminée',
  'plan.morningSession': 'Session du matin',
  'plan.eveningSession': 'Session du soir',
  'plan.minutes': '{{count}} min',
  'plan.streakDay': 'Jour {{count}} de la série ✓',
  'plan.sessionsToday': '{{done}} session(s) sur {{required}} aujourd’hui',
  'plan.youFinished': 'Vous avez terminé {{title}}',
  'plan.readOverDays_one': 'Lu en {{count}} jour',
  'plan.readOverDays_other': 'Lu en {{count}} jours',
  'plan.remindersPaused': 'les rappels sont en pause',
  'plan.chooseNextBook': 'Choisissez votre prochain livre',
  'completed.title': 'Livres terminés',
  'completed.empty': 'Les livres que vous terminez dans votre plan de lecture apparaîtront ici.',
  'completed.finishedOn': 'Terminé le {{date}}',
  'completed.day_one': '{{count}} jour',
  'completed.day_other': '{{count}} jours',

  // ── Reliquats de la bibliothèque ──────────────────────────────────────────
  'library.selectPassageForXref': 'Sélectionner un passage pour le renvoi',
  'library.findingRelated': 'Recherche de passages liés…',
  'library.aiSearchOffline': 'Une connexion Internet est requise pour la recherche par question',
  'library.importFailedTitle': 'Échec de l’importation',
  'library.couldNotImport': 'Impossible d’importer le fichier.',
  'library.bookAdded': 'Livre ajouté',
  'library.bookAddedBody': '« {{title}} » est maintenant dans Mes livres.',
  'library.importErrorTitle': 'Erreur d’importation',
  'library.unexpectedError': 'Une erreur inattendue s’est produite.',
  'nav.browsingAsGuest': 'Navigation en tant qu’invité',
  'reader.selectBookToBegin': 'Sélectionnez un livre pour commencer à lire',
  'tags.exportFailed': 'Échec de l’exportation',
  'tags.couldNotExport': 'Impossible d’exporter les compilations.',
  'tags.couldNotRemoveSelection': 'Impossible de retirer la sélection',
  'tags.reorderHint': 'Faites glisser la poignée pour réorganiser · ⇤ ⇥ pour changer le niveau · touchez une compilation pour réordonner ses citations.',
  'tags.swipeHint': 'Faites glisser une compilation vers la droite pour la rendre publique ou privée.',
  'discover.publishHint': 'Faites glisser une compilation vers la droite dans votre écran Compilations pour la publier ici.',
  'reminders.notificationsOff':
    'Les notifications sont désactivées pour Immerse, les rappels ne peuvent donc pas être délivrés. '
    + 'Activez-les dans les réglages de votre appareil.',
  'plan.continueJourney': 'Poursuivez votre chemin de lecture',
  'plan.yourBook': 'Votre livre',
  'reader.notesInParagraph_one': '{{count}} note dans ce paragraphe',
  'reader.notesInParagraph_other': '{{count}} notes dans ce paragraphe',
  'plan.awaitsMorning': '{{book}} vous attend — lecture du matin',
  'plan.awaitsEvening': '{{book}} vous attend — lecture du soir',
  'reminders.dailyReadingFrom': 'Lecture du jour · {{source}}',
  'library.tapToExpandHint': 'Touchez pour développer · Maintenez pour ouvrir dans le lecteur',
  'library.deleteBookImportedBody': 'Ce livre et toutes ses annotations seront supprimés définitivement.',
  'library.deleteBookBundledBody':
    'Ce livre et toutes ses annotations seront supprimés. Il reviendra lors de la prochaine actualisation de la bibliothèque.',
  'library.deleteCategoryConfirm': 'Supprimer « {{name}} » ?',
  'library.deleteCategoryBody_one': 'Cela retirera aussi {{count}} livre et toutes ses annotations.',
  'library.deleteCategoryBody_other': 'Cela retirera aussi {{count}} livres et toutes leurs annotations.',
  'library.deleteCategoryEmptyBody': 'Cette catégorie sera supprimée définitivement.',

  'auth.passwordTooShortTitle': 'Mot de passe trop court',
  'auth.passwordsMustMatch': 'Assurez-vous que les deux mots de passe sont identiques.',
  'auth.usernamePlain': 'Nom d’utilisateur ID',
  'auth.fullNameOptional': 'Nom complet (facultatif)',
  'auth.emailPlain': 'E-mail',
  'auth.passwordPlain': 'Mot de passe',
  'auth.emailAddressPlain': 'Adresse e-mail',

  // ── Visite guidée (mobile) ────────────────────────────────────────────────
  'onboarding.skip': 'Passer',
  'onboarding.tour.libraryMain.label': 'Écran Bibliothèque',
  'onboarding.tour.libraryMain.caption':
    'La Bibliothèque réunit plus de 400 textes sacrés de toutes les grandes traditions. Touchez une tradition pour explorer ses livres.',
  'onboarding.tour.libraryExpanded.label': 'Bibliothèque développée',
  'onboarding.tour.libraryExpanded.caption':
    'Chaque tradition se développe pour montrer auteurs et collections. Touchez un titre pour l’ouvrir dans le lecteur.',
  'onboarding.tour.librarySearch.label': 'Recherche dans la bibliothèque',
  'onboarding.tour.librarySearch.caption':
    'Cherchez dans les 400 textes et plus à la fois. Touchez un résultat pour le développer, ou faites un appui long pour l’ouvrir directement dans le lecteur.',
  'onboarding.tour.searchQuickTag.label': 'Compilation rapide des résultats',
  'onboarding.tour.searchQuickTag.caption':
    'Sélectionnez un ou plusieurs résultats de recherche et attribuez-les à une compilation d’un seul geste. Un moyen rapide de bâtir une collection thématique à partir de toute la bibliothèque.',
  'onboarding.tour.home.label': 'Écran d’accueil',
  'onboarding.tour.home.caption':
    'Votre écran d’accueil indique combien de compilations, de notes et de renvois vous avez créés, ainsi que vos livres lus récemment. Touchez un titre pour poursuivre votre lecture.',
  'onboarding.tour.homePlan.label': 'Plan de lecture sur l’accueil',
  'onboarding.tour.homePlan.caption':
    'Prenez l’habitude de lire chaque jour : suivez un plan de lecture dans le livre de votre choix et pour la durée de votre choix, ou recevez des versets aléatoires tirés des traditions que vous sélectionnez, avec des rappels quotidiens et une série qui s’allonge chaque jour où vous lisez.',
  'onboarding.tour.settingsDaily.label': 'Réglages des lectures quotidiennes',
  'onboarding.tour.settingsDaily.caption':
    'Dans les Réglages, configurez les versets aléatoires en choisissant les traditions où puiser et les heures auxquelles vous souhaitez un rappel discret, ou passez à un plan de lecture pour avancer chaque jour dans un livre.',
  'onboarding.tour.readerSelect.label': 'Sélection de texte dans le lecteur',
  'onboarding.tour.readerSelect.caption':
    'Appuyez longuement sur un passage pour le sélectionner. Utilisez les icônes en bas de l’écran pour l’ajouter à une compilation, une note, un renvoi ou obtenir un résumé IA.',
  'onboarding.tour.readerNote.label': 'Note dans le lecteur',
  'onboarding.tour.readerNote.caption':
    'Les notes s’attachent au texte exact que vous avez sélectionné. Le repère doré dans la marge vous permet de les retrouver et de les rouvrir à tout moment.',
  'onboarding.tour.readerXref.label': 'Renvoi dans le lecteur',
  'onboarding.tour.readerXref.caption':
    'Les renvois relient des passages de livres et de traditions différents. Appuyez longuement sur une citation reliée pour y accéder dans le lecteur.',
  'onboarding.tour.readerAi.label': 'Résumé IA dans le lecteur',
  'onboarding.tour.readerAi.caption':
    'Après avoir sélectionné un passage, touchez l’icône d’étincelles pour un résumé IA instantané, particulièrement utile pour les textes denses ou peu familiers.',
  'onboarding.tour.readerListen.label': 'Mode écoute du lecteur',
  'onboarding.tour.readerListen.caption':
    'Touchez le bouton casque pour écouter n’importe quel livre à voix haute : le lecteur surligne chaque passage au fil de la lecture. Maintenez le bouton casque pour choisir parmi une sélection de voix naturelles.',
  'onboarding.tour.tags.label': 'Écran Compilations',
  'onboarding.tour.tags.caption':
    'L’écran Compilations regroupe par thème les passages que vous avez compilés. Touchez le nom d’une compilation pour voir ses passages cités avec leurs références complètes.',
  'onboarding.tour.xrefs.label': 'Écran Renvois',
  'onboarding.tour.xrefs.caption':
    'L’écran Renvois montre tous vos passages reliés côte à côte. Appuyez longuement sur l’un des deux côtés pour accéder à ce passage dans le lecteur.',
  'onboarding.tour.discover.label': 'Écran Découvrir',
  'onboarding.tour.discover.caption':
    'Dans l’écran Découvrir, trouvez des compilations partagées par d’autres lecteurs. Touchez une compilation pour prévisualiser ses passages, puis importez-la dans votre propre bibliothèque.',
  'onboarding.tour.tagShare.label': 'Panneau de partage de compilation',
  'onboarding.tour.tagShare.caption':
    'Exportez n’importe quelle compilation en document Word, PDF, tableur, Markdown et plus encore, avec vos notes et vos renvois inclus.',

  // ── Appearance (reader typography) ───────────────────────────────────────
  'appearance.title': 'Apparence',
  'appearance.navHint': 'Police, espacement, couleur',
  'appearance.reading': 'Lecture',
  'appearance.preview': 'Aperçu',
  'appearance.previewText': 'La lecture est une conversation paisible qui traverse les siècles.',
  'appearance.typeface': 'Police',
  'appearance.typefaceSystem': 'Système',
  'appearance.typefaceLiterataBlurb': 'Conçue pour la lecture prolongée. S’adapte à la taille.',
  'appearance.typefaceCharisBlurb': 'Descendante de Charter. Solide en petit corps.',
  'appearance.typefaceGaramondBlurb': 'Classique de style ancien. Plus légère sur la page.',
  'appearance.typefaceSystemBlurb': 'Celle fournie par cet appareil.',
  'appearance.textSize': 'Taille du texte',
  'appearance.lineSpacing': 'Interligne',
  'appearance.lineSpacingTight': 'Serré',
  'appearance.lineSpacingNormal': 'Normal',
  'appearance.lineSpacingRelaxed': 'Aéré',
  'appearance.lineSpacingLoose': 'Très aéré',
  'appearance.margins': 'Marges',
  'appearance.marginsNarrow': 'Étroites',
  'appearance.marginsNormal': 'Normales',
  'appearance.marginsWide': 'Larges',
  'appearance.justify': 'Justifier le texte',
  'appearance.justifyHint': 'Aligne les deux bords, avec césure.',
  'appearance.paragraphStyle': 'Paragraphes',
  'appearance.paragraphSpaced': 'Espacés',
  'appearance.paragraphIndented': 'Alinéas',
  'appearance.paragraphHint': 'Les alinéas correspondent à la mise en page traditionnelle.',
  'appearance.theme': 'Couleur de page',
  'appearance.themeLight': 'Clair',
  'appearance.themeSepia': 'Sépia',
  'appearance.themeQuiet': 'Doux',
  'appearance.themeDark': 'Sombre',
  'appearance.themeNight': 'Nuit',
  'appearance.themeSystem': 'Comme l’app',
  'appearance.fineTuning': 'Réglage fin',
  'appearance.characterSpacing': 'Espacement des caractères',
  'appearance.wordSpacing': 'Espacement des mots',
  'appearance.textWeight': 'Graisse du texte',
  'appearance.paragraphNumbers': 'Numéros de paragraphe',
  'appearance.paragraphNumbersHint': 'Affiche les numéros de référence dans la marge.',
  'appearance.appTheme': 'Thème de l’app',
  'appearance.appThemeHint': 'S’applique en dehors du lecteur.',
  'appearance.reset': 'Rétablir les valeurs par défaut',

  // ── Libellés de collection pour les citations ─────────────────────────────
  'citation.bible': 'La Bible',
  'citation.tanakh': 'Tanakh',
  'citation.quran': 'Le Coran',
  'citation.guruGranthSahib': 'Guru Granth Sahib',
};
