import type { LocaleTable } from './keys';

/**
 * Russian UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key.
 *
 * Every plural group carries four forms, not two. Russian counts 1 книга,
 * 3 книги, 5 книг — `_one`, `_few`, `_many` — and `_other` covers the
 * fractional counts CLDR sends there, so it is written out rather than left to
 * fall through to English mid-sentence.
 *
 * Terminology fixed once, here: a tag/compilation is a *подборка* (renamed
 * 2026-08-17 from *метка*), a note a *заметка*, and a cross-reference a
 * *перекрёстная ссылка*, shortened to «Ссылки» only where the navigation has
 * no room for the full term.
 */
export const ru: LocaleTable = {
  'common.cancel': 'Отмена',
  'common.remove': 'Убрать',
  'common.removing': 'Удаление…',
  'common.save': 'Сохранить',
  'common.done': 'Готово',
  'common.ok': 'OK',
  'common.continue': 'Продолжить',
  'common.tryAgain': 'Пожалуйста, попробуйте ещё раз.',
  'common.delete': 'Удалить',
  'common.clear': 'Очистить',
  'common.signInCreate': 'Войти / Зарегистрироваться',
  'common.book_one': '{{count}} книга',
  'common.book_few': '{{count}} книги',
  'common.book_many': '{{count}} книг',
  'common.book_other': '{{count}} книги',
  'common.saving': 'Сохранение…',
  'common.loading': 'Загрузка…',
  'common.copy': 'Копировать',
  'common.retry': 'Попробовать ещё раз',
  'common.back': 'Назад',
  'common.next': 'Далее',
  'common.searching': 'Поиск…',
  'common.noResults': 'Ничего не найдено.',
  'common.dismiss': 'Закрыть',
  'common.options': 'Действия',
  'common.collapseLibrary': 'Свернуть библиотеку',
  'common.expandLibrary': 'Развернуть библиотеку',
  'common.minutesAgo': '{{count}} мин назад',
  'common.hoursAgo': '{{count}} ч назад',
  'common.daysAgo': '{{count}} дн назад',
  'common.highlight_one': '{{count}} выделение',
  'common.highlight_few': '{{count}} выделения',
  'common.highlight_many': '{{count}} выделений',
  'common.highlight_other': '{{count}} выделения',
  'common.edit': 'Изменить',
  'common.justNow': 'только что',
  'common.opening': 'Открытие…',
  'common.or': 'или',
  'common.pleaseWait': 'Подождите…',
  'common.somethingWrong': 'Что-то пошло не так.',
  'common.rename': 'Переименовать',
  'common.dragToReorder': 'Перетащите, чтобы изменить порядок',
  'common.openInReader': 'Открыть в читалке',
  'common.otherTradition': 'Другое',

  'nav.home': 'Главная',
  'nav.library': 'Библиотека',
  'nav.tags': 'Подборки',
  'nav.notes': 'Заметки',
  'nav.xrefs': 'Ссылки',
  'nav.discover': 'Обзор',
  'nav.settings': 'Настройки',
  'nav.guest': 'Гость',
  'nav.reader': 'Чтение',
  'nav.signOut': 'Выйти',

  'library.title': 'Библиотека',
  'library.languageSheetTitle': 'Язык библиотеки',
  'library.availableToDownload': 'Доступно для загрузки',
  'library.downloading': 'Загрузка {{percent}} %',
  'library.verifying': 'Проверка…',
  'library.importing': 'Импорт…',
  'library.cleaning': 'Завершение…',
  'library.downloadFailed': 'Не удалось загрузить',
  'library.updateAvailable': 'Доступно обновление',
  'library.updateLanguageA11y': 'Обновить {{language}}',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Изменить язык библиотеки',

  'library.myBooks': 'Мои книги',
  'library.searchAll': 'Поиск по всем книгам…',
  'library.searchSelected_one': 'Поиск по {{count}} выбранной книге…',
  'library.searchSelected_few': 'Поиск по {{count}} выбранным книгам…',
  'library.searchSelected_many': 'Поиск по {{count}} выбранным книгам…',
  'library.searchSelected_other': 'Поиск по {{count}} выбранным книгам…',
  'library.noResultsFor': 'По запросу «{{query}}» ничего не найдено.',
  'library.result_one': '{{count}} результат',
  'library.result_few': '{{count}} результата',
  'library.result_many': '{{count}} результатов',
  'library.result_other': '{{count}} результата',
  'library.relatedPassages': 'Похожие отрывки',
  'library.relatedOn': 'в',
  'library.relatedPrefix': 'ПОХОЖЕЕ',
  'library.booksAndSections': 'Книги и разделы',
  'library.tapToOpenHint': 'Нажмите, чтобы открыть',
  'library.importTitle': 'Импортировать книгу (TXT, EPUB, DOCX, RTF, PDF)',
  'library.importProFeature':
    'Импорт книг доступен в Pro. Оформите Pro в настройках, чтобы добавлять свои книги.',
  'library.importFailed': 'Не удалось импортировать.',
  'library.importSucceeded': 'Книга «{{title}}» импортирована.',
  'library.noImportedBooks':
    'Импортированных книг пока нет. Нажмите кнопку рядом со строкой поиска, чтобы добавить книгу.',
  'library.deleteBookConfirm': 'Удалить «{{title}}»?',
  'library.tagAction': 'Подборка',

  'settings.language': 'Язык',
  'settings.appLanguage': 'Язык приложения',
  'settings.appLanguageHint': 'Кнопки и меню. Не связано с тем, какую библиотеку вы читаете.',
  'settings.restartForDirection': 'Перезапустите, чтобы завершить смену языка',
  'settings.restartForDirectionBody':
    '{{language}} пишется справа налево. Закройте и снова откройте Immerse, чтобы отразить интерфейс.',
  'settings.restartForDirectionBodyLtr':
    'Закройте и снова откройте Immerse, чтобы вернуть направление слева направо.',
  'settings.downloadedLibraries': 'Загруженные библиотеки',
  'settings.downloadedLibrariesHint': 'Переключайтесь между ними на экране «Библиотека».',
  'settings.includedWithApp': 'входит в приложение',
  'settings.removeLanguageTitle': 'Удалить {{language}}?',
  'settings.removeLanguageBody':
    'Эти книги будут удалены с устройства. Вы сможете загрузить их снова в любой момент.',
  'settings.removeLanguageKeepsAnnotations':
    'Ваши {{annotations}} в этих книгах сохранятся и появятся снова, если вы опять загрузите {{language}}.',
  'settings.removeFailed': 'Не удалось удалить',
  'settings.account': 'Аккаунт',
  'settings.fullName': 'Полное имя',
  'settings.edit': 'Изменить',
  'settings.username': 'Имя пользователя',
  'settings.plan': 'Тариф',
  'settings.fontSize': 'Размер текста',
  'settings.fontPreview': 'Пример текста размера {{size}}. Эта настройка синхронизируется на всех ваших устройствах.',
  'settings.dailyReadings': 'Уведомления',
  'settings.randomVersesAndPlan': 'Случайные стихи и план чтения',
  'settings.readingMorningEvening': 'Чтение каждое утро и каждый вечер',
  'settings.appearance': 'Оформление',
  'settings.appearanceLight': 'Светлое',
  'settings.appearanceDark': 'Тёмное',
  'settings.appearanceSystem': 'Системное',
  'settings.upgrade': 'Перейти на Pro',
  'settings.upgradeCta': 'ПЕРЕЙТИ НА PRO — 0,99 $/МЕС',
  'settings.upgradeBlurb':
    'Откройте краткие пересказы с ИИ, премиальные голоса озвучки и импорт своих книг. 0,99 $ в месяц.',
  'settings.purchases': 'Покупки',
  'settings.restorePurchase': 'Восстановить покупку',
  'settings.restorePurchaseHint': 'Восстанавливает доступ Pro, уже оплаченный в App Store, Google Play или на сайте.',
  'settings.about': 'О приложении',
  'settings.version': 'Версия',
  'settings.privacyPolicy': 'Политика конфиденциальности',
  'settings.viewExternal': 'Открыть ↗',
  'settings.termsOfService': 'Условия использования',
  'settings.introTour': 'Знакомство с приложением',
  'settings.fullFeatureVideo': 'Полное видео о возможностях',
  'settings.replayOnboarding': 'Пересмотреть вводные экраны',
  'settings.view': 'Открыть',
  'settings.watchFeatureVideo': 'Посмотреть полное видео',
  'settings.accountActions': 'Действия с аккаунтом',
  'settings.legal': 'Правовая информация',
  'settings.contactSupport': 'Связаться с поддержкой',
  'settings.communityGuidelines': 'Правила сообщества',
  'settings.signOut': 'Выйти',
  'settings.deleteAccount': 'Удалить аккаунт',
  'settings.deleting': 'Удаление…',
  'settings.error': 'Ошибка',
  'settings.deleteAccountConfirm':
    'Ваш аккаунт и все аннотации, подборки, заметки и прогресс чтения будут удалены навсегда. Это действие необратимо.',
  'settings.areYouSure': 'Вы уверены?',
  'settings.deleteAccountFinal':
    'Ваш аккаунт и все данные будут удалены немедленно и не подлежат восстановлению.',
  'settings.deletePermanently': 'Да, удалить навсегда',
  'settings.restoreFailed': 'Не удалось восстановить',
  'settings.proRestored': 'Pro восстановлен!',
  'settings.proRestoredBody': 'Ваша подписка активна.',
  'settings.noSubscription': 'Подписка не найдена',
  'settings.noSubscriptionBody':
    'Нам не удалось найти активную подписку, связанную с этим аккаунтом.',
  'settings.planGuest': 'Гость',
  'settings.planStandard': 'Стандарт',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (пробный)',

  'settings.welcomeToPro': 'Добро пожаловать в Pro!',
  'settings.manage': 'Управлять',
  'settings.subscribeToPro': 'Подписаться на Pro',

  'home.tags': 'Подборки',
  'home.notes': 'Заметки',
  'home.xrefs': 'Ссылки',
  'home.readingPlan': 'ПЛАН ЧТЕНИЯ',
  'home.dailyVerses': 'СТИХИ ДНЯ',
  'home.dayStreak_one': '{{count}} день подряд',
  'home.dayStreak_few': '{{count}} дня подряд',
  'home.dayStreak_many': '{{count}} дней подряд',
  'home.dayStreak_other': '{{count}} дня подряд',
  'home.dailyReading': 'Чтение дня',
  'home.dailyReadingsTitle': 'Ежедневные чтения',
  'home.tapToSetUp': 'Нажмите, чтобы настроить',
  'home.tapToReadVerse': 'Нажмите, чтобы прочитать стих',
  'home.tapToContinue': 'Нажмите, чтобы продолжить',
  'home.planFinished': 'Завершено — выберите следующую книгу',
  'home.recentlyViewed': 'Недавно открытые',
  'home.removeFromRecent': 'Убрать из недавних',
  'home.removeFromRecentBody': 'Убрать «{{title}}» и сбросить прогресс до 0 %?',
  'home.signInCreate': 'Войти / Зарегистрироваться',
  'home.startReadingHint': 'Начните читать, и ваши недавние книги появятся здесь.',
  'home.viewLibrary': 'ОТКРЫТЬ БИБЛИОТЕКУ',

  'home.signInBlurb': 'Войдите, чтобы видеть недавно открытые книги, аннотации и многое другое на всех своих устройствах.',

  'auth.tagline': 'Чтение и исследование священных текстов',
  'auth.usernamePlaceholder': 'Имя пользователя *',
  'auth.fullNamePlaceholder': 'Полное имя',
  'auth.emailPlaceholder': 'Эл. почта *',
  'auth.passwordPlaceholder': 'Пароль *',
  'auth.emailAddressPlaceholder': 'Адрес эл. почты *',
  'auth.signIn': 'Войти',
  'auth.signUp': 'Зарегистрироваться',
  'auth.createAccount': 'Создать аккаунт',
  'auth.forgotPassword': 'Забыли пароль?',
  'auth.browseWithout': 'Продолжить без аккаунта',
  'auth.guestSubtext': 'Читайте и ищите по книгам — прогресс и заметки не сохранятся',
  'auth.resetPassword': 'Сброс пароля',
  'auth.sendResetLink': 'Отправить ссылку',
  'auth.createPasswordPlaceholder': 'Придумайте пароль *',
  'auth.backToSignIn': 'Назад ко входу',
  'auth.forgotBlurb':
    'Укажите адрес эл. почты, и мы пришлём ссылку для сброса пароля.',
  'auth.usernameAvailable': '✓ Свободно',
  'auth.usernameTakenShort': '✗ Занято',
  'auth.usernameHint': 'от 3 до 20 символов',
  'auth.usernameAlreadyTaken': 'Это имя пользователя уже занято.',
  'auth.resetLinkSent': 'Мы отправили ссылку для сброса пароля на {{email}}',
  'auth.error': 'Ошибка',
  'auth.missingFields': 'Заполнены не все поля',
  'auth.missingFieldsBody': 'Введите эл. почту и пароль.',
  'auth.invalidUsername': 'Недопустимое имя пользователя',
  'auth.invalidUsernameBody': 'Имя пользователя должно содержать от 3 до 20 символов: только буквы, цифры и подчёркивания.',
  'auth.usernameTaken': 'Имя занято',
  'auth.usernameTakenBody': 'Выберите другое имя пользователя.',
  'auth.checkUsername': 'Проверка имени',
  'auth.checkUsernameBody': 'Дождитесь окончания проверки имени пользователя.',
  'auth.checkEmail': 'Проверьте почту',
  'auth.checkEmailBody': 'Мы отправили ссылку для подтверждения на {{email}}',
  'auth.checkEmailSignInBody':
    'Мы отправили ссылку для подтверждения на {{email}}. После подтверждения войдите в свой аккаунт.',
  'auth.enterEmail': 'Введите эл. почту',
  'auth.enterEmailBody': 'Укажите адрес электронной почты.',
  'auth.emailSent': 'Письмо отправлено',
  'auth.emailSentBody': 'Проверьте почту — там ссылка для сброса пароля.',

  'auth.emailConfirmed': 'Почта подтверждена',
  'auth.accountReadySignIn':
    'Ваш аккаунт готов. Войдите с помощью эл. почты и пароля, чтобы начать.',
  'auth.accountReadyOpenApp':
    'Ваш аккаунт готов. Откройте приложение Immerse на телефоне, чтобы войти, или продолжите в браузере ниже.',
  'auth.openingApp': 'Ваш аккаунт готов. Открываем Immerse и выполняем вход…',
  'auth.openImmerse': 'Открыть Immerse',
  'auth.continueOnWeb': 'Продолжить в браузере',
  'auth.signInToImmerse': 'Войти в Immerse',
  'auth.continueToImmerse': 'Перейти в Immerse',
  'auth.chooseNewPassword': 'Придумайте новый пароль для своего аккаунта',
  'auth.newPasswordPlaceholder': 'Новый пароль',
  'auth.confirmNewPasswordPlaceholder': 'Повторите новый пароль',
  'auth.updatePassword': 'Обновить пароль',
  'auth.enterConfirmPassword': 'Введите и подтвердите новый пароль.',
  'auth.passwordTooShort': 'Пароль должен содержать не менее 8 символов.',
  'auth.passwordsDontMatch': 'Пароли не совпадают.',
  'auth.passwordUpdated': 'Пароль обновлён',
  'auth.passwordUpdatedBody': 'Теперь можно входить с новым паролем.',
  'auth.resetFailed':
    'Не удалось обновить пароль. Возможно, срок действия ссылки истёк — запросите новую.',

  'reminders.headerTitle': 'Ежедневные чтения',
  'reminders.enable': 'Включить ежедневные чтения',
  'reminders.openSettings': 'Открыть настройки',
  'reminders.source': 'Источник',
  'reminders.randomVerses': 'Случайные стихи',
  'reminders.readingPlan': 'План чтения',
  'reminders.chooseBook': 'Выберите книгу',
  'reminders.bookFinished': 'Завершено ✓ — выберите следующую книгу',
  'reminders.sessionLength': 'Длительность занятия',
  'reminders.sessionCaption': 'Относится к каждому занятию — {{dur}} утром и {{dur}} вечером.',
  'reminders.reminders': 'Напоминания',
  'reminders.time': 'Время',
  'reminders.morning': 'Утро',
  'reminders.evening': 'Вечер',
  'reminders.yourStreak': 'Ваша серия',
  'reminders.today': 'Сегодня',
  'reminders.currentStreak': 'Текущая серия',
  'reminders.bestStreak': 'Лучшая серия',
  'reminders.completedBooks': 'Прочитанные книги',
  'reminders.day_one': '{{count}} день',
  'reminders.day_few': '{{count}} дня',
  'reminders.day_many': '{{count}} дней',
  'reminders.day_other': '{{count}} дня',
  'reminders.hour': '1 ч',
  'reminders.minutes': '{{count}} мин',
  'reminders.signInRequired': 'Требуется вход',
  'reminders.signInRequiredBody': 'Создайте аккаунт, чтобы следовать плану чтения и видеть свой прогресс.',
  'reminders.notNow': 'Не сейчас',
  'reminders.enabledSub': 'Показывает ваше чтение дня на главном экране.',
  'reminders.disabledSub': 'Выключено — чтение дня скрыто с главного экрана.',
  'reminders.chooseNextToResume': 'Выберите следующую книгу выше, чтобы возобновить напоминания.',
  'reminders.chooseBookToEnable': 'Выберите книгу выше, чтобы включить напоминания.',
  'reminders.selectSourceToEnable': 'Выберите хотя бы один источник выше, чтобы включить напоминания.',
  'reminders.todayComplete': 'выполнено ✓',
  'reminders.todayPending': 'ожидается',
  'reminders.todayMorningDone': 'утро ✓',
  'reminders.todayMorningPending': 'утро — ожидается',
  'reminders.todayEveningDone': 'вечер ✓',
  'reminders.todayEveningPending': 'вечер — ожидается',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Читайте глубже. Связывайте больше.',
  'paywall.featureAiLabel': 'Пересказы отрывков с ИИ',
  'paywall.featureAiDesc': 'Просите пояснения и комментарии к любому отрывку',
  'paywall.featureVoicesLabel': 'Премиальные голоса озвучки',
  'paywall.featureVoicesDesc': 'Естественное, выразительное чтение голосом на ваш выбор',
  'paywall.featureImportLabel': 'Импорт своих книг',
  'paywall.featureImportDesc': 'Добавляйте в библиотеку файлы EPUB, PDF и DOCX',
  'paywall.subscribe': 'Оформить — {{price}} в месяц',
  'paywall.cancelNote': 'Отмена в любой момент · Оплата ежемесячно',
  'paywall.restore': 'Восстановить покупки',
  'paywall.terms': 'Условия использования',
  'paywall.privacy': 'Политика конфиденциальности',
  'paywall.notAvailable': 'Недоступно',
  'paywall.notAvailableBody': 'Встроенные покупки в этой сборке ещё не настроены. Загляните после выхода в App Store.',
  'paywall.welcome': 'Добро пожаловать в Pro!',
  'paywall.welcomeBody': 'Ваша подписка активна.',
  'paywall.purchaseFailed': 'Не удалось оформить покупку',
  'paywall.restoreFailed': 'Не удалось восстановить',

  'xrefs.title': 'Перекрёстные ссылки',
  'xrefs.empty': 'Перекрёстных ссылок пока нет. Ссылки, созданные в читалке, появятся здесь.',
  'xrefs.signInTitle': 'Войдите, чтобы увидеть свои ссылки',
  'xrefs.signInBody': 'Связывайте близкие отрывки со всей библиотеки.',
  'xrefs.searchSelected': 'Поиск по выбранным ссылкам...',
  'xrefs.searchPlaceholder': 'Поиск по отрывкам или подписям...',
  'xrefs.noMatch': 'Ни одна ссылка не соответствует запросу.',
  'xrefs.addLabel': 'Добавить подпись…',
  'xrefs.deleteConfirm': 'Удалить перекрёстную ссылку?',
  'xrefs.deleteBody': 'Оба выделенных фрагмента сохранятся.',

  'notes.title': 'Заметки',
  'notes.empty': 'Заметок пока нет. Заметки, созданные в читалке, появятся здесь.',
  'notes.signInTitle': 'Войдите, чтобы увидеть свои заметки',
  'notes.signInBody': 'Добавляйте к отрывкам комментарии и размышления по ходу чтения.',
  'notes.searchPlaceholder': 'Поиск по заметкам...',
  'notes.searchSelected': 'Поиск по выбранным заметкам...',
  'notes.byBook': 'По книгам',
  'notes.byDate': 'По дате',
  'notes.writeNote': 'Напишите заметку…',
  'notes.noMatch': 'Ни одна заметка не соответствует запросу.',
  'notes.deleteConfirm': 'Удалить заметку?',
  'notes.deleteBody': 'Выделенный фрагмент сохранится.',

  'tags.title': 'Подборки',
  'tags.empty': 'Подборок пока нет. Подборки, созданные в читалке, появятся здесь.',
  'tags.signInTitle': 'Войдите, чтобы увидеть свои подборки',
  'tags.signInBody': 'Создавайте и упорядочивайте подборки цитат со всей библиотеки.',
  'tags.organize': 'Упорядочить',
  'tags.searchPlaceholder': 'Поиск по подборкам...',
  'tags.searchSelected': 'Поиск по выбранным подборкам...',
  'tags.noMatch': 'Ни одна подборка не соответствует запросу.',
  'tags.deleteConfirm': 'Удалить подборку?',
  'tags.deleteBody': 'Метка «{{name}}» и все её фрагменты будут удалены.',

  'tags.renameTitle': 'Переименовать подборку',
  'tags.setPrivate': 'Сделать личной',
  'tags.setPublic': 'Сделать общей',
  'tags.publicTag': 'Общая подборка',
  'tags.removePassage': 'Убрать из подборки',
  'tags.removePassageConfirm': 'Убрать этот отрывок из подборки?',
  'tags.indent': 'Вложить',
  'tags.outdent': 'Вынести',
  'tags.organizeHint':
    'Перетаскивайте за ручку, чтобы изменить порядок \u00b7 \u21e4 \u21e5 меняет вложенность \u00b7 нажмите на подборку, чтобы упорядочить её цитаты.',
  'tags.searchTagsPassages': 'Поиск по подборкам и отрывкам…',
  'tags.exportSelected': 'Экспортировать выбранные подборки',
  'xrefs.exportSelected': 'Экспортировать выбранные перекрёстные ссылки',
  'tags.export': 'Экспорт',
  'tags.exporting': 'Экспорт…',
  'tags.exportInclude': 'Включить',
  'tags.exportNothingToInclude': 'Ни в одной из выбранных подборок нет: {{items}}',

  'panel.createAccount': 'Создать аккаунт',
  'panel.signInToSave': 'Создайте бесплатный аккаунт, чтобы сохранять подборки, заметки и ссылки.',
  'panel.editSelection': 'Изменить выделение текста',

  'reader.xrefMode': 'Режим ссылки — нажмите и удерживайте, чтобы выбрать отрывок',
  'reader.error': 'Ошибка читалки',
  'reader.opening': 'Открываем книгу…',
  'reader.footnote': 'Сноска',

  'reader.selectBook': 'Выберите книгу, чтобы начать читать',
  'reader.tableOfContents': 'Содержание',
  'reader.tocButtonHint': 'Перейти к разделу этой книги',
  'reader.expandSection': 'Развернуть раздел',
  'reader.collapseSection': 'Свернуть раздел',
  'reader.expand': 'Развернуть',
  'reader.collapse': 'Свернуть',
  'reader.actionTag': 'Подборка',
  'reader.actionNote': 'Заметка',
  'reader.actionXref': 'Ссылка',
  'reader.actionAi': 'ИИ',
  'reader.actionCopy': 'Копировать',
  'reader.updateSelection': 'Обновить выделение',
  'reader.updating': 'Обновление…',
  'reader.pickAsXref': 'Выбрать для ссылки',
  'reader.editSelectionHint':
    'Выделите новый текст для этой аннотации, затем выберите действие',
  'reader.savingXref': 'Сохраняем перекрёстную ссылку…',
  'reader.pickTargetHint': 'Выделите текст или нажмите на отрывок, чтобы связать',
  'reader.footnoteUnavailable': 'Текст сноски недоступен в веб-версии.',
  'reader.bookNotFound': 'Книга не найдена',
  'reader.viewTags': 'Показать подборки',
  'reader.viewNote': 'Показать заметку',
  'reader.viewXrefs': 'Показать перекрёстные ссылки',
  'reader.noQuotesFiled': 'Сюда пока не добавлено ни одной цитаты.',

  'ai.summary': 'Пересказ с ИИ',
  'ai.upgradeBlurb': 'Перейдите на Immerse Pro всего за 0,99 $, чтобы пользоваться пересказами с ИИ и другими возможностями Pro.',
  'ai.upgradeBtn': 'Перейти на Pro — 0,99 $/мес',
  'ai.thinking': 'Думаю…',
  'ai.error': 'Не удалось получить пересказ. Проверьте подключение и попробуйте ещё раз.',
  'ai.copied': '✓ Скопировано',
  'ai.copyHint': 'Нажмите и удерживайте, чтобы скопировать',

  'note.title': 'Заметка',
  'note.addTitle': 'Добавить заметку',
  'note.placeholder': 'Напишите заметку здесь…',
  'note.loading': 'Загрузка…',
  'note.emptyTitle': 'Пустая заметка',
  'note.emptyBody': 'Напишите что-нибудь перед сохранением.',
  'note.saveFailed': 'Не удалось сохранить заметку',
  'note.deleteTitle': 'Удалить заметку?',
  'note.deleteBody': 'Заметка будет удалена. Если на этом отрывке больше нет аннотаций, выделение тоже будет снято.',
  'note.deleteFailed': 'Не удалось удалить заметку',
  'note.signInRequired': 'Требуется вход',
  'note.signInBody': 'Заметки сохраняются в вашем аккаунте. Войдите или создайте аккаунт.',

  'xref.title': 'Перекрёстная ссылка',
  'xref.yourSelection': 'ВАШЕ ВЫДЕЛЕНИЕ',
  'xref.pickSecond': 'Выберите второй отрывок  →',
  'xref.noneFound': 'Перекрёстных ссылок не найдено.',

  'xref.findPassage': 'Найдите отрывок для связи',
  'xref.searchPlaceholder': 'Поиск по любому отрывку…',
  'xref.save': 'Сохранить ссылку',
  'xref.from': 'Откуда',
  'xref.to': 'Куда',
  'xref.linksTo': 'ссылается на',

  'banner.googlePlay': 'Доступно в Google Play',
  'banner.appStore': 'Загрузить в App Store',
  'banner.install': 'Установить',
  'banner.get': 'Получить',

  'tagPanel.new': 'Новая подборка',
  'tagPanel.createWithin': 'Создать подборку в «{{parent}}»',
  'tagPanel.addTitle': 'Добавить в подборку',
  'tagPanel.viewTitle': 'Подборки',
  'tagPanel.addSubTag': 'Добавить вложенную подборку',
  'tagPanel.emptyAdd': 'Подборок пока нет — создайте выше',
  'tagPanel.emptyView': 'На этом выделении нет подборок',

  'voice.title': 'Голос чтения',
  'voice.onyx': 'Onyx — глубокий и тёплый',
  'voice.cedar': 'Cedar — естественный и насыщенный',
  'voice.ash': 'Ash — ясный и прямой',
  'voice.nova': 'Nova — звонкий',
  'voice.shimmer': 'Shimmer — мягкий',
  'voice.marin': 'Marin — естественный и спокойный',

  'reader.signInRequired': 'Требуется вход',
  'reader.signInBody': 'Создайте аккаунт, чтобы сохранять подборки, заметки и историю чтения.',
  'reader.notNow': 'Не сейчас',
  'reader.signIn': 'Войти',
  'reader.pdfNotFound': 'Не удалось найти PDF-файл.',
  'reader.contentLoadFailed': 'Не удалось загрузить содержимое',
  'reader.noBook': 'Книга не указана',
  'reader.storageError': 'Ошибка хранилища',

  'discover.recent': 'НЕДАВНИЕ',
  'discover.trending': 'ПОПУЛЯРНОЕ',
  'discover.searchPlaceholder': 'Поиск по подборкам и пользователям…',
  'discover.searchSelected': 'Поиск по выбранным подборкам…',
  'discover.import': 'Импортировать',
  'discover.imported': 'Импортировано',
  'discover.import_one': '{{count}} импорт',
  'discover.import_few': '{{count}} импорта',
  'discover.import_many': '{{count}} импортов',
  'discover.import_other': '{{count}} импорта',
  'discover.noneYet': 'Общих подборок пока нет',
  'discover.noResults': 'Ничего не найдено',
  'discover.tryDifferent': 'Попробуйте другой запрос.',
  'discover.signInTitle': 'Войдите, чтобы открыть «Обзор»',
  'discover.signInBody': 'Смотрите, что находят другие читатели во всех традициях.',
  'discover.anonymous': 'Аноним',
  'discover.beFirst': 'Поделитесь подборкой первым.',
  'discover.ownTag': 'Это ваша собственная подборка',
  'discover.alreadyImported': 'Уже импортировано',
  'discover.importFailed': 'Не удалось импортировать',
  'discover.exportFailed': 'Не удалось экспортировать',
  'discover.unknownError': 'Неизвестная ошибка',

  'usertags.autoImports': 'Автоматически добавляет общие подборки этого пользователя в ваше приложение',
  'usertags.noTags': 'Общих подборок нет',
  'usertags.noTagsBody': 'Этот пользователь пока не поделился ни одной подборкой.',
  'usertags.follow': 'Подписаться',
  'usertags.unfollow': 'Отписаться',
  'usertags.share': 'Поделиться',
  'usertags.error': 'Ошибка',
  'usertags.somethingWrong': 'Что-то пошло не так',

  'onboarding.chooseLanguage': 'Выберите язык',
  'onboarding.changeLaterSettings': 'Это можно изменить позже в настройках.',
  'onboarding.libraryDownloadHint': 'Чтобы загрузить библиотеку на языке {{language}}, нажмите ⌄ рядом со словом «Библиотека» на экране библиотеки.',
  'onboarding.continue': 'Продолжить',
  'onboarding.chooseTextSize': 'Выберите размер текста',
  'onboarding.fontPreviewQuote':
    '«Ищите — и найдёте; стучите — и отворят вам».',
  'onboarding.getStarted': 'Начать',

  'onboarding.closeIntro': 'Закрыть знакомство',
  'onboarding.goToStep': 'Перейти к шагу {{number}}',
  'onboarding.libraryTitle': 'Библиотека',
  'onboarding.libraryCaption': 'Просматривайте отобранную библиотеку разных традиций. Нажмите на книгу, чтобы начать читать.',
  'onboarding.searchTitle': 'Ищите везде',
  'onboarding.searchCaption': 'Ищите сразу по всем книгам и переходите прямо к отрывку.',
  'onboarding.tagAsYouGoTitle': 'Собирайте подборки по ходу чтения',
  'onboarding.tagAsYouGoCaption': 'Добавляйте отрывок в подборку прямо из результатов поиска.',
  'onboarding.buildTagsTitle': 'Создавайте свои подборки',
  'onboarding.buildTagsCaption': 'Группируйте отрывки в своих подборках, чтобы легко к ним возвращаться.',
  'onboarding.selectActTitle': 'Выделяйте и действуйте',
  'onboarding.selectActCaption': 'Выделите любой текст, чтобы подсветить его, добавить в подборку, добавить заметку или связать ссылкой.',
  'onboarding.marginTitle': 'Аннотации на полях',
  'onboarding.marginCaption': 'Ваши подборки, заметки и ссылки живут на полях.',
  'onboarding.navigateTitle': 'Быстрая навигация',
  'onboarding.navigateCaption': 'Откройте содержание, чтобы перемещаться по книге.',
  'onboarding.yourTagsTitle': 'Ваши подборки',
  'onboarding.yourTagsCaption': 'Возвращайтесь к каждому отрывку из подборки, сгруппированному по подборкам.',
  'onboarding.xrefsTitle': 'Перекрёстные ссылки',
  'onboarding.xrefsCaption': 'Связывайте близкие отрывки между книгами и традициями.',
  'onboarding.shareTitle': 'Делитесь и публикуйте',
  'onboarding.shareCaption': 'Поделитесь цитатой или опубликуйте подборку для сообщества.',

  // ── Экспорт ───────────────────────────────────────────────────────────────
  'export.shareTags_one': 'Поделиться {{count}} подборкой',
  'export.shareTags_few': 'Поделиться {{count}} подборками',
  'export.shareTags_many': 'Поделиться {{count}} подборками',
  'export.shareTags_other': 'Поделиться {{count}} подборками',
  'export.shareTagsGeneric': 'Поделиться подборками',
  'export.shareXrefs_one': 'Поделиться {{count}} перекрёстной ссылкой',
  'export.shareXrefs_few': 'Поделиться {{count}} перекрёстными ссылками',
  'export.shareXrefs_many': 'Поделиться {{count}} перекрёстными ссылками',
  'export.shareXrefs_other': 'Поделиться {{count}} перекрёстными ссылками',
  'export.preparing': 'Подготовка…',
  'export.notesOn': 'Ваши заметки к каждому отрывку',
  'export.notesNone': 'На этих отрывках нет заметок',
  'export.xrefsOn': 'Связанные отрывки под каждой цитатой',
  'export.xrefsNone': 'На этих отрывках нет перекрёстных ссылок',
  'export.docxTitle': 'Документ Word (.docx)',
  'export.docxShort': 'Word (.docx)',
  'export.docxDesc': 'Заголовки подборок с цитатами. Открывается в Word, Pages или Google Документах.',
  'export.pdfTitle': 'Документ PDF',
  'export.pdfDesc': 'Свёрстанный документ для печати или отправки.',
  'export.csvTitle': 'Таблица (.csv)',
  'export.csvDesc': 'По строке на отрывок. Открывается в Excel, Numbers или Google Таблицах.',
  'export.mdTitle': 'Markdown (.md)',
  'export.mdDesc': 'Для Obsidian, Notion или любого текстового редактора.',
  'export.noPassagesTagged': '(в этой подборке нет отрывков)',
  'export.seeAlso': 'См. также:',

  // ── План чтения ───────────────────────────────────────────────────────────
  'plan.chooseBook': 'Выберите книгу',
  'plan.searchBooks': 'Поиск книг…',
  'plan.noBooksMatch': 'По запросу «{{query}}» книг не найдено.',
  'plan.readingComplete': 'Чтение завершено',
  'plan.morningSession': 'Утреннее занятие',
  'plan.eveningSession': 'Вечернее занятие',
  'plan.minutes': '{{count}} мин',
  'plan.streakDay': 'День серии {{count}} ✓',
  'plan.sessionsToday': 'Сегодня {{done}} из {{required}} занятий',
  'plan.youFinished': 'Вы дочитали {{title}}',
  'plan.readOverDays_one': 'Прочитано за {{count}} день',
  'plan.readOverDays_few': 'Прочитано за {{count}} дня',
  'plan.readOverDays_many': 'Прочитано за {{count}} дней',
  'plan.readOverDays_other': 'Прочитано за {{count}} дня',
  'plan.remindersPaused': 'напоминания приостановлены',
  'plan.chooseNextBook': 'Выберите следующую книгу',
  'completed.title': 'Прочитанные книги',
  'completed.empty': 'Книги, которые вы дочитаете по плану чтения, появятся здесь.',
  'completed.finishedOn': 'Завершено {{date}}',
  'completed.day_one': '{{count}} день',
  'completed.day_few': '{{count}} дня',
  'completed.day_many': '{{count}} дней',
  'completed.day_other': '{{count}} дня',

  // ── Остальное по библиотеке ───────────────────────────────────────────────
  'library.selectPassageForXref': 'Выберите отрывок для перекрёстной ссылки',
  'library.findingRelated': 'Ищем похожие отрывки…',
  'library.aiSearchOffline': 'Для поиска по вопросу требуется подключение к интернету',
  'library.importFailedTitle': 'Не удалось импортировать',
  'library.couldNotImport': 'Не удалось импортировать файл.',
  'library.bookAdded': 'Книга добавлена',
  'library.bookAddedBody': '«{{title}}» теперь в разделе «Мои книги».',
  'library.importErrorTitle': 'Ошибка импорта',
  'library.unexpectedError': 'Произошла непредвиденная ошибка.',
  'nav.browsingAsGuest': 'Просмотр как гость',
  'reader.selectBookToBegin': 'Выберите книгу, чтобы начать читать',
  'tags.exportFailed': 'Не удалось экспортировать',
  'tags.couldNotExport': 'Не удалось экспортировать подборки.',
  'tags.couldNotRemoveSelection': 'Не удалось убрать выделение',
  'tags.reorderHint': 'Перетаскивайте за ручку, чтобы изменить порядок · ⇤ ⇥ меняет вложенность · нажмите на подборку, чтобы упорядочить её цитаты.',
  'tags.swipeHint': 'Проведите по подборке вправо, чтобы сделать её общей или личной.',
  'discover.publishHint': 'Проведите по подборке вправо на экране «Подборки», чтобы опубликовать её здесь.',
  'reminders.notificationsOff':
    'Уведомления для Immerse отключены, поэтому напоминания не смогут прийти. '
    + 'Включите их в настройках устройства.',
  'plan.continueJourney': 'Продолжите свой путь чтения',
  'plan.yourBook': 'Ваша книга',
  'reader.notesInParagraph_one': '{{count}} заметка в этом абзаце',
  'reader.notesInParagraph_few': '{{count}} заметки в этом абзаце',
  'reader.notesInParagraph_many': '{{count}} заметок в этом абзаце',
  'reader.notesInParagraph_other': '{{count}} заметки в этом абзаце',
  'plan.awaitsMorning': '{{book}} ждёт — утреннее чтение',
  'plan.awaitsEvening': '{{book}} ждёт — вечернее чтение',
  'reminders.dailyReadingFrom': 'Чтение дня · {{source}}',
  'library.tapToExpandHint': 'Нажмите, чтобы развернуть · Удерживайте, чтобы открыть в читалке',
  'library.deleteBookImportedBody': 'Эта книга и все её аннотации будут удалены навсегда.',
  'library.deleteBookBundledBody':
    'Эта книга и все её аннотации будут удалены. Она вернётся при следующем обновлении библиотеки.',
  'library.deleteCategoryConfirm': 'Удалить «{{name}}»?',
  'library.deleteCategoryBody_one': 'Также будет удалена {{count}} книга и все её аннотации.',
  'library.deleteCategoryBody_few': 'Также будут удалены {{count}} книги и все их аннотации.',
  'library.deleteCategoryBody_many': 'Также будут удалены {{count}} книг и все их аннотации.',
  'library.deleteCategoryBody_other': 'Также будут удалены {{count}} книги и все их аннотации.',
  'library.deleteCategoryEmptyBody': 'Эта категория будет удалена навсегда.',

  'auth.passwordTooShortTitle': 'Слишком короткий пароль',
  'auth.passwordsMustMatch': 'Убедитесь, что оба пароля совпадают.',
  'auth.usernamePlain': 'Имя пользователя',
  'auth.fullNameOptional': 'Полное имя (необязательно)',
  'auth.emailPlain': 'Эл. почта',
  'auth.passwordPlain': 'Пароль',
  'auth.emailAddressPlain': 'Адрес эл. почты',

  // ── Знакомство с приложением (мобильное) ──────────────────────────────────
  'onboarding.skip': 'Пропустить',
  'onboarding.tour.libraryMain.label': 'Экран библиотеки',
  'onboarding.tour.libraryMain.caption':
    'В библиотеке собрано более 400 священных текстов всех крупных традиций. Нажмите на традицию, чтобы посмотреть её книги.',
  'onboarding.tour.libraryExpanded.label': 'Развёрнутая библиотека',
  'onboarding.tour.libraryExpanded.caption':
    'Каждая традиция раскрывается, показывая авторов и собрания. Нажмите на любое название, чтобы открыть его в читалке.',
  'onboarding.tour.librarySearch.label': 'Поиск по библиотеке',
  'onboarding.tour.librarySearch.caption':
    'Ищите сразу по всем 400+ текстам. Нажмите на результат, чтобы развернуть его, или удерживайте, чтобы сразу открыть в читалке.',
  'onboarding.tour.searchQuickTag.label': 'Быстрые подборки в результатах поиска',
  'onboarding.tour.searchQuickTag.caption':
    'Выберите один или несколько результатов поиска и добавьте их в подборку одним касанием. Быстрый способ собрать тематическую подборку со всей библиотеки.',
  'onboarding.tour.home.label': 'Главный экран',
  'onboarding.tour.home.caption':
    'На главном экране видно, сколько подборок, заметок и перекрёстных ссылок вы создали, а также ваши недавние книги. Нажмите на название, чтобы продолжить чтение.',
  'onboarding.tour.homePlan.label': 'План чтения на главном экране',
  'onboarding.tour.homePlan.caption':
    'Выработайте привычку читать каждый день: следуйте плану чтения по любой книге и на любую длительность или получайте случайные стихи из выбранных вами традиций — с ежедневными напоминаниями и серией, которая растёт с каждым днём чтения.',
  'onboarding.tour.settingsDaily.label': 'Настройки ежедневных чтений',
  'onboarding.tour.settingsDaily.caption':
    'В настройках выберите традиции для случайных стихов и время, когда вам удобно получать мягкое напоминание, — или переключитесь на план чтения, чтобы каждый день продвигаться по одной книге.',
  'onboarding.tour.readerSelect.label': 'Выделение текста в читалке',
  'onboarding.tour.readerSelect.caption':
    'Нажмите и удерживайте любой отрывок, чтобы выделить его. Значками внизу экрана добавьте отрывок в подборку, заметку, перекрёстную ссылку или получите пересказ с ИИ.',
  'onboarding.tour.readerNote.label': 'Заметка в читалке',
  'onboarding.tour.readerNote.caption':
    'Заметки прикрепляются к тому тексту, который вы выделили. Золотой маркер на полях позволяет найти и открыть их в любой момент.',
  'onboarding.tour.readerXref.label': 'Перекрёстная ссылка в читалке',
  'onboarding.tour.readerXref.caption':
    'Перекрёстные ссылки связывают отрывки из разных книг и традиций. Нажмите и удерживайте связанную цитату, чтобы перейти к ней в читалке.',
  'onboarding.tour.readerAi.label': 'Пересказ с ИИ в читалке',
  'onboarding.tour.readerAi.caption':
    'Выделив отрывок, нажмите значок искр, чтобы получить мгновенный пересказ с ИИ, — особенно полезно для сложных или незнакомых текстов.',
  'onboarding.tour.readerListen.label': 'Режим прослушивания',
  'onboarding.tour.readerListen.caption':
    'Нажмите кнопку с наушниками, чтобы книга читалась вслух: читалка подсвечивает каждый отрывок по ходу озвучки. Нажмите и удерживайте эту кнопку, чтобы выбрать один из естественных голосов.',
  'onboarding.tour.tags.label': 'Экран подборок',
  'onboarding.tour.tags.caption':
    'Экран «Подборки» группирует отрывки из подборок по темам. Нажмите на название подборки, чтобы увидеть её цитаты с полными ссылками на источник.',
  'onboarding.tour.xrefs.label': 'Экран перекрёстных ссылок',
  'onboarding.tour.xrefs.caption':
    'Экран перекрёстных ссылок показывает все связанные отрывки рядом друг с другом. Нажмите и удерживайте любую из сторон, чтобы перейти к этому отрывку в читалке.',
  'onboarding.tour.discover.label': 'Экран «Обзор»',
  'onboarding.tour.discover.caption':
    'На экране «Обзор» вы найдёте подборки, которыми поделились другие читатели. Нажмите на подборку, чтобы посмотреть её отрывки, а затем добавьте её к себе.',
  'onboarding.tour.tagShare.label': 'Панель отправки подборки',
  'onboarding.tour.tagShare.caption':
    'Экспортируйте любую подборку в документ Word, PDF, таблицу, Markdown и другие форматы — вместе с вашими заметками и перекрёстными ссылками.',

  // ── Appearance (reader typography) ───────────────────────────────────────
  'appearance.title': 'Оформление',
  'appearance.navHint': 'Шрифт, интервалы, цвет',
  'appearance.reading': 'Чтение',
  'appearance.preview': 'Предпросмотр',
  'appearance.previewText': 'Чтение — это тихий разговор, проходящий сквозь века.',
  'appearance.typeface': 'Шрифт',
  'appearance.typefaceSystem': 'Системный',
  'appearance.typefaceLiterataBlurb': 'Создан для долгого чтения. Подстраивается под размер.',
  'appearance.typefaceCharisBlurb': 'Потомок Charter. Устойчив в мелком кегле.',
  'appearance.typefaceGaramondBlurb': 'Классическая антиква. Легче на странице.',
  'appearance.typefaceSystemBlurb': 'Тот, что предоставляет устройство.',
  'appearance.textSize': 'Размер текста',
  'appearance.lineSpacing': 'Межстрочный интервал',
  'appearance.lineSpacingTight': 'Узкий',
  'appearance.lineSpacingNormal': 'Обычный',
  'appearance.lineSpacingRelaxed': 'Свободный',
  'appearance.lineSpacingLoose': 'Широкий',
  'appearance.margins': 'Поля',
  'appearance.marginsNarrow': 'Узкие',
  'appearance.marginsNormal': 'Обычные',
  'appearance.marginsWide': 'Широкие',
  'appearance.justify': 'Выравнивание по ширине',
  'appearance.justifyHint': 'Выравнивает оба края, с переносами.',
  'appearance.paragraphStyle': 'Абзацы',
  'appearance.paragraphSpaced': 'С отступом',
  'appearance.paragraphIndented': 'С красной строки',
  'appearance.paragraphHint': 'Красная строка — традиционный книжный набор.',
  'appearance.theme': 'Цвет страницы',
  'appearance.themeLight': 'Светлая',
  'appearance.themeSepia': 'Сепия',
  'appearance.themeQuiet': 'Приглушённая',
  'appearance.themeDark': 'Тёмная',
  'appearance.themeNight': 'Ночная',
  'appearance.themeSystem': 'Как в приложении',
  'appearance.fineTuning': 'Точная настройка',
  'appearance.characterSpacing': 'Межбуквенный интервал',
  'appearance.wordSpacing': 'Межсловный интервал',
  'appearance.textWeight': 'Насыщенность текста',
  'appearance.paragraphNumbers': 'Номера абзацев',
  'appearance.paragraphNumbersHint': 'Показывать номера для ссылок на полях.',
  'appearance.appTheme': 'Тема приложения',
  'appearance.appThemeHint': 'Применяется вне читалки.',
  'appearance.reset': 'Сбросить настройки',

  // ── Названия собраний для ссылок ──────────────────────────────────────────
  'citation.bible': 'Библия',
  'citation.tanakh': 'Танах',
  'citation.quran': 'Коран',
  'citation.guruGranthSahib': 'Гуру Грантх Сахиб',
};
