import type { LocaleTable } from './keys';

/**
 * Turkish UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key.
 *
 * Every plural group carries only `_other`. A Turkish noun stays singular after
 * a numeral — «1 kitap», «5 kitap» — so a separate `_one` would repeat the same
 * sentence word for word; the CLDR `one` category simply resolves to `_other`.
 *
 * Sentences are built so an interpolated value never needs a case suffix, since
 * the suffix Turkish would want depends on the value's own final vowel and no
 * template can know it. Terminology fixed once, here: a tag/compilation is a
 * *derleme* (renamed 2026-08-17 from *etiket*, a front-vowel word — watch
 * suffix harmony: -yi/-ler/-de/-den/-ye/-nin), a cross-reference a *çapraz
 * referans*, a passage a *pasaj*.
 */
export const tr: LocaleTable = {
  'common.cancel': 'İptal',
  'common.remove': 'Kaldır',
  'common.removing': 'Kaldırılıyor…',
  'common.save': 'Kaydet',
  'common.done': 'Tamam',
  'common.ok': 'Tamam',
  'common.continue': 'Devam',
  'common.tryAgain': 'Lütfen tekrar deneyin.',
  'common.delete': 'Sil',
  'common.clear': 'Temizle',
  'common.signInCreate': 'Giriş yapın veya hesap oluşturun',
  'common.book_other': '{{count}} kitap',
  'common.saving': 'Kaydediliyor…',
  'common.loading': 'Yükleniyor…',
  'common.copy': 'Kopyala',
  'common.retry': 'Tekrar deneyin',
  'common.back': 'Geri',
  'common.next': 'İleri',
  'common.searching': 'Aranıyor…',
  'common.noResults': 'Sonuç bulunamadı.',
  'common.dismiss': 'Kapat',
  'common.options': 'Seçenekler',
  'common.collapseLibrary': 'Kütüphaneyi daralt',
  'common.expandLibrary': 'Kütüphaneyi genişlet',
  'common.minutesAgo': '{{count}} dk önce',
  'common.hoursAgo': '{{count}} sa önce',
  'common.daysAgo': '{{count}} gün önce',
  'common.highlight_other': '{{count}} vurgu',
  'common.edit': 'Düzenle',
  'common.justNow': 'az önce',
  'common.opening': 'Açılıyor…',
  'common.or': 'veya',
  'common.pleaseWait': 'Lütfen bekleyin…',
  'common.somethingWrong': 'Bir şeyler ters gitti.',
  'common.rename': 'Yeniden adlandır',
  'common.dragToReorder': 'Sıralamak için sürükleyin',
  'common.openInReader': 'Okuyucuda aç',
  'common.otherTradition': 'Diğer',

  'nav.home': 'Ana sayfa',
  'nav.library': 'Kütüphane',
  'nav.tags': 'Derlemeler',
  'nav.notes': 'Notlar',
  'nav.xrefs': 'Referanslar',
  'nav.discover': 'Keşfet',
  'nav.settings': 'Ayarlar',
  'nav.guest': 'Misafir',
  'nav.reader': 'Okuyucu',
  'nav.signOut': 'Çıkış yap',

  'library.title': 'Kütüphane',
  'library.languageSheetTitle': 'Kütüphane dili',
  'library.availableToDownload': 'İndirilebilir',
  'library.downloading': 'İndiriliyor %{{percent}}',
  'library.verifying': 'Doğrulanıyor…',
  'library.importing': 'İçe aktarılıyor…',
  'library.cleaning': 'Tamamlanıyor…',
  'library.downloadFailed': 'İndirme başarısız',
  'library.updateAvailable': 'Güncelleme mevcut',
  'library.updateLanguageA11y': '{{language}} dilini güncelle',
  'library.changeLanguageA11y': '{{title}}, {{language}}. Kütüphane dilini değiştir',

  'library.myBooks': 'Kitaplarım',
  'library.searchAll': 'Tüm kitaplarda ara…',
  'library.searchSelected_other': 'Seçili {{count}} kitapta ara…',
  'library.noResultsFor': '“{{query}}” için sonuç bulunamadı.',
  'library.result_other': '{{count}} sonuç',
  'library.relatedPassages': 'İlgili pasajlar',
  'library.relatedOn': 'kaynak',
  'library.relatedPrefix': 'İLGİLİ',
  'library.booksAndSections': 'Kitaplar ve bölümler',
  'library.tapToOpenHint': 'Açmak için dokunun',
  'library.importTitle': 'Kitap içe aktar (TXT, EPUB, DOCX, RTF, PDF)',
  'library.importProFeature':
    'Kitap içe aktarma bir Pro özelliğidir. Kendi kitaplarınızı aktarmak için Ayarlar’dan Pro’ya geçin.',
  'library.importFailed': 'İçe aktarma başarısız.',
  'library.importSucceeded': '“{{title}}” başarıyla içe aktarıldı.',
  'library.noImportedBooks':
    'Henüz içe aktarılmış kitap yok. Kitap eklemek için arama çubuğunun yanındaki düğmeyi kullanın.',
  'library.deleteBookConfirm': '“{{title}}” silinsin mi?',
  'library.tagAction': 'Derleme',

  'settings.language': 'Dil',
  'settings.appLanguage': 'Uygulama dili',
  'settings.appLanguageHint': 'Düğmeler ve menüler. Hangi kütüphaneyi okuduğunuzdan bağımsızdır.',
  'settings.restartForDirection': 'Geçişi tamamlamak için yeniden başlatın',
  'settings.restartForDirectionBody':
    '{{language}} sağdan sola yazılır. Yerleşimin yön değiştirmesi için Immerse’i kapatıp yeniden açın.',
  'settings.restartForDirectionBodyLtr':
    'Yerleşimi soldan sağa döndürmek için Immerse’i kapatıp yeniden açın.',
  'settings.downloadedLibraries': 'İndirilen kütüphaneler',
  'settings.downloadedLibrariesHint': 'Aralarında Kütüphane ekranından geçiş yapın.',
  'settings.includedWithApp': 'uygulamayla birlikte gelir',
  'settings.removeLanguageTitle': '{{language}} kaldırılsın mı?',
  'settings.removeLanguageBody':
    'Bu kitaplar bu cihazdan silinecek. Dilediğiniz zaman yeniden indirebilirsiniz.',
  'settings.removeLanguageKeepsAnnotations':
    'Bu kitaplardaki {{annotations}} korunacak ve {{language}} dilini yeniden indirdiğinizde tekrar görünecek.',
  'settings.removeFailed': 'Kaldırılamadı',
  'settings.account': 'Hesap',
  'settings.fullName': 'Ad soyad',
  'settings.edit': 'Düzenle',
  'settings.username': 'Kullanıcı adı',
  'settings.plan': 'Plan',
  'settings.fontSize': 'Yazı boyutu',
  'settings.fontPreview': '{{size}} boyutunda önizleme metni. Bu ayar tüm cihazlarınızda eşitlenir.',
  'settings.dailyReadings': 'Günlük okumalar',
  'settings.randomVersesAndPlan': 'Rastgele ayetler ve okuma planı',
  'settings.readingMorningEvening': 'Her sabah ve her akşam bir okuma',
  'settings.appearance': 'Görünüm',
  'settings.appearanceLight': 'Açık',
  'settings.appearanceDark': 'Koyu',
  'settings.appearanceSystem': 'Sistem',
  'settings.upgrade': 'Yükselt',
  'settings.upgradeCta': 'PRO’YA GEÇİN — AYDA 0,99 $',
  'settings.upgradeBlurb':
    'Yapay zekâ özetlerini, premium seslendirme seslerini ve kendi kitaplarınızı aktarmayı açın. Ayda 0,99 $.',
  'settings.purchases': 'Satın alımlar',
  'settings.restorePurchase': 'Satın alımı geri yükle',
  'settings.restorePurchaseHint': 'Zaten ödediğiniz Pro erişimini geri getirir — App Store, Google Play veya web üzerinden.',
  'settings.about': 'Hakkında',
  'settings.version': 'Sürüm',
  'settings.privacyPolicy': 'Gizlilik Politikası',
  'settings.viewExternal': 'Görüntüle ↗',
  'settings.termsOfService': 'Kullanım Koşulları',
  'settings.introTour': 'Tanıtım turu',
  'settings.fullFeatureVideo': 'Tüm özellikler videosu',
  'settings.replayOnboarding': 'Tanıtım ekranlarını yeniden izle',
  'settings.view': 'Görüntüle',
  'settings.watchFeatureVideo': 'Tüm özellikler videosunu izle',
  'settings.accountActions': 'Hesap işlemleri',
  'settings.legal': 'Yasal',
  'settings.communityGuidelines': 'Topluluk kuralları',
  'settings.signOut': 'Çıkış yap',
  'settings.deleteAccount': 'Hesabı sil',
  'settings.deleting': 'Siliniyor…',
  'settings.error': 'Hata',
  'settings.deleteAccountConfirm':
    'Bu işlem hesabınızı ve tüm açıklamalarınızı, derlemelerinizi, notlarınızı ve okuma ilerlemenizi kalıcı olarak siler. Geri alınamaz.',
  'settings.areYouSure': 'Emin misiniz?',
  'settings.deleteAccountFinal':
    'Hesabınız ve tüm verileriniz hemen silinecek ve kurtarılamayacak.',
  'settings.deletePermanently': 'Evet, kalıcı olarak sil',
  'settings.restoreFailed': 'Geri yükleme başarısız',
  'settings.proRestored': 'Pro geri yüklendi!',
  'settings.proRestoredBody': 'Aboneliğiniz artık etkin.',
  'settings.noSubscription': 'Abonelik bulunamadı',
  'settings.noSubscriptionBody':
    'Bu hesaba bağlı etkin bir abonelik bulamadık.',
  'settings.planGuest': 'Misafir',
  'settings.planStandard': 'Standart',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro (deneme)',

  'settings.welcomeToPro': 'Pro’ya hoş geldiniz!',
  'settings.manage': 'Yönet',

  'home.tags': 'Derlemeler',
  'home.notes': 'Notlar',
  'home.xrefs': 'Referanslar',
  'home.readingPlan': 'OKUMA PLANI',
  'home.dailyVerses': 'GÜNÜN AYETLERİ',
  'home.dayStreak_other': '{{count}} günlük seri',
  'home.dailyReading': 'Günlük okuma',
  'home.dailyReadingsTitle': 'Günlük okumalar',
  'home.tapToSetUp': 'Ayarlamak için dokunun',
  'home.tapToReadVerse': 'Bir ayet okumak için dokunun',
  'home.tapToContinue': 'Devam etmek için dokunun',
  'home.planFinished': 'Bitti — sıradaki kitabınızı seçin',
  'home.recentlyViewed': 'Son görüntülenenler',
  'home.removeFromRecent': 'Son görüntülenenlerden kaldır',
  'home.removeFromRecentBody': '“{{title}}” kaldırılsın ve okuma ilerlemesi %0’a sıfırlansın mı?',
  'home.signInCreate': 'Giriş yap / Hesap oluştur',
  'home.startReadingHint': 'Okumaya başlayın; son kitaplarınız burada görünsün.',
  'home.viewLibrary': 'KÜTÜPHANEYİ GÖR',

  'home.signInBlurb': 'Son görüntülediğiniz kitapları, açıklamalarınızı ve daha fazlasını tüm cihazlarınızda görmek için giriş yapın.',

  'auth.tagline': 'Dinler arası e-okuyucu ve araştırma',
  'auth.usernamePlaceholder': 'Kullanıcı adı *',
  'auth.fullNamePlaceholder': 'Ad soyad',
  'auth.emailPlaceholder': 'E-posta *',
  'auth.passwordPlaceholder': 'Parola *',
  'auth.emailAddressPlaceholder': 'E-posta adresi *',
  'auth.signIn': 'Giriş yap',
  'auth.signUp': 'Kaydol',
  'auth.createAccount': 'Hesap oluştur',
  'auth.forgotPassword': 'Parolanızı mı unuttunuz?',
  'auth.browseWithout': 'Hesap açmadan göz atın',
  'auth.guestSubtext': 'Kitapları okuyup arayın — ilerleme ve notlar kaydedilmez',
  'auth.resetPassword': 'Parolayı sıfırla',
  'auth.sendResetLink': 'Sıfırlama bağlantısı gönder',
  'auth.createPasswordPlaceholder': 'Parola oluştur *',
  'auth.backToSignIn': 'Girişe dön',
  'auth.forgotBlurb':
    'E-posta adresinizi girin; parolanızı sıfırlamanız için bir bağlantı gönderelim.',
  'auth.usernameAvailable': '✓ Uygun',
  'auth.usernameTakenShort': '✗ Alınmış',
  'auth.usernameHint': '3–20 karakter',
  'auth.usernameAlreadyTaken': 'Bu kullanıcı adı zaten alınmış.',
  'auth.resetLinkSent': 'Parola sıfırlama bağlantısını {{email}} adresine gönderdik',
  'auth.error': 'Hata',
  'auth.missingFields': 'Eksik alanlar',
  'auth.missingFieldsBody': 'Lütfen e-posta ve parola girin.',
  'auth.invalidUsername': 'Geçersiz kullanıcı adı',
  'auth.invalidUsernameBody': 'Kullanıcı adı 3–20 karakter olmalı: yalnızca harf, rakam ve alt çizgi.',
  'auth.usernameTaken': 'Kullanıcı adı alınmış',
  'auth.usernameTakenBody': 'Lütfen başka bir kullanıcı adı seçin.',
  'auth.checkUsername': 'Kullanıcı adı denetleniyor',
  'auth.checkUsernameBody': 'Lütfen kullanıcı adı doğrulamasının bitmesini bekleyin.',
  'auth.checkEmail': 'E-postanızı kontrol edin',
  'auth.checkEmailBody': 'Onay bağlantısını {{email}} adresine gönderdik',
  'auth.checkEmailSignInBody':
    'Onay bağlantısını {{email}} adresine gönderdik. Onayladıktan sonra hesabınıza giriş yapın.',
  'auth.enterEmail': 'E-posta girin',
  'auth.enterEmailBody': 'Lütfen e-posta adresinizi girin.',
  'auth.emailSent': 'E-posta gönderildi',
  'auth.emailSentBody': 'Parola sıfırlama bağlantısı için gelen kutunuza bakın.',

  'auth.emailConfirmed': 'E-posta onaylandı',
  'auth.accountReadySignIn':
    'Hesabınız hazır. Başlamak için e-posta ve parolanızla giriş yapın.',
  'auth.accountReadyOpenApp':
    'Hesabınız hazır. Giriş yapmak için telefonunuzdaki Immerse uygulamasını açın ya da aşağıdan web’de devam edin.',
  'auth.openingApp': 'Hesabınız hazır. Immerse açılıyor ve girişiniz yapılıyor…',
  'auth.openImmerse': 'Immerse’i aç',
  'auth.continueOnWeb': 'Bunun yerine web’de devam et',
  'auth.signInToImmerse': 'Immerse’e giriş yap',
  'auth.continueToImmerse': 'Immerse’e devam et',
  'auth.chooseNewPassword': 'Hesabınız için yeni bir parola seçin',
  'auth.newPasswordPlaceholder': 'Yeni parola',
  'auth.confirmNewPasswordPlaceholder': 'Yeni parolayı onaylayın',
  'auth.updatePassword': 'Parolayı güncelle',
  'auth.enterConfirmPassword': 'Lütfen yeni parolanızı girip onaylayın.',
  'auth.passwordTooShort': 'Parola en az 8 karakter olmalıdır.',
  'auth.passwordsDontMatch': 'Parolalar eşleşmiyor.',
  'auth.passwordUpdated': 'Parola güncellendi',
  'auth.passwordUpdatedBody': 'Artık yeni parolanızı kullanabilirsiniz.',
  'auth.resetFailed':
    'Parolanız güncellenemedi. Sıfırlama bağlantısının süresi dolmuş olabilir — lütfen yenisini isteyin.',

  'reminders.headerTitle': 'Günlük okumalar',
  'reminders.enable': 'Günlük okumaları aç',
  'reminders.openSettings': 'Ayarları aç',
  'reminders.source': 'Kaynak',
  'reminders.randomVerses': 'Rastgele ayetler',
  'reminders.readingPlan': 'Okuma planı',
  'reminders.chooseBook': 'Bir kitap seçin',
  'reminders.bookFinished': 'Bitti ✓ — sıradaki kitabınızı seçin',
  'reminders.sessionLength': 'Oturum süresi',
  'reminders.sessionCaption': 'Her oturum için geçerlidir — sabah {{dur}}, akşam {{dur}}.',
  'reminders.reminders': 'Hatırlatıcılar',
  'reminders.time': 'Saat',
  'reminders.morning': 'Sabah',
  'reminders.evening': 'Akşam',
  'reminders.yourStreak': 'Seriniz',
  'reminders.today': 'Bugün',
  'reminders.currentStreak': 'Güncel seri',
  'reminders.bestStreak': 'En iyi seri',
  'reminders.completedBooks': 'Tamamlanan kitaplar',
  'reminders.day_other': '{{count}} gün',
  'reminders.hour': '1 sa',
  'reminders.minutes': '{{count}} dk',
  'reminders.signInRequired': 'Giriş gerekli',
  'reminders.signInRequiredBody': 'Okuma planı izlemek ve ilerlemenizi görmek için hesap oluşturun.',
  'reminders.notNow': 'Şimdi değil',
  'reminders.enabledSub': 'Günlük okumanızı ana sayfada gösterir.',
  'reminders.disabledSub': 'Kapalı — günlük okumanız ana sayfada gizli.',
  'reminders.chooseNextToResume': 'Hatırlatıcıları sürdürmek için yukarıdan sıradaki kitabınızı seçin.',
  'reminders.chooseBookToEnable': 'Hatırlatıcıları açmak için yukarıdan bir kitap seçin.',
  'reminders.selectSourceToEnable': 'Hatırlatıcıları açmak için yukarıdan en az bir kaynak seçin.',
  'reminders.todayComplete': 'tamamlandı ✓',
  'reminders.todayPending': 'bekliyor',
  'reminders.todayMorningDone': 'sabah ✓',
  'reminders.todayMorningPending': 'sabah bekliyor',
  'reminders.todayEveningDone': 'akşam ✓',
  'reminders.todayEveningPending': 'akşam bekliyor',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': 'Daha derin okuyun. Daha çok bağ kurun.',
  'paywall.featureAiLabel': 'Yapay zekâ pasaj özetleri',
  'paywall.featureAiDesc': 'Herhangi bir pasaj için açıklama ve yorum isteyin',
  'paywall.featureVoicesLabel': 'Premium seslendirme sesleri',
  'paywall.featureVoicesDesc': 'Seçtiğiniz sesle doğal ve etkileyici anlatım',
  'paywall.featureImportLabel': 'Kendi kitaplarınızı aktarın',
  'paywall.featureImportDesc': 'Kütüphanenize EPUB, PDF ve DOCX dosyaları ekleyin',
  'paywall.subscribe': 'Abone ol — ayda {{price}}',
  'paywall.cancelNote': 'İstediğiniz zaman iptal · Aylık faturalandırma',
  'paywall.restore': 'Satın alımları geri yükle',
  'paywall.terms': 'Kullanım Koşulları',
  'paywall.privacy': 'Gizlilik Politikası',
  'paywall.notAvailable': 'Kullanılamıyor',
  'paywall.notAvailableBody': 'Uygulama içi satın alımlar bu sürümde henüz yapılandırılmadı. App Store yayınından sonra tekrar bakın.',
  'paywall.welcome': 'Pro’ya hoş geldiniz!',
  'paywall.welcomeBody': 'Aboneliğiniz artık etkin.',
  'paywall.purchaseFailed': 'Satın alma başarısız',
  'paywall.restoreFailed': 'Geri yükleme başarısız',

  'xrefs.title': 'Çapraz referanslar',
  'xrefs.empty': 'Henüz çapraz referans yok. Okuyucuda oluşturduklarınız burada görünecek.',
  'xrefs.signInTitle': 'Çapraz referanslarınızı görmek için giriş yapın',
  'xrefs.signInBody': 'Kütüphanenin her yerinden ilgili pasajları birbirine bağlayın.',
  'xrefs.searchSelected': 'Seçili çapraz referanslarda ara...',
  'xrefs.searchPlaceholder': 'Pasajlarda veya etiketlerde ara...',
  'xrefs.noMatch': 'Aramanızla eşleşen çapraz referans yok.',
  'xrefs.addLabel': 'Etiket ekle…',
  'xrefs.deleteConfirm': 'Çapraz referans silinsin mi?',
  'xrefs.deleteBody': 'Vurgulanan iki seçim korunacak.',

  'notes.title': 'Notlar',
  'notes.empty': 'Henüz not yok. Okuyucuda oluşturduğunuz notlar burada görünecek.',
  'notes.signInTitle': 'Notlarınızı görmek için giriş yapın',
  'notes.signInBody': 'Okurken pasajlara yorum ve düşüncelerinizi ekleyin.',
  'notes.searchPlaceholder': 'Notlarda ara...',
  'notes.searchSelected': 'Seçili notlarda ara...',
  'notes.byBook': 'Kitaba göre',
  'notes.byDate': 'Tarihe göre',
  'notes.writeNote': 'Notunuzu yazın…',
  'notes.noMatch': 'Aramanızla eşleşen not yok.',
  'notes.deleteConfirm': 'Not silinsin mi?',
  'notes.deleteBody': 'Vurgulanan seçim korunacak.',

  'tags.title': 'Derlemeler',
  'tags.empty': 'Henüz derleme yok. Okuyucuda oluşturduğunuz derlemeler burada görünecek.',
  'tags.signInTitle': 'Derlemelerinizi görmek için giriş yapın',
  'tags.signInBody': 'Kütüphanenin her yerinden alıntı derlemeleri oluşturun ve düzenleyin.',
  'tags.organize': 'Düzenle',
  'tags.searchPlaceholder': 'Derlemelerde ara...',
  'tags.searchSelected': 'Seçili derlemelerde ara...',
  'tags.noMatch': 'Aramanızla eşleşen derleme yok.',
  'tags.deleteConfirm': 'Derleme silinsin mi?',
  'tags.deleteBody': '“{{name}}” ve tüm seçimleri kaldırılacak.',

  'tags.renameTitle': 'Derlemeyi yeniden adlandır',
  'tags.setPrivate': 'Gizli yap',
  'tags.setPublic': 'Herkese açık yap',
  'tags.publicTag': 'Herkese açık derleme',
  'tags.removePassage': 'Derlemeden kaldır',
  'tags.removePassageConfirm': 'Bu pasaj derlemeden kaldırılsın mı?',
  'tags.indent': 'İçeri al',
  'tags.outdent': 'Dışarı al',
  'tags.organizeHint':
    'Sıralamak için tutamacı sürükleyin \u00b7 \u21e4 \u21e5 ile iç içe düzeyi değiştirin \u00b7 alıntıları sıralamak için bir derlemeye tıklayın.',
  'tags.searchTagsPassages': 'Derlemelerde ve pasajlarda ara…',
  'tags.exportSelected': 'Seçili derlemeleri dışa aktar',
  'tags.export': 'Dışa aktar',
  'tags.exporting': 'Dışa aktarılıyor…',
  'tags.exportInclude': 'Dahil et',
  'tags.exportNothingToInclude': 'Seçili derlemelerin hiçbirinde {{items}} yok',

  'panel.createAccount': 'Hesap oluştur',
  'panel.signInToSave': 'Derlemeleri, notları ve çapraz referansları kaydetmek için ücretsiz hesap oluşturun.',
  'panel.editSelection': 'Metin seçimini düzenle',

  'reader.xrefMode': 'Çapraz referans modu — pasaj seçmek için uzun basın',
  'reader.error': 'Okuyucu hatası',
  'reader.opening': 'Kitap açılıyor…',
  'reader.footnote': 'Dipnot',

  'reader.selectBook': 'Okumaya başlamak için bir kitap seçin',
  'reader.tableOfContents': 'İçindekiler',
  'reader.expandSection': 'Bölümü genişlet',
  'reader.collapseSection': 'Bölümü daralt',
  'reader.expand': 'Genişlet',
  'reader.collapse': 'Daralt',
  'reader.actionTag': 'Derleme',
  'reader.actionNote': 'Not',
  'reader.actionXref': 'Referans',
  'reader.actionAi': 'YZ',
  'reader.actionCopy': 'Kopyala',
  'reader.updateSelection': 'Seçimi güncelle',
  'reader.updating': 'Güncelleniyor…',
  'reader.pickAsXref': 'Çapraz referans olarak seç',
  'reader.editSelectionHint':
    'Bu açıklama için yeni metni vurgulayın, sonra seçin',
  'reader.savingXref': 'Çapraz referans kaydediliyor…',
  'reader.pickTargetHint': 'Bağlamak için metin seçin veya bir pasaja tıklayın',
  'reader.footnoteUnavailable': 'Dipnot metni web sürümünde bulunmuyor.',
  'reader.bookNotFound': 'Kitap bulunamadı',
  'reader.viewTags': 'Derlemeleri gör',
  'reader.viewNote': 'Notu gör',
  'reader.viewXrefs': 'Çapraz referansları gör',
  'reader.noQuotesFiled': 'Buraya henüz alıntı eklenmemiş.',

  'ai.summary': 'Yapay zekâ özeti',
  'ai.upgradeBlurb': 'Yapay zekâ özetlerini ve diğer Pro özelliklerini kullanmak için yalnızca 0,99 $ ile Immerse Pro’ya geçin.',
  'ai.upgradeBtn': 'Pro’ya geçin — ayda 0,99 $',
  'ai.thinking': 'Düşünüyor…',
  'ai.error': 'Yapay zekâ özeti alınamadı. Lütfen bağlantınızı kontrol edip tekrar deneyin.',
  'ai.copied': '✓ Kopyalandı',
  'ai.copyHint': 'Kopyalamak için uzun basın',

  'note.title': 'Not',
  'note.addTitle': 'Not ekle',
  'note.placeholder': 'Notunuzu buraya yazın…',
  'note.loading': 'Yükleniyor…',
  'note.emptyTitle': 'Boş not',
  'note.emptyBody': 'Kaydetmeden önce lütfen bir şeyler yazın.',
  'note.saveFailed': 'Not kaydedilemedi',
  'note.deleteTitle': 'Not silinsin mi?',
  'note.deleteBody': 'Bu, notu kaldırır. Bu pasajda başka açıklama yoksa seçim de kaldırılır.',
  'note.deleteFailed': 'Not silinemedi',
  'note.signInRequired': 'Giriş gerekli',
  'note.signInBody': 'Notlar hesabınıza kaydedilir. Lütfen giriş yapın veya hesap oluşturun.',

  'xref.title': 'Çapraz referans',
  'xref.yourSelection': 'SEÇİMİNİZ',
  'xref.pickSecond': 'İkinci pasajı seçin  →',
  'xref.noneFound': 'Çapraz referans bulunamadı.',

  'xref.findPassage': 'Bağlanacak bir pasaj bulun',
  'xref.searchPlaceholder': 'Herhangi bir pasajda ara…',
  'xref.save': 'Çapraz referansı kaydet',
  'xref.from': 'Kaynak',
  'xref.to': 'Hedef',
  'xref.linksTo': 'şuna bağlanır:',

  'banner.googlePlay': 'Google Play’den alın',
  'banner.appStore': 'App Store’dan indirin',
  'banner.install': 'Yükle',
  'banner.get': 'Al',

  'tagPanel.new': 'Yeni derleme',
  'tagPanel.create': 'Oluştur',
  'tagPanel.addTitle': 'Derlemeye ekle',
  'tagPanel.viewTitle': 'Derlemeler',
  'tagPanel.under': 'şunun altına:',
  'tagPanel.addSubTag': 'Alt derleme ekle',
  'tagPanel.emptyAdd': 'Henüz derleme yok — yukarıdan oluşturun',
  'tagPanel.emptyView': 'Bu seçimde derleme yok',

  'voice.title': 'Okuma sesi',
  'voice.onyx': 'Onyx — derin ve sıcak',
  'voice.cedar': 'Cedar — doğal ve dolgun',
  'voice.ash': 'Ash — net ve doğrudan',
  'voice.nova': 'Nova — parlak',
  'voice.shimmer': 'Shimmer — yumuşak',
  'voice.marin': 'Marin — doğal ve sakin',

  'reader.signInRequired': 'Giriş gerekli',
  'reader.signInBody': 'Okurken derlemelerinizi, notlarınızı ve çapraz referanslarınızı kaydetmek için hesap oluşturun.',
  'reader.notNow': 'Şimdi değil',
  'reader.signIn': 'Giriş yap',
  'reader.pdfNotFound': 'PDF dosyası bulunamadı.',
  'reader.contentLoadFailed': 'İçerik yüklenemedi',
  'reader.noBook': 'Kitap belirtilmedi',
  'reader.storageError': 'Depolama hatası',

  'discover.recent': 'SON EKLENENLER',
  'discover.trending': 'ÖNE ÇIKANLAR',
  'discover.searchPlaceholder': 'Derlemelerde ve kullanıcılarda ara…',
  'discover.searchSelected': 'Seçili derlemelerde ara…',
  'discover.import': 'İçe aktar',
  'discover.imported': 'İçe aktarıldı',
  'discover.import_other': '{{count}} içe aktarma',
  'discover.noneYet': 'Henüz paylaşılmış derleme yok',
  'discover.noResults': 'Sonuç yok',
  'discover.tryDifferent': 'Farklı bir arama terimi deneyin.',
  'discover.signInTitle': 'Keşfet’e erişmek için giriş yapın',
  'discover.signInBody': 'Diğer okurların tüm geleneklerde neler keşfettiğini görün.',
  'discover.anonymous': 'Anonim',
  'discover.beFirst': 'Derleme paylaşan ilk kişi olun.',
  'discover.ownTag': 'Bu sizin kendi derlemeniz',
  'discover.alreadyImported': 'Zaten içe aktarıldı',
  'discover.importFailed': 'İçe aktarma başarısız',
  'discover.exportFailed': 'Dışa aktarma başarısız',
  'discover.unknownError': 'Bilinmeyen hata',

  'usertags.autoImports': 'Bu kullanıcının herkese açık derlemelerini uygulamanıza otomatik aktarır',
  'usertags.noTags': 'Herkese açık derleme yok',
  'usertags.noTagsBody': 'Bu kullanıcı henüz hiç derleme paylaşmadı.',
  'usertags.follow': 'Takip et',
  'usertags.unfollow': 'Takibi bırak',
  'usertags.share': 'Paylaş',
  'usertags.error': 'Hata',
  'usertags.somethingWrong': 'Bir şeyler ters gitti',

  'onboarding.chooseLanguage': 'Dilinizi seçin',
  'onboarding.changeLaterSettings': 'Bunu daha sonra Ayarlar’dan değiştirebilirsiniz.',
  'onboarding.libraryDownloadHint': 'Kütüphaneyi {{language}} dilinde indirmek için Kütüphane ekranında “Kütüphane” yanındaki ⌄ simgesine dokunun.',
  'onboarding.continue': 'Devam',
  'onboarding.chooseTextSize': 'Yazı boyutunu seçin',
  'onboarding.fontPreviewQuote':
    '“Arayın, bulacaksınız; kapıyı çalın, size açılacaktır.”',
  'onboarding.getStarted': 'Başlayın',

  'onboarding.closeIntro': 'Tanıtımı kapat',
  'onboarding.goToStep': '{{number}}. adıma git',
  'onboarding.libraryTitle': 'Kütüphane',
  'onboarding.libraryCaption': 'Özenle derlenmiş, birçok geleneği kapsayan bir kütüphaneye göz atın. Okumaya başlamak için bir kitaba dokunun.',
  'onboarding.searchTitle': 'Her şeyi arayın',
  'onboarding.searchCaption': 'Tüm kitaplarda aynı anda arayın ve doğrudan pasaja gidin.',
  'onboarding.tagAsYouGoTitle': 'Okudukça derleyin',
  'onboarding.tagAsYouGoCaption': 'Arama sonuçlarından doğrudan bir pasajı derlemeye ekleyin.',
  'onboarding.buildTagsTitle': 'Derlemelerinizi oluşturun',
  'onboarding.buildTagsCaption': 'Kolayca hatırlamak için pasajları kendi derlemeleriniz altında toplayın.',
  'onboarding.selectActTitle': 'Seçin ve harekete geçin',
  'onboarding.selectActCaption': 'Herhangi bir metni vurgulamak, derlemeye eklemek, not almak veya çapraz referans vermek için seçin.',
  'onboarding.marginTitle': 'Kenar açıklamaları',
  'onboarding.marginCaption': 'Derlemeleriniz, notlarınız ve çapraz referanslarınız sayfa kenarında durur.',
  'onboarding.navigateTitle': 'Hızlıca gezinin',
  'onboarding.navigateCaption': 'Kitapta dolaşmak için içindekiler bölümünü açın.',
  'onboarding.yourTagsTitle': 'Derlemeleriniz',
  'onboarding.yourTagsCaption': 'Derlemeye eklediğiniz her pasajı derlemeye göre yeniden ziyaret edin.',
  'onboarding.xrefsTitle': 'Çapraz referanslar',
  'onboarding.xrefsCaption': 'İlgili pasajları kitaplar ve gelenekler arasında bağlayın.',
  'onboarding.shareTitle': 'Paylaşın ve yayınlayın',
  'onboarding.shareCaption': 'Bir alıntıyı paylaşın veya topluluk için bir derleme yayınlayın.',

  // ── Dışa aktarma paneli ───────────────────────────────────────────────────
  'export.shareTags_other': '{{count}} derlemeyi paylaş',
  'export.shareTagsGeneric': 'Derlemeleri paylaş',
  'export.preparing': 'Hazırlanıyor…',
  'export.notesOn': 'Her pasaj için yazdığınız notlar',
  'export.notesNone': 'Bu pasajlarda not yok',
  'export.xrefsOn': 'Her alıntının altındaki bağlı pasajlar',
  'export.xrefsNone': 'Bu pasajlarda çapraz referans yok',
  'export.docxTitle': 'Word belgesi (.docx)',
  'export.docxShort': 'Word (.docx)',
  'export.docxDesc': 'Derleme başlıkları ve alıntılanan pasajlar. Word, Pages veya Google Dokümanlar’da açılır.',
  'export.pdfTitle': 'PDF belgesi',
  'export.pdfDesc': 'Yazdırmak veya paylaşmak için biçimlendirilmiş belge.',
  'export.csvTitle': 'Hesap tablosu (.csv)',
  'export.csvDesc': 'Her pasaj için bir satır. Excel, Numbers veya Google E-Tablolar’da açılır.',
  'export.mdTitle': 'Markdown (.md)',
  'export.mdDesc': 'Obsidian, Notion veya herhangi bir düz metin aracı için.',
  'export.noPassagesTagged': '(bu derlemede pasaj yok)',
  'export.seeAlso': 'Ayrıca bakınız:',

  // ── Okuma planı ───────────────────────────────────────────────────────────
  'plan.chooseBook': 'Bir kitap seçin',
  'plan.searchBooks': 'Kitaplarda ara…',
  'plan.noBooksMatch': '“{{query}}” ile eşleşen kitap yok.',
  'plan.readingComplete': 'Okuma tamamlandı',
  'plan.morningSession': 'Sabah oturumu',
  'plan.eveningSession': 'Akşam oturumu',
  'plan.minutes': '{{count}} dk',
  'plan.streakDay': 'Seri günü {{count}} ✓',
  'plan.sessionsToday': 'Bugün {{required}} oturumdan {{done}} tanesi',
  'plan.youFinished': '{{title}} kitabını bitirdiniz',
  'plan.readOverDays_other': '{{count}} günde okundu',
  'plan.remindersPaused': 'hatırlatıcılar duraklatıldı',
  'plan.chooseNextBook': 'Sıradaki kitabınızı seçin',
  'completed.title': 'Tamamlanan kitaplar',
  'completed.empty': 'Okuma planınızda bitirdiğiniz kitaplar burada görünecek.',
  'completed.finishedOn': '{{date}} tarihinde bitirildi',
  'completed.day_other': '{{count}} gün',

  // ── Kütüphaneden geri kalanlar ────────────────────────────────────────────
  'library.selectPassageForXref': 'Çapraz referans için pasaj seçin',
  'library.findingRelated': 'İlgili pasajlar aranıyor…',
  'library.importFailedTitle': 'İçe aktarma başarısız',
  'library.couldNotImport': 'Dosya içe aktarılamadı.',
  'library.bookAdded': 'Kitap eklendi',
  'library.bookAddedBody': '“{{title}}” artık Kitaplarım’da.',
  'library.importErrorTitle': 'İçe aktarma hatası',
  'library.unexpectedError': 'Beklenmeyen bir hata oluştu.',
  'nav.browsingAsGuest': 'Misafir olarak geziliyor',
  'reader.selectBookToBegin': 'Okumaya başlamak için bir kitap seçin',
  'tags.exportFailed': 'Dışa aktarma başarısız',
  'tags.couldNotExport': 'Derlemeler dışa aktarılamadı.',
  'tags.couldNotRemoveSelection': 'Seçim kaldırılamadı',
  'tags.reorderHint': 'Sıralamak için tutamacı sürükleyin · ⇤ ⇥ ile iç içe düzeyi değiştirin · alıntıları sıralamak için bir derlemeye dokunun.',
  'tags.swipeHint': 'Bir derlemeyi herkese açık ya da gizli yapmak için sağa kaydırın.',
  'discover.publishHint': 'Burada yayınlamak için Derlemeler ekranında bir derlemeyi sağa kaydırın.',
  'reminders.notificationsOff':
    'Immerse için bildirimler kapalı olduğundan hatırlatıcılar iletilemiyor. '
    + 'Cihaz ayarlarınızdan bildirimleri açın.',
  'plan.continueJourney': 'Okuma yolculuğunuza devam edin',
  'plan.yourBook': 'Kitabınız',
  'reader.notesInParagraph_other': 'Bu paragrafta {{count}} not',
  'plan.awaitsMorning': '{{book}} sizi bekliyor — sabah okuması',
  'plan.awaitsEvening': '{{book}} sizi bekliyor — akşam okuması',
  'reminders.dailyReadingFrom': 'Günlük okuma · {{source}}',
  'library.tapToExpandHint': 'Genişletmek için dokunun · Okuyucuda açmak için basılı tutun',
  'library.deleteBookImportedBody': 'Bu kitap ve tüm açıklamaları kalıcı olarak kaldırılacak.',
  'library.deleteBookBundledBody':
    'Bu kitap ve tüm açıklamaları kaldırılacak. Kütüphane bir sonraki yenilendiğinde geri gelecek.',
  'library.deleteCategoryConfirm': '“{{name}}” silinsin mi?',
  'library.deleteCategoryBody_other': 'Bu ayrıca {{count}} kitabı ve tüm açıklamalarını kaldırır.',
  'library.deleteCategoryEmptyBody': 'Bu kategori kalıcı olarak kaldırılacak.',

  'auth.passwordTooShortTitle': 'Parola çok kısa',
  'auth.passwordsMustMatch': 'Lütfen iki parolanın da aynı olduğundan emin olun.',
  'auth.usernamePlain': 'Kullanıcı adı',
  'auth.fullNameOptional': 'Ad soyad (isteğe bağlı)',
  'auth.emailPlain': 'E-posta',
  'auth.passwordPlain': 'Parola',
  'auth.emailAddressPlain': 'E-posta adresi',

  // ── Tanıtım turu (mobil) ──────────────────────────────────────────────────
  'onboarding.skip': 'Atla',
  'onboarding.tour.libraryMain.label': 'Kütüphane ekranı',
  'onboarding.tour.libraryMain.caption':
    'Kütüphane, tüm büyük geleneklerden 400’den fazla kutsal metin barındırır. Kitaplarını görmek için bir geleneğe dokunun.',
  'onboarding.tour.libraryExpanded.label': 'Genişletilmiş kütüphane',
  'onboarding.tour.libraryExpanded.caption':
    'Her gelenek açılarak yazarları ve derlemeleri gösterir. Okuyucuda açmak için herhangi bir başlığa dokunun.',
  'onboarding.tour.librarySearch.label': 'Kütüphane araması',
  'onboarding.tour.librarySearch.caption':
    '400’den fazla metinde aynı anda arayın. Bir sonuca dokunarak genişletin, doğrudan okuyucuda açmak için uzun basın.',
  'onboarding.tour.searchQuickTag.label': 'Arama sonucunda hızlı derleme',
  'onboarding.tour.searchQuickTag.caption':
    'Bir ya da birçok arama sonucunu seçip tek dokunuşla bir derlemeye ekleyin. Tüm kütüphaneden tematik bir derleme kurmanın hızlı yolu.',
  'onboarding.tour.home.label': 'Ana sayfa',
  'onboarding.tour.home.caption':
    'Ana sayfanız kaç derleme, not ve çapraz referans oluşturduğunuzu ve son okuduğunuz kitapları gösterir. Okumaya devam etmek için bir başlığa dokunun.',
  'onboarding.tour.homePlan.label': 'Ana sayfada okuma planı',
  'onboarding.tour.homePlan.caption':
    'Günlük okuma alışkanlığı edinin: seçtiğiniz kitapta ve seçtiğiniz sürede bir okuma planı izleyin ya da belirlediğiniz geleneklerden rastgele ayetler alın — günlük hatırlatıcılar ve okuduğunuz her günle büyüyen bir seriyle.',
  'onboarding.tour.settingsDaily.label': 'Günlük okuma ayarları',
  'onboarding.tour.settingsDaily.caption':
    'Ayarlar’da, rastgele ayetler için hangi geleneklerden yararlanılacağını ve nazik bir hatırlatma istediğiniz saatleri belirleyin — ya da her gün tek bir kitapta ilerlemek için okuma planına geçin.',
  'onboarding.tour.readerSelect.label': 'Okuyucuda metin seçimi',
  'onboarding.tour.readerSelect.caption':
    'Seçmek için herhangi bir pasaja uzun basın. Bir derlemeye eklemek, not almak, çapraz referans vermek veya yapay zekâ özeti almak için ekranın altındaki simgeleri kullanın.',
  'onboarding.tour.readerNote.label': 'Okuyucuda not görüntüleme',
  'onboarding.tour.readerNote.caption':
    'Notlar seçtiğiniz metnin tam olarak kendisine iliştirilir. Kenardaki altın işaret, onları istediğiniz zaman bulup yeniden açmanızı sağlar.',
  'onboarding.tour.readerXref.label': 'Okuyucuda çapraz referans',
  'onboarding.tour.readerXref.caption':
    'Çapraz referanslar farklı kitap ve geleneklerdeki pasajları birbirine bağlar. Bağlı bir alıntıya uzun basarak okuyucuda ona atlayın.',
  'onboarding.tour.readerAi.label': 'Okuyucuda yapay zekâ özeti',
  'onboarding.tour.readerAi.caption':
    'Bir pasajı seçtikten sonra, anında yapay zekâ özeti için parıltı simgesine dokunun — yoğun ya da yabancı metinlerde özellikle yararlıdır.',
  'onboarding.tour.readerListen.label': 'Okuyucuda dinleme modu',
  'onboarding.tour.readerListen.caption':
    'Herhangi bir kitabı sesli dinlemek için kulaklık düğmesine dokunun; okuyucu çalarken her pasajı vurgular. Doğal sesler arasından seçim yapmak için kulaklık düğmesine basılı tutun.',
  'onboarding.tour.tags.label': 'Derlemeler ekranı',
  'onboarding.tour.tags.caption':
    'Derlemeler ekranı, derlemelerinize eklediğiniz pasajları temaya göre toplar. Alıntılanan pasajları tam künyeleriyle görmek için bir derleme adına dokunun.',
  'onboarding.tour.xrefs.label': 'Çapraz referanslar ekranı',
  'onboarding.tour.xrefs.caption':
    'Çapraz referanslar ekranı bağladığınız tüm pasajları yan yana gösterir. O pasaja okuyucuda gitmek için iki taraftan birine uzun basın.',
  'onboarding.tour.discover.label': 'Keşfet ekranı',
  'onboarding.tour.discover.caption':
    'Keşfet ekranında diğer okurların paylaştığı derlemeleri bulun. Pasajlarına göz atmak için bir derlemeye dokunun, sonra kendi kütüphanenize aktarın.',
  'onboarding.tour.tagShare.label': 'Derleme paylaşma paneli',
  'onboarding.tour.tagShare.caption':
    'Herhangi bir derlemeyi Word belgesi, PDF, hesap tablosu, Markdown ve daha fazlası olarak dışa aktarın — notlarınız ve çapraz referanslarınız dahil.',

  // ── Appearance (reader typography) ───────────────────────────────────────
  'appearance.title': 'Görünüm',
  'appearance.navHint': 'Yazı tipi, aralık, renk',
  'appearance.reading': 'Okuma',
  'appearance.preview': 'Önizleme',
  'appearance.previewText': 'Okumak, yüzyılları aşan sessiz bir sohbettir.',
  'appearance.typeface': 'Yazı tipi',
  'appearance.typefaceSystem': 'Sistem',
  'appearance.typefaceLiterataBlurb': 'Uzun okuma için tasarlandı. Boyuta uyum sağlar.',
  'appearance.typefaceCharisBlurb': 'Charter’ın devamı. Küçük boyutta sağlam.',
  'appearance.typefaceGaramondBlurb': 'Klasik eski stil. Sayfada daha hafif.',
  'appearance.typefaceSystemBlurb': 'Bu cihazın sağladığı yazı tipi.',
  'appearance.textSize': 'Metin boyutu',
  'appearance.lineSpacing': 'Satır aralığı',
  'appearance.lineSpacingTight': 'Dar',
  'appearance.lineSpacingNormal': 'Normal',
  'appearance.lineSpacingRelaxed': 'Geniş',
  'appearance.lineSpacingLoose': 'Çok geniş',
  'appearance.margins': 'Kenar boşlukları',
  'appearance.marginsNarrow': 'Dar',
  'appearance.marginsNormal': 'Normal',
  'appearance.marginsWide': 'Geniş',
  'appearance.justify': 'Metni iki yana yasla',
  'appearance.justifyHint': 'Her iki kenarı hizalar, heceleme ile.',
  'appearance.paragraphStyle': 'Paragraflar',
  'appearance.paragraphSpaced': 'Aralıklı',
  'appearance.paragraphIndented': 'Girintili',
  'appearance.paragraphHint': 'Girintili, geleneksel kitap düzenidir.',
  'appearance.theme': 'Sayfa rengi',
  'appearance.themeLight': 'Açık',
  'appearance.themeSepia': 'Sepya',
  'appearance.themeQuiet': 'Yumuşak',
  'appearance.themeDark': 'Koyu',
  'appearance.themeNight': 'Gece',
  'appearance.themeSystem': 'Uygulamayla aynı',
  'appearance.fineTuning': 'İnce ayar',
  'appearance.characterSpacing': 'Karakter aralığı',
  'appearance.wordSpacing': 'Kelime aralığı',
  'appearance.textWeight': 'Metin kalınlığı',
  'appearance.paragraphNumbers': 'Paragraf numaraları',
  'appearance.paragraphNumbersHint': 'Kenar boşluğunda referans numaralarını gösterir.',
  'appearance.appTheme': 'Uygulama teması',
  'appearance.appThemeHint': 'Okuyucu dışında geçerlidir.',
  'appearance.reset': 'Varsayılanlara dön',
};
