import type { LocaleTable } from './keys';

/**
 * Simplified Chinese UI strings.
 *
 * Partial by design: any key omitted here falls back to English rather than
 * rendering a raw key.
 *
 * Every plural group carries only `_other`. Chinese has a single CLDR category,
 * so a `_one` variant would be a form the language never asks for — one book
 * and five books are written the same way, with the measure word doing the work.
 *
 * Terminology fixed once, here: a tag/compilation is 汇编 (renamed 2026-08-17
 * from 标签; also matches the existing Bahá'í-library category name for
 * "Compilations"), a note 笔记, a cross-reference 交叉引用 (shortened to 引用
 * in the navigation), and a passage 段落.
 */
export const zh: LocaleTable = {
  'common.cancel': '取消',
  'common.remove': '移除',
  'common.removing': '正在移除…',
  'common.save': '保存',
  'common.done': '完成',
  'common.ok': '好',
  'common.continue': '继续',
  'common.tryAgain': '请重试。',
  'common.delete': '删除',
  'common.clear': '清除',
  'common.signInCreate': '登录 / 注册',
  'common.book_other': '{{count}} 本书',
  'common.saving': '正在保存…',
  'common.loading': '正在加载…',
  'common.copy': '复制',
  'common.retry': '重试',
  'common.back': '返回',
  'common.next': '下一步',
  'common.searching': '正在搜索…',
  'common.noResults': '未找到结果。',
  'common.dismiss': '关闭',
  'common.options': '选项',
  'common.collapseLibrary': '收起书库',
  'common.expandLibrary': '展开书库',
  'common.minutesAgo': '{{count}} 分钟前',
  'common.hoursAgo': '{{count}} 小时前',
  'common.daysAgo': '{{count}} 天前',
  'common.highlight_other': '{{count}} 处高亮',
  'common.edit': '编辑',
  'common.justNow': '刚刚',
  'common.opening': '正在打开…',
  'common.or': '或',
  'common.pleaseWait': '请稍候…',
  'common.somethingWrong': '出错了。',
  'common.rename': '重命名',
  'common.dragToReorder': '拖动以调整顺序',
  'common.openInReader': '在阅读器中打开',
  'common.otherTradition': '其他',

  'nav.home': '主页',
  'nav.library': '书库',
  'nav.tags': '汇编',
  'nav.notes': '笔记',
  'nav.xrefs': '引用',
  'nav.discover': '发现',
  'nav.settings': '设置',
  'nav.guest': '访客',
  'nav.reader': '阅读器',
  'nav.signOut': '退出登录',

  'library.title': '书库',
  'library.languageSheetTitle': '书库语言',
  'library.availableToDownload': '可供下载',
  'library.downloading': '正在下载 {{percent}}%',
  'library.verifying': '正在校验…',
  'library.importing': '正在导入…',
  'library.cleaning': '正在收尾…',
  'library.downloadFailed': '下载失败',
  'library.updateAvailable': '有可用更新',
  'library.updateLanguageA11y': '更新{{language}}',
  'library.changeLanguageA11y': '{{title}}，{{language}}。更改书库语言',

  'library.myBooks': '我的书',
  'library.searchAll': '搜索全部书籍…',
  'library.searchSelected_other': '在所选的 {{count}} 本书中搜索…',
  'library.noResultsFor': '未找到“{{query}}”的结果。',
  'library.result_other': '{{count}} 条结果',
  'library.relatedPassages': '相关段落',
  'library.relatedOn': '于',
  'library.relatedPrefix': '相关',
  'library.booksAndSections': '书籍与章节',
  'library.tapToOpenHint': '点按打开',
  'library.importTitle': '导入书籍（TXT、EPUB、DOCX、RTF、PDF）',
  'library.importProFeature':
    '导入书籍是 Pro 功能。请在设置中升级到 Pro，即可导入自己的书籍。',
  'library.importFailed': '导入失败。',
  'library.importSucceeded': '“{{title}}”已成功导入。',
  'library.noImportedBooks':
    '尚未导入任何书籍。点击搜索栏旁边的按钮即可导入。',
  'library.deleteBookConfirm': '删除“{{title}}”？',
  'library.tagAction': '汇编',

  'settings.language': '语言',
  'settings.appLanguage': '应用语言',
  'settings.appLanguageHint': '按钮与菜单的语言，与你阅读哪个书库无关。',
  'settings.restartForDirection': '重启以完成切换',
  'settings.restartForDirectionBody':
    '{{language}} 从右向左书写。请关闭并重新打开 Immerse，以翻转界面方向。',
  'settings.restartForDirectionBodyLtr':
    '请关闭并重新打开 Immerse，以恢复从左向右的界面方向。',
  'settings.downloadedLibraries': '已下载的书库',
  'settings.downloadedLibrariesHint': '可在书库页面之间切换。',
  'settings.includedWithApp': '随应用附带',
  'settings.removeLanguageTitle': '移除 {{language}}？',
  'settings.removeLanguageBody':
    '这些书籍将从本设备删除。你可以随时重新下载。',
  'settings.removeLanguageKeepsAnnotations':
    '你在这些书中的{{annotations}}会保留；重新下载 {{language}} 后会再次出现。',
  'settings.removeFailed': '无法移除',
  'settings.account': '账户',
  'settings.fullName': '姓名',
  'settings.edit': '编辑',
  'settings.username': '用户名',
  'settings.plan': '方案',
  'settings.fontSize': '字号',
  'settings.fontPreview': '这是 {{size}} 字号的预览文本。此设置会同步到你的所有设备。',
  'settings.dailyReadings': '通知',
  'settings.randomVersesAndPlan': '随机经文与阅读计划',
  'settings.readingMorningEvening': '每天早晚各一段阅读',
  'settings.appearance': '外观',
  'settings.appearanceLight': '浅色',
  'settings.appearanceDark': '深色',
  'settings.appearanceSystem': '跟随系统',
  'settings.upgrade': '升级',
  'settings.upgradeCta': '升级到 PRO — 每月 $0.99',
  'settings.upgradeBlurb':
    '解锁 AI 摘要、优质朗读语音，以及导入自己的书籍。每月 $0.99。',
  'settings.purchases': '购买',
  'settings.restorePurchase': '恢复购买',
  'settings.restorePurchaseHint': '恢复您已付费购买的 Pro 权限——无论是通过 App Store、Google Play 还是网页购买。',
  'settings.about': '关于',
  'settings.version': '版本',
  'settings.privacyPolicy': '隐私政策',
  'settings.viewExternal': '查看 ↗',
  'settings.termsOfService': '服务条款',
  'settings.introTour': '功能导览',
  'settings.fullFeatureVideo': '完整功能视频',
  'settings.replayOnboarding': '重看引导截图',
  'settings.view': '查看',
  'settings.watchFeatureVideo': '观看完整功能视频',
  'settings.accountActions': '账户操作',
  'settings.legal': '法律信息',
  'settings.contactSupport': '联系支持',
  'settings.communityGuidelines': '社区准则',
  'settings.signOut': '退出登录',
  'settings.deleteAccount': '删除账户',
  'settings.deleting': '正在删除…',
  'settings.error': '错误',
  'settings.deleteAccountConfirm':
    '此操作将永久删除你的账户，以及全部注释、汇编、笔记和阅读进度，且无法撤销。',
  'settings.areYouSure': '确定吗？',
  'settings.deleteAccountFinal':
    '你的账户和全部数据将立即删除，且无法恢复。',
  'settings.deletePermanently': '是的，永久删除',
  'settings.restoreFailed': '恢复失败',
  'settings.proRestored': 'Pro 已恢复！',
  'settings.proRestoredBody': '你的订阅现已生效。',
  'settings.noSubscription': '未找到订阅',
  'settings.noSubscriptionBody':
    '我们没有找到与此账户关联的有效订阅。',
  'settings.planGuest': '访客',
  'settings.planStandard': '标准版',
  'settings.planPro': 'Pro',
  'settings.planTrial': 'Pro（试用）',

  'settings.welcomeToPro': '欢迎使用 Pro！',
  'settings.manage': '管理',
  'settings.subscribeToPro': '订阅 Pro',

  'home.tags': '汇编',
  'home.notes': '笔记',
  'home.xrefs': '引用',
  'home.readingPlan': '阅读计划',
  'home.dailyVerses': '每日经文',
  'home.dayStreak_other': '连续 {{count}} 天',
  'home.dailyReading': '每日阅读',
  'home.dailyReadingsTitle': '每日阅读',
  'home.tapToSetUp': '点按以设置',
  'home.tapToReadVerse': '点按以阅读一段经文',
  'home.tapToContinue': '点按以继续',
  'home.planFinished': '已读完 — 请选择下一本书',
  'home.recentlyViewed': '最近阅读',
  'home.removeFromRecent': '从最近阅读中移除',
  'home.removeFromRecentBody': '移除“{{title}}”并将阅读进度重置为 0%？',
  'home.signInCreate': '登录 / 注册',
  'home.startReadingHint': '开始阅读后，最近读过的书会显示在这里。',
  'home.viewLibrary': '查看书库',

  'home.signInBlurb': '登录后即可在所有设备上查看最近阅读的书籍、注释等内容。',

  'auth.tagline': '跨信仰电子阅读与研究',
  'auth.usernamePlaceholder': '用户名 ID *',
  'auth.fullNamePlaceholder': '姓名',
  'auth.emailPlaceholder': '电子邮箱 *',
  'auth.passwordPlaceholder': '密码 *',
  'auth.emailAddressPlaceholder': '电子邮箱地址 *',
  'auth.signIn': '登录',
  'auth.signUp': '注册',
  'auth.createAccount': '创建账户',
  'auth.forgotPassword': '忘记密码？',
  'auth.browseWithout': '不创建账户，直接浏览',
  'auth.guestSubtext': '可以阅读和搜索书籍，但不会保存进度和笔记',
  'auth.resetPassword': '重置密码',
  'auth.sendResetLink': '发送重置链接',
  'auth.createPasswordPlaceholder': '设置密码 *',
  'auth.backToSignIn': '返回登录',
  'auth.forgotBlurb':
    '请输入你的电子邮箱地址，我们会发送一个重置密码的链接。',
  'auth.usernameAvailable': '✓ 可用',
  'auth.usernameTakenShort': '✗ 已被占用',
  'auth.usernameHint': '3–20 个字符',
  'auth.usernameAlreadyTaken': '该用户名已被占用。',
  'auth.resetLinkSent': '我们已将密码重置链接发送至 {{email}}',
  'auth.error': '错误',
  'auth.missingFields': '信息不完整',
  'auth.missingFieldsBody': '请输入电子邮箱和密码。',
  'auth.invalidUsername': '用户名无效',
  'auth.invalidUsernameBody': '用户名须为 3–20 个字符，只能包含字母、数字和下划线。',
  'auth.usernameTaken': '用户名已被占用',
  'auth.usernameTakenBody': '请换一个用户名。',
  'auth.checkUsername': '正在检查用户名',
  'auth.checkUsernameBody': '请等待用户名校验完成。',
  'auth.checkEmail': '请查收邮件',
  'auth.checkEmailBody': '我们已将确认链接发送至 {{email}}',
  'auth.checkEmailSignInBody':
    '我们已将确认链接发送至 {{email}}。确认后即可登录你的账户。',
  'auth.enterEmail': '请输入邮箱',
  'auth.enterEmailBody': '请输入你的电子邮箱地址。',
  'auth.emailSent': '邮件已发送',
  'auth.emailSentBody': '请在收件箱中查看密码重置链接。',

  'auth.emailConfirmed': '邮箱已确认',
  'auth.accountReadySignIn':
    '你的账户已就绪。请使用电子邮箱和密码登录以开始使用。',
  'auth.accountReadyOpenApp':
    '你的账户已就绪。请在手机上打开 Immerse 应用登录，或在下方继续使用网页版。',
  'auth.openingApp': '你的账户已就绪。正在打开 Immerse 并为你登录…',
  'auth.openImmerse': '打开 Immerse',
  'auth.continueOnWeb': '改为在网页上继续',
  'auth.signInToImmerse': '登录 Immerse',
  'auth.continueToImmerse': '前往 Immerse',
  'auth.chooseNewPassword': '为你的账户设置一个新密码',
  'auth.newPasswordPlaceholder': '新密码',
  'auth.confirmNewPasswordPlaceholder': '确认新密码',
  'auth.updatePassword': '更新密码',
  'auth.enterConfirmPassword': '请输入并确认你的新密码。',
  'auth.passwordTooShort': '密码至少需要 8 个字符。',
  'auth.passwordsDontMatch': '两次输入的密码不一致。',
  'auth.passwordUpdated': '密码已更新',
  'auth.passwordUpdatedBody': '现在可以使用新密码了。',
  'auth.resetFailed':
    '无法更新你的密码。重置链接可能已过期，请重新申请。',

  'reminders.headerTitle': '每日阅读',
  'reminders.enable': '开启每日阅读',
  'reminders.openSettings': '打开设置',
  'reminders.source': '来源',
  'reminders.randomVerses': '随机经文',
  'reminders.readingPlan': '阅读计划',
  'reminders.chooseBook': '选择一本书',
  'reminders.bookFinished': '已读完 ✓ — 请选择下一本书',
  'reminders.sessionLength': '每次时长',
  'reminders.sessionCaption': '适用于每一次阅读 — 早上 {{dur}}，晚上 {{dur}}。',
  'reminders.reminders': '提醒',
  'reminders.time': '时间',
  'reminders.morning': '早上',
  'reminders.evening': '晚上',
  'reminders.yourStreak': '你的连续天数',
  'reminders.today': '今天',
  'reminders.currentStreak': '当前连续天数',
  'reminders.bestStreak': '最佳连续天数',
  'reminders.completedBooks': '已读完的书',
  'reminders.day_other': '{{count}} 天',
  'reminders.hour': '1 小时',
  'reminders.minutes': '{{count}} 分钟',
  'reminders.signInRequired': '需要登录',
  'reminders.signInRequiredBody': '创建账户即可跟随阅读计划并记录你的进度。',
  'reminders.notNow': '暂不',
  'reminders.enabledSub': '在主页显示你今天的阅读。',
  'reminders.disabledSub': '已关闭 — 今天的阅读不会显示在主页。',
  'reminders.chooseNextToResume': '请在上方选择下一本书，以恢复提醒。',
  'reminders.chooseBookToEnable': '请在上方选择一本书，以开启提醒。',
  'reminders.selectSourceToEnable': '请在上方至少选择一个来源，以开启提醒。',
  'reminders.todayComplete': '已完成 ✓',
  'reminders.todayPending': '待完成',
  'reminders.todayMorningDone': '早上 ✓',
  'reminders.todayMorningPending': '早上待完成',
  'reminders.todayEveningDone': '晚上 ✓',
  'reminders.todayEveningPending': '晚上待完成',

  'paywall.heading': 'Immerse Pro',
  'paywall.subheading': '读得更深，联得更广。',
  'paywall.featureAiLabel': 'AI 段落摘要',
  'paywall.featureAiDesc': '可就任何段落索取解释与评注',
  'paywall.featureVoicesLabel': '优质朗读语音',
  'paywall.featureVoicesDesc': '自然、富有表现力的朗读，语音由你挑选',
  'paywall.featureImportLabel': '导入自己的书籍',
  'paywall.featureImportDesc': '将 EPUB、PDF 和 DOCX 文件加入你的书库',
  'paywall.subscribe': '订阅 — 每月 {{price}}',
  'paywall.cancelNote': '可随时取消 · 按月计费',
  'paywall.restore': '恢复购买',
  'paywall.terms': '服务条款',
  'paywall.privacy': '隐私政策',
  'paywall.notAvailable': '暂不可用',
  'paywall.notAvailableBody': '此版本尚未配置应用内购买。请在 App Store 上架后再来查看。',
  'paywall.welcome': '欢迎使用 Pro！',
  'paywall.welcomeBody': '你的订阅现已生效。',
  'paywall.purchaseFailed': '购买失败',
  'paywall.restoreFailed': '恢复失败',

  'xrefs.title': '交叉引用',
  'xrefs.empty': '还没有交叉引用。你在阅读器中创建的交叉引用会显示在这里。',
  'xrefs.signInTitle': '登录以查看你的交叉引用',
  'xrefs.signInBody': '把整个书库中相关的段落连接起来。',
  'xrefs.searchSelected': '在所选交叉引用中搜索...',
  'xrefs.searchPlaceholder': '搜索段落或标注...',
  'xrefs.noMatch': '没有符合搜索条件的交叉引用。',
  'xrefs.addLabel': '添加标注…',
  'xrefs.deleteConfirm': '删除交叉引用？',
  'xrefs.deleteBody': '两处高亮选段都会保留。',

  'notes.title': '笔记',
  'notes.empty': '还没有笔记。你在阅读器中创建的笔记会显示在这里。',
  'notes.signInTitle': '登录以查看你的笔记',
  'notes.signInBody': '边读边为段落写下评注与感想。',
  'notes.searchPlaceholder': '搜索笔记...',
  'notes.searchSelected': '在所选笔记中搜索...',
  'notes.byBook': '按书籍',
  'notes.byDate': '按日期',
  'notes.writeNote': '写下你的笔记…',
  'notes.noMatch': '没有符合搜索条件的笔记。',
  'notes.deleteConfirm': '删除笔记？',
  'notes.deleteBody': '高亮的选段会保留。',

  'tags.title': '汇编',
  'tags.empty': '还没有汇编。你在阅读器中创建的汇编会显示在这里。',
  'tags.signInTitle': '登录以查看你的汇编',
  'tags.signInBody': '从整个书库中建立并整理你的引文集。',
  'tags.organize': '整理',
  'tags.searchPlaceholder': '搜索汇编...',
  'tags.searchSelected': '在所选汇编中搜索...',
  'tags.noMatch': '没有符合搜索条件的汇编。',
  'tags.deleteConfirm': '删除汇编？',
  'tags.deleteBody': '“{{name}}”及其全部选段都将被移除。',

  'tags.renameTitle': '重命名汇编',
  'tags.setPrivate': '设为私密',
  'tags.setPublic': '设为公开',
  'tags.publicTag': '公开汇编',
  'tags.removePassage': '从汇编中移除',
  'tags.removePassageConfirm': '将此段落从汇编中移除？',
  'tags.indent': '增加缩进',
  'tags.outdent': '减少缩进',
  'tags.organizeHint':
    '拖动手柄可调整顺序 · ⇤ ⇥ 可更改层级 · 点击汇编可调整其引文顺序。',
  'tags.searchTagsPassages': '搜索汇编和段落…',
  'tags.exportSelected': '导出所选汇编',
  'xrefs.exportSelected': '导出所选交叉引用',
  'tags.export': '导出',
  'tags.exporting': '正在导出…',
  'tags.exportInclude': '包含',
  'tags.exportNothingToInclude': '所选汇编中都没有{{items}}',

  'panel.createAccount': '创建账户',
  'panel.signInToSave': '创建免费账户即可保存汇编、笔记和交叉引用。',
  'panel.editSelection': '编辑所选文本',

  'reader.xrefMode': '交叉引用模式 — 长按以选取段落',
  'reader.error': '阅读器错误',
  'reader.opening': '正在打开书籍…',
  'reader.footnote': '脚注',

  'reader.selectBook': '选择一本书开始阅读',
  'reader.tableOfContents': '目录',
  'reader.tocButtonHint': '跳到本书的某一节',
  'reader.expandSection': '展开此节',
  'reader.collapseSection': '收起此节',
  'reader.expand': '展开',
  'reader.collapse': '收起',
  'reader.actionTag': '汇编',
  'reader.actionNote': '笔记',
  'reader.actionXref': '引用',
  'reader.actionAi': 'AI',
  'reader.actionCopy': '复制',
  'reader.updateSelection': '更新选区',
  'reader.updating': '正在更新…',
  'reader.pickAsXref': '选为交叉引用',
  'reader.editSelectionHint':
    '为此注释选取新的文本，然后做出选择',
  'reader.savingXref': '正在保存交叉引用…',
  'reader.pickTargetHint': '选择文本或点击某个段落以建立连接',
  'reader.footnoteUnavailable': '网页版暂不提供脚注文本。',
  'reader.bookNotFound': '未找到该书',
  'reader.viewTags': '查看汇编',
  'reader.viewNote': '查看笔记',
  'reader.viewXrefs': '查看交叉引用',
  'reader.noQuotesFiled': '这里还没有归入任何引文。',

  'ai.summary': 'AI 摘要',
  'ai.upgradeBlurb': '只需 $0.99 升级到 Immerse Pro，即可使用 AI 摘要及其他 Pro 功能。',
  'ai.upgradeBtn': '升级到 Pro — 每月 $0.99',
  'ai.thinking': '正在思考…',
  'ai.error': '无法获取 AI 摘要。请检查网络连接后重试。',
  'ai.copied': '✓ 已复制',
  'ai.copyHint': '长按以复制',

  'note.title': '笔记',
  'note.addTitle': '添加笔记',
  'note.placeholder': '在这里写下你的笔记…',
  'note.loading': '正在加载…',
  'note.emptyTitle': '笔记为空',
  'note.emptyBody': '保存前请先写点什么。',
  'note.saveFailed': '无法保存笔记',
  'note.deleteTitle': '删除笔记？',
  'note.deleteBody': '这会删除该笔记。如果此段落上没有其他注释，选区也会一并移除。',
  'note.deleteFailed': '无法删除笔记',
  'note.signInRequired': '需要登录',
  'note.signInBody': '笔记保存在你的账户中。请登录或创建账户。',

  'xref.title': '交叉引用',
  'xref.yourSelection': '你的选段',
  'xref.pickSecond': '选取第二个段落  →',
  'xref.noneFound': '未找到交叉引用。',

  'xref.findPassage': '查找要连接的段落',
  'xref.searchPlaceholder': '搜索任意段落…',
  'xref.save': '保存交叉引用',
  'xref.from': '从',
  'xref.to': '到',
  'xref.linksTo': '连接到',

  'xref.suggestMatch': '推荐匹配段落',
  'xref.suggesting': '正在查找相关段落…',
  'xref.suggestError': '暂时无法获取推荐',
  'xref.noMatches': '未找到匹配项。请自行选择。',
  'xref.looseMatch': '大致匹配',
  'xref.useThisPassage': '使用此段落',
  'xref.inCompilation': '已在你的汇编“{{name}}”中',
  'xref.youNotedThis': '你已为此段落添加笔记',

  'banner.googlePlay': '在 Google Play 上获取',
  'banner.appStore': '在 App Store 下载',
  'banner.install': '安装',
  'banner.get': '获取',

  'tagPanel.new': '新建汇编',
  'tagPanel.createWithin': '在“{{parent}}”中创建汇编',
  'tagPanel.addTitle': '加入汇编',
  'tagPanel.viewTitle': '汇编',
  'tagPanel.addSubTag': '添加子汇编',
  'tagPanel.emptyAdd': '还没有汇编 — 请在上方创建',
  'tagPanel.emptyView': '此选段上没有汇编',

  'voice.title': '朗读语音',
  'voice.onyx': 'Onyx — 低沉温厚',
  'voice.cedar': 'Cedar — 自然饱满',
  'voice.ash': 'Ash — 清晰直接',
  'voice.nova': 'Nova — 明亮',
  'voice.shimmer': 'Shimmer — 柔和',
  'voice.marin': 'Marin — 自然轻缓',

  'reader.signInRequired': '需要登录',
  'reader.signInBody': '创建账户即可保存汇编、笔记和交叉引用。',
  'reader.notNow': '暂不',
  'reader.signIn': '登录',
  'reader.pdfNotFound': '找不到该 PDF 文件。',
  'reader.contentLoadFailed': '内容加载失败',
  'reader.noBook': '未指定书籍',
  'reader.storageError': '存储错误',

  'discover.recent': '最新',
  'discover.trending': '热门',
  'discover.searchPlaceholder': '搜索汇编和用户…',
  'discover.searchSelected': '在所选汇编中搜索…',
  'discover.import': '导入',
  'discover.imported': '已导入',
  'discover.import_other': '{{count}} 次导入',
  'discover.noneYet': '还没有共享的汇编',
  'discover.noResults': '没有结果',
  'discover.tryDifferent': '换一个搜索词试试。',
  'discover.signInTitle': '登录以使用「发现」',
  'discover.signInBody': '看看其他读者在各个传统中发现了什么。',
  'discover.anonymous': '匿名',
  'discover.beFirst': '成为第一个分享汇编的人。',
  'discover.ownTag': '这是你自己的汇编',
  'discover.alreadyImported': '已导入',
  'discover.importFailed': '导入失败',
  'discover.exportFailed': '导出失败',
  'discover.unknownError': '未知错误',

  'usertags.autoImports': '自动将该用户的公开汇编导入你的应用',
  'usertags.noTags': '没有公开汇编',
  'usertags.noTagsBody': '该用户尚未分享任何汇编。',
  'usertags.follow': '关注',
  'usertags.unfollow': '取消关注',
  'usertags.share': '分享',
  'usertags.error': '错误',
  'usertags.somethingWrong': '出错了',

  'onboarding.chooseLanguage': '选择你的语言',
  'onboarding.changeLaterSettings': '之后可以在设置中更改。',
  'onboarding.libraryDownloadHint': '要下载 {{language}} 书库，请在书库页面点按“书库”旁边的 ⌄。',
  'onboarding.continue': '继续',
  'onboarding.chooseTextSize': '选择文字大小',
  'onboarding.fontPreviewQuote':
    '“寻找，就寻见；叩门，就给你们开门。”',
  'onboarding.getStarted': '开始使用',

  'onboarding.closeIntro': '关闭导览',
  'onboarding.goToStep': '前往第 {{number}} 步',
  'onboarding.libraryTitle': '书库',
  'onboarding.libraryCaption': '浏览一个精心编选、涵盖多个传统的书库。点按任意书籍即可开始阅读。',
  'onboarding.searchTitle': '搜索一切',
  'onboarding.searchCaption': '一次搜索全部书籍，直接跳到相应段落。',
  'onboarding.tagAsYouGoTitle': '边读边整理汇编',
  'onboarding.tagAsYouGoCaption': '直接在搜索结果中把段落加入汇编。',
  'onboarding.buildTagsTitle': '建立你的汇编',
  'onboarding.buildTagsCaption': '把段落归入你自己的汇编，方便随时回顾。',
  'onboarding.selectActTitle': '选中并操作',
  'onboarding.selectActCaption': '选中任意文本即可高亮、加入汇编、写笔记或建立交叉引用。',
  'onboarding.marginTitle': '页边注释',
  'onboarding.marginCaption': '你的汇编、笔记和交叉引用都收在页边。',
  'onboarding.navigateTitle': '快速导航',
  'onboarding.navigateCaption': '打开目录即可在书中自由移动。',
  'onboarding.yourTagsTitle': '你的汇编',
  'onboarding.yourTagsCaption': '按汇编回顾每一段收入汇编的经文。',
  'onboarding.xrefsTitle': '交叉引用',
  'onboarding.xrefsCaption': '把不同书籍与传统之间相关的段落连接起来。',
  'onboarding.shareTitle': '分享与发布',
  'onboarding.shareCaption': '分享一段引文，或把汇编发布给社区。',

  // ── 分享链接（第 5 阶段）─────────────────────────────────────────────────
  'share.createLink': '创建分享链接',
  'share.createLinkHint': '一个私密网页，不会出现在「发现」中。',
  'share.linkReady': '链接已就绪',
  'share.linkCopied': '链接已复制',
  'share.copyLink': '复制链接',
  'share.shareVia': '分享…',
  'share.revoke': '撤销',
  'share.revokeConfirm': '撤销此链接？持有该链接的人将失去访问权限。',
  'share.discoverToggle': '发布到「发现」',
  'share.discoverToggleHint': '任何人都可以找到并保存此汇编。',
  'share.stopDiscover': '从「发现」中移除',
  'share.publishedNote': '已发布到「发现」——关闭开关即可停止分享。',
  'share.selectOne': '选择一个汇编以创建链接。',
  'sharePage.eyebrow': '共享的汇编',
  'sharePage.openInReader': '在阅读器中打开',
  'sharePage.save': '保存到我的汇编',
  'sharePage.saving': '正在保存…',
  'sharePage.saved': '已保存到你的汇编',
  'sharePage.saveHint': '将打开 Immerse 应用，或登录后在网页端保存。',
  'sharePage.signInToSave': '登录后即可将其保存到你的汇编。',
  'sharePage.footer': '在 Immerse 中阅读更多',

  // ── 导出面板 ──────────────────────────────────────────────────────────────
  'export.shareTags_other': '分享 {{count}} 个汇编',
  'export.shareTagsGeneric': '分享汇编',
  'export.shareXrefs_other': '分享 {{count}} 条交叉引用',
  'export.preparing': '正在准备…',
  'export.notesOn': '你为每个段落写下的笔记',
  'export.notesNone': '这些段落上没有笔记',
  'export.xrefsOn': '每条引文下方的关联段落',
  'export.xrefsNone': '这些段落上没有交叉引用',
  'export.docxTitle': 'Word 文档（.docx）',
  'export.docxShort': 'Word（.docx）',
  'export.docxDesc': '以汇编为标题，附上引用的段落。可用 Word、Pages 或 Google 文档打开。',
  'export.pdfTitle': 'PDF 文档',
  'export.pdfDesc': '已排版的文档，适合打印或分享。',
  'export.csvTitle': '表格（.csv）',
  'export.csvDesc': '每个段落一行。可用 Excel、Numbers 或 Google 表格打开。',
  'export.mdTitle': 'Markdown（.md）',
  'export.mdDesc': '适用于 Obsidian、Notion 或任何纯文本工具。',
  'export.noPassagesTagged': '（此汇编中没有段落）',
  'export.seeAlso': '另见：',

  // ── 阅读计划 ──────────────────────────────────────────────────────────────
  'plan.chooseBook': '选择一本书',
  'plan.searchBooks': '搜索书籍…',
  'plan.noBooksMatch': '没有符合“{{query}}”的书籍。',
  'plan.readingComplete': '本次阅读完成',
  'plan.morningSession': '早间阅读',
  'plan.eveningSession': '晚间阅读',
  'plan.minutes': '{{count}} 分钟',
  'plan.streakDay': '连续第 {{count}} 天 ✓',
  'plan.sessionsToday': '今天已完成 {{done}}/{{required}} 次阅读',
  'plan.youFinished': '你读完了{{title}}',
  'plan.readOverDays_other': '用 {{count}} 天读完',
  'plan.remindersPaused': '提醒已暂停',
  'plan.chooseNextBook': '选择你的下一本书',
  'completed.title': '已读完的书',
  'completed.empty': '你在阅读计划中读完的书会显示在这里。',
  'completed.finishedOn': '{{date}} 读完',
  'completed.day_other': '{{count}} 天',

  // ── 书库其余部分 ──────────────────────────────────────────────────────────
  'library.selectPassageForXref': '选择用于交叉引用的段落',
  'library.findingRelated': '正在查找相关段落…',
  'library.aiSearchOffline': '以提问方式搜索需要互联网连接',
  'library.importFailedTitle': '导入失败',
  'library.couldNotImport': '无法导入该文件。',
  'library.bookAdded': '书籍已添加',
  'library.bookAddedBody': '“{{title}}”已加入「我的书」。',
  'library.importErrorTitle': '导入出错',
  'library.unexpectedError': '发生了意外错误。',
  'nav.browsingAsGuest': '正在以访客身份浏览',
  'reader.selectBookToBegin': '选择一本书开始阅读',
  'tags.exportFailed': '导出失败',
  'tags.couldNotExport': '无法导出汇编。',
  'tags.couldNotRemoveSelection': '无法移除该选段',
  'tags.reorderHint': '拖动手柄可调整顺序 · ⇤ ⇥ 可更改层级 · 点按汇编可调整其引文顺序。',
  'tags.swipeHint': '向右滑动汇编即可设为公开或私密。',
  'discover.publishHint': '在「汇编」页面向右滑动某个汇编，即可发布到这里。',
  'reminders.notificationsOff':
    'Immerse 的通知已关闭，因此无法送达提醒。'
    + '请在设备设置中开启通知。',
  'plan.continueJourney': '继续你的阅读之旅',
  'plan.yourBook': '你的书',
  'reader.notesInParagraph_other': '本段有 {{count}} 条笔记',
  'plan.awaitsMorning': '{{book}}在等你 — 早间阅读',
  'plan.awaitsEvening': '{{book}}在等你 — 晚间阅读',
  'reminders.dailyReadingFrom': '每日阅读 · {{source}}',
  'library.tapToExpandHint': '点按展开 · 长按在阅读器中打开',
  'library.deleteBookImportedBody': '这本书及其全部注释将被永久移除。',
  'library.deleteBookBundledBody':
    '这本书及其全部注释将被移除。书库下次刷新时它会重新出现。',
  'library.deleteCategoryConfirm': '删除“{{name}}”？',
  'library.deleteCategoryBody_other': '这还会移除 {{count}} 本书及其全部注释。',
  'library.deleteCategoryEmptyBody': '此分类将被永久移除。',

  'auth.passwordTooShortTitle': '密码太短',
  'auth.passwordsMustMatch': '请确保两次输入的密码一致。',
  'auth.usernamePlain': '用户名 ID',
  'auth.fullNameOptional': '姓名（可选）',
  'auth.emailPlain': '电子邮箱',
  'auth.passwordPlain': '密码',
  'auth.emailAddressPlain': '电子邮箱地址',

  // ── 功能导览（移动端） ────────────────────────────────────────────────────
  'onboarding.skip': '跳过',
  'onboarding.tour.libraryMain.label': '书库页面',
  'onboarding.tour.libraryMain.caption':
    '书库收录了各大传统的 400 多部经典。点按一个传统即可浏览其中的书籍。',
  'onboarding.tour.libraryExpanded.label': '展开后的书库',
  'onboarding.tour.libraryExpanded.caption':
    '每个传统都可展开，显示作者与文集。点按任意书名即可在阅读器中打开。',
  'onboarding.tour.librarySearch.label': '书库搜索',
  'onboarding.tour.librarySearch.caption':
    '一次搜索全部 400 多部经典。点按结果可展开，长按则直接在阅读器中打开。',
  'onboarding.tour.searchQuickTag.label': '搜索结果快速加入汇编',
  'onboarding.tour.searchQuickTag.caption':
    '选中一条或多条搜索结果，一次点按即可归入某个汇编。这是从整个书库快速建立主题合集的方法。',
  'onboarding.tour.home.label': '主页',
  'onboarding.tour.home.caption':
    '主页会显示你创建了多少汇编、笔记和交叉引用，以及最近读过的书。点按书名即可继续阅读。',
  'onboarding.tour.homePlan.label': '主页上的阅读计划',
  'onboarding.tour.homePlan.caption':
    '养成每天阅读的习惯：按你选择的书籍和时长跟随阅读计划，或从你选定的传统中获取随机经文 — 配有每日提醒，以及一条随着阅读天数不断增长的连续记录。',
  'onboarding.tour.settingsDaily.label': '每日阅读设置',
  'onboarding.tour.settingsDaily.caption':
    '在设置中，为随机经文挑选取材的传统和你希望收到轻声提醒的时间，或者切换到阅读计划，每天读完一本书的一部分。',
  'onboarding.tour.readerSelect.label': '在阅读器中选中文本',
  'onboarding.tour.readerSelect.caption':
    '长按任意段落即可选中。用屏幕底部的图标加入汇编、添加笔记、添加交叉引用，或获取 AI 摘要。',
  'onboarding.tour.readerNote.label': '在阅读器中查看笔记',
  'onboarding.tour.readerNote.caption':
    '笔记会附着在你选中的确切文本上。页边的金色标记让你随时找到并重新打开它们。',
  'onboarding.tour.readerXref.label': '在阅读器中查看交叉引用',
  'onboarding.tour.readerXref.caption':
    '交叉引用把不同书籍与传统中的段落连接起来。长按任意关联引文，即可在阅读器中跳转过去。',
  'onboarding.tour.readerAi.label': '阅读器中的 AI 摘要',
  'onboarding.tour.readerAi.caption':
    '选中段落后，点按闪光图标即可获得即时的 AI 摘要 — 对艰深或陌生的文本尤其有用。',
  'onboarding.tour.readerListen.label': '阅读器的聆听模式',
  'onboarding.tour.readerListen.caption':
    '点按耳机按钮即可朗读任意书籍，阅读器会随着朗读高亮相应段落。长按耳机按钮可从多种自然语音中挑选。',
  'onboarding.tour.tags.label': '汇编页面',
  'onboarding.tour.tags.caption':
    '汇编页面按主题归类你收入汇编的段落。点按汇编名称即可查看其引文及完整出处。',
  'onboarding.tour.xrefs.label': '交叉引用页面',
  'onboarding.tour.xrefs.caption':
    '交叉引用页面把你连接过的段落并排展示。长按任意一侧即可在阅读器中跳到该段落。',
  'onboarding.tour.discover.label': '「发现」页面',
  'onboarding.tour.discover.caption':
    '在「发现」页面可以找到其他读者分享的汇编。点按汇编预览其中的段落，然后导入到你自己的书库。',
  'onboarding.tour.tagShare.label': '汇编分享面板',
  'onboarding.tour.tagShare.caption':
    '可将任意汇编导出为 Word 文档、PDF、表格、Markdown 等格式 — 并包含你的笔记和交叉引用。',

  // ── Appearance (reader typography) ───────────────────────────────────────
  'appearance.title': '外观',
  'appearance.navHint': '字体、间距、页面颜色',
  'appearance.reading': '阅读',
  'appearance.preview': '预览',
  'appearance.previewText': '阅读是一场跨越世纪的静默交谈。',
  'appearance.typeface': '字体',
  'appearance.typefaceSystem': '系统',
  'appearance.typefaceLiterataBlurb': '为长时间阅读而设计，随字号自动调整。',
  'appearance.typefaceCharisBlurb': '源自 Charter，小字号依然清晰。',
  'appearance.typefaceGaramondBlurb': '古典风格，页面更显轻盈。',
  'appearance.typefaceSystemBlurb': '使用本设备自带的字体。',
  'appearance.textSize': '文字大小',
  'appearance.lineSpacing': '行距',
  'appearance.lineSpacingTight': '紧凑',
  'appearance.lineSpacingNormal': '标准',
  'appearance.lineSpacingRelaxed': '宽松',
  'appearance.lineSpacingLoose': '松散',
  'appearance.margins': '页边距',
  'appearance.marginsNarrow': '窄',
  'appearance.marginsNormal': '标准',
  'appearance.marginsWide': '宽',
  'appearance.justify': '两端对齐',
  'appearance.justifyHint': '两端对齐并自动断词。',
  'appearance.paragraphStyle': '段落',
  'appearance.paragraphSpaced': '间隔',
  'appearance.paragraphIndented': '首行缩进',
  'appearance.paragraphHint': '首行缩进是传统书籍的排版方式。',
  'appearance.theme': '页面颜色',
  'appearance.themeLight': '明亮',
  'appearance.themeSepia': '护眼',
  'appearance.themeQuiet': '柔和',
  'appearance.themeDark': '深色',
  'appearance.themeNight': '夜间',
  'appearance.themeSystem': '跟随应用',
  'appearance.fineTuning': '精细调整',
  'appearance.characterSpacing': '字符间距',
  'appearance.wordSpacing': '词间距',
  'appearance.textWeight': '字重',
  'appearance.paragraphNumbers': '段落编号',
  'appearance.paragraphNumbersHint': '在页边显示引用编号。',
  'appearance.appTheme': '应用主题',
  'appearance.appThemeHint': '应用于阅读器之外的界面。',
  'appearance.reset': '恢复默认',

  // ── 引用出处名称 ──────────────────────────────────────────────────────────
  'citation.bible': '圣经',
  'citation.tanakh': '塔纳赫',
  'citation.quran': '古兰经',
  'citation.guruGranthSahib': '古鲁·格兰特·萨希卜',
};
